#Date: 20th August 2026
#Topics Covered:

-- SQL ASSIGNMENT – UPDATE & DELETE

/* USE THE 10 TABLES CREATED AND POPULATED IN THE PREVIOUS ASSIGNMENTS.
FOR EACH QUESTION, WRITE THE APPROPRIATE SQL QUERY AND VERIFY THE RESULT USING:
SELECT * FROM TABLE_NAME; */

--##A. UPDATE – SINGLE COLUMN
--1. IN THE STUDENTS TABLE, UPDATE THE DEPARTMENT OF THE STUDENT WITH STUDENTID = 101 TO 'COMPUTER SCIENCE'.
--2. IN THE EMPLOYEES TABLE, UPDATE THE SALARY OF THE EMPLOYEE WITH EMPLOYEEID = 201 TO 55000.
--3. IN THE PATIENTS TABLE, UPDATE THE DISEASE OF THE PATIENT WITH PATIENTID = 301 TO 'FEVER'.
--4. IN THE BOOKS TABLE, UPDATE THE PRICE OF THE BOOK WITH BOOKID = 401 TO 750.
--5. IN THE PRODUCTS TABLE, UPDATE THE PRICE OF THE PRODUCT WITH PRODUCTID = 501 TO 2500.

UPDATE studentdb.students set DEPARTMENT = 'COMPUTER SCIENCE' WHERE STUDENT_id = 101;
UPDATE employeedb.employees SET SALARY = 55000 WHERE EMPLOYEE_ID=201;
UPDATE hospitaldb.patients SET DISEASE= 'FEVER' WHERE PATIENT_ID= 301;
UPDATE librarydb.BOOKS SET PRICE = 750 WHERE BOOKID=401;
UPDATE shoppingdb.products SET PRICE = 2500 WHERE PRODUCT_ID=501;


--##B. UPDATE – MULTIPLE COLUMNS
--6. IN THE STUDENTS TABLE, UPDATE THE AGE AND DEPARTMENT OF THE STUDENT WITH STUDENTID = 102.
--7. IN THE EMPLOYEES TABLE, UPDATE THE DEPARTMENT AND SALARY OF THE EMPLOYEE WITH EMPLOYEEID = 202.
--8. IN THE PATIENTS TABLE, UPDATE THE PHONE AND DISEASE OF THE PATIENT WITH PATIENTID = 302.
--9. IN THE BOOKS TABLE, UPDATE THE AUTHOR AND PRICE OF THE BOOK WITH BOOKID = 402.
--10. IN THE PRODUCTS TABLE, UPDATE THE BRAND AND PRICE OF THE PRODUCT WITH PRODUCTID = 502.

UPDATE studentdb.students SET AGE = 30, DEPARTMENT = 'HR' WHERE STUDENT_id = 102;
UPDATE employeedb.employees SET DEPARTMENT='HR', SALARY = 40000 WHERE EMPLOYEE_ID=202;
UPDATE hospitaldb.patients SET PHONE='9983984982', DISEASE= 'PEI PUDICHIRUCHU' WHERE PATIENT_ID = 302;
UPDATE librarydb.books SET AUTHOR ='AVIKUTTY', PRICE = 50000 WHERE BOOKID = 402;
UPDATE shoppingdb.products SET BRAND = 'THERILA', PRICE = 40000 WHERE PRODUCT_ID=502;

--##C. UPDATE – USING CONDITIONS
--11. INCREASE THE SALARY BY 10% FOR ALL EMPLOYEES IN THE EMPLOYEES TABLE WHOSE DEPARTMENT IS 'IT'.
--12. INCREASE THE PRICE BY 5% FOR ALL BOOKS IN THE BOOKS TABLE BELONGING TO THE 'TECHNOLOGY' CATEGORY.
--13. UPDATE THE AVAILABILITY TO 'AVAILABLE' FOR ALL ROOMS IN THE ROOMS TABLE WHERE PRICEPERDAY IS LESS THAN 3000.
--14. UPDATE THE DISCOUNT TO 10 FOR ALL PRODUCTS IN THE PRODUCTS TABLE WHOSE PRICE IS GREATER THAN 5000.
--15. UPDATE THE RATING TO 5.0 FOR ALL MOVIES IN THE MOVIES TABLE WHOSE GENRE IS 'DRAMA'.

UPDATE employeedb.employees SET SALARY = 1.1*SALARY WHERE DEPARTMENT = 'IT';
UPDATE librarydb.books SET PRICE = (21/20)*PRICE WHERE CATEGORY = 'TECHNOLOGY';
UPDATE hoteldb.rooms SET AVAILABILITY = 'AVAILABLE' WHERE PRICE_PERDAY<3000;
UPDATE shoppingdb.products SET DISCOUNT = 10 WHERE PRICE >5000;
UPDATE moviedb.movies SET RATING = 5.0 WHERE GENRE = 'DRAMA';

--DELETE
-- ##D. DELETE – SINGLE RECORD
--16. DELETE THE STUDENT WHOSE STUDENTID = 110.
--17. DELETE THE EMPLOYEE WHOSE EMPLOYEEID = 210.
--18. DELETE THE PATIENT WHOSE PATIENTID = 310.
--19. DELETE THE BOOK WHOSE BOOKID = 410.
--20. DELETE THE PRODUCT WHOSE PRODUCTID = 510.

DELETE FROM studentdb.students WHERE STUDENT_id = 110;
DELETE FROM employeedb.employees WHERE EMPLOYEE_ID = 210;
DELETE FROM hospitaldb.patients WHERE PATIENT_ID = 310;
DELETE FROM librarydb.books WHERE BOOKID = 410;
DELETE FROM shoppingdb.productS WHERE PRODUCT_ID=510;

--##E. DELETE – USING CONDITIONS
--21. DELETE ALL STUDENTS WHOSE AGE IS LESS THAN 18.
--22. DELETE ALL EMPLOYEES WHOSE SALARY IS LESS THAN 25000.
--23. DELETE ALL PATIENTS WHOSE DISEASE IS 'FLU'.
--24. DELETE ALL BOOKS WHOSE PRICE IS LESS THAN 200.
--25. DELETE ALL PRODUCTS WHOSE STOCKQUANTITY IS 0.

DELETE FROM studentdb.students WHERE AGE<18;
DELETE FROM employeedb.employees WHERE SALARY<25000;
DELETE FROM hospitaldb.patients WHERE DISEASE = 'FLU';
DELETE FROM librarydb.books WHERE PRICE <200;
DELETE FROM shoppingdb.products WHERE STOCK_QUANTITY = 0;
  
--##F. DELETE – MULTIPLE CONDITIONS
--26. DELETE ALL STUDENTS WHOSE AGE IS GREATER THAN 25 AND WHOSE DEPARTMENT IS 'MECHANICAL'.
--27. DELETE ALL EMPLOYEES WHOSE DEPARTMENT IS 'HR' AND WHOSE SALARY IS LESS THAN 30000.
--28. DELETE ALL ROOMS WHOSE AVAILABILITY IS 'UNAVAILABLE' AND WHOSE PRICEPERDAY IS LESS THAN 2000.
--29. DELETE ALL MOVIES WHOSE LANGUAGE IS 'TAMIL' AND WHOSE RATING IS LESS THAN 3.0.
--30. DELETE ALL CUSTOMERS WHOSE CITY IS 'CHENNAI' OR WHOSE COUNTRY IS NULL.

DELETE FROM studentdb.students WHERE AGE > 25 AND DEPARTMENT='MECHANICAL';
DELETE FROM employeedb.employees WHERE DEPARTMENT = 'HR'AND SALARY<30000;
DELETE FROM hoteldb.rooms WHERE AVAILABILITY = 'UNAVAILABLE' AND PRICE_PERDAY<2000;
DELETE FROM moviedb.movies WHERE LANGUAGE = 'TAMIL' AND RATING <3.0;
DELETE FROM CUSTOMERS.CITY WHERE CITY = 'CHENNAI' AND COUNTRY IS NULL;

----------------------------------------- End of Test - 01 ---------------------------------------------------------------------------------
