#Date: 21ST AUGUST 2026
# Topics covered:

--SQL DATA CONSTRAINTS
--USE THE TABLES FROM YOUR PREVIOUS ASSIGNMENTS AND PRACTICE THE FOLLOWING.
--A. UNIQUE CONSTRAINT
/* 1. CREATE A STUDENTS TABLE WHERE EMAIL MUST CONTAIN UNIQUE VALUES.
2. ADD A UNIQUE CONSTRAINT TO THE PHONE COLUMN IN THE EMPLOYEES TABLE.
3. CREATE A PRODUCTS TABLE WHERE PRODUCTCODE MUST BE UNIQUE.
4. TRY INSERTING TWO STUDENTS WITH THE SAME EMAIL AND OBSERVE THE ERROR. */

create table students(
    Studnet_id int primary key,
    student_name varchar(30) not null,
    email varchar(30) not null
);

alter table employeedb.employees add constraint phonenumber_Constraint unique(PHONE);
CREATE TABLE PRODUCTS(
    PRODUCTID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(30),
    PRODUCT_CODE VARCHAR(30) UNIQUE
);

INSERT INTO students (STUDNET_ID, EMAIL) VALUES (1,'RAJESH@GMAIL.COM');
--ERROR: BECASUE GAMIL IS NOT UNIQUE

--B. PRIMARY KEY
/*5. CREATE A STUDENTS TABLE WITH STUDENTID AS THE PRIMARY KEY.
6. CREATE AN EMPLOYEES TABLE WITH EMPLOYEEID AS THE PRIMARY KEY.
7. TRY INSERTING TWO EMPLOYEES WITH THE SAME EMPLOYEEID AND OBSERVE THE RESULT.
8. TRY INSERTING A STUDENT RECORD WITH NULL AS THE STUDENTID AND OBSERVE THE RESULT.*/

CREATE TABLE STUDENTS (
    STUDENTID INT PRIMARY KEY,
    STUDNET_NAME VARCHAR(30)
);

CREATE TABLE employeedb.employees (
    EMPLOYEEID INT PRIMARY KEY,
    EMP_NAME VARCHAR(30)
);

INSERT INTO STU VALUES (1,'AVI'), (1,'AVI');
--ERROR: DUE TO DUPLICATE VALUES
/* IMPORTANT_NOTE: Databricks does not enforce PRIMARY KEY uniqueness because it is a distributed analytics platform optimized for 
                  large-scale data processing. Enforcing uniqueness would require checking data across multiple partitions and nodes, 
                  which would significantly impact performance. Therefore, PRIMARY KEY constraints are typically informational, 
                  while data quality and uniqueness are usually enforced through ETL logic, MERGE operations, and validation checks.*/

--C. COMPOSITE KEY

/*9. CREATE A TABLE NAMED STUDENTCOURSES WITH:
   - STUDENTID
   - COURSEID
   - ENROLLMENTDATE
10. MAKE STUDENTID AND COURSEID TOGETHER A COMPOSITE PRIMARY KEY.
11. INSERT A RECORD WITH STUDENTID = 101 AND COURSEID = 501.
12. TRY INSERTING ANOTHER RECORD WITH THE SAME STUDENTID = 101 AND COURSEID = 501. OBSERVE THE RESULT.
13. INSERT ANOTHER RECORD WITH STUDENTID = 101 AND A DIFFERENT COURSEID = 502. CHECK WHETHER THE INSERTION IS SUCCESSFUL.*/

CREATE TABLE STUDENTCOURSES(
    STUDENTID INT,
    COURSEID INT,
    ENROLLMENTDATE DATE
);

ALTER TABLE studentcourses ADD CONSTRAINT COMP_KEY PRIMARY KEY(STUDENTID, COURSEID);

INSERT INTO studentcourses VALUES(101,501,'2019-01-01')
ERROR IF: ALL VALUES ARE SAME (STUOID, COURID, DATE). IF DATE ALONE DIFF, NO ERROR

 INSERT INTO studentcourses VALUES(101,502,);
--INSERTION IS SUCCESSFUL


--D. FOREIGN KEY

/*13. CREATE A DEPARTMENTS TABLE WITH:
   • DEPARTMENTID - PRIMARY KEY
   • DEPARTMENTNAME
14. CREATE AN EMPLOYEES TABLE WITH:
   • EMPLOYEEID - PRIMARY KEY
   • EMPLOYEENAME
   • DEPARTMENTID - FOREIGN KEY REFERENCING DEPARTMENTS
15. INSERT AT LEAST 3 DEPARTMENTS INTO THE DEPARTMENTS TABLE.
16. INSERT EMPLOYEES USING VALID DEPARTMENTID VALUES.
17. TRY INSERTING AN EMPLOYEE WITH A DEPARTMENTID THAT DOES NOT EXIST IN THE DEPARTMENTS TABLE. OBSERVE THE RESULT.*/

CREATE TABLE DEPARTMENT(
    DEPARTMENTID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30)
);

CREATE TABLE EMPLOYEE(
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(30),
    DEPARTMENTID INT,
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DepartmentID)
);

INSERT INTO DEPARTMENTS VALUES (1, 'CS'), (2,'EEE'), (3,'MECH'), (4,'CHEM');

INSERT INTO EMPLOYEES VALUES (101, 'PYTHON',1), (102,'WIRES',2), (103,'BENZENE',4);

INSERT INTO EMPLOYEES VALUES (105, 'BALANCESHEET',7);
--ERROR: BECAUSE DEPID 7 IS NOT AVAILABLE & NULL VALUES CAN BE ACCEPTED IN EMP TABLE

-- E. NOT NULL

/*18. CREATE A STUDENTS TABLE WHERE STUDENTNAME AND EMAIL CANNOT CONTAIN NULL VALUES.
19. TRY INSERTING A STUDENT WITHOUT PROVIDING A STUDENTNAME. OBSERVE THE RESULT.
20. TRY INSERTING A STUDENT WITH NULL AS THE EMAIL. OBSERVE THE RESULT.*/

CREATE TABLE students(
    STUDENTNAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL
);

INSERT INTO STUDNETS (EMAIL) VALUES('123@GMAIL.COM')
--ERROR: STUDENTNAME CANNOT BE NULL

INSERT INTO STUDNETS (EMAIL) VALUES(NULL)
--ERROR: EMAIL CANNOT BE NULL

  -- F. CHECK CONSTRAINT

/* 21. CREATE AN EMPLOYEES TABLE WHERE SALARY MUST BE GREATER THAN 10000.
22. TRY INSERTING AN EMPLOYEE WITH A SALARY OF 5000. OBSERVE THE RESULT.
23. CREATE A STUDENTS TABLE WHERE AGE MUST BE BETWEEN 18 AND 60.
24. TRY INSERTING A STUDENT WITH AN AGE OF 15. OBSERVE THE RESULT.
25. CREATE A PRODUCTS TABLE WHERE PRICE MUST BE GREATER THAN 0.
26. CREATE A PATIENTS TABLE WHERE AGE MUST BE GREATER THAN OR EQUAL TO 0.*/

CREATE TABLE EMPLOYEE(
    EMPID INT PRIMARY KEY,
    EMPNAME VARCHAR(30) NOT NULL,
    EMPMAIL VARCHAR(30) NOT NULL,
    SALARY DECIMAL (10,2) CHECK (SALARY>5000)
);

INSERT INTO employee VALUES (1,'AVI','2@GMAIL',2000);
--ERROR: SALARY CANNOT BE LESS THAN 5000

ALTER TABLE students ADD CONSTRAINT CHECK_CONSTRAINT CHECK(AGE BETWEEN 18 AND 60);

INSERT INTO STUDENTS VALUES (1,'AVI','EMAIL@GMAIL',12);
--ERROR: AGE NOT IN RANGE (IT SHOULD BE BETWEEN 18 AND 60)

CREATE TABLE PRODUCTS (
    PRODUCTID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(20) NOT NULL,
    PRICE DECIMAL(10,2) CHECK (PRICE>0)
);

CREATE TABLE PATIENTS (
    PATIENTID INT PRIMARY KEY,
    PATIENTNAME VARCHAR(30) NOT NULL,
    AGE INT CHECK(AGE>=0)
);

--G. DEFAULT CONSTRAINT

/*27. CREATE AN EMPLOYEES TABLE WHERE THE DEPARTMENT HAS A DEFAULT VALUE OF 'IT'.
28. INSERT AN EMPLOYEE WITHOUT PROVIDING THE DEPARTMENT VALUE. VERIFY THE DEFAULT VALUE.
29. CREATE A PRODUCTS TABLE WHERE STOCKQUANTITY HAS A DEFAULT VALUE OF 0.
30. INSERT A PRODUCT WITHOUT PROVIDING STOCKQUANTITY AND VERIFY THE RESULT.*/

CREATE TABLE EMPLOYEES(
    EMPID INT PRIMARY KEY,
    EMPNAME VARCHAR(30) NOT NULL,
    DEPARTMENT VARCHAR(30) DEFAULT 'IT');

INSERT INTO EMPLOYEES VALUES (1,'AVI');
--ANS: DEFAULT VALUE 'IT' WILL BE SELECTED

CREATE TABLE PRODUCTS(
    PROID INT PRIMARY KEY,
    PRONAME VARCHAR(30) NOT NULL,
    STOCKQUANTITY INT DEFAULT 0
);

INSERT INTO PRODUCTS VALUES(1,'AVI')
--ANS: DEFAULT VALUE 0 IS SELECTED

-- H. COMBINATION PRACTICE

/*31. CREATE A STUDENTS TABLE WITH:
   • STUDENTID - PRIMARY KEY
   • STUDENTNAME - NOT NULL
   • EMAIL - UNIQUE
   • AGE - CHECK BETWEEN 18 AND 60
   • CITY - DEFAULT 'CHENNAI'

32. CREATE A DEPARTMENTS TABLE WITH:
   • DEPARTMENTID - PRIMARY KEY
   • DEPARTMENTNAME - UNIQUE AND NOT NULL

33. CREATE AN EMPLOYEES TABLE WITH:
   • EMPLOYEEID - PRIMARY KEY
   • EMPLOYEENAME - NOT NULL
   • EMAIL - UNIQUE
   • SALARY - CHECK GREATER THAN 10000
   • DEPARTMENTID - FOREIGN KEY

34. CREATE A STUDENTCOURSES TABLE WITH:
   • STUDENTID
   • COURSEID
   • ENROLLMENTDATE
   MAKE STUDENTID + COURSEID A COMPOSITE PRIMARY KEY.

35. CREATE A PRODUCTS TABLE USING AT LEAST FOUR DIFFERENT CONSTRAINTS AMONG PRIMARY KEY, 
    UNIQUE, NOT NULL, CHECK, AND DEFAULT.*/

CREATE TABLE STUDNETS(
    STUDENTID INT PRIMARY KEY,
    STUDENTNAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) UNIQUE,
    AGE INT CHECK (AGE BETWEEN 18 AND 60),
    CITY VARCHAR(50) DEFAULT 'CHENNAI'
);

CREATE TABLE DEPARTMENT(
    DEPID INT PRIMARY KEY,
    DEPANAME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE EMPLOYEES(
    EMPLOYEEID INT PRIMARY KEY,
    EMPLOYEENAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) UNIQUE,
    SALARY DECIMAL (10,2) CHECK(SALARY>10000),
    DEPID INT,
    FOREIGN KEY DEPID REFERENCES DEPARTMENTS(DEPARTMENTID)
);

CREATE TABLE STUDENTCOURSES(
    STUDENTID INT,
    COURSEID INT,
    ENROLLMENTS INT,
    ADD CONSTRAINT COMP_KEY PRIMARY KEY(STUDNETID, COURSEID)
);

CREATE TABLE PRODUCTS (
  ID INT PRIMARY KEY,
  PRODUCTNAME VARCHAR(30) UNIQUE,
  PRODUCTPRICE INT NOT NULL,
  STOCKQUANTITY INT CHECK (STOCKQUANTITY > 0),
  CREATEDATE DATE CURRENT_DATE()
);


