#Date: 24th August 2026
#Topics Covered: 

/* IS NULL AND IS NOT NULL
USE THE TABLES FROM YOUR PREVIOUS ASSIGNMENTS: STUDENTS, EMPLOYEES, PATIENTS, BOOKS, PRODUCTS, MOVIES, AND CUSTOMERS.

A. IS NULL – PRACTICE QUESTIONS

1. DISPLAY ALL STUDENTS WHOSE EMAIL IS NULL.
2. DISPLAY ALL STUDENTS WHOSE MOBILENUMBER IS NULL.
3. DISPLAY ALL EMPLOYEES WHOSE DEPARTMENT IS NULL.
4. DISPLAY ALL EMPLOYEES WHOSE EMAIL IS NULL.
5. DISPLAY ALL PATIENTS WHOSE DISEASE IS NULL.
6. DISPLAY ALL PATIENTS WHOSE DOCTORNAME IS NULL.
7. DISPLAY ALL BOOKS WHOSE PUBLISHEDYEAR IS NULL.
8. DISPLAY ALL BOOKS WHOSE AUTHOR IS NULL.
9. DISPLAY ALL PRODUCTS WHOSE BRAND IS NULL.
10. DISPLAY ALL PRODUCTS WHOSE MANUFACTURINGDATE IS NULL.
11. DISPLAY ALL CUSTOMERS WHOSE EMAIL IS NULL.
12. DISPLAY ALL CUSTOMERS WHOSE COUNTRY IS NULL. */

SELECT * FROM STUDENTS WHERE EMAIL IS NULL;
SELECT * FROM STUDENTS WHERE MOBILE_NUMBER IS NULL;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IS NULL;
SELECT * FROM EMPLOYEES WHERE EMAIL IS NULL;
SELECT * FROM PATIENTS WHERE DISEASE IS NULL;
SELECT * FROM PATIENTS WHERE DOCTORNAME IS NULL;
SELECT * FROM BOOKS WHERE PUBLISHED_YEAR IS NULL;
SELECT * FROM BOOKS WHERE AUTHOR IS NULL;
SELECT * FROM PRODUCTS WHERE BRAND IS NULL;
SELECT * FROM PRODUCTS WHERE MANUFACTURING_DATE IS NULL;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NULL;
SELECT * FROM CUSTOMERS WHERE COUNTRY IS NULL;

/* 
B. IS NOT NULL – PRACTICE QUESTIONS

13. DISPLAY ALL STUDENTS WHOSE EMAIL IS NOT NULL.
14. DISPLAY ALL STUDENTS WHOSE DEPARTMENT IS NOT NULL.
15. DISPLAY ALL EMPLOYEES WHOSE SALARY IS NOT NULL.
16. DISPLAY ALL EMPLOYEES WHOSE EMAIL IS NOT NULL.
17. DISPLAY ALL PATIENTS WHOSE DISEASE IS NOT NULL.
18. DISPLAY ALL PATIENTS WHOSE DOCTORNAME IS NOT NULL.
19. DISPLAY ALL BOOKS WHOSE AUTHOR IS NOT NULL.
20. DISPLAY ALL BOOKS WHOSE PRICE IS NOT NULL.
21. DISPLAY ALL PRODUCTS WHOSE BRAND IS NOT NULL.
22. DISPLAY ALL PRODUCTS WHOSE MANUFACTURINGDATE IS NOT NULL.
23. DISPLAY ALL CUSTOMERS WHOSE EMAIL IS NOT NULL.
24. DISPLAY ALL CUSTOMERS WHOSE COUNTRY IS NOT NULL. */

SELECT * FROM STUDENTS WHERE EMAIL IS NOT NULL;
SELECT * FROM STUDENTS WHERE DEPARTMENT IS NOT NULL;
SELECT * FROM EMPLOYEES WHERE SALARY IS NOT NULL;
SELECT * FROM EMPLOYEES WHERE EMAIL IS NOT NULL;
SELECT * FROM PATIENTS WHERE DISEASE IS NOT NULL;
SELECT * FROM PATIENTS WHERE DOCTORNAME IS NOT NULL;
SELECT * FROM BOOKS WHERE AUTHOR IS NOT NULL;
SELECT * FROM BOOKS WHERE PRICE IS NOT NULL;
SELECT * FROM PRODUCTS WHERE BRAND IS NOT NULL;
SELECT * FROM PRODUCTS WHERE MANUFACTURING_DATE IS NOT NULL;
SELECT * FROM CUSTOMER WHERE EMAIL IS NOT NULL;
SELECT * FROM CUSTOMER WHERE COUNTRY IS NOT NULL;

/* 
C. IS NULL WITH CONDITIONS

25. DISPLAY STUDENTS WHOSE EMAIL IS NULL AND WHOSE DEPARTMENT IS 'IT'.
26. DISPLAY EMPLOYEES WHOSE DEPARTMENT IS NULL AND WHOSE SALARY IS GREATER THAN 30000.
27. DISPLAY PATIENTS WHOSE DISEASE IS NULL AND WHOSE AGE IS GREATER THAN 25.
28. DISPLAY PRODUCTS WHOSE BRAND IS NULL AND WHOSE PRICE IS GREATER THAN 5000.
29. DISPLAY CUSTOMERS WHOSE EMAIL IS NULL AND WHOSE CITY IS 'CHENNAI'.

*/

SELECT * FROM STUDENTS WHERE EMAIL IS NULL AND DEPARTMENT = 'IT';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IS NULL AND SALARY > 30000;
SELECT * FROM PATIENTS WHERE DISEASE IS NULL AND AGE >25;
SELECT * FROM PRODUCTS WHERE BRAND IS NULL AND PRICE >5000;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NULL AND CITY = 'CHENNAI';

/* 
D. IS NOT NULL WITH CONDITIONS

30. DISPLAY STUDENTS WHOSE EMAIL IS NOT NULL AND WHOSE DEPARTMENT IS 'CSE'.
31. DISPLAY EMPLOYEES WHOSE DEPARTMENT IS NOT NULL AND WHOSE SALARY IS GREATER THAN 40000.
32. DISPLAY PATIENTS WHOSE DISEASE IS NOT NULL AND WHOSE AGE IS GREATER THAN 30.
33. DISPLAY BOOKS WHOSE AUTHOR IS NOT NULL AND WHOSE PRICE IS LESS THAN 1000.
34. DISPLAY PRODUCTS WHOSE BRAND IS NOT NULL AND WHOSE STOCK QUANTITY IS GREATER THAN 10.
35. DISPLAY CUSTOMERS WHOSE EMAIL IS NOT NULL AND WHOSE CITY IS 'CHENNAI'. */

SELECT * FROM STUDENTS WHERE EMAIL IS NOT NULL AND DEPARTMENT = 'CSE';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IS NOT NULL AND SALARY >40000;
SELECT * FROM PATIENTS WHERE DISEASE IS NOT NULL AND AGE >30;
SELECT * FROM BOOKS WHERE AUTHOR IS NOT NULL AND PRICE<1000;
SELECT * FROM PRODUCTS WHERE BRAND IS NOT NULL AND STOCK_QUANTITY >10;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND CITY = 'CHENNAI';

/* E. MIXED PRACTICE

36. DISPLAY STUDENTS WHOSE EMAIL IS EITHER NULL OR WHOSE DEPARTMENT IS 'IT'.
37. DISPLAY EMPLOYEES WHOSE EMAIL IS NOT NULL AND WHOSE DEPARTMENT IS EITHER 'IT' OR 'HR'.
38. DISPLAY PRODUCTS WHOSE BRAND IS NULL OR WHOSE DISCOUNT IS NULL.
39. DISPLAY CUSTOMERS WHOSE EMAIL IS NOT NULL AND WHOSE COUNTRY IS NOT NULL.
40. DISPLAY PATIENTS WHOSE DISEASE IS NULL BUT WHOSE PHONE IS NOT NULL. */

SELECT * FROM STUDENTS WHERE EMAIL IS NULL OR DEPARTMENT = 'IT';
SELECT * FROM EMPLOYEES WHERE EMAIL IS NOT NULL AND DEPARTMENT IN ('IT','HR');
SELECT * FROM PRODUCTS WHERE BRAND IS NULL OR DISCOUNT IS NULL;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND COUNTRY IS NOT NULL;
SELECT * FROM PATIENTS WHERE DISEASE IS NULL AND PHONE IS NOT NULL;
