#Date: 24th August 2026
#Topics Covered:

/*IN AND NOT IN

USE THE STUDENTS, EMPLOYEES, PATIENTS, BOOKS, PRODUCTS, COURSES, MOVIES, ROOMS,
AND CUSTOMERS TABLES FROM YOUR PREVIOUS ASSIGNMENTS.

A. IN OPERATOR - PRACTICE QUESTIONS

1. DISPLAY STUDENTS WHOSE DEPARTMENT IS EITHER IT, CSE, OR ECE USING IN.
2. DISPLAY EMPLOYEES WHOSE DEPARTMENT IS EITHER IT, HR, OR FINANCE.
3. DISPLAY PATIENTS WHOSE BLOODGROUP IS EITHER A+, B+, OR O+.
4. DISPLAY BOOKS WHOSE CATEGORY IS EITHER TECHNOLOGY, HISTORY, OR SCIENCE.
5. DISPLAY PRODUCTS WHOSE CATEGORY IS EITHER ELECTRONICS, ACCESSORIES, OR FURNITURE.
6. DISPLAY COURSES OFFERED BY EITHER THE CSE, IT, OR ECE DEPARTMENT.
7. DISPLAY MOVIES WHOSE LANGUAGE IS EITHER TAMIL, ENGLISH, OR HINDI.
8. DISPLAY ROOMS WHOSE ROOMTYPE IS EITHER SINGLE, DOUBLE, OR DELUXE.
9. DISPLAY CUSTOMERS WHO ARE FROM CHENNAI, COIMBATORE, OR MADURAI.
10. DISPLAY EMPLOYEES WHOSE JOBROLE IS EITHER DEVELOPER, TESTER, OR ANALYST. */

SELECT * FROM STUDENTS WHERE DEPARTMENT IN ('IT', 'CSE','ECE');
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN ('IT','HR','FINANCE');
SELECT * FROM PATIENTS WHERE BLOOD_GROUP IN ('A+','B+','O+');
SELECT * FROM BOOKS WHERE CATEGORY IN ('TECHNOLOGY','HISTORY','SCIENCE');
SELECT * FROM PRODUCTS WHERE CATEGORY IN ('ELECTRONICS','ACCESSORIES','FURNITURE');
SELECT * FROM COURSES WHERE DEPARTMENT   IN ('CSE','IT','ECE');
SELECT * FROM MOVIES WHERE LANGUAGE IN ('TAMIL','ENGLISH','HINDI');
SELECT * FROM ROOMS WHERE ROOM_TYPE IN ('SINGLE','DOUBLE','DELUXE');
SELECT * FROM CUSTOMERS WHERE CITY IN ('CHENNAI','COIMBATORE','MADURAI');
SELECT * FROM EMPLOYEES WHERE JOB_ROLE IN ('DEVELOPER', 'TESTER','ANALYST');

/* 

B. NOT IN OPERATOR - PRACTICE QUESTIONS

11. DISPLAY STUDENTS WHO ARE NOT FROM THE IT, CSE, OR ECE DEPARTMENTS.
12. DISPLAY EMPLOYEES WHO ARE NOT FROM THE HR OR FINANCE DEPARTMENTS.
13. DISPLAY PATIENTS WHOSE BLOOD GROUP IS NOT A+, B+, OR O+.
14. DISPLAY BOOKS WHOSE CATEGORY IS NOT TECHNOLOGY OR HISTORY.
15. DISPLAY PRODUCTS WHOSE CATEGORY IS NOT ELECTRONICS OR ACCESSORIES.
16. DISPLAY COURSES THAT ARE NOT OFFERED BY THE CSE OR IT DEPARTMENTS.
17. DISPLAY MOVIES WHOSE LANGUAGE IS NOT TAMIL OR ENGLISH.
18. DISPLAY ROOMS WHOSE TYPE IS NOT SINGLE OR DOUBLE.
19. DISPLAY CUSTOMERS WHO ARE NOT FROM CHENNAI OR COIMBATORE.
20. DISPLAY EMPLOYEES WHOSE JOB ROLE IS NOT DEVELOPER, TESTER, OR ANALYST.

*/ 

SELECT * FROM students WHERE DEPARTMENT NOT IN ('ECE','IT','CSE');
SELECT * FROM EMPLOYEES WHERE DEPARTMENT NOT IN ('HR','FINANCE');
SELECT * FROM PATIENTS WHERE BLOOD_GROUP NOT IN ('A+','B+','O+');
SELECT * FROM BOOKS WHERE CATEGORY NOT IN ('TECHNOLOGY','HISTORY');
SELECT * FROM PRODUCTS WHERE CATEGORY NOT IN ('ELECTRONICS','ACCESSORIES');
SELECT * FROM COURSES WHERE DEPARTMENT NOT IN ('CSE','IT');
SELECT * FROM MOVIES WHERE LANGUAGE NOT IN ('TAMIL','ENGLISH');
SELECT * FROM ROOMS WHERE ROOM_TYPE NOT IN ('SINGLE','DOUBLE');
SELECT * FROM CUSTOMERS WHERE CITY NOT IN ('CHENNAI','COIMBATORE');
SELECT * FROM EMPLOYEES WHERE JOB_ROLE NOT IN ('DEVELOPER','TESTER','ANALYST');

/* 
  
C. IN WITH NUMERIC VALUES

21. DISPLAY STUDENTS WHOSE STUDENTID IS 101, 105, OR 110.
22. DISPLAY EMPLOYEES WHOSE EMPLOYEEID IS 201, 205, OR 210.
23. DISPLAY PRODUCTS WHOSE PRODUCTID IS 501, 505, OR 510.
24. DISPLAY BOOKS WHOSE PRICE IS 500, 750, OR 1000.
25. DISPLAY ROOMS WHOSE ROOMNUMBER IS 101, 205, OR 301. */

SELECT * FROM STUDENTS WHERE STUDENT_id IN (101,105,110);
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (201,205,210);
SELECT * FROM PRODUCTS WHERE PRODUCT_ID IN (501,505,510);
SELECT * FROM BOOKS WHERE PRICE IN (500,750,1000);
SELECT * FROM ROOMS WHERE ROOMNUMBER IN(101,205,301);

/*

D. NOT IN WITH NUMERIC VALUES
26. DISPLAY STUDENTS WHOSE STUDENTID IS NOT 101, 105, OR 110.
27. DISPLAY EMPLOYEES WHOSE EMPLOYEEID IS NOT 201, 205, OR 210.
28. DISPLAY PRODUCTS WHOSE PRODUCTID IS NOT 501, 505, OR 510.
29. DISPLAY BOOKS WHOSE PRICE IS NOT 500, 750, OR 1000.
30. DISPLAY ROOMS WHOSE ROOMNUMBER IS NOT 101, 205, OR 301.
*/

SELECT * FROM STUDENTS WHERE STUDENT_id NOT IN (101,105,110);
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID NOT IN (201,205,210);
SELECT * FROM PRODUCTS WHERE PRODUCT_ID NOT IN (501,505,510);
SELECT * FROM BOOKS WHERE PRICE NOT IN (500,750,1000);
SELECT * FROM ROOMS WHERE ROOMNUMBER NOT IN(101,205,301);

/* 

E. IN / NOT IN WITH CONDITIONS
31. DISPLAY EMPLOYEES FROM IT, HR, OR FINANCE WHOSE SALARY IS GREATER THAN 40000.
32. DISPLAY STUDENTS FROM CSE, IT, OR ECE WHOSE AGE IS GREATER THAN 20.
33. DISPLAY PRODUCTS BELONGING TO ELECTRONICS OR ACCESSORIES WITH PRICE GREATER THAN 5000.
34. DISPLAY BOOKS FROM TECHNOLOGY OR SCIENCE CATEGORIES WITH PRICE LESS THAN 1000.
35. DISPLAY CUSTOMERS FROM CHENNAI, BANGALORE, OR HYDERABAD WHOSE REGISTRATION DATE IS NOT NULL.
36. DISPLAY EMPLOYEES NOT FROM HR OR FINANCE WHOSE SALARY IS GREATER THAN 30000.
37. DISPLAY STUDENTS NOT FROM CSE OR IT WHOSE AGE IS GREATER THAN 21.
38. DISPLAY PRODUCTS NOT BELONGING TO ELECTRONICS OR FURNITURE WHOSE STOCK QUANTITY IS GREATER THAN 10.
39. DISPLAY MOVIES WHOSE LANGUAGE IS TAMIL, ENGLISH, OR HINDI AND WHOSE RATING IS GREATER THAN 4.
40. DISPLAY PATIENTS WHOSE BLOOD GROUP IS NOT A+, B+, OR O+ AND WHOSE AGE IS GREATER THAN 30.
*/

SELECT * FROM EMPLOYEES WHERE SALARY>40000 AND DEPARTMENT IN ('IT','HR','FINANCE');
SELECT * FROM STUDENTS WHERE AGE>20 AND DEPARTMENT IN ('CSE','IT','ECE');
SELECT * FROM PRODUCTS WHERE PRICE >5000 AND CATEGORY IN ('ELECTRONICS','ACCESSORIES');
SELECT * FROM BOOKS WHERE PRICE<1000 AND CATEGORY IN ('TECHNOLOGY','SCIENCE');
SELECT * FROM CUSTOMERS WHERE REGISTRATION_DATE IS NOT NULL AND CITY IN ('CHENNAI','BANGALORE','HYDERABAD');
SELECT * FROM EMPLOYEES WHERE SALARY > 30000 AND DEPARTMENT NOT IN ('HR','FINANCE');
SELECT * FROM  STUDENTS WHERE AGE>21 AND DEPARTMENT NOT IN ('CSE','IT');
SELECT * FROM PRODUCTS WHERE STOCK_QUANTITY >10 AND CATEGORY NOT IN ('ELECTRONICS','FURNITURE');
SELECT * FROM MOVIES WHERE RATING > 4.0 AND LANGUAGE IN ('TAMIL','ENGLISH','HINDI');
SELECT * FROM PATIENTS WHERE AGE > 30 AND BLOOD_GROUP NOT IN ('A+','B+','O+');


