#Date: 24th August 2026
#Topics Covered:

/* DISTINCT
OBJECTIVE: PRACTICE USING DISTINCT TO RETRIEVE UNIQUE/NON-DUPLICATE VALUES FROM A TABLE.
USE THE TABLES FROM YOUR PREVIOUS ASSIGNMENTS: STUDENTS, EMPLOYEES, PATIENTS, BOOKS,
PRODUCTS, COURSES, MOVIES, AND CUSTOMERS.

A. BASIC DISTINCT

1. DISPLAY ALL UNIQUE DEPARTMENTS FROM THE STUDENTS TABLE.
2. DISPLAY ALL UNIQUE GENDERS FROM THE STUDENTS TABLE.
3. DISPLAY ALL UNIQUE DEPARTMENTS FROM THE EMPLOYEES TABLE.
4. DISPLAY ALL UNIQUE JOB ROLES/DESIGNATIONS FROM THE EMPLOYEES TABLE.
5. DISPLAY ALL UNIQUE BLOOD GROUPS FROM THE PATIENTS TABLE.
6. DISPLAY ALL UNIQUE DISEASES FROM THE PATIENTS TABLE.
7. DISPLAY ALL UNIQUE BOOK CATEGORIES FROM THE BOOKS TABLE.
8. DISPLAY ALL UNIQUE AUTHORS FROM THE BOOKS TABLE.
9. DISPLAY ALL UNIQUE PRODUCT CATEGORIES FROM THE PRODUCTS TABLE.
10. DISPLAY ALL UNIQUE BRANDS FROM THE PRODUCTS TABLE.
11. DISPLAY ALL UNIQUE DEPARTMENTS FROM THE COURSES TABLE.
12. DISPLAY ALL UNIQUE COURSE DURATIONS FROM THE COURSES TABLE.
13. DISPLAY ALL UNIQUE LANGUAGES FROM THE MOVIES TABLE.
14. DISPLAY ALL UNIQUE GENRES FROM THE MOVIES TABLE.
15. DISPLAY ALL UNIQUE CITIES FROM THE CUSTOMERS TABLE.
16. DISPLAY ALL UNIQUE STATES FROM THE CUSTOMERS TABLE.
17. DISPLAY ALL UNIQUE COUNTRIES FROM THE CUSTOMERS TABLE.
18. DISPLAY ALL UNIQUE EMPLOYEE DEPARTMENTS AND JOB ROLES.
19. DISPLAY ALL UNIQUE PRODUCT CATEGORIES AND BRANDS.
20. DISPLAY ALL UNIQUE COMBINATIONS OF CITY AND STATE FROM THE CUSTOMERS TABLE. */

select distinct department from students;
select distinct gender from students;
select distinct department from employee;
select distinct designation from employee;
select distinct blood_group from patients;
select distinct diseases from patients;
select distinct book_categories from books;
select distinct authour from books;
select distinct product_category from products;
select distinct brands from products;
select distinct department from courses;
select distinct course_duration from courses;
select distinct languages from movies;
select distinct genre from movies;
select distinct city from customers;
select distinct state from customers;
select distinct country from customers;
select distinct employee_department, Job_role from employees;
select distinct product_category, brand from products;
select distinct city, state from customers;

/* 
B. DISTINCT WITH CONDITIONS

21. DISPLAY UNIQUE DEPARTMENTS OF STUDENTS WHOSE AGE IS GREATER THAN 20.
22. DISPLAY UNIQUE JOB ROLES OF EMPLOYEES WHOSE SALARY IS GREATER THAN 40,000.
23. DISPLAY UNIQUE DISEASES OF PATIENTS WHOSE AGE IS GREATER THAN 30.
24. DISPLAY UNIQUE BOOK CATEGORIES WHERE THE PRICE IS GREATER THAN 500.
25. DISPLAY UNIQUE PRODUCT BRANDS WHERE THE PRICE IS GREATER THAN 10,000.
26. DISPLAY UNIQUE MOVIE GENRES WHERE THE RATING IS GREATER THAN 4.
27. DISPLAY UNIQUE CUSTOMER CITIES WHERE THE COUNTRY IS 'INDIA'.
28. DISPLAY UNIQUE DEPARTMENTS FROM STUDENTS BELONGING TO EITHER 'IT' OR 'CSE'.
29. DISPLAY UNIQUE EMPLOYEE DEPARTMENTS WHERE SALARY IS BETWEEN 30,000 AND 60,000.
30. DISPLAY UNIQUE PRODUCT CATEGORIES WHERE STOCK QUANTITY IS GREATER THAN 10. */

SELECT DISTINCT DEPARTMENT FROM STUDENTS WHERE AGE>20;
SELECT DISTINCT JOB_ROLES FROM EMPLOYEES WHERE SALARY>40000;
SELECT DISTINCT DISEASES FROM PATIENTS WHERE AGE>30;
SELECT DISTINCT BOOK_CATEGORIES FROM BOOKS WHERE PRICE>500;
SELECT DISTINCT BRANDS FROM PRODUCTS WHERE PRICE>10000;
SELECT DISTINCT GENRE FROM MOVIES WHERE RATING > 4.0;
SELECT DISTINCT CITY FROM CUSTOMERS WHERE COUNTRY = 'INDIA';
SELECT DISTINCT DEPARTMENT FROM STUDENTS WHERE DEPARTMENT IN ('CSE','IT');
SELECT DISTINCT DEPARTMENT FROM EMPLOYEES WHERE SALARY BETWEEN 30000 AND 60000;
SELECT DISTINCT CATEGORIES FROM PRODUCT WHERE STOCK_QUANTITY>10;

/* 
C. DISTINCT WITH OTHER OPERATORS

31. DISPLAY UNIQUE STUDENT DEPARTMENTS USING IN FOR 'IT', 'CSE', AND 'ECE'.
32. DISPLAY UNIQUE EMPLOYEE DEPARTMENTS USING NOT IN FOR 'HR' AND 'FINANCE'.
33. DISPLAY UNIQUE PRODUCT CATEGORIES WHERE PRICE IS BETWEEN 5,000 AND 50,000.
34. DISPLAY UNIQUE BOOK CATEGORIES WHERE PRICE IS NOT BETWEEN 500 AND 1,000.
35. DISPLAY UNIQUE CUSTOMER CITIES WHERE EMAIL IS NOT NULL.
36. DISPLAY UNIQUE CUSTOMER CITIES WHERE EMAIL IS NULL.
37. DISPLAY UNIQUE EMPLOYEE DEPARTMENTS WHERE SALARY IS GREATER THAN 50,000.
38. DISPLAY UNIQUE STUDENT DEPARTMENTS WHERE AGE IS NOT BETWEEN 18 AND 25.
39. DISPLAY UNIQUE PRODUCT BRANDS WHERE THE BRAND IS NOT NULL.
40. DISPLAY UNIQUE PATIENT BLOOD GROUPS WHERE THE DISEASE IS NULL. */

SELECT DISTINCT DEPARTMENT FROM STUDENTS WHERE DEPARTMENT IN ('IT','CSE','ECE');
SELECT DISTINCT DEPARTMENT FROM EMPLOYEES WHERE DEPARTMENT NOT IN ('HR','FINANCE');
SELECT DISTINCT CATEGORIES FROM PRODUCTS WHERE PRICE BETWEEN 5000 AND 50000;
SELECT DISTINCT CATEGORIES FROM PRODUCTS WHERE PRICE NOT BETWEEN 500 AND 1000;
SELECT DISTINCT CITY FROM CUSTOMERS WHERE EMAIL IS NOT NULL;
SELECT DISTINCT CITY FROM CUSTOMERS WHERE EMAIL IS NULL;
SELECT DISTINCT DEPARTMENT FROM EMPLOYEES WHERE SALARY >50000;
SELECT DISTINCT DEPARTMENT FROM STUDENTS WHERE AGE NOT BETWEEN 18 AND 25;
SELECT DISTINCT BRAND FROM PRODUCT WHERE BRAND IS NOT NULL;
SELECT DISTINCT BLOOD_GROUP FROM PATIENTS WHERE DISEASE IS NULL;
