#Date: 25th August 2026
#Class covered: 24th August 2026
#Topics Covered:

/* LOGICAL OPERATORS

TOPICS COVERED - • AND, • OR, • NOT
OBJECTIVE: PRACTICE COMBINING MULTIPLE CONDITIONS IN SQL USING LOGICAL OPERATORS.
USE THE STUDENTS, EMPLOYEES, PATIENTS, BOOKS, PRODUCTS, COURSES, MOVIES, AND CUSTOMERS TABLES FROM YOUR PREVIOUS ASSIGNMENTS.


A. AND OPERATOR - 20 QUESTIONS

1. DISPLAY STUDENTS WHO ARE FROM THE IT DEPARTMENT AND WHOSE AGE IS GREATER THAN 20.
2. DISPLAY STUDENTS WHOSE AGE IS BETWEEN 18 AND 25 AND WHOSE GENDER IS 'FEMALE'.
3. DISPLAY EMPLOYEES WHO WORK IN THE IT DEPARTMENT AND HAVE A SALARY GREATER THAN 40000.
4. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN 50000 AND WHOSE DESIGNATION IS 'DEVELOPER'.
5. DISPLAY PATIENTS WHOSE AGE IS GREATER THAN 30 AND WHOSE GENDER IS 'FEMALE'.
6. DISPLAY PATIENTS WHOSE BLOOD GROUP IS 'O+' AND WHOSE DISEASE IS 'FEVER'.
7. DISPLAY BOOKS WHOSE CATEGORY IS 'TECHNOLOGY' AND WHOSE PRICE IS GREATER THAN 500.
8. DISPLAY BOOKS WHOSE PRICE IS BETWEEN 500 AND 1000 AND WHOSE CATEGORY IS 'TECHNOLOGY'.
9. DISPLAY PRODUCTS WHOSE CATEGORY IS 'ELECTRONICS' AND WHOSE PRICE IS GREATER THAN 1000.
10. DISPLAY PRODUCTS WHOSE STOCK QUANTITY IS GREATER THAN 10 AND WHOSE PRICE IS LESS THAN 5000.
11. DISPLAY COURSES FROM THE CSE DEPARTMENT AND WHOSE FEES ARE GREATER THAN 30000.
12. DISPLAY COURSES WHOSE DURATION IS '6 MONTHS' AND WHOSE FEES ARE LESS THAN 50000.
13. DISPLAY MOVIES WHOSE LANGUAGE IS 'TAMIL' AND WHOSE RATING IS GREATER THAN 4.
14. DISPLAY CUSTOMERS FROM 'CHENNAI' AND WHOSE COUNTRY IS 'INDIA'.
15. DISPLAY STUDENTS WHOSE DEPARTMENT IS 'CSE' AND WHOSE AGE IS BETWEEN 18 AND 25.
16. DISPLAY EMPLOYEES FROM THE IT DEPARTMENT AND WHOSE SALARY IS BETWEEN 40000 AND 70000.
17. DISPLAY PRODUCTS FROM THE ELECTRONICS CATEGORY AND WHOSE BRAND IS 'SAMSUNG'.
18. DISPLAY BOOKS WHOSE AUTHOR IS 'JOHN' AND WHOSE PRICE IS GREATER THAN 500.
19. DISPLAY PATIENTS WHOSE DISEASE IS NOT NULL AND WHOSE AGE IS GREATER THAN 25.
20. DISPLAY CUSTOMERS WHOSE EMAIL IS NOT NULL AND WHOSE CITY IS 'CHENNAI'. */

SELECT * FROM STUDENTS WHERE DEPARTMENT = 'IT' AND AGE>20;
SELECT * FROM STUDENTS WHERE AGE BETWEEN 18 AND 25 AND GENDER = 'FEMALE';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT' AND SALARY >40000;
SELECT * FROM EMPLOYEES WHERE SALARY >50000 AND DESIGNATION = 'DEVELOPER';
SELECT * FROM PATIENTS WHERE AGE >30 AND GENDER = 'FEMALE';
SELECT * FROM PATIENTS WHERE BLOOD_GROUP = 'O+' AND DISEASE = 'FEVER';
SELECT * FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY' AND PRICE > 500;
SELECT * FROM BOOKS WHERE PRICE BETWEEN 500 AND 1000 AND CATEGORY = 'TECHNOLOGY';
SELECT * FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS' AND PRICE>1000;
SELECT * FROM PRODUCTS WHERE STOCK_QUANTITY > 10 AND PRICE <50000;
SELECT * FROM COURSES WHERE DEPARTMENT = 'CSE' AND FEES > 30000;
SELECT * FROM COURSES WHERE DURATION = '6 MONTHS' AND FEES <50000;
SELECT * FROM MOVIES WHERE LANGUAGE = 'TAMIL' AND RATING >4.0;
SELECT * FROM CUSTOMERS WHERE CITY = 'CHENNAI' AND COUNTRY = 'INDIA';
SELECT * FROM STUDENTS WHERE DEPARTMENT = 'CSE' AND AGE BETWEEN 18 AND 25;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT' AND SALARY BETWEEN 40000 AND 70000;
SELECT * FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS' AND BRAND = 'SAMSUNG';
SELECT * FROM BOOKS WHERE AUTHOR = 'JOHN' AND PRICE > 500;
SELECT * FROM PATIENTS WHERE DISEASE IS NOT NULL AND AGE > 25;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND CITY = 'CHENNAI';


/* B. OR OPERATOR - 20 QUESTIONS

21. DISPLAY STUDENTS WHO ARE FROM EITHER IT OR CSE.
22. DISPLAY STUDENTS WHOSE AGE IS LESS THAN 18 OR GREATER THAN 25.
23. DISPLAY EMPLOYEES FROM IT OR HR.
24. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN 60000 OR LESS THAN 30000.
25. DISPLAY PATIENTS WHOSE BLOOD GROUP IS A+ OR O+.
26. DISPLAY PATIENTS WHOSE DISEASE IS FEVER OR COLD.
27. DISPLAY BOOKS BELONGING TO THE TECHNOLOGY OR SCIENCE CATEGORY.
28. DISPLAY BOOKS WHOSE PRICE IS LESS THAN 500 OR GREATER THAN 1500.
29. DISPLAY PRODUCTS BELONGING TO ELECTRONICS OR ACCESSORIES.
30. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN 5000 OR STOCK QUANTITY IS LESS THAN 5.
31. DISPLAY COURSES OFFERED BY CSE OR IT.
32. DISPLAY COURSES WHOSE FEES ARE LESS THAN 25000 OR GREATER THAN 75000.
33. DISPLAY MOVIES WHOSE LANGUAGE IS TAMIL OR ENGLISH.
34. DISPLAY MOVIES WHOSE RATING IS GREATER THAN 4.5 OR LESS THAN 3.
35. DISPLAY CUSTOMERS FROM CHENNAI OR BANGALORE.
36. DISPLAY STUDENTS WHOSE DEPARTMENT IS CSE OR WHOSE AGE IS GREATER THAN 22.
37. DISPLAY EMPLOYEES WHOSE DESIGNATION IS DEVELOPER OR TESTER.
38. DISPLAY PRODUCTS WHOSE BRAND IS SAMSUNG OR APPLE.
39. DISPLAY BOOKS WHOSE CATEGORY IS TECHNOLOGY OR WHOSE PRICE IS GREATER THAN 1000.
40. DISPLAY PATIENTS WHOSE AGE IS GREATER THAN 50 OR WHOSE BLOOD GROUP IS O-. */

SELECT * FROM STUDENTS WHERE DEPARTMENT IN ('IT','CSE');
SELECT * FROM STUDENTS WHERE AGE<18 OR AGE>25;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN ('IT','HR');
SELECT * FROM EMPLOYEES WHERE SALARY > 60000 OR SALARY < 30000;
SELECT * FROM PATIENTS WHERE BLOOD_GROUP IN ('A+','O+');
SELECT * FROM PATIENTS WHERE DISEASE IN ('FEVER','COLD');
SELECT * FROM BOOKS WHERE CATEGORY IN ('TECHNOLOGY','SCIENCE');
SELECT * FROM BOOKS WHERE PRICE<500 OR PRICE>1500;
SELECT * FROM PRODUCTS WHERE CATEGORY IN ('ELECTRONICS','ACCESSORIES');
SELECT * FROM PRODUCTS WHERE PRICE>50000 OR STOCK_QUANTITY<5;
SELECT * FROM COURSES WHERE DEPARTMENT IN ('CSE','IT');
SELECT * FROM COURSES WHERE FEES < 25000 OR FEES > 75000;
SELECT * FROM MVIES WHERE LANGUAGE IN ('TAMIL','ENGLISH');
SELECT * FROM MOVIES WHERE RATING > 4.5 OR RATING <3;
SELECT * FROM CUSTOMERS WHERE CITY IN ('CHENNAI','BANGALORE');
SELECT * FROM STUDENTS WHERE DEPARTMENT = 'CSE' OR AGE>22;
SELECT * FROM EMPLOYEES WHERE DESIGNATION IN ('DEVELOPER','TESTER');
SELECT * FROM PRODUCTS WHERE BRAND IN ('SAMSUNG','APPLE');
SELECT * FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY' OR PRICE>1000;
SELECT * FROM PATIENTS WHERE AGE>50 OR BLOOD_GROUP = 'O-';


/* C. NOT OPERATOR - 20 QUESTIONS

41. DISPLAY STUDENTS WHO ARE NOT FROM THE IT DEPARTMENT.
42. DISPLAY STUDENTS WHOSE AGE IS NOT GREATER THAN 20.
43. DISPLAY EMPLOYEES WHO ARE NOT FROM THE HR DEPARTMENT.
44. DISPLAY EMPLOYEES WHOSE DESIGNATION IS NOT 'DEVELOPER'.
45. DISPLAY PATIENTS WHOSE GENDER IS NOT 'MALE'.
46. DISPLAY PATIENTS WHOSE BLOOD GROUP IS NOT 'O+'.
47. DISPLAY BOOKS WHOSE CATEGORY IS NOT 'TECHNOLOGY'.
48. DISPLAY BOOKS WHOSE PRICE IS NOT BETWEEN 500 AND 1000.
49. DISPLAY PRODUCTS WHOSE CATEGORY IS NOT 'ELECTRONICS'.
50. DISPLAY PRODUCTS WHOSE PRICE IS NOT GREATER THAN 1000.
51. DISPLAY COURSES WHOSE DEPARTMENT IS NOT 'CSE'.
52. DISPLAY COURSES WHOSE FEES ARE NOT BETWEEN 30000 AND 60000.
53. DISPLAY MOVIES WHOSE LANGUAGE IS NOT 'TAMIL'.
54. DISPLAY MOVIES WHOSE RATING IS NOT GREATER THAN 4.
55. DISPLAY CUSTOMERS WHO ARE NOT FROM CHENNAI.
56. DISPLAY STUDENTS WHOSE DEPARTMENT IS NOT CSE AND WHOSE AGE IS GREATER THAN 20.
57. DISPLAY EMPLOYEES WHO ARE NOT FROM IT AND WHOSE SALARY IS GREATER THAN 30000.
58. DISPLAY PRODUCTS WHOSE CATEGORY IS NOT ELECTRONICS AND WHOSE STOCK IS GREATER THAN 10.
59. DISPLAY BOOKS WHOSE CATEGORY IS NOT TECHNOLOGY OR WHOSE PRICE IS GREATER THAN 1000.
60. DISPLAY PATIENTS WHOSE DISEASE IS NOT 'FEVER'. */

SELECT * FROM STUDENTS WHERE NOT DEPARTMENT = 'IT';
SELECT * FROM STUDENTS WHERE NOT AGE>20;
SELECT * FROM EMPLOYEES WHERE NOT DEPARTMENT = 'HR';
SELECT * FROM EMPLOYEES WHERE NOT DESIGNATION = 'DEVELOPER';
SELECT * FROM PATIENTS WHERE NOT GENDER = 'MALE';
SELECT * FROM PATIENTS WHERE NOT BLOOD_GROUP = 'O+';
SELECT * FROM BOOKS WHERE NOT CATEGORY = 'TECHNOLOGY';
SELECT * FROM BOOKS WHERE NOT PRICE BETWEEN 500 AND 1000;
SELECT * FROM PRODUCTS WHERE MPT CATEGORY = 'ELECTRONICS';
SELECT * FROM PRODUCTS WHERE NOT PRICE >10000;
SELECT * FROM COURSES WHERE NOT DEPARTMENT = 'CSE';
SELECT * FROM COURSES WHERE NOT FEES BETWEEN 30000 AND 60000;
SELECT * FROM MOVIES WHERE NOT LANGUAGE = 'TAMIL';
SELECT * FROM MOVIES WHERE NOT RATING>4.0;
SELECT * FROM CUSTOMERS WHERE NOT CITY = 'CHENNAI';
SELECT * FROM STUDENTS WHERE NOT DEPARTMENT = 'CSE' AND AGE>20;
SELECT * FROM EMPLOYEES WHERE NOT DEPARTMENT = 'IT' AND SALARY >30000;
SELECT * FROM PRODUCTS WHERE NOT CATEGORY = 'ELECTRONICS' AND STOCK>10;
SELECT * FROM BOOKS WHERE NOT CATEGORY = 'TECHNOLOGY' OR PRICE>1000;
SELECT* FROM PATIENTS WHERE NOT DISEASE = 'FEVER';

/* D. MIXED LOGICAL OPERATOR PRACTICE

61. DISPLAY STUDENTS WHO ARE FROM IT AND WHOSE AGE IS GREATER THAN 20 OR WHOSE DEPARTMENT IS CSE.
62. DISPLAY EMPLOYEES WHO ARE FROM IT AND WHOSE SALARY IS GREATER THAN 50000 OR WHOSE DESIGNATION IS MANAGER.
63. DISPLAY PRODUCTS THAT ARE IN THE ELECTRONICS CATEGORY AND COST MORE THAN 10000 OR BELONG TO THE APPLE BRAND.
64. DISPLAY BOOKS THAT ARE IN THE TECHNOLOGY CATEGORY AND COST MORE THAN 500 OR ARE WRITTEN BY 'JOHN'.
65. DISPLAY PATIENTS WHO ARE FEMALE AND OLDER THAN 30 OR HAVE BLOOD GROUP O+.
66. DISPLAY CUSTOMERS FROM CHENNAI AND WHOSE EMAIL IS NOT NULL OR FROM BANGALORE.
67. DISPLAY STUDENTS WHOSE DEPARTMENT IS EITHER IT OR CSE AND WHOSE AGE IS GREATER THAN 20.
68. DISPLAY EMPLOYEES WHOSE DEPARTMENT IS EITHER IT OR HR AND WHOSE SALARY IS GREATER THAN 40000.
69. DISPLAY PRODUCTS WHOSE CATEGORY IS EITHER ELECTRONICS OR ACCESSORIES AND WHOSE PRICE IS BETWEEN 500 AND 5000.
70. DISPLAY MOVIES WHOSE LANGUAGE IS EITHER TAMIL OR ENGLISH AND WHOSE RATING IS GREATER THAN 4. */

SELECT * FROM STUDENTS WHERE DEPARTMENT = 'IT' AND AGE>20 OR DEPARTMENT = 'CSE';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT' AND SALARY >50000 OR DESIGNATION = 'MANAGER';
SELECT * FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS' AND PRICE>10000 OR BRAND = 'APPLE';
SELECT * FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY' AND PRICE > 500 OR AUTHOR = 'JOHN';
SELECT * FROM PATIENTS WHERE GENDER = 'FEMALE' AND AGE >30 OR BLOOD_GROUP = 'O+VE';
SELECT * FROM CUSTOMERS WHERE CITY = 'CHENNAI' AND EMAIL IS NOT NULL OR CITY = 'BANGALORE';
SELECT * FROM STUDNETS WHERE DEPARTMENT IN ('IT','CSE') AND AGE>20;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN ('IT','HR') AND SALARY>40000;
SELECT * FROM PRODUCTS WHERE CATEGORY IN ('ELECTRONICS','ACCESSORIES') AND PRICE BETWEEN 5000 AND 50000;
SELECT * FROM MOVIES WHERE LANGUAGE IN ('TAMIL','ENGLISH') AND RATING >4.0;

/* E. LOGICAL OPERATORS WITH NULL, IN, BETWEEN, AND LIKE

71. DISPLAY STUDENTS WHOSE DEPARTMENT IS IT AND WHOSE EMAIL IS NOT NULL.
72. DISPLAY EMPLOYEES WHOSE DEPARTMENT IS IT OR WHOSE EMAIL IS NULL.
73. DISPLAY PATIENTS WHOSE BLOOD GROUP IS A+ OR B+ AND WHOSE AGE IS GREATER THAN 25.
74. DISPLAY BOOKS WHOSE CATEGORY IS IN TECHNOLOGY, SCIENCE AND WHOSE PRICE IS BETWEEN 500 AND 1500.
75. DISPLAY PRODUCTS WHOSE BRAND IS NOT NULL AND WHOSE PRICE IS GREATER THAN 10000.
76. DISPLAY CUSTOMERS WHOSE CITY IS EITHER CHENNAI OR COIMBATORE AND WHOSE EMAIL IS NOT NULL.
77. DISPLAY STUDENTS WHOSE NAME STARTS WITH 'A' AND WHOSE AGE IS GREATER THAN 20.
78. DISPLAY EMPLOYEES WHOSE NAME CONTAINS 'AN' OR WHOSE SALARY IS GREATER THAN 50000.
79. DISPLAY PRODUCTS WHOSE NAME CONTAINS 'PHONE' AND WHOSE PRICE IS BETWEEN 5000 AND 50000.
80. DISPLAY BOOKS WHOSE NAME STARTS WITH 'S' OR WHOSE CATEGORY IS 'TECHNOLOGY'. */

SELECT * FROM STUDENTS WHERE DEPARTMENT = 'IT' AND EMAIL IS NOT NULL;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT' OR EMAIL IS NULL;
SELECT * FROM PATIENTS WHERE BLOOD_GROUP IN ('A+', 'B+') AND AGE > 25;
SELECT * FROM BOOKS WHERE CATEGORY IN ('TEHCNOLOGY', 'SCIENCE') AND PRICE BETWEEN 500 AND 1500;
SELECT * FROM PRODUCTS WHERE BRAND IS NOT NULL AND PRICE >10000;
SELECT * FROM CUSTOMERS WHERE CITY IN ('CHENNAI','COIMBATORE') AND EMAIL IS NOT NULL;
SELECT * FROM STUDENTS WHERE NAME LIKE 'A%' AND AGE > 20;
SELECT * FROM EMPLOYEES WHERE NAME LIKE '%AN%' OR SALARY > 50000;
SELECT * FROM PRODUCTS WHERE NAME LIKE '%PHONE%' AND PRICE BETWEEN 5000 AND 50000;
SELECT * FROM BOOKS WHERE NAME LIKE 'S%' OR CATEGORY = 'TECHNOLOGY';
