#Date: 25th August 2026
#Class conducted: 24th August 2026
#Topics covered:

/* LIKE & WILDCARDS

OBJECTIVE
PRACTICE PATTERN MATCHING USING THE LIKE OPERATOR WITH SQL WILDCARDS:
% → REPRESENTS ZERO, ONE, OR MULTIPLE CHARACTERS
_ → REPRESENTS EXACTLY ONE CHARACTER

USE THE TABLES FROM YOUR PREVIOUS ASSIGNMENTS:
STUDENTS, EMPLOYEES, PATIENTS, BOOKS, PRODUCTS, COURSES, MOVIES AND CUSTOMERS.

A. LIKE WITH %

1. DISPLAY STUDENTS WHOSE NAMES START WITH A.
2. DISPLAY STUDENTS WHOSE NAMES END WITH A.
3. DISPLAY STUDENTS WHOSE NAMES CONTAIN AN.
4. DISPLAY EMPLOYEES WHOSE NAMES START WITH R.
5. DISPLAY EMPLOYEES WHOSE NAMES END WITH N.
6. DISPLAY EMPLOYEES WHOSE NAMES CONTAIN AR.
7. DISPLAY PATIENTS WHOSE NAMES START WITH P.
8. DISPLAY PATIENTS WHOSE NAMES END WITH I.
9. DISPLAY PATIENTS WHOSE DISEASE CONTAINS FEVER.
10. DISPLAY BOOKS WHOSE NAMES START WITH S.
11. DISPLAY BOOKS WHOSE NAMES END WITH SQL.
12. DISPLAY BOOKS WHOSE NAMES CONTAIN DATA.
13. DISPLAY PRODUCTS WHOSE NAMES START WITH M.
14. DISPLAY PRODUCTS WHOSE NAMES END WITH PHONE.
15. DISPLAY PRODUCTS WHOSE NAMES CONTAIN BOOK.
16. DISPLAY CUSTOMERS WHOSE NAMES START WITH K.
17. DISPLAY CUSTOMERS WHOSE NAMES END WITH A.
18. DISPLAY CUSTOMERS WHOSE CITY CONTAINS PUR.
19. DISPLAY COURSES WHOSE NAMES CONTAIN DATA.
20. DISPLAY MOVIES WHOSE NAMES START WITH THE. */


SELECT * FROM STUDENTS WHERE NAME LIKE 'A%';
SELECT * FROM STUDENTS WHERE NAME LIKE '%A';
SELECT * FROM STUDENTS WHERE NAME LIKE '%AN%';
SELECT * FROM EMPLOYEES WHERE NAME LIKE 'R%';
SELECT * FROM EMPLOYEES WHERE NAME LIKE '%N';
SELECT * FROM EMPLOYEES WHERE NAME LIKE '%AR%';
SELECT * FROM PATIENTS WHERE NAME LIKE 'P%';
SELECT * FROM PATIENTS WHERE NAME LIKE '%I';
SELECT * FROM PATIENTS WHERE NAME LIKE '%FEVER%';
SELECT * FROM BOOKS WHERE NAME LIKE 'S%';
SELECT * FROM BOOKS WHERE NAME LIKE '%SQL';
SELECT * FROM BOOKS WHERE NAME LIKE '%DATA%';
SELECT * FROM PRODUCTS WHERE NAME LIKE 'M%';
SELECT * FROM PRODUCTS WHERE NAME LIKE '%PHONE';
SELECT * FROM PRODUCTS WHERE NAME LIKE '%BOOK%';
SELECT * FROM CUSTOMERS WHERE NAME LIKE 'K%';
SELECT * FROM CUSTOMERS WHERE NAME LIKE '%A';
SELECT * FROM CUSTOMERS WHERE CITY LIKE '%PUR%';
SELECT * FROM COURSES WHERE NAME LIKE '%DATA%';
SELECT * FROM MOVIES WHERE NAME LIKE 'THE%';

/* 
B. LIKE WITH _ - 20 QUESTIONS
REMEMBER:
  _ = EXACTLY ONE CHARACTER

21. DISPLAY STUDENTS WHOSE NAMES HAVE EXACTLY 5 CHARACTERS.
22. DISPLAY STUDENTS WHOSE NAMES HAVE EXACTLY 6 CHARACTERS.
23. DISPLAY EMPLOYEES WHOSE NAMES HAVE EXACTLY 5 CHARACTERS.
24. DISPLAY EMPLOYEES WHOSE NAMES START WITH A AND HAVE EXACTLY 5 CHARACTERS.
25. DISPLAY PATIENTS WHOSE NAMES HAVE EXACTLY 4 CHARACTERS.
26. DISPLAY BOOKS WHOSE NAMES HAVE EXACTLY 5 CHARACTERS.
27. DISPLAY PRODUCTS WHOSE NAMES HAVE EXACTLY 6 CHARACTERS.
28. DISPLAY CUSTOMERS WHOSE NAMES HAVE EXACTLY 5 CHARACTERS.
29. DISPLAY STUDENTS WHOSE SECOND CHARACTER IS A.
30. DISPLAY EMPLOYEES WHOSE SECOND CHARACTER IS R.
31. DISPLAY PATIENTS WHOSE THIRD CHARACTER IS I.
32. DISPLAY BOOKS WHOSE SECOND CHARACTER IS O.
33. DISPLAY PRODUCTS WHOSE SECOND CHARACTER IS A.
34. DISPLAY CUSTOMERS WHOSE SECOND CHARACTER IS A.
35. DISPLAY STUDENTS WHOSE FIRST CHARACTER IS A AND SECOND CHARACTER IS K.
36. DISPLAY EMPLOYEES WHOSE FIRST CHARACTER IS R AND THIRD CHARACTER IS H.
37. DISPLAY BOOKS WHOSE FIRST CHARACTER IS S AND THIRD CHARACTER IS L.
38. DISPLAY PRODUCTS WHOSE FIRST CHARACTER IS M AND FOURTH CHARACTER IS I.
39. DISPLAY CUSTOMERS WHOSE FIRST CHARACTER IS K AND LAST CHARACTER IS A.
40. DISPLAY MOVIES WHOSE NAMES HAVE EXACTLY 7 CHARACTERS.*/

SELECT * FROM STUDENTS WHERE NAME LIKE '_____';
SELECT * FROM STUDENTS WHERE NAME LIKE '______';
SELECT * FROM EMPLOYEES WHERE NAME LIKE '_____';
SELECT * FROM EMPLOYEES WHERE NAME LIKE 'A____';
SELECT * FROM PATIENTS WHERE NAME LIKE '____';
SELECT * FROM BOOKS WHERE NAME LIKE '_____';
SELECT * FROM PRODUCT WHERE NAME LIKE '______';
SELECT * FROM CUSTOMERS WHERE NAME LIKE '_____';
SELECT * FROM STUDENTS WHERE NAME LIKE '_A%';
SELECT * FROM EMPLOYEES WHERE NAME LIKE '_R%';
SELECT * FROM PATIENTS WHERE NAME LIKE '__I%';
SELECT * FROM BOOKS WHERE NAME LIKE '_O%';
SELECT * FROM PRODUCTS WHERE NAME LIKE '_A%';
SELECT * FROM CUSTOMERS WHERE NAME LIKE '_A%';
SELECT * FROM STUDENTS WHERE NAME LIKE 'AK%';
SELECT * FROM EMPLOYEES WHERE NAME LIKE 'R_H%';
SELECT * FROM BOOKS WHERE NAME LIKE 'S_L%';
SELECT * FROM PRODUCTS WHERE NAME LIKE 'M__I%';
SELECT * FROM CUSTOMERS WHERE NAME LIKE 'K%A';
SELECT * FROM MOVIES WHERE NAME LIKE '_______';

/* C. COMBINING % AND _

41. DISPLAY STUDENTS WHOSE NAMES START WITH A AND HAVE AT LEAST ONE MORE CHARACTER.
42. DISPLAY EMPLOYEES WHOSE NAMES START WITH R AND SHOW THEIR CHARACTER IS I.
43. DISPLAY PATIENTS WHOSE NAMES START WITH P AND END WITH A.
44. DISPLAY BOOKS WHOSE NAMES START WITH S AND CONTAIN AT LEAST ONE MORE CHARACTER.
45. DISPLAY PRODUCTS WHOSE NAMES START WITH M AND END WITH E.
46. DISPLAY CUSTOMERS WHOSE NAMES START WITH K AND END WITH A.
47. DISPLAY STUDENTS WHOSE NAMES HAVE A AS THE SECOND CHARACTER AND CAN CONTAIN ANY NUMBER OF CHARACTERS AFTER IT.
48. DISPLAY EMPLOYEES WHOSE NAMES HAVE R AS THE SECOND CHARACTER AND END WITH N.
49. DISPLAY BOOKS WHOSE NAMES START WITH D AND CONTAIN SQL.
50. DISPLAY PRODUCTS WHOSE NAMES CONTAIN PHONE AND END WITH ANY CHARACTER. */

SELECT * FROM STUDENTS WHERE NAME LIKE 'A_%';
SELECT * FROM EMPLOYEES WHERE NAME LIKE 'R_H%';
SELECT * FROM PATIENTS WHERE NAME LIKE 'P%A';
SELECT * FROM BOOKS WHERE NAME LIKE 'S_%';
SELECT * FROM PRODUCTS WHERE NAME LIKE 'M%E';
SELECT * FROM CUSTOMERS WHERE NAME LIKE 'K%A';
SELECT * FROM STUDENTS WHERE NAME LIKE '_A%';
SELECT * FROM EMPLOYEES WHERE NAME LIKE '_R%N';
SELECT * FROM BOOKS WHERE NAME LIKE 'D%SQL%';
SELECT * FROM PRODUCTS WHERE NAME LIKE '%PHONE_';

/* D. NOT LIKE – PRACTICE QUESTIONS

51. DISPLAY STUDENTS WHOSE NAMES DO NOT START WITH A.
52. DISPLAY EMPLOYEES WHOSE NAMES DO NOT END WITH N.
53. DISPLAY PATIENTS WHOSE DISEASE DOES NOT CONTAIN FEVER.
54. DISPLAY BOOKS WHOSE NAMES DO NOT START WITH S.
55. DISPLAY PRODUCTS WHOSE NAMES DO NOT CONTAIN PHONE.
56. DISPLAY CUSTOMERS WHOSE NAMES DO NOT END WITH A.
57. DISPLAY COURSES WHOSE NAMES DO NOT CONTAIN DATA.
58. DISPLAY MOVIES WHOSE NAMES DO NOT START WITH THE.
59. DISPLAY STUDENTS WHOSE NAMES DO NOT CONTAIN AN.
60. DISPLAY EMPLOYEES WHOSE NAMES DO NOT START WITH R. */

SELECT * FROM STUDENTS WHERE NAME NOT LIKE 'A%';
SELECT * FROM EMPLOYEES WHERE NAME NOT LIKE '%N';
SELECT * FROM PATIENTS WHERE NAME NOT LIKE '%FEVER%';
SELECT * FROM BOOKS WHERE NAME NOT LIKE 'S%';
SELECT * FROM PRODUCT WHERE NAME NOT LIKE '%PHONE%';
SELECT * FROM CUSTOMER WHERE NAME NOT LIKE '%A';
SELECT * FROM COURSES WHERE NAME NOT LIKE '%DATA%';
SELECT * FROM MOVIES WHERE NAME NOT LIKE 'THE%';
SELECT * FROM STUDENTS WHERE NAME NOT LIKE '%AN%';
SELECT * FROM EMPLOYEES WHERE NAME NOT LIKE 'R%';

/* 
E. LIKE WITH OTHER CONDITIONS

61. DISPLAY STUDENTS WHOSE NAMES START WITH A AND WHOSE AGE IS GREATER THAN 20.
62. DISPLAY EMPLOYEES WHOSE NAMES START WITH R AND WHOSE SALARY IS GREATER THAN 40,000.
63. DISPLAY PATIENTS WHOSE NAMES START WITH P AND WHOSE AGE IS BETWEEN 20 AND 40.
64. DISPLAY BOOKS WHOSE NAMES CONTAIN SQL AND WHOSE PRICE IS LESS THAN 1,000.
65. DISPLAY PRODUCTS WHOSE NAMES CONTAIN PHONE AND WHOSE PRICE IS GREATER THAN 5,000.
66. DISPLAY CUSTOMERS WHOSE NAMES START WITH K AND WHOSE CITY IS CHENNAI.
67. DISPLAY STUDENTS WHOSE DEPARTMENT IS IT AND WHOSE NAME STARTS WITH A.
68. DISPLAY EMPLOYEES WHOSE DEPARTMENT IS IT AND WHOSE NAME CONTAINS AR.
69. DISPLAY PRODUCTS WHOSE CATEGORY IS ELECTRONICS AND WHOSE BRAND STARTS WITH S.
70. DISPLAY MOVIES WHOSE LANGUAGE IS TAMIL AND WHOSE NAME STARTS WITH H. */



/* F. MIXED LIKE & WILDCARD CHALLENGE

71. FIND STUDENTS WHOSE NAMES START WITH A AND END WITH A.
72. FIND EMPLOYEES WHOSE NAMES START WITH S AND CONTAIN R.
73. FIND PATIENTS WHOSE NAMES CONTAIN RI.
74. FIND BOOKS WHOSE NAMES CONTAIN DATA ANYWHERE IN THE NAME.
75. FIND PRODUCTS WHOSE NAMES START WITH SMART.
76. FIND CUSTOMERS WHOSE CITY ENDS WITH PUR.
77. FIND COURSES WHOSE NAMES START WITH DATA AND CONTAIN SCIENCE.
78. FIND MOVIES WHOSE NAMES CONTAIN THE WORD LOVE.
79. FIND EMPLOYEES WHOSE NAMES HAVE EXACTLY 6 CHARACTERS AND START WITH A.
80. FIND STUDENTS WHOSE NAMES HAVE EXACTLY 5 CHARACTERS AND END WITH A. */


