#Date: 25th August 2026
#Class Covered: 24th August 2026
#Topics Covered:

/* AGGREGATE FUNCTIONS

TOPICS - • COUNT(), • SUM(), • MIN(), • MAX(), • AVG()
OBJECTIVE: PRACTICE CALCULATING SUMMARY VALUES FROM TABLES USING AGGREGATE FUNCTIONS.
USE THE STUDENTS, EMPLOYEES, PATIENTS, BOOKS, PRODUCTS, COURSES, AND CUSTOMERS TABLES FROM YOUR PREVIOUS ASSIGNMENTS.

A. COUNT() – 20 QUESTIONS

1. FIND THE TOTAL NUMBER OF STUDENTS.
2. FIND THE TOTAL NUMBER OF EMPLOYEES.
3. FIND THE TOTAL NUMBER OF PATIENTS.
4. FIND THE TOTAL NUMBER OF BOOKS.
5. FIND THE TOTAL NUMBER OF PRODUCTS.
6. FIND THE TOTAL NUMBER OF COURSES.
7. FIND THE TOTAL NUMBER OF CUSTOMERS.
8. COUNT THE NUMBER OF STUDENTS WHOSE DEPARTMENT IS IT.
9. COUNT THE NUMBER OF EMPLOYEES WORKING IN THE IT DEPARTMENT.
10. COUNT THE NUMBER OF PATIENTS WHOSE DISEASE IS NOT NULL.
11. COUNT THE NUMBER OF BOOKS AVAILABLE IN THE TECHNOLOGY CATEGORY.
12. COUNT THE NUMBER OF PRODUCTS BELONGING TO THE ELECTRONICS CATEGORY.
13. COUNT THE NUMBER OF STUDENTS WHOSE AGE IS GREATER THAN 20.
14. COUNT THE NUMBER OF EMPLOYEES WHOSE SALARY IS GREATER THAN 50000.
15. COUNT THE NUMBER OF PRODUCTS WHOSE PRICE IS BETWEEN 10000 AND 50000.
16. COUNT THE NUMBER OF CUSTOMERS FROM CHENNAI.
17. COUNT THE NUMBER OF STUDENTS WHOSE EMAIL IS NULL.
18. COUNT THE NUMBER OF EMPLOYEES WHOSE EMAIL IS NOT NULL.
19. COUNT THE NUMBER OF UNIQUE DEPARTMENTS IN THE STUDENTS TABLE.
20. COUNT THE NUMBER OF UNIQUE PRODUCT BRANDS. */

SELECT COUNT(*) FROM STUDENTS;
SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT(*) FROM PATIENTS;
SELECT COUNT(*) FROM BOOKS;
SELECT COUNT(*) FROM PRODUCTS;
SELECT COUNT(*) FROM COURSES;
SELECT COUNT(*) FROM CUSTOMERS;
SELECT COUNT(*) FROM STUDENTS WHERE DEPARTMENT = 'IT';
SELECT COUNT(*) FROM employees WHERE DEPARTMENT = 'IT';
SELECT COUNT(DISEASE) FROM PATIENTS;
SELECT COUNT(*) FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY';
SELECT COUNT(*) FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS';
SELECT COUNT(*) FROM STUDENTS WHERE AGE >20;
SELECT COUNT(*) FROM EMPLOYEES WHERE SALARY>50000;
SELECT COUNT(*) FROM PRODUCTS WHERE PRICE BETWEEN 10000 AND 50000;
SELECT COUNT(*) FROM  CUSTOMERS WHERE CITY = 'CHENNAI';
SELECT COUNT(*) FROM STUDENTS WHERE EMAIL IS NULL;
SELECT COUNT(EMAIL) FROM EMPLOYEES;
SELECT COUNT(DISTINCT DEPARTMENT) FROM STUDENTS;
SELECT COUNT(BRAND) FROM PRODUCTS;

/* B. SUM() – 20 QUESTIONS

21. FIND THE TOTAL SALARY PAID TO ALL EMPLOYEES.
22. FIND THE TOTAL SALARY PAID TO EMPLOYEES IN THE IT DEPARTMENT.
23. FIND THE TOTAL QUANTITY OF BOOKS AVAILABLE.
24. FIND THE TOTAL STOCK QUANTITY OF ALL PRODUCTS.
25. FIND THE TOTAL PRICE OF ALL PRODUCTS.
26. FIND THE TOTAL FEES OF ALL COURSES.
27. FIND THE TOTAL SALARY OF EMPLOYEES WHOSE SALARY IS GREATER THAN 40000.
28. FIND THE TOTAL PRICE OF PRODUCTS BELONGING TO THE ELECTRONICS CATEGORY.
29. FIND THE TOTAL QUANTITY OF BOOKS IN THE TECHNOLOGY CATEGORY.
30. FIND THE TOTAL STOCK OF PRODUCTS FROM THE SAMSUNG BRAND.
31. FIND THE TOTAL SALARY OF EMPLOYEES FROM HR.
32. FIND THE TOTAL FEES OF COURSES OFFERED BY THE CSE DEPARTMENT.
33. FIND THE TOTAL QUANTITY OF PRODUCTS WHOSE PRICE IS GREATER THAN 10000.
34. FIND THE TOTAL SALARY OF EMPLOYEES WHOSE AGE IS GREATER THAN 30 IF AN EMPLOYEE AGE COLUMN IS AVAILABLE.
35. FIND THE TOTAL PRICE OF BOOKS WHOSE CATEGORY IS TECHNOLOGY.
36. FIND THE TOTAL STOCK QUANTITY WHERE STOCK IS GREATER THAN 10.
37. FIND THE TOTAL SALARY OF EMPLOYEES WHOSE DESIGNATION IS DEVELOPER.
38. FIND THE TOTAL FEES OF COURSES WHOSE DURATION IS 6 MONTHS.
39. FIND THE TOTAL QUANTITY OF BOOKS WHOSE PRICE IS BETWEEN 500 AND 1000.
40. FIND THE TOTAL STOCK OF PRODUCTS WHOSE CATEGORY IS ELECTRONICS. */

SELECT SUM(SALARY) FROM EMPLOYEES;
SELECT SUM(SALARY) FROM employees WHERE DEPARTMENT = 'IT';
SELECT SUM(QUANTITY_BOOK) FROM BOOKS;
SELECT SUM(STOCK_QUANTITY) FROM PRODUCTS;
SELECT SUM(PRICE) FROM PRODUCTS;
SELECT SUM(FEES) FROM COURSES;
SELECT SUM(SALARY) FROM EMPLOYEES WHERE SALARY>40000;
SELECT SUM(PRICE) FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS';
SELECT SUM(TOTAL_QUANTITYOFBOOKS) FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY';
SELECT SUM(TOTAL_STOCK) FROM PRODUCTS WHERE BRAND = 'SAMSUNG';
SELECT SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR';
SELECT SUM(FEES) FROM COURSES WHERE DEPARTMENT = 'CSE';
SELECT SUM(QUANTITY) FROM PRODUCTS WHERE PRICE>10000;
SELECT SUM(SALARY) FROM EMPLOYEES WHERE AGE>30;
SELECT SUM(PRICE) FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY';
SELECT SUM(STOCK_QUANTITY) FROM PRODUCTS WHERE STOCK_QUANTITY>10;
SELECT SUM(SALARY) FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER';
SELECT SUM(FEES) FROM COURSES WHERE COURSE_DURATION = '6 MONTHS';
SELECT SUM(QUANTITY_OF_BOOKS) FROM BOOKS WHERE PRICE BETWEEN 500 AND 1000;
SELECT SUM(STOCK) FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS';

/* C. MIN() – 20 QUESTIONS

41. FIND THE MINIMUM SALARY AMONG ALL EMPLOYEES.
42. FIND THE MINIMUM SALARY IN THE IT DEPARTMENT.
43. FIND THE MINIMUM PRICE OF ALL BOOKS.
44. FIND THE MINIMUM PRICE OF PRODUCTS.
45. FIND THE MINIMUM COURSE FEE.
46. FIND THE MINIMUM AGE OF STUDENTS.
47. FIND THE MINIMUM AGE OF PATIENTS.
48. FIND THE MINIMUM QUANTITY OF BOOKS AVAILABLE.
49. FIND THE MINIMUM STOCK QUANTITY OF PRODUCTS.
50. FIND THE MINIMUM SALARY AMONG EMPLOYEES WHOSE DEPARTMENT IS HR.
51. FIND THE MINIMUM PRICE OF BOOKS IN THE TECHNOLOGY CATEGORY.
52. FIND THE MINIMUM PRICE OF PRODUCTS IN THE ELECTRONICS CATEGORY.
53. FIND THE MINIMUM COURSE FEE OFFERED BY THE CSE DEPARTMENT.
54. FIND THE MINIMUM SALARY AMONG EMPLOYEES WHOSE DESIGNATION IS DEVELOPER.
55. FIND THE MINIMUM AGE OF STUDENTS BELONGING TO THE IT DEPARTMENT.
56. FIND THE MINIMUM PRICE OF PRODUCTS WHOSE STOCK IS GREATER THAN 10.
57. FIND THE MINIMUM BOOK QUANTITY.
58. FIND THE MINIMUM SALARY AMONG EMPLOYEES WHOSE SALARY IS GREATER THAN 40000.
59. FIND THE MINIMUM PRODUCT PRICE FROM THE SAMSUNG BRAND.
60. FIND THE MINIMUM RATING AMONG MOVIES. */

SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT';
SELECT MIN(PRICE) FROM  BOOKS;
SELECT MIN(PRICE) FROM PRODUCTS;
SELECT MIN(FEES) FROM COURSES;
SELECT MIN(AGE) FROM STUDENTS;
SELECT MIN(AGE) FROM PATIENTS;
SELECT MIN(QUANTITY) FROM BOOKS;
SELECT MIN(QUANTITY) FROM PRODUCTS;
SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR';
SELECT MIN(PRICE) FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY';
SELECT MIN(PRICE) FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS';
SELECT MIN(FEES) FROM COURSES WHERE DEPARTMENT = 'CSE';
SELECT MIN(SALARY) FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER';
SELECT MIN(AGE) FROM STUDENTS WHERE DEPARTMENT = 'IT';
SELECT MIN(PRICE) FROM PRODUCTS WHERE STOCK_QUANTITY>10;
SELECT MIN(QUANTITY) FROM BOOKS;
SELECT MIN(SALARY) FROM EMPLOYEES WHERE SALARY > 40000;
SELECT MIN(PRICE) FROM PRODUCTS WHERE BRAND = 'SAMSUNG';
SELECT MIN(RATING) FROM MOVIES;

/* D. MAX() – 20 QUESTIONS

61. FIND THE MAXIMUM SALARY AMONG ALL EMPLOYEES.
62. FIND THE MAXIMUM SALARY IN THE IT DEPARTMENT.
63. FIND THE MAXIMUM PRICE OF ALL BOOKS.
64. FIND THE MAXIMUM PRICE OF ALL PRODUCTS.
65. FIND THE MAXIMUM COURSE FEE.
66. FIND THE MAXIMUM AGE OF STUDENTS.
67. FIND THE MAXIMUM AGE OF PATIENTS.
68. FIND THE MAXIMUM QUANTITY OF BOOKS AVAILABLE.
69. FIND THE MAXIMUM STOCK QUANTITY OF PRODUCTS.
70. FIND THE MAXIMUM SALARY AMONG EMPLOYEES IN THE HR DEPARTMENT.
71. FIND THE MAXIMUM PRICE OF BOOKS IN THE TECHNOLOGY CATEGORY.
72. FIND THE MAXIMUM PRICE OF PRODUCTS IN THE ELECTRONICS CATEGORY.
73. FIND THE MAXIMUM COURSE FEE OFFERED BY THE CSE DEPARTMENT.
74. FIND THE MAXIMUM SALARY OF EMPLOYEES WHOSE DESIGNATION IS DEVELOPER.
75. FIND THE MAXIMUM AGE OF STUDENTS BELONGING TO THE IT DEPARTMENT.
76. FIND THE MAXIMUM PRODUCT PRICE WHERE STOCK IS GREATER THAN 10.
77. FIND THE MAXIMUM BOOK QUANTITY.
78. FIND THE MAXIMUM SALARY AMONG EMPLOYEES WHOSE SALARY IS GREATER THAN 40000.
79. FIND THE MAXIMUM PRODUCT PRICE FROM THE SAMSUNG BRAND.
80. FIND THE MAXIMUM MOVIE RATING. */

SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT';
SELECT MAX(PRICE) FROM  BOOKS;
SELECT MAX(PRICE) FROM PRODUCTS;
SELECT MAX(FEES) FROM COURSES;
SELECT MAX(AGE) FROM STUDENTS;
SELECT MAX(AGE) FROM PATIENTS;
SELECT MAX(QUANTITY) FROM BOOKS;
SELECT MAX(QUANTITY) FROM PRODUCTS;
SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR';
SELECT MAX(PRICE) FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY';
SELECT MAX(PRICE) FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS';
SELECT MAX(FEES) FROM COURSES WHERE DEPARTMENT = 'CSE';
SELECT MAX(SALARY) FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER';
SELECT MAX(AGE) FROM STUDENTS WHERE DEPARTMENT = 'IT';
SELECT MAX(PRICE) FROM PRODUCTS WHERE STOCK_QUANTITY>10;
SELECT MAX(QUANTITY) FROM BOOKS;
SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY > 40000;
SELECT MAX(PRICE) FROM PRODUCTS WHERE BRAND = 'SAMSUNG';
SELECT MAX(RATING) FROM MOVIES;

/* E. AVG() – 20 QUESTIONS

81. FIND THE AVERAGE SALARY OF ALL EMPLOYEES.
82. FIND THE AVERAGE SALARY OF EMPLOYEES IN THE IT DEPARTMENT.
83. FIND THE AVERAGE PRICE OF ALL BOOKS.
84. FIND THE AVERAGE PRICE OF ALL PRODUCTS.
85. FIND THE AVERAGE COURSE FEE.
86. FIND THE AVERAGE AGE OF STUDENTS.
87. FIND THE AVERAGE AGE OF PATIENTS.
88. FIND THE AVERAGE QUANTITY OF BOOKS.
89. FIND THE AVERAGE STOCK QUANTITY OF PRODUCTS.
90. FIND THE AVERAGE SALARY OF EMPLOYEES IN THE HR DEPARTMENT.
91. FIND THE AVERAGE PRICE OF BOOKS IN THE TECHNOLOGY CATEGORY.
92. FIND THE AVERAGE PRICE OF PRODUCTS IN THE ELECTRONICS CATEGORY.
93. FIND THE AVERAGE COURSE FEE OFFERED BY THE CSE DEPARTMENT.
94. FIND THE AVERAGE SALARY OF EMPLOYEES WHOSE DESIGNATION IS DEVELOPER.
95. FIND THE AVERAGE AGE OF STUDENTS BELONGING TO THE IT DEPARTMENT.
96. FIND THE AVERAGE PRODUCT PRICE WHERE STOCK QUANTITY IS GREATER THAN 10.
97. FIND THE AVERAGE QUANTITY OF BOOKS WHOSE PRICE IS BETWEEN 500 AND 1000.
98. FIND THE AVERAGE SALARY OF EMPLOYEES WHOSE SALARY IS GREATER THAN 40000.
99. FIND THE AVERAGE PRICE OF PRODUCTS FROM THE SAMSUNG BRAND.
100. FIND THE AVERAGE RATING OF ALL MOVIES. */

SELECT avg (SALARY) FROM EMPLOYEES;
SELECT AVG (SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT';
SELECT AVG (PRICE) FROM  BOOKS;
SELECT AVG (PRICE) FROM PRODUCTS;
SELECT AVG (FEES) FROM COURSES;
SELECT AVG (AGE) FROM STUDENTS;
SELECT AVG (AGE) FROM PATIENTS;
SELECT AVG (QUANTITY) FROM BOOKS;
SELECT AVG (QUANTITY) FROM PRODUCTS;
SELECT AVG (SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR';
SELECT AVG (PRICE) FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY';
SELECT AVG (PRICE) FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS';
SELECT AVG (FEES) FROM COURSES WHERE DEPARTMENT = 'CSE';
SELECT AVG (SALARY) FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER';
SELECT AVG (AGE) FROM STUDENTS WHERE DEPARTMENT = 'IT';
SELECT AVG (PRICE) FROM PRODUCTS WHERE STOCK_QUANTITY>10;
SELECT AVG (QUANTITY) FROM BOOKS;
SELECT AVG (SALARY) FROM EMPLOYEES WHERE SALARY > 40000;
SELECT AVG (PRICE) FROM PRODUCTS WHERE BRAND = 'SAMSUNG';
SELECT AVG (RATING) FROM MOVIES;
