#Date: 25th August 2026
#Topics Covered:

/* SCALAR FUNCTIONS

A. STRING SCALAR FUNCTIONS - 20 QUESTIONS

1. DISPLAY ALL STUDENT NAMES IN UPPERCASE USING UPPER().
2. DISPLAY ALL EMPLOYEE NAMES IN LOWERCASE USING LOWER().
3. DISPLAY THE LENGTH OF EACH STUDENT'S NAME USING LENGTH().
4. DISPLAY EMPLOYEE NAMES ALONG WITH THEIR FIRST 3 CHARACTERS USING LEFT().
5. DISPLAY STUDENT NAMES ALONG WITH THEIR LAST 3 CHARACTERS USING RIGHT().
6. DISPLAY THE FIRST 5 CHARACTERS OF EACH PRODUCT NAME.
7. DISPLAY THE LAST 4 CHARACTERS OF EACH BOOK NAME.
8. DISPLAY STUDENT FIRST NAME AND LAST NAME AS A SINGLE FULL NAME USING CONCAT().
9. DISPLAY EMPLOYEE NAME AND DEPARTMENT AS ONE COMBINED COLUMN.
10. DISPLAY PRODUCT NAME AND BRAND AS ONE COMBINED COLUMN.
11. REMOVE LEADING AND TRAILING SPACES FROM STUDENT NAMES USING TRIM().
12. DISPLAY THE FIRST 4 CHARACTERS OF EACH EMPLOYEE NAME USING SUBSTRING().
13. EXTRACT CHARACTERS FROM POSITION 2 TO 5 FROM EACH PRODUCT NAME.
14. DISPLAY EACH STUDENT'S NAME IN UPPERCASE AND ITS LENGTH.
15. DISPLAY EACH EMPLOYEE'S NAME IN LOWERCASE AND ITS LENGTH.
16. DISPLAY CUSTOMER FIRST NAME AND CITY USING CONCAT().
17. DISPLAY BOOK NAME AND CATEGORY AS A SINGLE COLUMN SEPARATED BY ' - '.
18. DISPLAY EMPLOYEE NAME AND DESIGNATION AS A SINGLE COLUMN.
19. DISPLAY PRODUCT NAME IN UPPERCASE AND BRAND IN LOWERCASE.
20. DISPLAY THE FIRST CHARACTER AND LAST CHARACTER OF EVERY STUDENT'S NAME. */

SELECT UPPER(STUDNET_NAME) FROM STUDENTS;
SELECT LOWER(EMPLOYEE_NAME) FROM EMPLOYEES;
SELECT LEN(STUDENT_NAME) FROM STUDENTS;
SELECT EMPLOYEE_NAME, LEFT(EMPLOYEE_NAME, 3) AS FIRST_THREE FROM EMPLOYEES;
SELECT STUDNET_NAME, RIGHT(STUDENT_NAME, 3) AS LAST_THREE FROM STUDENTS;
SELECT SUBSTRING(PRODUCT_NAME,1,6) FROM PRODUCTS;
SELECT RIGHT(BOOK_NAME,4) FROM BOOKS;
SELECT CONCAT(FIRST_NAME, LAST_NAME) AS FULL_NAME FROM STUDENTS;
SELECT CONCAT(EMPLOYEE_NAME, DEPARTMENT) AS COMBINED_COLUMN FROM EMPLOYEES;
SELECT CONCAT(PRODUCT_NAME, BRAND) AS COMBINED_COLUMN FROM PRODUCTS;
SELECT TRIM(STUDENT_NAME) AS TRIMED_NAME FROM STUDENTS;
SELECT SUBSTRING(EMPLOYEE_NAME,1,4) AS FIRST_4_CHAR FROM EMPLOYEES;
SELECT SUBSTRING (PRODUCT_NAME, 2,5) AS CHARACTERS FROM PRODUCTS;
SELECT STUDENT_NAME, UPPER(STUDENT_NAME) AS UPPER_NAME, LEN(STUDENT_NAME) AS LENGHT FROM STUDENTS;
SELECT EMPLOYEE_NAME, LOWER(EMPLOYEE_NAME) AS LOWER_NAME, LEN(EMPLOYEE_NAME) AS LENGTH FROM EMPLOYEES;
SELECT CONCAT(FIRST_NAME, CITY) AS COMBINED_NAME FROM CUSTOMERS;
SELECT CONCAT(BOOK_NAME,' - ' , CATEGORY) AS COMBINED_COLUMN FROM BOOKS;
SELECT CONCAT(EMPLOYEE_NAME,' - ', DESIGNATION) AS COMBINED_COLUMN FROM EMPLOYEES;
SELECT UPPER(PRODUCT_NAME) AS UPPER_NAME, LOWER(BRAND) AS BRAND_NAME FROM PRODUCTS;
SELECT LEFT(STUDENT_NAME,1) AS FIRST_CHAR, RIGHT(STUDENT_NAME,1) AS LAST_CHAR FROM STUDENTS;


/* B. NUMERIC SCALAR FUNCTIONS - 20 QUESTIONS

21. DISPLAY EMPLOYEE SALARY ROUNDED TO THE NEAREST INTEGER USING ROUND().
22. ROUND PRODUCT PRICES TO 2 DECIMAL PLACES.
23. ROUND COURSE FEES TO THE NEAREST 100.
24. DISPLAY THE CEILING VALUE OF EACH PRODUCT PRICE USING CEIL().
25. DISPLAY THE FLOOR VALUE OF EACH PRODUCT PRICE USING FLOOR().
26. FIND THE ABSOLUTE DIFFERENCE BETWEEN EMPLOYEE SALARY AND 50000 USING ABS().
27. CALCULATE THE REMAINDER WHEN EACH PRODUCT PRICE IS DIVIDED BY 1000 USING MOD().
28. CALCULATE SALARY * 12 FOR EVERY EMPLOYEE.
29. CALCULATE A 10% INCREMENT FOR EVERY EMPLOYEE'S SALARY.
30. CALCULATE A 15% DISCOUNT FOR EVERY PRODUCT.
31. CALCULATE THE FINAL PRODUCT PRICE AFTER APPLYING A 10% DISCOUNT.
32. CALCULATE THE SQUARE OF EACH STUDENT'S AGE USING POWER().
33. CALCULATE THE CUBE OF EACH PRODUCT QUANTITY.
34. DISPLAY THE ABSOLUTE DIFFERENCE BETWEEN PRODUCT PRICE AND 10000.
35. DISPLAY THE CEILING VALUE OF COURSE FEES.
36. DISPLAY THE FLOOR VALUE OF BOOK PRICES.
37. CALCULATE THE REMAINDER OF EACH EMPLOYEE SALARY WHEN DIVIDED BY 10000.
38. CALCULATE THE TOTAL VALUE OF EACH PRODUCT USING PRICE * QUANTITY.
39. CALCULATE THE ANNUAL SALARY OF EACH EMPLOYEE.
40. CALCULATE THE SALARY AFTER A 20% INCREMENT AND ROUND IT TO 2 DECIMAL PLACES. */

SELECT ROUND(SALARY,2) FROM EMPLOYEES;
SELECT ROUND(PRICE,2) FROM PRODUCTS;
SELECT ROUND(FEES,-2) FROM COURSES;
SELECT CEIL(PRICE) FROM PRODUCTS;
SELECT FLOOR(PRICE) FROM PRODUCTS;
SELECT ABS(SALARY-50000) AS REMAINING FROM EMPLOYEES;
SELECT MOD(PRICE,1000) AS REMAINDER FROM PRODUCTS;
SELECT SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEES;
SELECT SALARY*1.10 AS INCREMENT FROM EMPLOYEES;
SELECT PRICE*0.85 AS DISCOUNT_PRICE FROM PRODUCTS;
SELECT PRICE*0.90 AS DOSCOUNTED_PRICE FROM PRODUCTS;
SELECT POWER(STUDENT_AGE,2) AS SQUARE FROM STUDENTS;
SELECT POWER(QUANTITY,3) AS CUBEVALUE FROM PRODUCTS;
SELECT ABS(PRICE-10000) AS DIFFERENCE FROM PRODUCTS;
SELECT CEIL(FEES) AS COURSE_FEES FROM COURSES;
SELECT FLOOR(PRICE) AS PRICE FROM PRODUCTS;
SELECT MOD(SALARY,10000) AS REMAINDER FROM EMPLOYEES;
SELECT PRICE*QUANTITY AS TOTA_VALUE FROM PRODUCTS;
SELECT SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEES;
SELECT ROUND(SALARY*1.10,2) AS INCREMENT_ROUNDOFF FROM EMPLOYEES;



/* C. DATE & TIME SCALAR FUNCTIONS - 20 QUESTIONS

41. DISPLAY THE CURRENT DATE USING CURRENT_DATE().
42. DISPLAY THE CURRENT TIME USING CURRENT_TIME().
43. DISPLAY THE CURRENT DATE AND TIME USING CURRENT_TIMESTAMP().
44. DISPLAY THE CURRENT DATE AND TIME USING NOW().
45. EXTRACT THE YEAR FROM EACH EMPLOYEE'S JOINING DATE USING YEAR().
46. EXTRACT THE MONTH FROM EACH EMPLOYEE'S JOINING DATE USING MONTH().
47. EXTRACT THE DAY FROM EACH EMPLOYEE'S JOINING DATE USING DAY().
48. EXTRACT THE YEAR FROM EACH CUSTOMER'S REGISTRATION DATE.
49. EXTRACT THE MONTH FROM EACH CUSTOMER'S REGISTRATION DATE.
50. EXTRACT THE DAY FROM EACH CUSTOMER'S REGISTRATION DATE.
51. DISPLAY THE JOINING DATE AND THE DATE 30 DAYS AFTER JOINING USING DATE_ADD().
52. DISPLAY THE JOINING DATE AND THE DATE 90 DAYS AFTER JOINING.
53. DISPLAY THE JOINING DATE AND THE DATE 42 DAYS BEFORE JOINING USING DATE_SUB().
54. DISPLAY THE REGISTRATION DATE AND THE DATE 126 DAYS AFTER REGISTRATION.
55. DISPLAY THE REGISTRATION DATE AND THE DATE 30 DAYS BEFORE REGISTRATION.
56. DISPLAY EMPLOYEE JOINING DATES IN DD-MM-YYYY FORMAT USING DATE_FORMAT().
57. DISPLAY CUSTOMER REGISTRATION DATES IN MM/DD/YYYY FORMAT.
58. DISPLAY PRODUCT MANUFACTURING DATES IN YYYY-MM-DD FORMAT.
59. EXTRACT THE YEAR AND MONTH FROM EACH EMPLOYEE JOINING DATE.
60. CALCULATE THE DIFFERENCE IN DAYS BETWEEN TWO DATE COLUMNS USING DATEDIFF(). */

SELECT CURRENT_DATE() AS DATE;
SELECT CURRENT_TIME() AS TIME_NOW;
SELECT CURRENT_TIMESTAMP() AS TIMESTAMP_NOW();
SELECT NOW() AS TIME_NOW();
SELECT YEAR(JOINING_DATE) AS YEAR;
SELECT MONTH(JOINING_DATE) AS MONTH;
SELECT DAY(JOINING_DATE) AS DAY;
SELECT YEAR(REGISTRATION_DATE) AS CUSTOMERYEAR;
SELECT MONTH(REGISTRATION_DATE) AS CUSTOMERMONTH;
SELECT DAY(REGISTRATION_DATE) AS CUSTOMERDAY;
SELECT DATE_ADD(JOIN_DATE,30) AS FUTURE_DATE FROM EMPLOYEES;
SELECT DATE_ADD(JOIN_DATE, 90) AS FUTURE_DATE FROM EMPLOYEES;
SELECT DATE_SUB(JOIN_DATE, 42) AS BEFORE_DATE FROM EMPLOYEES;
SELECT DATE_ADD(REGISTRATION_DATE, 126) FUTURE_DATE FROM CUSTOMERS;
SELECT DATE_SUB(REGISTRATION_DATE,30) BEFORE_DATE FROM CUSTOMERS;
SELECT DATE_FORMAT(JOINING_DATE,'DD-MM-YYYY') AS JOIN_DATE FROM EMPLOYEES;
SELECT DATE_FORMAT(REGISTRATION_DATE, 'MM/DD/YYYY') AS REG_DATE FROM CUSTOMERS;
SELECT DATE_FORMAT(MANUFACTURING_DATE, 'YYYY-MM-DD') AS MANUFACTING_DATE FROM PRODUCTS;
SELECT YEAR(JOINING_DATE) AS YEAR, MONTH(JOINING_DATE) AS MONTH FROM EMPLOYEES;
SELECT DATE_DIFF(REGISTRATION_DATE, JOINING_DATE) AS DATE_DIFFERENCE FROM CUSTOMERS;

/* D. NULL-HANDLING SCALAR FUNCTIONS - 15 QUESTIONS

61. DISPLAY STUDENT EMAIL. IF EMAIL IS NULL, DISPLAY 'NOT AVAILABLE' USING IFNULL().
62. DISPLAY EMPLOYEE PHONE NUMBER. IF IT IS NULL, DISPLAY 'NO PHONE'.
63. DISPLAY PRODUCT BRAND. IF IT IS NULL, DISPLAY 'UNKNOWN BRAND'.
64. DISPLAY BOOK AUTHOR. IF IT IS NULL, DISPLAY 'UNKNOWN AUTHOR'.
65. DISPLAY CUSTOMER EMAIL. IF IT IS NULL, DISPLAY 'EMAIL MISSING'.
66. REPLACE NULL EMPLOYEE DEPARTMENT WITH 'NOT ASSIGNED'.
67. REPLACE NULL PRODUCT DISCOUNT WITH 0.
68. REPLACE NULL COURSE FEES WITH 0.
69. DISPLAY PATIENT DISEASE. IF NULL, DISPLAY 'NOT SPECIFIED'.
70. DISPLAY STUDENT PHONE NUMBER USING COALESCE().
71. DISPLAY EMPLOYEE EMAIL USING COALESCE() AND REPLACE NULL WITH 'NO EMAIL'.
72. DISPLAY PRODUCT BRAND USING COALESCE() AND REPLACE NULL WITH 'NO BRAND'.
73. USE COALESCE() TO DISPLAY THE FIRST AVAILABLE VALUE AMONG PHONE, EMAIL, AND ALTERNATE PHONE.
74. DISPLAY COURSE DURATION. IF NULL, DISPLAY 'DURATION NOT AVAILABLE'.
75. DISPLAY BOOK PUBLICATION YEAR. IF NULL, DISPLAY 'YEAR UNKNOWN'. */

SELECT IFNULL(EMAIL, 'NOT AVAILABLE') AS EMAIL FROM STUDENTS;
SELECT IFNULL(PHONE_NUMBER, 'NO PHONE') AS PHONE_NUMBER FROM EMPLOYEES;
SELECT IFNULL(BRAND, 'UNKNOWN BRAND') AS BRAND FROM PRODUCTS;
SELECT IFNULL(AUTHOR, 'UNKNOWN AUTHOR') AS AUTHOR FROM BOOKS;
SELECT IFNULL(EMAIL, 'EMAIL MISSING') AS EMAIL FROM CUSTOMERS;
SELECT IFNULL(DEPARTMENT, 'NOT ASSIGNED') AS DEPARTMENT FROM EMPLOYEES;
SELECT IFNULL(DISCOUNT, 0) AS DISCOUNT FROM PRODUCTS;
SELECT IFNULL(FEES, 0) AS FEES FROM COURSES;
SELECT IFNULL(DISEASE, 'NOT SPECIFIED') AS DISEASE FROM PATIENTS;
SELECT COALESCE(PHONE_NUMBER, 'NO PHONE') AS PHONE_NUMBER FROM STUDENTS;
SELECT COALESCE(EMAIL, 'NO EMAIL') AS EMAIL FROM EMPLOYEES;
SELECT COALESCE(BRAND, 'NO BRAND') AS BRAND FROM PRODUCTS;
SELECT COALESCE(PHONE_NUMBER, EMAIL, ALTERNATE_PHONE) AS CONTACT_DETAILS FROM CUSTOMERS;
SELECT IFNULL(DURATION, 'DURATION NOT AVAILABLE') AS DURATION FROM COURSES;
SELECT IFNULL(PUBLICATION_YEAR, 'YEAR UNKNOWN') AS PUBLICATION_YEAR FROM BOOKS;

/* E. CONDITIONAL SCALAR FUNCTIONS - 15 QUESTIONS

USING IF()

76. DISPLAY EMPLOYEE NAME AND SALARY. SHOW 'HIGH' IF SALARY >= 60000, OTHERWISE 'LOW'.
77. DISPLAY STUDENT NAME AND MARKS. SHOW 'PASS' IF MARKS >= 40, OTHERWISE 'FAIL'.
78. DISPLAY PRODUCT NAME AND STOCK. SHOW 'AVAILABLE' IF STOCK > 0, OTHERWISE 'OUT OF STOCK'.
79. DISPLAY EMPLOYEE NAME. SHOW 'EXPERIENCED' IF EXPERIENCE >= 5, OTHERWISE 'FRESHER'.
80. DISPLAY COURSE NAME. SHOW 'EXPENSIVE' IF FEES > 50000, OTHERWISE 'AFFORDABLE'.
81. DISPLAY BOOK NAME. SHOW 'PREMIUM' IF PRICE >= 1000, OTHERWISE 'REGULAR'.
82. DISPLAY CUSTOMER NAME. SHOW 'ADULT' IF AGE >= 18, OTHERWISE 'MINOR'.
83. DISPLAY PRODUCT NAME. SHOW 'LOW STOCK' IF STOCK < 10, OTHERWISE 'SUFFICIENT STOCK'.
84. DISPLAY EMPLOYEE NAME. SHOW 'ELIGIBLE' IF SALARY >= 50000, OTHERWISE 'NOT ELIGIBLE'.
85. DISPLAY STUDENT NAME. SHOW 'ELIGIBLE' IF ATTENDANCE >= 75, OTHERWISE 'NOT ELIGIBLE'. */

SELECT EMPLOYEE_NAME, IF(SALARY >= 60000, 'HIGH', 'LOW') AS SALARY_STATUS FROM EMPLOYEES;
SELECT STUDENT_NAME, IF(MARKS >= 40, 'PASS', 'FAIL') AS RESULT FROM STUDENTS;
SELECT PRODUCT_NAME, IF(STOCK > 0, 'AVAILABLE', 'OUT OF STOCK') AS STOCK_STATUS FROM PRODUCTS;
SELECT EMPLOYEE_NAME, IF(EXPERIENCE >= 5, 'EXPERIENCED', 'FRESHER') AS EXPERIENCE_STATUS FROM EMPLOYEES;
SELECT COURSE_NAME, IF(FEES > 50000, 'EXPENSIVE', 'AFFORDABLE') AS COURSE_STATUS FROM COURSES;
SELECT BOOK_NAME, IF(PRICE >= 1000, 'PREMIUM', 'REGULAR') AS BOOK_STATUS FROM BOOKS;
SELECT CUSTOMER_NAME, IF(AGE >= 18, 'ADULT', 'MINOR') AS CUSTOMER_STATUS FROM CUSTOMERS;
SELECT PRODUCT_NAME, IF(STOCK < 10, 'LOW STOCK', 'SUFFICIENT STOCK') AS STOCK_STATUS FROM PRODUCTS;
SELECT EMPLOYEE_NAME, IF(SALARY >= 50000, 'ELIGIBLE', 'NOT ELIGIBLE') AS ELIGIBILITY_STATUS FROM EMPLOYEES;
SELECT STUDENT_NAME, IF(ATTENDANCE >= 75, 'ELIGIBLE', 'NOT ELIGIBLE') AS ELIGIBILITY_STATUS FROM STUDENTS;

/* F. MIXED SCALAR FUNCTION QUESTIONS

86. DISPLAY EMPLOYEE NAMES IN UPPERCASE ALONG WITH THEIR SALARY ROUNDED TO 2 DECIMAL PLACES.
87. DISPLAY PRODUCT NAMES IN LOWERCASE ALONG WITH THE PRICE AFTER A 10% DISCOUNT.
88. DISPLAY STUDENT NAMES IN UPPERCASE ALONG WITH THEIR NAME LENGTH.
89. DISPLAY EMPLOYEE NAME, ANNUAL SALARY, AND ROUNDED ANNUAL SALARY.
90. DISPLAY PRODUCT NAME, PRICE, GST AMOUNT, AND FINAL PRICE.
91. DISPLAY CUSTOMER NAME AND REGISTRATION YEAR.
92. DISPLAY EMPLOYEE NAME AND JOINING MONTH.
93. DISPLAY BOOK NAME IN UPPERCASE AND PRICE ROUNDED TO 2 DECIMAL PLACES.
94. DISPLAY PRODUCT NAME AND TOTAL STOCK VALUE USING PRICE * QUANTITY.
95. DISPLAY EMPLOYEE NAME AND SALARY AFTER A 10% INCREMENT.
96. DISPLAY STUDENT NAME, AGE, AND AGE SQUARED USING POWER().
97. DISPLAY PRODUCT NAME AND THE REMAINDER OF PRICE DIVIDED BY 1000.
98. DISPLAY CUSTOMER NAME AND REGISTRATION DATE AFTER 30 DAYS.
99. DISPLAY EMPLOYEE NAME AND REPLACE NULL DEPARTMENT WITH 'NOT ASSIGNED'.
100. DISPLAY PRODUCT NAME IN UPPERCASE, PRICE ROUNDED TO 2 DECIMAL PLACES, AND REPLACE NULL BRAND WITH 'UNKNOWN'. */

SELECT STUDENT_NAME, IF(ATTENDANCE >= 75, 'ELIGIBLE', 'NOT ELIGIBLE') AS ELIGIBILITY_STATUS FROM STUDENTS;
SELECT UPPER(EMPLOYEE_NAME) AS EMPLOYEE_NAME, ROUND(SALARY,2) AS SALARY FROM EMPLOYEES;
SELECT LOWER(PRODUCT_NAME) AS PRODUCT_NAME, PRICE*0.90 AS DISCOUNTED_PRICE FROM PRODUCTS;
SELECT UPPER(STUDENT_NAME) AS STUDENT_NAME, LEN(STUDENT_NAME) AS NAME_LENGTH FROM STUDENTS;
SELECT EMPLOYEE_NAME, SALARY*12 AS ANNUAL_SALARY, ROUND(SALARY*12,2) AS ROUNDED_ANNUAL_SALARY FROM EMPLOYEES;
SELECT PRODUCT_NAME, PRICE, PRICE*0.18 AS GST_AMOUNT, PRICE+(PRICE*0.18) AS FINAL_PRICE FROM PRODUCTS;
SELECT CUSTOMER_NAME, YEAR(REGISTRATION_DATE) AS REGISTRATION_YEAR FROM CUSTOMERS;
SELECT EMPLOYEE_NAME, MONTH(JOINING_DATE) AS JOINING_MONTH FROM EMPLOYEES;
SELECT UPPER(BOOK_NAME) AS BOOK_NAME, ROUND(PRICE,2) AS PRICE FROM BOOKS;
SELECT PRODUCT_NAME, PRICE*QUANTITY AS TOTAL_STOCK_VALUE FROM PRODUCTS;
SELECT EMPLOYEE_NAME, SALARY*1.10 AS INCREMENTED_SALARY FROM EMPLOYEES;
SELECT STUDENT_NAME, AGE, POWER(AGE,2) AS AGE_SQUARED FROM STUDENTS;
SELECT PRODUCT_NAME, MOD(PRICE,1000) AS REMAINDER FROM PRODUCTS;
SELECT CUSTOMER_NAME, DATE_ADD(REGISTRATION_DATE,30) AS REGISTRATION_DATE_AFTER_30_DAYS FROM CUSTOMERS;
SELECT EMPLOYEE_NAME, IFNULL(DEPARTMENT,'NOT ASSIGNED') AS DEPARTMENT FROM EMPLOYEES;
SELECT UPPER(PRODUCT_NAME) AS PRODUCT_NAME, ROUND(PRICE,2) AS PRICE, IFNULL(BRAND,'UNKNOWN') AS BRAND FROM PRODUCTS;
