#Date: 26th August 2026
#Date Covered: 25th August 2026
#Topics Covered:

/* CASE STATEMENT
OBJECTIVE
PRACTICE USING THE CASE EXPRESSION TO CREATE CONDITIONAL RESULTS IN SQL.
CASE WORKS LIKE IF-ELSE IN SQL.

BASIC SYNTAX

CASE
    WHEN CONDITION THEN RESULT
    WHEN CONDITION THEN RESULT
    ELSE RESULT
END

EXAMPLE

SELECT STUDENTNAME, AGE,
       CASE
           WHEN AGE >= 18 THEN 'ADULT'
           ELSE 'MINOR'
       END AS AGE_CATEGORY
FROM STUDENTS; */

/* A. BASIC CASE – 20 QUESTIONS

1. DISPLAY STUDENT NAME AND AGE. CREATE AN AGE_CATEGORY:
   • AGE >= 18 → ADULT
   • OTHERWISE → MINOR

2. DISPLAY EMPLOYEE NAME AND SALARY. CATEGORIZE SALARY:
   • SALARY >= 60000 → HIGH
   • SALARY >= 40000 → MEDIUM
   • OTHERWISE → LOW

3. DISPLAY STUDENT NAME AND MARKS. CATEGORIZE MARKS:
   • 90 AND ABOVE → EXCELLENT
   • 75-89 → VERY GOOD
   • 50-74 → GOOD
   • BELOW 50 → FAIL

4. DISPLAY EMPLOYEE NAME AND SALARY. IF SALARY IS >= 50000, DISPLAY ELIGIBLE, OTHERWISE NOT ELIGIBLE.
5. DISPLAY PRODUCT NAME AND PRICE. CATEGORIZE:
   • PRICE >= 50000 → EXPENSIVE
   • PRICE >= 10000 → MODERATE
   • OTHERWISE → AFFORDABLE
6. DISPLAY BOOK NAME AND PRICE. CATEGORIZE:
   • PRICE >= 1000 → PREMIUM
   • OTHERWISE → REGULAR
7. DISPLAY PATIENT NAME AND AGE. CATEGORIZE:
   • AGE >= 60 → SENIOR CITIZEN
   • AGE >= 18 → ADULT
   • OTHERWISE → MINOR
8. DISPLAY EMPLOYEE NAME AND EXPERIENCE. CATEGORIZE:
   • EXPERIENCE >= 10 → SENIOR
   • EXPERIENCE >= 5 → INTERMEDIATE
   • OTHERWISE → JUNIOR
9. DISPLAY COURSE NAME AND FEES. CATEGORIZE:
   • FEES >= 50000 → HIGH FEE
   • FEES >= 30000 → MEDIUM FEE
   • OTHERWISE → LOW FEE
10. DISPLAY PRODUCT NAME AND STOCK. CATEGORIZE:
    • STOCK = 0 → OUT OF STOCK
    • STOCK < 10 → LOW STOCK
    • OTHERWISE → AVAILABLE
11. DISPLAY STUDENTS AND THEIR MARKS. DISPLAY PASS IF MARKS >= 40, OTHERWISE FAIL.
12. DISPLAY EMPLOYEES AND SALARY. DISPLAY HIGH SALARY IF SALARY >= 70000, OTHERWISE NORMAL SALARY.
13. DISPLAY BOOKS AND PRICE. DISPLAY COSTLY IF PRICE > 1500, OTHERWISE AFFORDABLE.
14. DISPLAY PRODUCTS AND QUANTITY. DISPLAY BULK STOCK IF QUANTITY >= 100, OTHERWISE NORMAL STOCK.
15. DISPLAY MOVIES AND RATING:
    • RATING >= 4.5 → EXCELLENT
    • RATING >= 3 → GOOD
    • OTHERWISE → AVERAGE
16. DISPLAY CUSTOMERS AND AGE:
    • AGE >= 60 → SENIOR
    • AGE >= 30 → ADULT
    • OTHERWISE → YOUNG
17. DISPLAY EMPLOYEES AND SALARY:
    • SALARY >= 100000 → GRADE A
    • SALARY >= 60000 → GRADE B
    • OTHERWISE → GRADE C
18. DISPLAY STUDENTS AND ATTENDANCE:
    • ATTENDANCE >= 90 → EXCELLENT
    • ATTENDANCE >= 75 → GOOD
    • OTHERWISE → LOW
19. DISPLAY PRODUCTS AND PRICE:
    • PRICE >= 100000 → LUXURY
    • PRICE >= 50000 → PREMIUM
    • OTHERWISE → STANDARD
20. DISPLAY COURSES AND DURATION:
    • DURATION >= 12 → LONG TERM
    • DURATION >= 6 → MEDIUM TERM
    • OTHERWISE → SHORT TERM */ 

SELECT STUDNET_NAME, AGE,
CASE WHEN AGE>18 THEN 'ADULT'
ELSE 'MINOR'
END AS AGE_CATEGORY
FROM STUDNETS;

SELECT NAME, SALARY,
CASE WHEN SALARY>=60000 THEN 'HIGH'
WHEN SALARY>=40000 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALARY_CATEGORY
FROM EMPLOYEE;

SELECT NAME, MARKS, 
CASE WHEN MARKS>=90 THEN 'EXCELLENT'
WHEN MARKS >=75 THEN 'VERG GOOD'
WHEN MARKS >=50 THEN 'GOOD'
ELSE 'FAIL'
END AS GRADE
FROM STUDNETS;

SELECT NAME, SALARY,
CASE WHEN SALARY >=50000 THEN 'ELIGIBLE'
ELSE 'MOT ELIGIBLE'
END AS ELIGIBILITY
FROM EMPLOYEES;


SELECT NAME, PRICE, 
CASE WHEN PRICE>=50000 THEN 'EXPENSIVE'
WHEN PRICE>=10000 THEN 'MODERATE'
ELSE 'AFFORDABLE'
END AS CATEGORY
FROM PRODUCTS;


SELECT NAME, PRICE,
CASE WHEN PRICE>=1000 THEN 'PREMIUM'
ELSE 'REGULAR'
END AS PRODUCT_TYPE
FROM PRODUCTS;

SELECT NAME, AGE,
CASE WHEN AGE>=60 THEN 'SENIOR CITIZEN'
WHEN AGE>=18 THEN 'ADULT'
ELSE 'MINOR'
END AS AGE_GROUP
FROM PATIENTS;

SELECT NAME, EXPERIENCE,
CASE WHEN EXPERIENCE>=10 THEN 'SENIOR'
WHEN EXPERIENCE>=5 THEN 'INTERMEDIATE'
ELSE 'JUNIOR'
END AS CATEGORY
FROM EMPLOYEES;

SELECT NAME, FEES, 
CASE WHEN FEES>=50000 THEN 'HIGH FEE'
WHEN FEES>=30000 THEN 'MEDIUM FEE'
ELSE 'LOW FEE'
END AS FEE_STRUCTURE
FROM COURSES;

SELECT NAME, STOCK,
CASE WHEN STOCK = 0 THEN 'OUT OF STOCK'
WHEN STOCK<10 THEN 'LOW STOCK'
ELSE 'AVAILABLE'
END AS STOCK_AVAILABLILITY
FROM PRODUCTS;

SELECT NAME, MARKS,
CASE WHEN MARKS>=40 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STUDNETS;

SELECT NAME, SALARY,
CASE WHEN SALARY>=70000 THEN 'HIGH SALARY'
ELSE 'NORMAL SALARY'
END AS SAL_CATEGORY
FROM EMPLOYEES;

SELECT NAME, PRICE,
CASE WHEN PRICE>1500 THEN 'COSTLY'
ELSE 'AFFORDABLE'
END AS CATEGORY FROM BOOKS;

SELECT PRODUCT_NAME, QUANTITY, 
CASE WHEN QUANTITY>=100 THEN 'BULK STOCK'
ELSE 'NORMAL STOCK'
END AS AVAILABILITY FROM PRODUCTS;


SELECT NAME, RATING, 
CASE WHEN RATING>=4.5 THEN 'EXCELLENT'
WHEN RATING>=3 THEN 'GOOD'
ELSE 'AVERAGE'
END AS CATEGORY FROM MOVIES;

SELECT CUSTOMERNAME, AGE,
CASE WHEN AGE>=60 THEN 'SENIOR'
WHEN AGE>=30 THEN 'ADULT'
ELSE 'YOUNG'
END AS CATEGORY FROM CUSTOMERS;

SELECT NAME, SALARY,
CASE WHEN SALARY>=100000 THEN 'GRADE A'
WHEN  SALARY>=60000 THEN 'GRADE B'
ELSE 'GRADE C'
END AS GRADE FROM EMPLOYEES;

SELECT NAME, ATTENDANCE,
CASE WHEN ATTENDANCE>=90 THEN 'EXCELLENT'
WHEN ATTENDANCE >= 75 THEN 'GOOD'
ELSE 'LOW'
END AS ATTENDANCE_AVAILABLE FROM STUDENTS;

SELECT NAME, PRICE,
CASE WHEN PRICE>=100000 THEN 'LUXURY'
WHEN PRICE>=50000 THEN 'PREMIUM'
ELSE 'STANDARD'
END AS CATEGORY FROM PRODUCTS;


SELECT NAME, DURATION,
CASE WHEN DURATION>=12 THEN 'LONG TERM'
WHEN DURATION >=6 THEN 'MEDIUM TERM'
ELSE 'SHORT TERM'
END AS DURATION FROM COURSES;



/* B. CASE WITH MULTIPLE CONDITIONS – 20 QUESTIONS

21. CATEGORIZE EMPLOYEES BASED ON SALARY AND DEPARTMENT:
    • IT + SALARY >= 60000 → IT HIGH SALARY
    • HR + SALARY >= 50000 → HR HIGH SALARY
    • OTHERWISE → OTHER

22. CATEGORIZE STUDENTS:
    • CSE + MARKS >= 80 → CSE EXCELLENT
    • IT + MARKS >= 80 → IT EXCELLENT
    • OTHERWISE → OTHER

23. CATEGORIZE PRODUCTS:
    • ELECTRONICS + PRICE >= 50000 → PREMIUM ELECTRONICS
    • ELECTRONICS + PRICE < 50000 → REGULAR ELECTRONICS
    • OTHERWISE → OTHER CATEGORY

24. CATEGORIZE EMPLOYEES:
    • SALARY >= 70000 AND EXPERIENCE >= 5 → SENIOR HIGH SALARY
    • SALARY >= 50000 → GOOD SALARY
    • OTHERWISE → REGULAR

25. CATEGORIZE STUDENTS:
    • AGE >= 18 AND ATTENDANCE >= 75 → ELIGIBLE
    • OTHERWISE → NOT ELIGIBLE

26. CATEGORIZE PRODUCTS:
    • STOCK = 0 → OUT OF STOCK
    • STOCK < 10 → LOW STOCK
    • STOCK >= 10 → AVAILABLE

27. CATEGORIZE BOOKS:
    • TECHNOLOGY AND PRICE > 1000 → PREMIUM TECHNOLOGY
    • TECHNOLOGY AND PRICE <= 1000 → REGULAR TECHNOLOGY
    • OTHERWISE → OTHER

28. CATEGORIZE PATIENTS:
    • AGE >= 60 AND DISEASE IS NOT NULL → SENIOR PATIENT
    • AGE >= 18 → ADULT PATIENT
    • OTHERWISE → YOUNG PATIENT

29. CATEGORIZE CUSTOMERS:
    • CHENNAI AND COUNTRY = INDIA → CHENNAI CUSTOMER
    • OTHERWISE → OTHER CUSTOMER

30. CATEGORIZE EMPLOYEES:
    • IT AND SALARY >= 50000 → IT HIGH
    • IT AND SALARY < 50000 → IT NORMAL
    • OTHERWISE → OTHER DEPARTMENT

31. CATEGORIZE PRODUCTS BASED ON PRICE AND STOCK:
    • PRICE >= 50000 AND STOCK > 10 → PREMIUM AVAILABLE
    • PRICE >= 50000 AND STOCK = 0 → PREMIUM UNAVAILABLE
    • OTHERWISE → REGULAR

32. CATEGORIZE STUDENTS:
    • MARKS >= 90 AND ATTENDANCE >= 90 → OUTSTANDING
    • MARKS >= 75 AND ATTENDANCE >= 75 → GOOD
    • OTHERWISE → NEEDS IMPROVEMENT

33. CATEGORIZE EMPLOYEES:
    • EXPERIENCE >= 10 AND SALARY >= 80000 → SENIOR
    • EXPERIENCE >= 5 → MID-LEVEL
    • OTHERWISE → JUNIOR

34. CATEGORIZE COURSES:
    • FEES > 50000 AND DURATION >= 12 → PREMIUM LONG TERM
    • FEES > 30000 → STANDARD
    • OTHERWISE → BASIC

35. CATEGORIZE MOVIES:
    • RATING >= 4.5 AND LANGUAGE = TAMIL → TAMIL HIT
    • RATING >= 4.5 → HIT
    • OTHERWISE → AVERAGE

36. CATEGORIZE BOOKS BASED ON PRICE AND CATEGORY:
    • TECHNOLOGY AND PRICE > 1000 → PREMIUM TECHNOLOGY
    • SCIENCE AND PRICE > 1000 → PREMIUM SCIENCE
    • OTHERWISE → REGULAR

37. CATEGORIZE EMPLOYEES:
    • DEPARTMENT = IT AND SALARY > 60000 → IT SENIOR
    • DEPARTMENT = HR AND SALARY > 50000 → HR SENIOR
    • OTHERWISE → OTHER

38. CATEGORIZE STUDENTS:
    • CSE AND AGE < 21 → YOUNG CSE
    • IT AND AGE < 21 → YOUNG IT
    • OTHERWISE → OTHER

39. CATEGORIZE CUSTOMERS:
    • CITY = CHENNAI AND EMAIL IS NOT NULL → VERIFIED CHENNAI
    • CITY = CHENNAI AND EMAIL IS NULL → UNVERIFIED CHENNAI
    • OTHERWISE → OTHER CITY

40. CATEGORIZE PRODUCTS:
    • BRAND IS NULL → UNKNOWN BRAND
    • STOCK = 0 → OUT OF STOCK
    • STOCK < 10 → LOW STOCK
    • OTHERWISE → AVAILABLE */

SELECT NAME, SALARY, DEPARTMENT,
CASE
    WHEN DEPARTMENT = 'IT' AND SALARY >= 60000 THEN 'IT HIGH SALARY'
    WHEN DEPARTMENT = 'HR' AND SALARY >= 50000 THEN 'HR HIGH SALARY'
    ELSE 'OTHER'
END AS SALARY_GROUP
FROM EMPLOYEES;

SELECT NAME, DEPARTMENT, MARKS,
CASE
    WHEN DEPARTMENT = 'CSE' AND MARKS >= 80 THEN 'CSE EXCELLENT'
    WHEN DEPARTMENT = 'IT' AND MARKS >= 80 THEN 'IT EXCELLENT'
    ELSE 'OTHER'
END AS PERFORMANCE_CATEGORY
FROM STUDENTS;

SELECT NAME, CATEGORY, PRICE,
CASE
    WHEN CATEGORY = 'ELECTRONICS' AND PRICE >= 50000 THEN 'PREMIUM ELECTRONICS'
    WHEN CATEGORY = 'ELECTRONICS' AND PRICE < 50000 THEN 'REGULAR ELECTRONICS'
    ELSE 'OTHER CATEGORY'
END AS PRODUCT_CATEGORY
FROM PRODUCTS;

SELECT NAME, SALARY, EXPERIENCE,
CASE
    WHEN SALARY >= 70000 AND EXPERIENCE >= 5 THEN 'SENIOR HIGH SALARY'
    WHEN SALARY >= 50000 THEN 'GOOD SALARY'
    ELSE 'REGULAR'
END AS EMPLOYEE_CATEGORY
FROM EMPLOYEES;

SELECT NAME, AGE, ATTENDANCE,
CASE
    WHEN AGE >= 18 AND ATTENDANCE >= 75 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS ELIGIBILITY_STATUS
FROM STUDENTS;

SELECT NAME, STOCK,
CASE
    WHEN STOCK = 0 THEN 'OUT OF STOCK'
    WHEN STOCK < 10 THEN 'LOW STOCK'
    ELSE 'AVAILABLE'
END AS STOCK_STATUS
FROM PRODUCTS;

SELECT NAME, CATEGORY, PRICE,
CASE
    WHEN CATEGORY = 'TECHNOLOGY' AND PRICE > 1000 THEN 'PREMIUM TECHNOLOGY'
    WHEN CATEGORY = 'TECHNOLOGY' AND PRICE <= 1000 THEN 'REGULAR TECHNOLOGY'
    ELSE 'OTHER'
END AS BOOK_CATEGORY
FROM BOOKS;

SELECT NAME, AGE, DISEASE,
CASE
    WHEN AGE >= 60 AND DISEASE IS NOT NULL THEN 'SENIOR PATIENT'
    WHEN AGE >= 18 THEN 'ADULT PATIENT'
    ELSE 'YOUNG PATIENT'
END AS PATIENT_CATEGORY
FROM PATIENTS;

SELECT NAME, CITY, COUNTRY,
CASE
    WHEN CITY = 'CHENNAI' AND COUNTRY = 'INDIA' THEN 'CHENNAI CUSTOMER'
    ELSE 'OTHER CUSTOMER'
END AS CUSTOMER_CATEGORY
FROM CUSTOMERS;

SELECT NAME, DEPARTMENT, SALARY,
CASE
    WHEN DEPARTMENT = 'IT' AND SALARY >= 50000 THEN 'IT HIGH'
    WHEN DEPARTMENT = 'IT' AND SALARY < 50000 THEN 'IT NORMAL'
    ELSE 'OTHER DEPARTMENT'
END AS EMPLOYEE_CATEGORY
FROM EMPLOYEES;

SELECT NAME, PRICE, STOCK,
CASE
    WHEN PRICE >= 50000 AND STOCK > 10 THEN 'PREMIUM AVAILABLE'
    WHEN PRICE >= 50000 AND STOCK = 0 THEN 'PREMIUM UNAVAILABLE'
    ELSE 'REGULAR'
END AS PRODUCT_STATUS
FROM PRODUCTS;

SELECT NAME, MARKS, ATTENDANCE,
CASE
    WHEN MARKS >= 90 AND ATTENDANCE >= 90 THEN 'OUTSTANDING'
    WHEN MARKS >= 75 AND ATTENDANCE >= 75 THEN 'GOOD'
    ELSE 'NEEDS IMPROVEMENT'
END AS PERFORMANCE_STATUS
FROM STUDENTS;

SELECT NAME, EXPERIENCE, SALARY,
CASE
    WHEN EXPERIENCE >= 10 AND SALARY >= 80000 THEN 'SENIOR'
    WHEN EXPERIENCE >= 5 THEN 'MID-LEVEL'
    ELSE 'JUNIOR'
END AS EXPERIENCE_LEVEL
FROM EMPLOYEES;

SELECT NAME, FEES, DURATION,
CASE
    WHEN FEES > 50000 AND DURATION >= 12 THEN 'PREMIUM LONG TERM'
    WHEN FEES > 30000 THEN 'STANDARD'
    ELSE 'BASIC'
END AS COURSE_CATEGORY
FROM COURSES;

SELECT NAME, RATING, LANGUAGE,
CASE
    WHEN RATING >= 4.5 AND LANGUAGE = 'TAMIL' THEN 'TAMIL HIT'
    WHEN RATING >= 4.5 THEN 'HIT'
    ELSE 'AVERAGE'
END AS MOVIE_CATEGORY
FROM MOVIES;

SELECT NAME, CATEGORY, PRICE,
CASE
    WHEN CATEGORY = 'TECHNOLOGY' AND PRICE > 1000 THEN 'PREMIUM TECHNOLOGY'
    WHEN CATEGORY = 'SCIENCE' AND PRICE > 1000 THEN 'PREMIUM SCIENCE'
    ELSE 'REGULAR'
END AS BOOK_CATEGORY
FROM BOOKS;

SELECT NAME, DEPARTMENT, SALARY,
CASE
    WHEN DEPARTMENT = 'IT' AND SALARY > 60000 THEN 'IT SENIOR'
    WHEN DEPARTMENT = 'HR' AND SALARY > 50000 THEN 'HR SENIOR'
    ELSE 'OTHER'
END AS EMPLOYEE_CATEGORY
FROM EMPLOYEES;

SELECT NAME, DEPARTMENT, AGE,
CASE
    WHEN DEPARTMENT = 'CSE' AND AGE < 21 THEN 'YOUNG CSE'
    WHEN DEPARTMENT = 'IT' AND AGE < 21 THEN 'YOUNG IT'
    ELSE 'OTHER'
END AS STUDENT_CATEGORY
FROM STUDENTS;

SELECT NAME, CITY, EMAIL,
CASE
    WHEN CITY = 'CHENNAI' AND EMAIL IS NOT NULL THEN 'VERIFIED CHENNAI'
    WHEN CITY = 'CHENNAI' AND EMAIL IS NULL THEN 'UNVERIFIED CHENNAI'
    ELSE 'OTHER CITY'
END AS CUSTOMER_STATUS
FROM CUSTOMERS;

SELECT NAME, BRAND, STOCK,
CASE
    WHEN BRAND IS NULL THEN 'UNKNOWN BRAND'
    WHEN STOCK = 0 THEN 'OUT OF STOCK'
    WHEN STOCK < 10 THEN 'LOW STOCK'
    ELSE 'AVAILABLE'
END AS PRODUCT_STATUS
FROM PRODUCTS;

/* C. CASE WITH NULL – 10 QUESTIONS

41. DISPLAY STUDENTS AND SHOW EMAIL AVAILABLE IF EMAIL IS NOT NULL, OTHERWISE EMAIL MISSING.
42. DISPLAY EMPLOYEES AND SHOW DEPARTMENT ASSIGNED IF DEPARTMENT IS NOT NULL, OTHERWISE DEPARTMENT MISSING.
43. DISPLAY PRODUCTS AND SHOW BRAND AVAILABLE IF BRAND IS NOT NULL, OTHERWISE BRAND MISSING.
44. DISPLAY BOOKS AND SHOW AUTHOR AVAILABLE IF AUTHOR IS NOT NULL, OTHERWISE AUTHOR MISSING.
45. DISPLAY CUSTOMERS AND SHOW EMAIL AVAILABLE IF EMAIL IS NOT NULL, OTHERWISE EMAIL MISSING.
46. DISPLAY PATIENTS AND SHOW DISEASE AVAILABLE IF DISEASE IS NOT NULL, OTHERWISE DISEASE NOT AVAILABLE.
47. DISPLAY PRODUCTS AND SHOW DISCOUNT AVAILABLE IF DISCOUNT IS NOT NULL, OTHERWISE NO DISCOUNT.
48. DISPLAY STUDENTS AND SHOW PHONE AVAILABLE IF PHONE IS NOT NULL, OTHERWISE PHONE MISSING.
49. DISPLAY EMPLOYEES AND SHOW MANAGER ASSIGNED IF MANAGER NAME IS NOT NULL, OTHERWISE NO MANAGER.
50. DISPLAY BOOKS AND SHOW PUBLICATION YEAR AVAILABLE IF PUBLICATION YEAR IS NOT NULL, OTHERWISE YEAR UNKNOWN. */

SELECT EMAIL,
CASE
    WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
    ELSE 'EMAIL MISSING'
END AS EMAIL_STATUS
FROM STUDENTS;

SELECT DEPARTMENT,
CASE
    WHEN DEPARTMENT IS NOT NULL THEN 'DEPARTMENT ASSIGNED'
    ELSE 'DEPARTMENT MISSING'
END AS DEPARTMENT_STATUS
FROM EMPLOYEES;

SELECT BRAND,
CASE
    WHEN BRAND IS NOT NULL THEN 'BRAND AVAILABLE'
    ELSE 'BRAND MISSING'
END AS BRAND_STATUS
FROM PRODUCTS;

SELECT AUTHOR,
CASE
    WHEN AUTHOR IS NOT NULL THEN 'AUTHOR AVAILABLE'
    ELSE 'AUTHOR MISSING'
END AS AUTHOR_STATUS
FROM BOOKS;

SELECT EMAIL,
CASE
    WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
    ELSE 'EMAIL MISSING'
END AS EMAIL_STATUS
FROM CUSTOMERS;

SELECT DISEASE,
CASE
    WHEN DISEASE IS NOT NULL THEN 'DISEASE AVAILABLE'
    ELSE 'DISEASE NOT AVAILABLE'
END AS DISEASE_STATUS
FROM PATIENTS;

SELECT NAME,
CASE
    WHEN DISCOUNT IS NOT NULL THEN 'DISCOUNT AVAILABLE'
    ELSE 'NO DISCOUNT'
END AS DISCOUNT_STATUS
FROM PRODUCTS;

SELECT PHONE,
CASE
    WHEN PHONE IS NOT NULL THEN 'PHONE AVAILABLE'
    ELSE 'PHONE MISSING'
END AS PHONE_STATUS
FROM STUDENTS;

SELECT MANAGER_NAME,
CASE
    WHEN MANAGER_NAME IS NOT NULL THEN 'MANAGER ASSIGNED'
    ELSE 'NO MANAGER'
END AS MANAGER_STATUS
FROM EMPLOYEES;

SELECT PUBLICATION_YEAR,
CASE
    WHEN PUBLICATION_YEAR IS NOT NULL THEN 'PUBLICATION YEAR AVAILABLE'
    ELSE 'YEAR UNKNOWN'
END AS PUBLICATION_STATUS
FROM BOOKS;

/*  
D. CASE WITH AGGREGATE FUNCTIONS – 10 QUESTIONS

51. COUNT HOW MANY EMPLOYEES HAVE SALARY >= 50000 USING CASE.
52. COUNT HOW MANY STUDENTS HAVE MARKS >= 40 USING CASE.
53. COUNT HOW MANY PRODUCTS ARE OUT OF STOCK USING CASE.
54. COUNT HOW MANY PRODUCTS HAVE PRICE >= 50000 USING CASE.
55. CALCULATE THE TOTAL SALARY OF EMPLOYEES WHOSE SALARY IS >= 50000 USING CASE.
56. CALCULATE THE TOTAL PRICE OF PRODUCTS IN THE ELECTRONICS CATEGORY USING CASE.
57. CALCULATE THE TOTAL STOCK OF PRODUCTS WHOSE STOCK IS GREATER THAN 10.
58. COUNT THE NUMBER OF STUDENTS WHOSE ATTENDANCE IS >= 75.
59. COUNT THE NUMBER OF EMPLOYEES BELONGING TO THE IT DEPARTMENT.
60. CALCULATE THE TOTAL SALES VALUE FOR PRODUCTS WHOSE PRICE IS GREATER THAN 1000.*/

SELECT SUM(
    CASE
        WHEN SALARY >= 50000 THEN 1
        ELSE 0
    END
) AS EMPLOYEE_COUNT
FROM EMPLOYEES;

SELECT SUM(
    CASE
        WHEN MARKS >= 40 THEN 1
        ELSE 0
    END
) AS STUDENT_COUNT
FROM STUDENTS;

SELECT SUM(
    CASE
        WHEN STOCK = 0 THEN 1
        ELSE 0
    END
) AS OUT_OF_STOCK_COUNT
FROM PRODUCTS;

SELECT SUM(
    CASE
        WHEN PRICE >= 50000 THEN 1
        ELSE 0
    END
) AS PRODUCT_COUNT
FROM PRODUCTS;

SELECT SUM(
    CASE
        WHEN SALARY >= 50000 THEN SALARY
        ELSE 0
    END
) AS TOTAL_SALARY
FROM EMPLOYEES;

SELECT SUM(
    CASE
        WHEN CATEGORY = 'ELECTRONICS' THEN PRICE
        ELSE 0
    END
) AS TOTAL_PRICE
FROM PRODUCTS;

SELECT SUM(
    CASE
        WHEN STOCK > 10 THEN STOCK
        ELSE 0
    END
) AS TOTAL_STOCK
FROM PRODUCTS;

SELECT SUM(
    CASE
        WHEN ATTENDANCE >= 75 THEN 1
        ELSE 0
    END
) AS STUDENT_COUNT
FROM STUDENTS;

SELECT SUM(
    CASE
        WHEN DEPARTMENT = 'IT' THEN 1
        ELSE 0
    END
) AS IT_EMPLOYEE_COUNT
FROM EMPLOYEES;

SELECT SUM(
    CASE
        WHEN (PRICE * QUANTITY) > 10000 THEN PRICE * QUANTITY
        ELSE 0
    END
) AS TOTAL_SALES
FROM PRODUCTS;

/* E. ADVANCED CASE PRACTICE - 20 QUESTIONS 
61. DISPLAY EMPLOYEE NAME, SALARY, AND SALARY GRADE USING CASE.
62. DISPLAY STUDENT NAME, MARKS, AND PERFORMANCE LEVEL USING CASE.
63. DISPLAY PRODUCT NAME, PRICE, AND PRICE CATEGORY USING CASE.
64. DISPLAY BOOK NAME, PRICE, AND PRICE CATEGORY USING CASE.
65. DISPLAY CUSTOMER NAME, AGE, AND AGE CATEGORY USING CASE.
66. DISPLAY EMPLOYEE NAME, SALARY, AND ANNUAL SALARY CATEGORY USING CASE.
67. DISPLAY PRODUCT NAME, PRICE, QUANTITY, AND STOCK STATUS USING CASE.
68. DISPLAY STUDENT NAME, MARKS, ATTENDANCE, AND ELIGIBILITY USING CASE.
69. DISPLAY COURSE NAME, FEES, AND FEE CATEGORY USING CASE.
70. DISPLAY MOVIE NAME, RATING, AND RATING CATEGORY USING CASE.
  
71. GIVE EMPLOYEES A GRADE:
• >= 90000 → A
• >= 70000 → B
• >= 50000 → C
• OTHERWISE → D

72. GIVE STUDENTS A RESULT:
• >= 90 → DISTINCTION
• >= 75 → FIRST CLASS
• >= 50 → SECOND CLASS
• OTHERWISE → FAIL

73. CATEGORIZE PRODUCTS:
• PRICE >= 100000 → LUXURY
• PRICE BETWEEN 50000 AND 99999 → PREMIUM
• PRICE BETWEEN 10000 AND 49999 → STANDARD
• BELOW 10000 → BUDGET

74. CATEGORIZE EMPLOYEES BASED ON EXPERIENCE:
• >= 10 → EXPERT
• 5-9 → EXPERIENCED
• 2-4 → INTERMEDIATE
• BELOW 2 → FRESHER

75. CATEGORIZE STUDENTS BASED ON ATTENDANCE:
• >= 90 → EXCELLENT
• 75-89 → GOOD
• 60-74 → AVERAGE
• BELOW 60 → POOR

76. DISPLAY EMPLOYEES AND CALCULATE A BONUS:
• SALARY >= 80000 → 20% BONUS
• SALARY >= 50000 → 10% BONUS
• OTHERWISE → 5% BONUS

77. DISPLAY PRODUCTS AND CALCULATE DISCOUNT:
• PRICE >= 100000 → 20%
• PRICE >= 50000 → 15%
• PRICE >= 10000 → 10%
• OTHERWISE → 5%

78. DISPLAY STUDENTS AND DETERMINE ELIGIBILITY:
• MARKS >= 50 AND ATTENDANCE >= 75 → ELIGIBLE
• OTHERWISE → NOT ELIGIBLE

79. DISPLAY EMPLOYEES AND DETERMINE PROMOTION ELIGIBILITY:
• EXPERIENCE >= 5 AND SALARY >= 60000 → ELIGIBLE
• OTHERWISE → NOT ELIGIBLE

80. DISPLAY PRODUCTS AND DETERMINE REORDER STATUS:
• STOCK = 0 → ORDER IMMEDIATELY
• STOCK < 10 → REORDER
• STOCK >= 10 → NO REORDER*/

SELECT NAME, SALARY,
CASE
    WHEN SALARY >= 60000 THEN 'HIGH'
    WHEN SALARY >= 40000 THEN 'MEDIUM'
    ELSE 'LOW'
END AS SALARY_GRADE
FROM EMPLOYEES;

SELECT NAME, MARKS,
CASE
    WHEN MARKS >= 90 THEN 'EXCELLENT'
    WHEN MARKS >= 75 THEN 'VERY GOOD'
    WHEN MARKS >= 50 THEN 'GOOD'
    ELSE 'FAIL'
END AS PERFORMANCE_LEVEL
FROM STUDENTS;

SELECT NAME, PRICE,
CASE
    WHEN PRICE >= 50000 THEN 'EXPENSIVE'
    WHEN PRICE >= 10000 THEN 'MODERATE'
    ELSE 'AFFORDABLE'
END AS PRICE_CATEGORY
FROM PRODUCTS;

SELECT NAME, PRICE,
CASE
    WHEN PRICE >= 1000 THEN 'PREMIUM'
    ELSE 'REGULAR'
END AS PRICE_CATEGORY
FROM BOOKS;

SELECT NAME, AGE,
CASE
    WHEN AGE >= 60 THEN 'SENIOR'
    WHEN AGE >= 30 THEN 'ADULT'
    ELSE 'YOUNG'
END AS AGE_CATEGORY
FROM CUSTOMERS;

SELECT NAME, SALARY,
CASE
    WHEN SALARY >= 80000 THEN SALARY * 1.20
    WHEN SALARY >= 50000 THEN SALARY * 1.10
    ELSE SALARY * 1.05
END AS ANNUAL_SALARY
FROM EMPLOYEES;

SELECT NAME, PRICE, QUANTITY,
CASE
    WHEN QUANTITY = 0 THEN 'OUT OF STOCK'
    WHEN QUANTITY < 10 THEN 'LOW STOCK'
    ELSE 'AVAILABLE'
END AS STOCK_STATUS
FROM PRODUCTS;

SELECT NAME, MARKS, ATTENDANCE,
CASE
    WHEN MARKS >= 50 AND ATTENDANCE >= 75 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS ELIGIBILITY
FROM STUDENTS;

SELECT NAME, FEES,
CASE
    WHEN FEES >= 50000 THEN 'HIGH FEE'
    WHEN FEES >= 30000 THEN 'MEDIUM FEE'
    ELSE 'LOW FEE'
END AS FEE_CATEGORY
FROM COURSES;

SELECT NAME, RATING,
CASE
    WHEN RATING >= 4.5 THEN 'EXCELLENT'
    WHEN RATING >= 3 THEN 'GOOD'
    ELSE 'AVERAGE'
END AS RATING_CATEGORY
FROM MOVIES;

SELECT NAME, SALARY,
CASE
    WHEN SALARY >= 90000 THEN 'A'
    WHEN SALARY >= 70000 THEN 'B'
    WHEN SALARY >= 50000 THEN 'C'
    ELSE 'D'
END AS GRADE
FROM EMPLOYEES;

SELECT NAME, MARKS,
CASE
    WHEN MARKS >= 90 THEN 'DISTINCTION'
    WHEN MARKS >= 75 THEN 'FIRST CLASS'
    WHEN MARKS >= 50 THEN 'SECOND CLASS'
    ELSE 'FAIL'
END AS RESULT
FROM STUDENTS;

SELECT NAME, PRICE,
CASE
    WHEN PRICE >= 100000 THEN 'LUXURY'
    WHEN PRICE BETWEEN 50000 AND 99999 THEN 'PREMIUM'
    WHEN PRICE BETWEEN 10000 AND 49999 THEN 'STANDARD'
    ELSE 'BUDGET'
END AS PRODUCT_CATEGORY
FROM PRODUCTS;

SELECT NAME, EXPERIENCE,
CASE
    WHEN EXPERIENCE >= 10 THEN 'EXPERT'
    WHEN EXPERIENCE BETWEEN 5 AND 9 THEN 'EXPERIENCED'
    WHEN EXPERIENCE BETWEEN 2 AND 4 THEN 'INTERMEDIATE'
    ELSE 'FRESHER'
END AS EXPERIENCE_LEVEL
FROM EMPLOYEES;

SELECT NAME, ATTENDANCE,
CASE
    WHEN ATTENDANCE >= 90 THEN 'EXCELLENT'
    WHEN ATTENDANCE BETWEEN 75 AND 89 THEN 'GOOD'
    WHEN ATTENDANCE BETWEEN 60 AND 74 THEN 'AVERAGE'
    ELSE 'POOR'
END AS ATTENDANCE_STATUS
FROM STUDENTS;

SELECT NAME,
CASE
    WHEN SALARY >= 80000 THEN SALARY * 1.20
    WHEN SALARY >= 50000 THEN SALARY * 1.10
    ELSE SALARY * 1.05
END AS SALARY_WITH_BONUS
FROM EMPLOYEES;

SELECT NAME,
CASE
    WHEN PRICE >= 100000 THEN PRICE * 0.20
    WHEN PRICE >= 50000 THEN PRICE * 0.15
    WHEN PRICE >= 10000 THEN PRICE * 0.10
    ELSE PRICE * 0.05
END AS DISCOUNT_AMOUNT
FROM PRODUCTS;

SELECT NAME, MARKS, ATTENDANCE,
CASE
    WHEN MARKS >= 50 AND ATTENDANCE >= 75 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS ELIGIBILITY
FROM STUDENTS;

SELECT NAME,
CASE
    WHEN EXPERIENCE >= 5 AND SALARY >= 60000 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS PROMOTION_ELIGIBILITY
FROM EMPLOYEES;

SELECT NAME, STOCK,
CASE
    WHEN STOCK = 0 THEN 'ORDER IMMEDIATELY'
    WHEN STOCK < 10 THEN 'REORDER'
    ELSE 'NO REORDER'
END AS REORDER_STATUS
FROM PRODUCTS;
