#Date: 28th August 2026
#Date Covered: 26th August 2026
#Topics Covered:

/* SUBQUERIES
OBJECTIVE
PRACTICE WRITING SUBQUERIES (NESTED QUERIES) USING SELECT, WHERE, IN, ANY, ALL, AND AGGREGATE FUNCTIONS.

  
A. BASIC SUBQUERY – 20 QUESTIONS

1. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN THE AVERAGE SALARY OF ALL EMPLOYEES.
2. DISPLAY EMPLOYEES WHOSE SALARY IS LESS THAN THE AVERAGE SALARY OF ALL EMPLOYEES.
3. DISPLAY THE EMPLOYEE WHO HAS THE MAXIMUM SALARY.
4. DISPLAY THE EMPLOYEE WHO HAS THE MINIMUM SALARY.
5. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN THE AVERAGE PRODUCT PRICE.
6. DISPLAY PRODUCTS WHOSE PRICE IS LESS THAN THE AVERAGE PRODUCT PRICE.
7. DISPLAY BOOKS WHOSE PRICE IS GREATER THAN THE AVERAGE BOOK PRICE.
8. DISPLAY BOOKS WHOSE PRICE IS LESS THAN THE AVERAGE BOOK PRICE.
9. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN THE AVERAGE AGE OF STUDENTS.
10. DISPLAY STUDENTS WHOSE AGE IS LESS THAN THE AVERAGE AGE OF STUDENTS.
11. DISPLAY EMPLOYEES WHOSE SALARY IS EQUAL TO THE MAXIMUM SALARY.
12. DISPLAY EMPLOYEES WHOSE SALARY IS EQUAL TO THE MINIMUM SALARY.
13. DISPLAY PRODUCTS WHOSE PRICE IS EQUAL TO THE MAXIMUM PRODUCT PRICE.
14. DISPLAY PRODUCTS WHOSE PRICE IS EQUAL TO THE MINIMUM PRODUCT PRICE.
15. DISPLAY BOOKS WHOSE PRICE IS EQUAL TO THE MAXIMUM BOOK PRICE.
16. DISPLAY STUDENTS WHO HAVE THE MAXIMUM AGE.
17. DISPLAY STUDENTS WHO HAVE THE MINIMUM AGE.
18. DISPLAY COURSES WHOSE FEES ARE GREATER THAN THE AVERAGE COURSE FEE.
19. DISPLAY COURSES WHOSE FEES ARE LESS THAN THE AVERAGE COURSE FEE.
20. DISPLAY MOVIES WHOSE RATING IS GREATER THAN THE AVERAGE MOVIE RATING. */ 

SELECT * FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);
SELECT * FROM PRODUCTS WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS);
SELECT * FROM PRODUCTS WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS);
SELECT * FROM BOOKS WHERE PRICE > (SELECT AVG(PRICE) FROM BOOKS);
SELECT * FROM BOOKS WHERE PRICE < (SELECT AVG(PRICE) FROM BOOKS);
SELECT * FROM STUDENTS WHERE AGE > (SELECT AVG(AGE) FROM STUDENTS);
SELECT * FROM STUDENTS WHERE AGE < (SELECT AVG(AGE) FROM STUDENTS);
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);
SELECT * FROM PRODUCTS WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS);
SELECT * FROM PRODUCTS WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCTS);
SELECT * FROM BOOKS WHERE PRICE = (SELECT MAX(PRICE) FROM BOOKS);
SELECT * FROM STUDENTS WHERE AGE = (SELECT MAX(AGE) FROM STUDENTS);
SELECT * FROM STUDENTS WHERE AGE = (SELECT MIN(AGE) FROM STUDENTS);
SELECT * FROM COURSES WHERE FEES > (SELECT AVG(FEES) FROM COURSES);
SELECT * FROM COURSES WHERE FEES < (SELECT AVG(FEES) FROM COURSES);
SELECT * FROM MOVIES WHERE RATING > (SELECT AVG(RATING) FROM MOVIES);

/* B. SUBQUERY WITH IN – 20 QUESTIONS

21. DISPLAY EMPLOYEES WHO WORK IN THE SAME DEPARTMENT AS THE EMPLOYEE NAMED 'RAHUL'.
22. DISPLAY STUDENTS WHO BELONG TO THE SAME DEPARTMENT AS THE STUDENT NAMED 'ANU'.
23. DISPLAY PRODUCTS BELONGING TO THE SAME CATEGORY AS THE PRODUCT NAMED 'LAPTOP'.
24. DISPLAY BOOKS BELONGING TO THE SAME CATEGORY AS THE BOOK NAMED 'SQL BASICS'.
25. DISPLAY EMPLOYEES WHO WORK IN DEPARTMENTS WHERE AT LEAST ONE EMPLOYEE EARNS MORE THAN 60000.
26. DISPLAY STUDENTS WHO BELONG TO DEPARTMENTS WHERE AT LEAST ONE STUDENT IS OLDER THAN 22.
27. DISPLAY PRODUCTS BELONGING TO CATEGORIES WHERE AT LEAST ONE PRODUCT COSTS MORE THAN 5000.
28. DISPLAY BOOKS BELONGING TO CATEGORIES WHERE AT LEAST ONE BOOK COSTS MORE THAN 1000.
29. DISPLAY EMPLOYEES WHO WORK IN DEPARTMENTS WHERE AT LEAST ONE EMPLOYEE HAS THE DESIGNATION 'MANAGER'.
30. DISPLAY COURSES BELONGING TO DEPARTMENTS WHERE AT LEAST ONE COURSE HAS FEES GREATER THAN 50000.
31. DISPLAY STUDENTS WHO BELONG TO DEPARTMENTS WHERE AT LEAST ONE STUDENT HAS AGE GREATER THAN 25.
32. DISPLAY PRODUCTS WHOSE CATEGORY IS AVAILABLE IN THE PRODUCTS TABLE WITH STOCK GREATER THAN 100.
33. DISPLAY EMPLOYEES WHOSE DEPARTMENT IS PRESENT AMONG DEPARTMENTS OF EMPLOYEES EARNING MORE THAN 70000.
34. DISPLAY BOOKS WHOSE CATEGORY IS PRESENT AMONG CATEGORIES HAVING BOOKS PRICED ABOVE 1500.
35. DISPLAY CUSTOMERS WHOSE CITY IS ALSO PRESENT IN THE LIST OF CITIES OF CUSTOMERS FROM THE STATE 'TAMIL NADU'.
36. DISPLAY EMPLOYEES WHOSE DEPARTMENT IS ALSO THE DEPARTMENT OF EMPLOYEES EARNING LESS THAN 30000.
37. DISPLAY STUDENTS WHOSE DEPARTMENT IS ALSO THE DEPARTMENT OF STUDENTS WITH AGE BETWEEN 20 AND 25.
38. DISPLAY PRODUCTS WHOSE BRAND IS ALSO THE BRAND OF PRODUCTS PRICED ABOVE 50000.
39. DISPLAY BOOKS WHOSE AUTHOR IS ALSO AN AUTHOR OF BOOKS PRICED ABOVE 1000.
40. DISPLAY COURSES WHOSE DEPARTMENT IS ALSO THE DEPARTMENT OF COURSES WITH DURATION '6 MONTHS'. */

SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE NAME = 'RAHUL');
SELECT * FROM STUDENTS WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM STUDENTS WHERE NAME = 'ANU');
SELECT * FROM PRODUCTS WHERE CATEGORY IN (SELECT CATEGORY FROM PRODUCTS WHERE PRODUCT_NAME = 'LAPTOP');
SELECT * FROM BOOKS WHERE CATEGORY IN (SELECT CATEGORY FROM BOOKS WHERE BOOK_NAME = 'SQL BASICS');
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE SALARY > 60000);
SELECT * FROM STUDENTS WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM STUDENTS WHERE AGE > 22);
SELECT * FROM PRODUCTS WHERE CATEGORY IN (SELECT CATEGORY FROM PRODUCTS WHERE PRICE > 5000);
SELECT * FROM BOOKS WHERE CATEGORY IN (SELECT CATEGORY FROM BOOKS WHERE PRICE > 1000);
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE DESIGNATION = 'MANAGER');
SELECT * FROM COURSES WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM COURSES WHERE FEES > 50000);
SELECT * FROM STUDENTS WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM STUDENTS WHERE AGE > 25);
SELECT * FROM PRODUCTS WHERE CATEGORY IN (SELECT CATEGORY FROM PRODUCTS WHERE STOCK > 100);
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE SALARY > 70000);
SELECT * FROM BOOKS WHERE CATEGORY IN (SELECT CATEGORY FROM BOOKS WHERE PRICE > 1500);
SELECT * FROM CUSTOMERS WHERE CITY IN (SELECT CITY FROM CUSTOMERS WHERE STATE = 'TAMIL NADU');
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE SALARY < 30000);
SELECT * FROM STUDENTS WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM STUDENTS WHERE AGE BETWEEN 20 AND 25);
SELECT * FROM PRODUCTS WHERE BRAND IN (SELECT BRAND FROM PRODUCTS WHERE PRICE > 50000);
SELECT * FROM BOOKS WHERE AUTHOR IN (SELECT AUTHOR FROM BOOKS WHERE PRICE > 1000);
SELECT * FROM COURSES WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM COURSES WHERE DURATION = '6 MONTHS');

/* C. SUBQUERY WITH AGGREGATE FUNCTIONS – 20 QUESTIONS

41. FIND EMPLOYEES WHOSE SALARY IS GREATER THAN THE AVERAGE IT EMPLOYEE SALARY.
42. FIND EMPLOYEES WHOSE SALARY IS GREATER THAN THE AVERAGE HR EMPLOYEE SALARY.
43. FIND EMPLOYEES WHOSE SALARY IS LESS THAN THE AVERAGE FINANCE EMPLOYEE SALARY.
44. FIND PRODUCTS WHOSE PRICE IS GREATER THAN THE AVERAGE ELECTRONICS PRODUCT PRICE.
45. FIND PRODUCTS WHOSE PRICE IS LESS THAN THE AVERAGE ACCESSORIES PRODUCT PRICE.
46. FIND BOOKS WHOSE PRICE IS GREATER THAN THE AVERAGE TECHNOLOGY BOOK PRICE.
47. FIND BOOKS WHOSE PRICE IS LESS THAN THE AVERAGE SCIENCE BOOK PRICE.
48. FIND STUDENTS WHOSE AGE IS GREATER THAN THE AVERAGE AGE OF IT STUDENTS.
49. FIND STUDENTS WHOSE AGE IS LESS THAN THE AVERAGE AGE OF CSE STUDENTS.
50. FIND COURSES WHOSE FEES ARE GREATER THAN THE AVERAGE FEES OF CSE COURSES.
51. FIND COURSES WHOSE FEES ARE LESS THAN THE AVERAGE FEES OF IT COURSES.
52. FIND EMPLOYEES WHOSE SALARY IS EQUAL TO THE MAXIMUM SALARY IN THE IT DEPARTMENT.
53. FIND EMPLOYEES WHOSE SALARY IS EQUAL TO THE MINIMUM SALARY IN THE HR DEPARTMENT.
54. FIND PRODUCTS WHOSE PRICE IS EQUAL TO THE MAXIMUM PRICE IN ELECTRONICS.
55. FIND PRODUCTS WHOSE PRICE IS EQUAL TO THE MINIMUM PRICE IN ACCESSORIES.
56. FIND BOOKS WHOSE PRICE IS EQUAL TO THE MAXIMUM PRICE IN TECHNOLOGY.
57. FIND STUDENTS WHOSE AGE IS EQUAL TO THE MAXIMUM AGE IN CSE.
58. FIND STUDENTS WHOSE AGE IS EQUAL TO THE MINIMUM AGE IN IT.
59. FIND COURSES WHOSE FEES ARE EQUAL TO THE MAXIMUM FEES IN CSE.
60. FIND MOVIES WHOSE RATING IS EQUAL TO THE MAXIMUM MOVIE RATING. */

SELECT * FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT');
SELECT * FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR');
SELECT * FROM EMPLOYEES WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'FINANCE');
SELECT * FROM PRODUCTS WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');
SELECT * FROM PRODUCTS WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY = 'ACCESSORIES');
SELECT * FROM BOOKS WHERE PRICE > (SELECT AVG(PRICE) FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');
SELECT * FROM BOOKS WHERE PRICE < (SELECT AVG(PRICE) FROM BOOKS WHERE CATEGORY = 'SCIENCE');
SELECT * FROM STUDENTS WHERE AGE > (SELECT AVG(AGE) FROM STUDENTS WHERE DEPARTMENT = 'IT');
SELECT * FROM STUDENTS WHERE AGE < (SELECT AVG(AGE) FROM STUDENTS WHERE DEPARTMENT = 'CSE');
SELECT * FROM COURSES WHERE FEES > (SELECT AVG(FEES) FROM COURSES WHERE DEPARTMENT = 'CSE');
SELECT * FROM COURSES WHERE FEES < (SELECT AVG(FEES) FROM COURSES WHERE DEPARTMENT = 'IT');
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT');
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR');
SELECT * FROM PRODUCTS WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');
SELECT * FROM PRODUCTS WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCTS WHERE CATEGORY = 'ACCESSORIES');
SELECT * FROM BOOKS WHERE PRICE = (SELECT MAX(PRICE) FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');
SELECT * FROM STUDENTS WHERE AGE = (SELECT MAX(AGE) FROM STUDENTS WHERE DEPARTMENT = 'CSE');
SELECT * FROM STUDENTS WHERE AGE = (SELECT MIN(AGE) FROM STUDENTS WHERE DEPARTMENT = 'IT');
SELECT * FROM COURSES WHERE FEES = (SELECT MAX(FEES) FROM COURSES WHERE DEPARTMENT = 'CSE');
SELECT * FROM MOVIES WHERE RATING = (SELECT MAX(RATING) FROM MOVIES);

/* D. CORRELATED SUBQUERY – 20 QUESTIONS

61. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN THE AVERAGE SALARY OF THEIR OWN DEPARTMENT.
62. DISPLAY EMPLOYEES WHOSE SALARY IS LESS THAN THE AVERAGE SALARY OF THEIR OWN DEPARTMENT.
63. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN THE AVERAGE AGE OF THEIR OWN DEPARTMENT.
64. DISPLAY STUDENTS WHOSE AGE IS LESS THAN THE AVERAGE AGE OF THEIR OWN DEPARTMENT.
65. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN THE AVERAGE PRICE OF THEIR OWN CATEGORY.
66. DISPLAY PRODUCTS WHOSE PRICE IS LESS THAN THE AVERAGE PRICE OF THEIR OWN CATEGORY.
67. DISPLAY BOOKS WHOSE PRICE IS GREATER THAN THE AVERAGE PRICE OF THEIR OWN CATEGORY.
68. DISPLAY BOOKS WHOSE PRICE IS LESS THAN THE AVERAGE PRICE OF THEIR OWN CATEGORY.
69. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN THE MINIMUM SALARY IN THEIR DEPARTMENT.
70. DISPLAY EMPLOYEES WHOSE SALARY IS EQUAL TO THE MAXIMUM SALARY IN THEIR DEPARTMENT.
71. DISPLAY STUDENTS WHOSE AGE IS EQUAL TO THE MAXIMUM AGE IN THEIR DEPARTMENT.
72. DISPLAY STUDENTS WHOSE AGE IS EQUAL TO THE MINIMUM AGE IN THEIR DEPARTMENT.
73. DISPLAY PRODUCTS WHOSE PRICE IS EQUAL TO THE MINIMUM PRICE IN THEIR CATEGORY.
74. DISPLAY PRODUCTS WHOSE PRICE IS EQUAL TO THE MAXIMUM PRICE IN THEIR CATEGORY.
75. DISPLAY BOOKS WHOSE PRICE IS EQUAL TO THE MAXIMUM PRICE IN THEIR CATEGORY.
76. DISPLAY BOOKS WHOSE PRICE IS EQUAL TO THE MINIMUM PRICE IN THEIR CATEGORY.
77. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN THE AVERAGE SALARY OF EMPLOYEES HAVING THE SAME DESIGNATION.
78. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN THE AVERAGE PRICE OF PRODUCTS HAVING THE SAME BRAND.
79. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN THE AVERAGE AGE OF STUDENTS HAVING THE SAME AGE.
80. DISPLAY COURSES WHOSE FEES ARE GREATER THAN THE AVERAGE FEES OF COURSES BELONGING TO THE SAME DEPARTMENT. */

SELECT * FROM EMPLOYEES E WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT);
SELECT * FROM EMPLOYEES E WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT);
SELECT * FROM STUDENTS S WHERE AGE > (SELECT AVG(AGE) FROM STUDENTS WHERE DEPARTMENT = S.DEPARTMENT);
SELECT * FROM STUDENTS S WHERE AGE < (SELECT AVG(AGE) FROM STUDENTS WHERE DEPARTMENT = S.DEPARTMENT);
SELECT * FROM PRODUCTS P WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY = P.CATEGORY);
SELECT * FROM PRODUCTS P WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY = P.CATEGORY);
SELECT * FROM BOOKS B WHERE PRICE > (SELECT AVG(PRICE) FROM BOOKS WHERE CATEGORY = B.CATEGORY);
SELECT * FROM BOOKS B WHERE PRICE < (SELECT AVG(PRICE) FROM BOOKS WHERE CATEGORY = B.CATEGORY);
SELECT * FROM EMPLOYEES E WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT);
SELECT * FROM EMPLOYEES E WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT);
SELECT * FROM STUDENTS S WHERE AGE = (SELECT MAX(AGE) FROM STUDENTS WHERE DEPARTMENT = S.DEPARTMENT);
SELECT * FROM STUDENTS S WHERE AGE = (SELECT MIN(AGE) FROM STUDENTS WHERE DEPARTMENT = S.DEPARTMENT);
SELECT * FROM PRODUCTS P WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCTS WHERE CATEGORY = P.CATEGORY);
SELECT * FROM PRODUCTS P WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS WHERE CATEGORY = P.CATEGORY);
SELECT * FROM BOOKS B WHERE PRICE = (SELECT MAX(PRICE) FROM BOOKS WHERE CATEGORY = B.CATEGORY);
SELECT * FROM BOOKS B WHERE PRICE = (SELECT MIN(PRICE) FROM BOOKS WHERE CATEGORY = B.CATEGORY);
SELECT * FROM EMPLOYEES E WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DESIGNATION = E.DESIGNATION);
SELECT * FROM PRODUCTS P WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS WHERE BRAND = P.BRAND);
SELECT * FROM STUDENTS S WHERE AGE > (SELECT AVG(AGE) FROM STUDENTS WHERE AGE = S.AGE);
SELECT * FROM COURSES C WHERE FEES > (SELECT AVG(FEES) FROM COURSES WHERE DEPARTMENT = C.DEPARTMENT);

/* E. SUBQUERY WITH ANY AND ALL – 20 QUESTIONS

81. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN ANY SALARY IN THE HR DEPARTMENT.
82. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN ALL SALARIES IN THE HR DEPARTMENT.
83. DISPLAY EMPLOYEES WHOSE SALARY IS LESS THAN ANY SALARY IN THE IT DEPARTMENT.
84. DISPLAY EMPLOYEES WHOSE SALARY IS LESS THAN ALL SALARIES IN THE IT DEPARTMENT.
85. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN ANY ELECTRONICS PRODUCT PRICE.
86. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN ALL ELECTRONICS PRODUCT PRICES.
87. DISPLAY BOOKS WHOSE PRICE IS LESS THAN ANY TECHNOLOGY BOOK PRICE.
88. DISPLAY BOOKS WHOSE PRICE IS LESS THAN ALL TECHNOLOGY BOOK PRICES.
89. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN ANY AGE OF CSE STUDENTS.
90. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN ALL AGES OF CSE STUDENTS.
91. DISPLAY COURSES WHOSE FEES ARE GREATER THAN ANY IT COURSE FEE.
92. DISPLAY COURSES WHOSE FEES ARE GREATER THAN ALL IT COURSE FEES.
93. DISPLAY EMPLOYEES WHOSE SALARY IS EQUAL TO ANY SALARY OF DEVELOPERS.
94. DISPLAY PRODUCTS WHOSE PRICE IS EQUAL TO ANY PRICE OF SAMSUNG PRODUCTS.
95. DISPLAY BOOKS WHOSE PRICE IS GREATER THAN ANY SCIENCE BOOK PRICE.
96. DISPLAY BOOKS WHOSE PRICE IS GREATER THAN ALL SCIENCE BOOK PRICES.
97. DISPLAY STUDENTS WHOSE AGE IS LESS THAN ANY AGE OF IT STUDENTS.
98. DISPLAY STUDENTS WHOSE AGE IS LESS THAN ALL AGES OF IT STUDENTS.
99. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN ALL SALARIES OF EMPLOYEES WORKING AS TESTERS.
100. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN ALL PRODUCTS BELONGING TO THE ACCESSORIES CATEGORY. */

SELECT * FROM EMPLOYEES WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'HR');
SELECT * FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'HR');
SELECT * FROM EMPLOYEES WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'IT');
SELECT * FROM EMPLOYEES WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'IT');
SELECT * FROM PRODUCTS WHERE PRICE > ANY (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');
SELECT * FROM PRODUCTS WHERE PRICE > ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');
SELECT * FROM BOOKS WHERE PRICE < ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');
SELECT * FROM BOOKS WHERE PRICE < ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');
SELECT * FROM STUDENTS WHERE AGE > ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'CSE');
SELECT * FROM STUDENTS WHERE AGE > ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'CSE');
SELECT * FROM COURSES WHERE FEES > ANY (SELECT FEES FROM COURSES WHERE DEPARTMENT = 'IT');
SELECT * FROM COURSES WHERE FEES > ALL (SELECT FEES FROM COURSES WHERE DEPARTMENT = 'IT');
SELECT * FROM EMPLOYEES WHERE SALARY = ANY (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER');
SELECT * FROM PRODUCTS WHERE PRICE = ANY (SELECT PRICE FROM PRODUCTS WHERE BRAND = 'SAMSUNG');
SELECT * FROM BOOKS WHERE PRICE > ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'SCIENCE');
SELECT * FROM BOOKS WHERE PRICE > ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'SCIENCE');
SELECT * FROM STUDENTS WHERE AGE < ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'IT');
SELECT * FROM STUDENTS WHERE AGE < ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'IT');
SELECT * FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION = 'TESTER');
SELECT * FROM PRODUCTS WHERE PRICE > ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ACCESSORIES');
