#Date: 27th August 2026
#Date Covered: 25th August 2026
#Topics Covered:


/* 
ANY AND ALL
OBJECTIVE
PRACTICE USING ANY AND ALL WITH SUBQUERIES.
• ANY → CONDITION SHOULD BE TRUE FOR AT LEAST ONE VALUE RETURNED BY THE SUBQUERY.
• ALL → CONDITION SHOULD BE TRUE FOR EVERY VALUE RETURNED BY THE SUBQUERY.
NOTE: ANY AND ALL ARE GENERALLY USED WITH A SUBQUERY AND COMPARISON OPERATORS SUCH AS >, <, =, >=, AND <=.


A. ANY – PRACTICE QUESTIONS

1. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN ANY SALARY OF EMPLOYEES IN THE HR DEPARTMENT.
2. DISPLAY EMPLOYEES WHOSE SALARY IS LESS THAN ANY SALARY OF EMPLOYEES IN THE IT DEPARTMENT.
3. DISPLAY EMPLOYEES WHOSE SALARY IS EQUAL TO ANY SALARY OF EMPLOYEES IN THE FINANCE DEPARTMENT.
4. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN ANY PRODUCT PRICE IN THE ELECTRONICS CATEGORY.
5. DISPLAY PRODUCTS WHOSE PRICE IS LESS THAN ANY PRODUCT PRICE IN THE ACCESSORIES CATEGORY.
6. DISPLAY BOOKS WHOSE PRICE IS GREATER THAN ANY BOOK PRICE IN THE TECHNOLOGY CATEGORY.
7. DISPLAY BOOKS WHOSE PRICE IS LESS THAN ANY BOOK PRICE IN THE SCIENCE CATEGORY.
8. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN ANY AGE OF STUDENTS IN THE IT DEPARTMENT.
9. DISPLAY STUDENTS WHOSE AGE IS LESS THAN ANY AGE OF STUDENTS IN THE CSE DEPARTMENT.
10. DISPLAY COURSES WHOSE FEES ARE GREATER THAN ANY FEES OF COURSES OFFERED BY THE IT DEPARTMENT.
11. DISPLAY COURSES WHOSE FEES ARE LESS THAN ANY FEES OF COURSES OFFERED BY THE CSE DEPARTMENT.
12. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN ANY SALARY OF EMPLOYEES WORKING AS DEVELOPER.
13. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN ANY PRICE OF PRODUCTS BELONGING TO THE SAMSUNG BRAND.
14. DISPLAY BOOKS WHOSE QUANTITY IS GREATER THAN ANY QUANTITY OF BOOKS IN THE TECHNOLOGY CATEGORY.
15. DISPLAY PATIENTS WHOSE AGE IS GREATER THAN ANY AGE OF PATIENTS WHOSE DISEASE IS 'FEVER'. */

SELECT * FROM EMPLOYEES
WHERE SALARY > ANY (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT = 'HR'
);

SELECT * FROM EMPLOYEES
WHERE SALARY < ANY (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT = 'IT'
);

SELECT * FROM EMPLOYEES
WHERE SALARY = ANY (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT = 'FINANCE'
);

SELECT * FROM PRODUCTS
WHERE PRICE > ANY (
    SELECT PRICE
    FROM PRODUCTS
    WHERE CATEGORY = 'ELECTRONICS'
);

SELECT * FROM PRODUCTS
WHERE PRICE < ANY (
    SELECT PRICE
    FROM PRODUCTS
    WHERE CATEGORY = 'ACCESSORIES'
);

SELECT * FROM BOOKS
WHERE PRICE > ANY (
    SELECT PRICE
    FROM BOOKS
    WHERE CATEGORY = 'TECHNOLOGY'
);

SELECT * FROM BOOKS
WHERE PRICE < ANY (
    SELECT PRICE
    FROM BOOKS
    WHERE CATEGORY = 'SCIENCE'
);

SELECT * FROM STUDENTS
WHERE AGE > ANY (
    SELECT AGE
    FROM STUDENTS
    WHERE DEPARTMENT = 'IT'
);

SELECT * FROM STUDENTS
WHERE AGE < ANY (
    SELECT AGE
    FROM STUDENTS
    WHERE DEPARTMENT = 'CSE'
);

SELECT * FROM COURSES
WHERE FEES > ANY (
    SELECT FEES
    FROM COURSES
    WHERE DEPARTMENT = 'IT'
);

SELECT * FROM COURSES
WHERE FEES < ANY (
    SELECT FEES
    FROM COURSES
    WHERE DEPARTMENT = 'CSE'
);

SELECT * FROM EMPLOYEES
WHERE SALARY > ANY (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE JOB_TITLE = 'DEVELOPER'
);

SELECT * FROM PRODUCTS
WHERE PRICE > ANY (
    SELECT PRICE
    FROM PRODUCTS
    WHERE BRAND = 'SAMSUNG'
);

SELECT * FROM BOOKS
WHERE QUANTITY > ANY (
    SELECT QUANTITY
    FROM BOOKS
    WHERE CATEGORY = 'TECHNOLOGY'
);

SELECT * FROM PATIENTS
WHERE AGE > ANY (
    SELECT AGE
    FROM PATIENTS
    WHERE DISEASE = 'FEVER'
);

/* B. ALL – PRACTICE QUESTIONS

16. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN ALL SALARIES OF EMPLOYEES IN THE HR DEPARTMENT.
17. DISPLAY EMPLOYEES WHOSE SALARY IS LESS THAN ALL SALARIES OF EMPLOYEES IN THE IT DEPARTMENT.
18. DISPLAY EMPLOYEES WHOSE SALARY IS EQUAL TO ALL SALARIES OF EMPLOYEES IN THE FINANCE DEPARTMENT.
19. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN ALL PRODUCT PRICES IN THE ELECTRONICS CATEGORY.
20. DISPLAY PRODUCTS WHOSE PRICE IS LESS THAN ALL PRODUCT PRICES IN THE ACCESSORIES CATEGORY.
21. DISPLAY BOOKS WHOSE PRICE IS GREATER THAN ALL BOOK PRICES IN THE TECHNOLOGY CATEGORY.
22. DISPLAY BOOKS WHOSE PRICE IS LESS THAN ALL BOOK PRICES IN THE SCIENCE CATEGORY.
23. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN ALL AGES OF STUDENTS IN THE IT DEPARTMENT.
24. DISPLAY STUDENTS WHOSE AGE IS LESS THAN ALL AGES OF STUDENTS IN THE CSE DEPARTMENT.
25. DISPLAY COURSES WHOSE FEES ARE GREATER THAN ALL FEES OF COURSES OFFERED BY THE IT DEPARTMENT.
26. DISPLAY COURSES WHOSE FEES ARE LESS THAN ALL FEES OF COURSES OFFERED BY THE CSE DEPARTMENT.
27. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN ALL SALARIES OF EMPLOYEES WORKING AS DEVELOPER.
28. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN ALL PRICES OF PRODUCTS BELONGING TO THE SAMSUNG BRAND.
29. DISPLAY BOOKS WHOSE QUANTITY IS GREATER THAN ALL QUANTITIES OF BOOKS IN THE TECHNOLOGY CATEGORY.
30. DISPLAY PATIENTS WHOSE AGE IS GREATER THAN ALL AGES OF PATIENTS WHOSE DISEASE IS 'FEVER'. */

SELECT * FROM EMPLOYEES
WHERE SALARY > ALL (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT = 'HR'
);

SELECT * FROM EMPLOYEES
WHERE SALARY < ALL (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT = 'IT'
);

SELECT * FROM EMPLOYEES
WHERE SALARY = ALL (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT = 'FINANCE'
);

SELECT * FROM PRODUCTS
WHERE PRICE > ALL (
    SELECT PRICE
    FROM PRODUCTS
    WHERE CATEGORY = 'ELECTRONICS'
);

SELECT * FROM PRODUCTS
WHERE PRICE < ALL (
    SELECT PRICE
    FROM PRODUCTS
    WHERE CATEGORY = 'ACCESSORIES'
);

SELECT * FROM BOOKS
WHERE PRICE > ALL (
    SELECT PRICE
    FROM BOOKS
    WHERE CATEGORY = 'TECHNOLOGY'
);

SELECT * FROM BOOKS
WHERE PRICE < ALL (
    SELECT PRICE
    FROM BOOKS
    WHERE CATEGORY = 'SCIENCE'
);

SELECT * FROM STUDENTS
WHERE AGE > ALL (
    SELECT AGE
    FROM STUDENTS
    WHERE DEPARTMENT = 'IT'
);

SELECT * FROM STUDENTS
WHERE AGE < ALL (
    SELECT AGE
    FROM STUDENTS
    WHERE DEPARTMENT = 'CSE'
);

SELECT * FROM COURSES
WHERE FEES > ALL (
    SELECT FEES
    FROM COURSES
    WHERE DEPARTMENT = 'IT'
);

SELECT * FROM COURSES
WHERE FEES < ALL (
    SELECT FEES
    FROM COURSES
    WHERE DEPARTMENT = 'CSE'
);

SELECT * FROM EMPLOYEES
WHERE SALARY > ALL (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE JOB_TITLE = 'DEVELOPER'
);

SELECT * FROM PRODUCTS
WHERE PRICE > ALL (
    SELECT PRICE
    FROM PRODUCTS
    WHERE BRAND = 'SAMSUNG'
);

SELECT * FROM BOOKS
WHERE QUANTITY > ALL (
    SELECT QUANTITY
    FROM BOOKS
    WHERE CATEGORY = 'TECHNOLOGY'
);

SELECT * FROM PATIENTS
WHERE AGE > ALL (
    SELECT AGE
    FROM PATIENTS
    WHERE DISEASE = 'FEVER'
);

/* C. MIXED ANY AND ALL

31. FIND EMPLOYEES WHOSE SALARY IS GREATER THAN ANY SALARY IN THE HR DEPARTMENT.
32. FIND EMPLOYEES WHOSE SALARY IS GREATER THAN ALL SALARIES IN THE HR DEPARTMENT.
33. FIND PRODUCTS WHOSE PRICE IS LESS THAN ANY ELECTRONICS PRODUCT PRICE.
34. FIND PRODUCTS WHOSE PRICE IS LESS THAN ALL ELECTRONICS PRODUCT PRICES.
35. FIND BOOKS WHOSE PRICE IS GREATER THAN ANY TECHNOLOGY BOOK PRICE.
36. FIND BOOKS WHOSE PRICE IS GREATER THAN ALL TECHNOLOGY BOOK PRICES.
37. FIND STUDENTS WHOSE AGE IS GREATER THAN ANY STUDENT AGE IN CSE.
38. FIND STUDENTS WHOSE AGE IS GREATER THAN ALL STUDENT AGES IN CSE.
39. FIND EMPLOYEES WHOSE SALARY IS LESS THAN ANY DEVELOPER SALARY.
40. FIND EMPLOYEES WHOSE SALARY IS LESS THAN ALL DEVELOPER SALARIES. */

SELECT * FROM EMPLOYEES
WHERE SALARY > ANY (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT = 'HR'
);

SELECT * FROM EMPLOYEES
WHERE SALARY > ALL (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT = 'HR'
);

SELECT * FROM PRODUCTS
WHERE PRICE < ANY (
    SELECT PRICE
    FROM PRODUCTS
    WHERE CATEGORY = 'ELECTRONICS'
);

SELECT * FROM PRODUCTS
WHERE PRICE < ALL (
    SELECT PRICE
    FROM PRODUCTS
    WHERE CATEGORY = 'ELECTRONICS'
);

SELECT * FROM BOOKS
WHERE PRICE > ANY (
    SELECT PRICE
    FROM BOOKS
    WHERE CATEGORY = 'TECHNOLOGY'
);

SELECT * FROM BOOKS
WHERE PRICE > ALL (
    SELECT PRICE
    FROM BOOKS
    WHERE CATEGORY = 'TECHNOLOGY'
);

SELECT * FROM STUDENTS
WHERE AGE > ANY (
    SELECT AGE
    FROM STUDENTS
    WHERE DEPARTMENT = 'CSE'
);

SELECT * FROM STUDENTS
WHERE AGE > ALL (
    SELECT AGE
    FROM STUDENTS
    WHERE DEPARTMENT = 'CSE'
);

SELECT * FROM EMPLOYEES
WHERE SALARY < ANY (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE JOB_TITLE = 'DEVELOPER'
);

SELECT * FROM EMPLOYEES
WHERE SALARY < ALL (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE JOB_TITLE = 'DEVELOPER'
);
