#Date: 25th August 2026
# Topics Covered:

/* 
ALIAS
OBJECTIVE
PRACTICE USING ALIASES TO GIVE TEMPORARY NAMES TO COLUMNS, EXPRESSIONS, AGGREGATE RESULTS, AND TABLES.

A. COLUMN ALIAS – 20 QUESTIONS

1. DISPLAY THE STUDENT NAME WITH THE ALIAS STUDENT_NAME.
2. DISPLAY THE EMPLOYEE NAME WITH THE ALIAS EMPLOYEE_NAME.
3. DISPLAY THE EMPLOYEE SALARY WITH THE ALIAS MONTHLY_SALARY.
4. DISPLAY THE PRODUCT NAME WITH THE ALIAS PRODUCT_NAME.
5. DISPLAY THE PRODUCT PRICE WITH THE ALIAS PRODUCT_PRICE.
6. DISPLAY THE BOOK NAME WITH THE ALIAS BOOK_NAME.
7. DISPLAY THE COURSE NAME WITH THE ALIAS COURSE_NAME.
8. DISPLAY THE CUSTOMER NAME WITH THE ALIAS CUSTOMER_NAME.
9. DISPLAY THE STUDENT DEPARTMENT WITH THE ALIAS DEPARTMENT_NAME.
10. DISPLAY THE EMPLOYEE DESIGNATION WITH THE ALIAS JOB_ROLE.
11. DISPLAY THE EMPLOYEE JOINING DATE WITH THE ALIAS DATE_OF_JOINING.
12. DISPLAY THE CUSTOMER REGISTRATION DATE WITH THE ALIAS REGISTRATION_DATE.
13. DISPLAY THE PRODUCT STOCK WITH THE ALIAS AVAILABLE_STOCK.
14. DISPLAY THE COURSE FEES WITH THE ALIAS COURSE_FEES.
15. DISPLAY THE STUDENT EMAIL WITH THE ALIAS EMAIL_ID.
16. DISPLAY THE EMPLOYEE PHONE NUMBER WITH THE ALIAS CONTACT_NUMBER.
17. DISPLAY THE BOOK AUTHOR WITH THE ALIAS AUTHOR_NAME.
18. DISPLAY THE PRODUCT BRAND WITH THE ALIAS BRAND_NAME.
19. DISPLAY THE PATIENT BLOOD GROUP WITH THE ALIAS BLOOD_GROUP.
20. DISPLAY THE MOVIE RATING WITH THE ALIAS MOVIE_RATING. */

SELECT STUDENTNAME AS STUDNET_NAME FROM STUDENTS;
SELECT EMPLOYEENAME AS EMPLOYEE_NAME FROM EMPLOYEES;
SELECT SALARY AS MONTHLY_SALARY FROM EMPLOYEES;
SELECT NAME AS PRODUCT_NAME FROM PRODUCTS;
SELECT PRICE AS PRODUCT_PRICE FROM PRODUCTS;
SELECT NAME AS BOOK_NAME FROM BOOKS;
SELECT NAME AS COURSE_NAME FROM COURSES;
SELECT NAME AS CUSTOMER_NAME FROM CUSTOMERS;
SELECT DEPARTMENT AS DEPARTMENT_NAME FROM STUDENTS;
SELECT DESIGNATION AS JOB_ROLE FROM EMPLOYEES;
SELECT JOINING_DATE AS DATE_OF_JOINING FROM EMPLOYEES;
SELECT REGISTRATIONDATE AS REGISTRATION_DATE FROM CUSTOMERS;
SELECT STOCK AS AVAILABLE_STOCK FROM PRODUCTS;
SELECT FEES AS COURSE_FEES FROM COURSES;
SELECT EMAIL AS EMAIL_ID FROM STUDENTS;
SELECT PHONE_NUMBER AS CONTACT_NUMBER FROM EMPLOYEES;
SELECT AUTHOR AS AUTHOR_NAME FROM BOOKS;
SELECT BRAND AS BRAND_NAME FROM PRODUCTS;
SELECT BLOODGROUP AS BLOOD_GROUP FROM PATIENTS;
SELECT RATING AS MOVIE_RATING FROM MOVIES;

/* B. ALIAS WITH EXPRESSIONS – 20 QUESTIONS

21. DISPLAY EMPLOYEE SALARY MULTIPLIED BY 12 WITH THE ALIAS ANNUAL_SALARY.
22. DISPLAY EMPLOYEE SALARY AFTER A 10% INCREMENT WITH THE ALIAS INCREMENTED_SALARY.
23. DISPLAY EMPLOYEE SALARY AFTER A 5% DEDUCTION WITH THE ALIAS NET_SALARY.
24. DISPLAY PRODUCT PRICE MULTIPLIED BY QUANTITY WITH THE ALIAS TOTAL_VALUE.
25. DISPLAY PRODUCT PRICE AFTER A 10% DISCOUNT WITH THE ALIAS DISCOUNTED_PRICE.
26. DISPLAY PRODUCT PRICE AFTER ADDING 18% GST WITH THE ALIAS FINAL_PRICE.
27. DISPLAY BOOK PRICE AFTER A 20% DISCOUNT WITH THE ALIAS DISCOUNTED_PRICE.
28. DISPLAY COURSE FEES AFTER A 15% DISCOUNT WITH THE ALIAS FINAL_FEES.
29. DISPLAY STUDENT AGE + 1 WITH THE ALIAS NEXT_YEAR_AGE.
30. DISPLAY EMPLOYEE SALARY DIVIDED BY 12 WITH THE ALIAS MONTHLY_SALARY.
31. DISPLAY PRODUCT PRICE × STOCK QUANTITY WITH THE ALIAS STOCK_VALUE.
32. DISPLAY EMPLOYEE SALARY × 12 × 1.10 WITH THE ALIAS ANNUAL_SALARY_AFTER_INCREMENT.
33. DISPLAY STUDENT NAME LENGTH USING LENGTH() WITH THE ALIAS NAME_LENGTH.
34. DISPLAY EMPLOYEE NAME IN UPPERCASE WITH THE ALIAS UPPER_NAME.
35. DISPLAY PRODUCT NAME IN LOWERCASE WITH THE ALIAS LOWER_PRODUCT_NAME.
36. DISPLAY STUDENT FIRST NAME AND LAST NAME USING CONCAT() WITH THE ALIAS FULL_NAME.
37. DISPLAY THE DATE 126 DAYS AFTER JOINING WITH THE ALIAS FUTURE_DATE.
38. DISPLAY THE DATE 42 DAYS BEFORE JOINING WITH THE ALIAS PREVIOUS_DATE.
39. DISPLAY THE DIFFERENCE BETWEEN SALARY AND 50000 WITH THE ALIAS SALARY_DIFFERENCE.
40. DISPLAY PRODUCT PRICE ROUNDED TO 2 DECIMAL PLACES WITH THE ALIAS ROUNDED_PRICE. */

SELECT SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEES;
SELECT SALARY*1.1 AS INCREMENTED_SALARY FROM EMPLOYEES;
SELECT SALARY*0.95 AS NET_SALARY FROM EMPLOYEES;
SELECT PRICE*QUANTITY AS TOTAL_VALUE FROM PRODUCTS;
SELECT PRICE*0.9 AS DISCOUNTED_PRICE FROM PRODUCTS;
SELECT PRICE*1.18 AS FINAL_PRICE FROM PRODUCTS;
SELECT PRICE*0.8 AS DISCOUNTED_PRICE FROM BOOKS;
SELECT FEES*0.85 AS FINAL_FEES FROM COURSES;
SELECT AGE+1 AS NEXT_YEAR_AGE FROM STUDENTS;
SELECT SALARY/12 AS MONTHLY_SALARY FROM EMPLOYEES;
SELECT PRICE*STOCK_QUANTITY AS STOCK_VALUE FROM PRODUCTS;
SELECT SALARY*12*1.10 AS ANNUAL_SALARY_AFTER_INCREMENT FROM EMPLOYEES;
SELECT LEN(STUDENT_NAME) AS NAME_LENGTH FROM STUDENTS;
SELECT UPPER(NAME) AS UPPER_NAME FROM EMPLOYEES;
SELECT LOWER(NAME) AS LOWER_PRODUCT_NAME FROM PRODUCTS;
SELECT CONCAT(FIRSTNAME , LASTNAME) AS FULL_NAME FROM STUDENTS;
SELECT DATE_ADD(DATE_OF_JOINING,126) AS FUTURE_DATE FROM EMPLOYEES;
SELECT DATE_SUB(DATE_OF_JOINING,42) AS PREVIOUS_DATE FROM EMPLOYEES;
SELECT ABS(SALARY - 50000) AS SALARY_DIFFERENCE FROM EMPLOYEES; -- !!!!ABS IS USED BCZ WE MAY GET -VE VALUES
SELECT ROUND(PRICE,2) AS ROUNDED_PRICE FROM PRODUCT;

/* C. ALIAS WITH AGGREGATE FUNCTIONS – 20 QUESTIONS

41. FIND THE TOTAL NUMBER OF STUDENTS AND GIVE THE RESULT THE ALIAS TOTAL_STUDENTS.
42. FIND THE TOTAL NUMBER OF EMPLOYEES WITH THE ALIAS TOTAL_EMPLOYEES.
43. FIND THE TOTAL NUMBER OF PRODUCTS WITH THE ALIAS TOTAL_PRODUCTS.
44. FIND THE TOTAL SALARY USING SUM() AND GIVE IT THE ALIAS TOTAL_SALARY.
45. FIND THE AVERAGE SALARY WITH THE ALIAS AVERAGE_SALARY.
46. FIND THE HIGHEST SALARY WITH THE ALIAS MAXIMUM_SALARY.
47. FIND THE LOWEST SALARY WITH THE ALIAS MINIMUM_SALARY.
48. FIND THE TOTAL PRODUCT STOCK WITH THE ALIAS TOTAL_STOCK.
49. FIND THE AVERAGE PRODUCT PRICE WITH THE ALIAS AVERAGE_PRICE.
50. FIND THE HIGHEST PRODUCT PRICE WITH THE ALIAS HIGHEST_PRICE.
51. FIND THE LOWEST PRODUCT PRICE WITH THE ALIAS LOWEST_PRICE.
52. FIND THE TOTAL COURSE FEES WITH THE ALIAS TOTAL_COURSE_FEES.
53. FIND THE AVERAGE COURSE FEES WITH THE ALIAS AVERAGE_COURSE_FEES.
54. FIND THE MAXIMUM COURSE FEE WITH THE ALIAS MAXIMUM_COURSE_FEE.
55. FIND THE MINIMUM COURSE FEE WITH THE ALIAS MINIMUM_COURSE_FEE.
56. FIND THE TOTAL BOOK QUANTITY WITH THE ALIAS TOTAL_BOOKS.
57. FIND THE AVERAGE BOOK PRICE WITH THE ALIAS AVERAGE_BOOK_PRICE.
58. FIND THE MAXIMUM BOOK PRICE WITH THE ALIAS MAXIMUM_BOOK_PRICE.
59. FIND THE MINIMUM BOOK PRICE WITH THE ALIAS MINIMUM_BOOK_PRICE.
60. COUNT THE NUMBER OF UNIQUE DEPARTMENTS AND GIVE THE RESULT THE ALIAS TOTAL_DEPARTMENTS. */ 

SELECT COUNT(*) AS TOTAL_STUDENTS FROM STUDENTS;
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES;
SELECT COUNT(*) AS TOTAL_PRODUCTS FROM PRODUCTS;
SELECT SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES;
SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES;
SELECT MAX(SALARY) AS MAXIMUM_SALARY FROM EMPLOYEES;
SELECT MIN(SALARY) AS MINIMUM_SALARY FROM EMPLOYEES;
SELECT SUM(STOCK) AS TOTAL_STOCK FROM PRODUCTS;
SELECT AVG(PRICE) AS AVERAGE_PRICE FROM PRODUCTS;
SELECT MAX(PRICE) AS HIGHEST_PRICE FROM PRODUCTS;
SELECT MIN(PRICE) AS LOWEST_PRICE FROM PRODUCTS;
SELECT SUM(FEES) AS TOTAL_COURSE_FEES FROM COURSES;
SELECT AVG(FEES) AS AVERAGE_COURSE_FEES FROM COURSES;
SELECT MAX(FEES) AS MAXIMUM_COURSE_FEE FROM COURSES;
SELECT MIN(FEES) AS MINIMUM_COURSE_FEE FROM COURSES;
SELECT SUM(BOOKS_QUANTITY) AS TOTAL_BOOKS FROM BOOKS;
SELECT AVG(PRICE) AS AVERGAE_BOOK_PRICE FROM BOOKS;
SELECT MAX(PRICE) AS MAXIMUM_BOOK_PRICE FROM BOOKS;
SELECT MIN(PRICE) AS MINIMUM_BOOK_PRICE FROM BOOKS;
SELECT COUNT(DISTINCT DEPARTMENT) AS TOTAL_DEPARTMENTS FROM STUDENTS;

/* D. ALIAS WITH CASE – 10 QUESTIONS

61. DISPLAY EMPLOYEE SALARY CATEGORY WITH THE ALIAS SALARY_CATEGORY.
62. DISPLAY STUDENT RESULT WITH THE ALIAS RESULT_STATUS.
63. DISPLAY PRODUCT STOCK STATUS WITH THE ALIAS STOCK_STATUS.
64. DISPLAY STUDENT AGE CATEGORY WITH THE ALIAS AGE_CATEGORY.
65. DISPLAY EMPLOYEE EXPERIENCE LEVEL WITH THE ALIAS EXPERIENCE_LEVEL.
66. DISPLAY PRODUCT PRICE CATEGORY WITH THE ALIAS PRICE_CATEGORY.
67. DISPLAY COURSE FEE CATEGORY WITH THE ALIAS FEE_CATEGORY.
68. DISPLAY MOVIE RATING CATEGORY WITH THE ALIAS RATING_CATEGORY.
69. DISPLAY CUSTOMER EMAIL STATUS WITH THE ALIAS EMAIL_STATUS.
70. DISPLAY EMPLOYEE PROMOTION ELIGIBILITY WITH THE ALIAS PROMOTION_STATUS. */

SELECT *, CASE 
    WHEN SALARY > 100000 THEN 'HIGH PAYING EMPLOYEE'
    WHEN SALARY > 50000 THEN 'MEDIUM PAYING EMPLOYEE'
    ELSE 'UNDER PAID'
END AS SALARY_CATEGORY
FROM EMPLOYEES;

SELECT *, CASE 
    WHEN MARKS>90 THEN 'GOOD'
    WHEN MARKS > 75 THEN 'OKAY'
    ELSE 'NEEDS IMPROVEMENT'
END AS RESULT_STATUS
FROM STUDENTS;

SELECT *, CASE
    WHEN SOTCK>50 THEN 'AVAILABLE'
    WHEN STOCK > 0 THEN 'NEEDS TO BE ORDERED'
    ELSE 'NO STOCK'
END AS STOCK_STATUS
FROM PRODUCTS;

SELECT *, CASE
    WHEN AGE>18 THEN 'GOOD'
    ELSE 'DRINK COMPLAN'
END AS AGE_CATEGORY
FROM STUDENTS;

SELECT *, CASE
    WHEN EXPERIENCE > 10 THEN 'SENIOR EXPERIENCED'
    WHEN EXPERIENCE >5 THEN 'TL'
    ELSE 'NEEDS EXPERIENCE'
END AS EXPERIENCE_LEVEL
FROM EMPLOYEES;

SELECT *, CASE
    WHEN PRICE>10000 THEN 'COSTLY'
    WHEN PRICE>5000 THEN 'BUDGET'
    ELSE 'CHEAP'
END AS PRICE_CATEGORY
FROM PRODUCTS;

SELECT *, CASE
    WHEN FEES>100000 THEN 'AI'
    WHEN FEES>50000 THEN 'DATASCIENCE'
    ELSE 'ENGINEERING'
END AS FEE_CATEGORY
FROM COURSES;


SELECT *, CASE
    WHEN RATING>4 THEN 'GOOD MOVIE'
    WHEN RATRING>3 THEN 'AVERAGE MOVIE'
    ELSE 'DONT GO'
END AS RATING_CATEGORY
FROM MOVIES;

SELECT *, CASE
    WHEN EMAIL IS NOT NULL THEN 'EMAIL IS AVAILABLE'
    ELSE 'EMAIL IS NOT AVAILABLE'
END AS EMAIL_STATUS
FROM STUDENTS;

SELECT *, CASE
    WHEN EXPERIENCE>3 THEN 'PROMOTION AVAILABLE'
    ELSE 'PROMOTION NOT AVAILABLE'
END AS PROMOTION_STATUS
FROM EMPLOYEES;

/* E. TABLE ALIASES – 10 QUESTIONS

71. GIVE THE EMPLOYEES TABLE THE ALIAS E AND DISPLAY EMPLOYEE NAME AND SALARY.
72. GIVE THE STUDENTS TABLE THE ALIAS S AND DISPLAY STUDENT NAME AND DEPARTMENT.
73. GIVE THE PRODUCTS TABLE THE ALIAS P AND DISPLAY PRODUCT NAME AND PRICE.
74. GIVE THE BOOKS TABLE THE ALIAS B AND DISPLAY BOOK NAME AND PRICE.
75. GIVE THE COURSES TABLE THE ALIAS C AND DISPLAY COURSE NAME AND FEES.
76. GIVE THE CUSTOMERS TABLE THE ALIAS CU AND DISPLAY CUSTOMER NAME AND CITY.
77. USE A TABLE ALIAS TO DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN 50000.
78. USE A TABLE ALIAS TO DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN 10000.
79. USE ALIASES FOR TWO INSTANCES OF THE EMPLOYEES TABLE AND COMPARE THEIR SALARIES.
80. USE TABLE ALIASES IN A QUERY INVOLVING EMPLOYEES AND DEPARTMENTS. */

SELECT E.EMPLOYEE_NAME, E.SALARY AS EMPLOYEE_NAME FROM EMPLOYEES AS E;
SELECT S.STUDENT_NAME AS STUDENT_NAME, S.DEPARTMENT AS DEPARTMENT FROM STUDENTS AS S;
SELECT P.NAME AS PRODUCT_NAME , P.PRICE AS PRICE FROM PRODUCTS AS P;
SELECT B.NAME AS BOOK_NAME, B.PRICE AS PRICE FROM BOOKS AS B;
SELECT C.COURSE_NAME AS COURSE_NAME, C.FEES AS FEES FROM COURSES AS C;
SELECT CU.CUSTOMERNAME AS CUSTOMER_NAME, CU.CITY AS CITY FROM CUSTOMERS AS CU;
SELECT E.SALARY AS EMPLOYEE_SALARY FROM EMPLOYEES AS E WHERE E.SALARY>50000;
SELECT P.PRICE AS PRICE FROM PRODUCTS AS P WHERE P.PRICE>10000;
SELECT E1.EMPLOYEENAME, E1.SALARY, E2.EMPLOYEENAME, E2.SALARY FROM EMPLOYEES E1
JOIN EMPLOYEES E2 ON E1.SALARY > E2.SALARY;
SELECT E.EMPLOYEE_ID, E.EMPLOYEENAME, D.DEPARTMENTID, D.DEPARTMENTNAME FROM EMPLOYEES AS E 
WHERE EXISTS  (SELECT * FROM DEPARTMENTS AS D);

/* F. ADVANCED ALIAS PRACTICE – 20 QUESTIONS

81. DISPLAY EMPLOYEE NAME, SALARY, AND ANNUAL SALARY USING MEANINGFUL ALIASES.
82. DISPLAY PRODUCT NAME, PRICE, QUANTITY, AND TOTAL STOCK VALUE USING ALIASES.
83. DISPLAY STUDENT NAME, MARKS, AND RESULT STATUS USING ALIASES.
84. DISPLAY COURSE NAME, FEES, AND DISCOUNTED FEES USING ALIASES.
85. DISPLAY EMPLOYEE NAME, SALARY, AND SALARY CATEGORY USING ALIASES.
86. DISPLAY PRODUCT NAME, PRICE, GST AMOUNT, AND FINAL PRICE USING ALIASES.
87. DISPLAY CUSTOMER NAME AND REGISTRATION YEAR USING AN ALIAS.
88. DISPLAY EMPLOYEE NAME AND JOINING DATE FORMATTED AS DD-MM-YYYY USING AN ALIAS.
89. DISPLAY STUDENT NAME AND NAME LENGTH USING AN ALIAS.
90. DISPLAY BOOK NAME AND DISCOUNTED PRICE USING AN ALIAS.
91. FIND THE AVERAGE SALARY OF EMPLOYEES AND GIVE THE RESULT THE ALIAS AVG_SALARY.
92. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN THE AVERAGE SALARY. USE AN APPROPRIATE ALIAS FOR THE CALCULATED AVERAGE IF REQUIRED.
93. DISPLAY THE HIGHEST SALARY WITH THE ALIAS MAX_SALARY.
94. DISPLAY THE LOWEST SALARY WITH THE ALIAS MIN_SALARY.
95. DISPLAY TOTAL PRODUCT INVENTORY VALUE WITH THE ALIAS TOTAL_INVENTORY_VALUE.
96. DISPLAY DEPARTMENT-WISE EMPLOYEE COUNT WITH ALIASES DEPARTMENT_NAME AND EMPLOYEE_COUNT.
97. DISPLAY DEPARTMENT-WISE AVERAGE SALARY WITH ALIASES DEPARTMENT_NAME AND AVERAGE_SALARY.
98. DISPLAY CATEGORY-WISE TOTAL PRODUCT VALUE WITH ALIASES CATEGORY_NAME AND TOTAL_VALUE.
99. DISPLAY CATEGORY-WISE MAXIMUM PRODUCT PRICE WITH ALIASES CATEGORY_NAME AND MAXIMUM_PRICE.
100. DISPLAY CATEGORY-WISE MINIMUM PRODUCT PRICE WITH ALIASES CATEGORY_NAME AND MINIMUM_PRICE. */

SELECT EMPLOYEENAME AS EMPLOYEE_NAME, SALARY AS EMPLOYEE_SALARY, SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEES;
SELECT PRODUCTNAME AS PRODUCT_NAME, PRICE AS PRICE, QUANTITY_STOCK AS STOCK, SUM(PRICE*QUANTITY_STOCK) AS TOTAL_STOCK_VALUE FROM PRODUCTS;

SELECT NAME AS STUDNET_NAME, MARKS AS MARKS, 
CASE 
    WHEN MARKS>90 THEN 'GOOD'
    WHEN MARKS > 75 THEN 'OKAY'
    ELSE 'NEEDS IMPROVEMENT'
END AS RESULT_STATUS
FROM STUDENTS;

SELECT COURSENAME AS COURSE_NAME, FEES AS FEES, FEES*0.9 AS DISCOUNTED_FEES FROM COURSES;

SELECT EMP_NAME AS EMPLOYEENAME, SALARY AS SALARY, 
CASE 
    WHEN SALARY > 100000 THEN 'HIGH PAYING EMPLOYEE'
    WHEN SALARY > 50000 THEN 'MEDIUM PAYING EMPLOYEE'
    ELSE 'UNDER PAID'
END AS SALARY_CATEGORY
FROM EMPLOYEES;

SELECT NAME PRODUCT_NAME, PRICE AS PRICE, PRICE*0.18 AS GST_AMOUNT,
PRICE+(PRICE*0.18) AS FINAL_PRICE FROM PRODUCTS;

SELECT NAME AS CUSTOMER_NAME, YEAR(REGDATE) AS REGISTRATION_DATE FROM CUSTOMERS;
SELECT EMPNAME AS EMPLOYEE_NAME, DATE_FORMAT(JOIN_DATE, 'dd-mm-yyyy') AS JOINING_DATE FROM EMPLOYEES;
SELECT STUDNETNAME AS STUDNET_NAME, LEN(STUDENT_NAME) AS NAME_LENGTH FROM STUDENTS;
SELECT BOOKNAME AS BOOK_NAME, PRICE*0.9 AS DISCOUNTED_PRICE FROM BOOKS;
SELECT AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES;
SELECT * FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES);
SELECT MAX(SALARY) AS MAX_SALARY FROM EMPLOYEES;
SELECT MIN(SALARY) AS MIN_SALARY FROM EMPLOYEES;
SELECT SUM(QUANTITY*STOCK_PRICE) AS TOTAL_INVENTORY_VALUE FROM PRODUCTS;
SELECT DEPARTMENT_NAME AS DEPARTMENT_NAME, COUNT(EMPLOYEE) AS EMPLOYEE_COUNT FROM EMPLOYEES GROUP BY DEPARTMENT_NAME;
SELECT DEPARTMENT_NAME AS DEPARTMENT_NAME, AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_NAME;
SELECT CATEGORY AS PRODUCT_CATEGORY, SUM(PRICE) AS TOTAL_REVENUE FROM PRODUCTS GROUP BY PRODUCT_CATEGORY;
SELECT CATEGORY AS PRODUCT_CATEGORY, MAX(PRICE) AS MAXIMUM_PRICE FROM PRODUCTS GROUP BY PRODUCT_CATEGORY;
SELECT CATEGORY AS PRODUCT_CATEGORY, MIN(PRICE) AS MINIMUM_PRICE FROM PRODUCTS GROUP BY PRODUCT_CATEGORY;

