#Date: 26th August 2026
#Date Covered: 25th August 2025
#Topics Covered:

/* EXISTS & NOT EXISTS

OBJECTIVE

PRACTICE USING EXISTS AND NOT EXISTS WITH SUBQUERIES.
• EXISTS → CHECKS WHETHER THE SUBQUERY RETURNS AT LEAST ONE ROW.
• NOT EXISTS → CHECKS WHETHER THE SUBQUERY RETURNS NO ROWS.

A. EXISTS - 20 QUESTIONS

1. DISPLAY ALL DEPARTMENTS FOR WHICH AT LEAST ONE EMPLOYEE EXISTS.
2. DISPLAY EMPLOYEES WHO BELONG TO A DEPARTMENT THAT EXISTS IN THE DEPARTMENTS TABLE.
3. DISPLAY STUDENTS WHOSE DEPARTMENT EXISTS IN THE DEPARTMENTS TABLE.
4. DISPLAY CUSTOMERS WHO HAVE AT LEAST ONE ORDER.
5. DISPLAY PRODUCTS THAT HAVE BEEN ORDERED AT LEAST ONCE.
6. DISPLAY EMPLOYEES WHO HAVE AT LEAST ONE RECORD IN THE EMPLOYEEPROJECTS TABLE.
7. DISPLAY STUDENTS WHO HAVE AT LEAST ONE COURSE ENROLLMENT.
8. DISPLAY CUSTOMERS WHO HAVE AT LEAST ONE PAYMENT RECORD.
9. DISPLAY PRODUCTS FOR WHICH AT LEAST ONE ORDER EXISTS.
10. DISPLAY DEPARTMENTS THAT HAVE AT LEAST ONE EMPLOYEE EARNING MORE THAN 50000.
11. DISPLAY EMPLOYEES WHOSE DEPARTMENT HAS AT LEAST ONE EMPLOYEE EARNING MORE THAN 70000.
12. DISPLAY STUDENTS WHOSE DEPARTMENT HAS AT LEAST ONE STUDENT OLDER THAN 21.
13. DISPLAY PRODUCTS WHOSE CATEGORY HAS AT LEAST ONE PRODUCT COSTING MORE THAN 50000.
14. DISPLAY BOOKS WHOSE CATEGORY HAS AT LEAST ONE BOOK PRICED ABOVE 1000.
15. DISPLAY CUSTOMERS WHO HAVE PLACED AN ORDER WITH AN ORDER AMOUNT GREATER THAN 10000.
16. DISPLAY EMPLOYEES WHO ARE ASSIGNED TO AT LEAST ONE PROJECT.
17. DISPLAY STUDENTS WHO HAVE AT LEAST ONE ASSIGNMENT SUBMITTED.
18. DISPLAY COURSES THAT HAVE AT LEAST ONE STUDENT ENROLLED.
19. DISPLAY PRODUCTS THAT HAVE AT LEAST ONE ORDER WITH QUANTITY GREATER THAN 10.
20. DISPLAY CUSTOMERS WHO HAVE AT LEAST ONE ORDER PLACED IN 2026. */

SELECT * FROM DEPARTMENTS D WHERE EXISTS (SELECT 1 FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID);
SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID);
SELECT * FROM STUDENTS S WHERE EXISTS (SELECT 1 FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = S.DEPARTMENT_ID);
SELECT * FROM CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID);
SELECT * FROM PRODUCTS P WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID);
SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID);
SELECT * FROM STUDENTS S WHERE EXISTS (SELECT 1 FROM ENROLLMENTS EN WHERE EN.STUDENT_ID = S.STUDENT_ID);
SELECT * FROM CUSTOMERS C WHERE EXISTS (SELECT 1 FROM PAYMENTS P WHERE P.CUSTOMER_ID = C.CUSTOMER_ID);
SELECT * FROM PRODUCTS P WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID);
SELECT * FROM DEPARTMENTS D WHERE EXISTS (SELECT 1 FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.SALARY > 50000);
SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.SALARY > 70000);
SELECT * FROM STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTS S2 WHERE S2.DEPARTMENT_ID = S.DEPARTMENT_ID AND S2.AGE > 21);
SELECT * FROM PRODUCTS P WHERE EXISTS (SELECT 1 FROM PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.PRICE > 50000);
SELECT * FROM BOOKS B WHERE EXISTS (SELECT 1 FROM BOOKS B2 WHERE B2.CATEGORY = B.CATEGORY AND B2.PRICE > 1000);
SELECT * FROM CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.ORDER_AMOUNT > 10000);
SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID);
SELECT * FROM STUDENTS S WHERE EXISTS (SELECT 1 FROM ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID);
SELECT * FROM COURSES C WHERE EXISTS (SELECT 1 FROM ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM PRODUCTS P WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND O.QUANTITY > 10);
SELECT * FROM CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND YEAR(O.ORDER_DATE) = 2026);

/* B. NOT EXISTS - 20 QUESTIONS

21. DISPLAY CUSTOMERS WHO HAVE NEVER PLACED AN ORDER.
22. DISPLAY PRODUCTS THAT HAVE NEVER BEEN ORDERED.
23. DISPLAY EMPLOYEES WHO ARE NOT ASSIGNED TO ANY PROJECT.
24. DISPLAY STUDENTS WHO HAVE NOT ENROLLED IN ANY COURSE.
25. DISPLAY COURSES IN WHICH NO STUDENTS ARE ENROLLED.
26. DISPLAY DEPARTMENTS THAT HAVE NO EMPLOYEES.
27. DISPLAY CUSTOMERS WHO HAVE NO PAYMENT RECORDS.
28. DISPLAY PRODUCTS THAT HAVE NO ORDER RECORDS.
29. DISPLAY EMPLOYEES WHO HAVE NO PROJECT ASSIGNMENTS.
30. DISPLAY STUDENTS WHO HAVE NO ASSIGNMENT SUBMISSIONS.
31. DISPLAY DEPARTMENTS WHERE NO EMPLOYEE EARNS MORE THAN 70000.
32. DISPLAY EMPLOYEES WHOSE DEPARTMENT HAS NO EMPLOYEE EARNING MORE THAN 70000.
33. DISPLAY PRODUCTS WHOSE CATEGORY HAS NO PRODUCT COSTING MORE THAN 50000.
34. DISPLAY BOOKS WHOSE CATEGORY HAS NO BOOK PRICED ABOVE 1000.
35. DISPLAY CUSTOMERS WHO HAVE NO ORDERS ABOVE 10000.
36. DISPLAY COURSES WITH NO STUDENT ENROLLMENT.
37. DISPLAY PRODUCTS THAT WERE NOT ORDERED DURING 2026.
38. DISPLAY CUSTOMERS WHO HAVE NOT PLACED ANY ORDER DURING 2026.
39. DISPLAY EMPLOYEES WHO HAVE NO PROJECT ASSIGNMENT WITH A STATUS OF 'ACTIVE'.
40. DISPLAY STUDENTS WHO HAVE NO ASSIGNMENT WITH A STATUS OF 'SUBMITTED'. */ 

SELECT * FROM CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID);
SELECT * FROM PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID);
SELECT * FROM EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID);
SELECT * FROM STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM ENROLLMENTS EN WHERE EN.STUDENT_ID = S.STUDENT_ID);
SELECT * FROM COURSES C WHERE NOT EXISTS (SELECT 1 FROM ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM DEPARTMENTS D WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID);
SELECT * FROM CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM PAYMENTS P WHERE P.CUSTOMER_ID = C.CUSTOMER_ID);
SELECT * FROM PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID);
SELECT * FROM EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID);
SELECT * FROM STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID);
SELECT * FROM DEPARTMENTS D WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.SALARY > 70000);
SELECT * FROM EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.SALARY > 70000);
SELECT * FROM PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.PRICE > 50000);
SELECT * FROM BOOKS B WHERE NOT EXISTS (SELECT 1 FROM BOOKS B2 WHERE B2.CATEGORY = B.CATEGORY AND B2.PRICE > 1000);
SELECT * FROM CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.ORDER_AMOUNT > 1000);
SELECT * FROM COURSES C WHERE NOT EXISTS (SELECT 1 FROM ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'ACTIVE');
SELECT * FROM STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID AND A.STATUS = 'SUBMITTED');

/* C. EXISTS WITH CONDITIONS - 20 QUESTIONS

41. DISPLAY EMPLOYEES FOR WHOM AN ACTIVE PROJECT EXISTS.
42. DISPLAY CUSTOMERS FOR WHOM AN ORDER AMOUNT GREATER THAN 5000 EXISTS.
43. DISPLAY PRODUCTS FOR WHICH AN ORDER QUANTITY GREATER THAN 5 EXISTS.
44. DISPLAY STUDENTS FOR WHOM AN ENROLLMENT IN THE 'DATA ENGINEERING' COURSE EXISTS.
45. DISPLAY EMPLOYEES WHOSE DEPARTMENT HAS AT LEAST ONE EMPLOYEE WITH SALARY GREATER THAN 60000.
46. DISPLAY STUDENTS WHOSE DEPARTMENT HAS AT LEAST ONE STUDENT WITH MARKS GREATER THAN 90.
47. DISPLAY PRODUCTS WHOSE CATEGORY HAS AT LEAST ONE PRODUCT WITH STOCK GREATER THAN 100.
48. DISPLAY BOOKS WHOSE CATEGORY HAS AT LEAST ONE BOOK PRICED BELOW 500.
49. DISPLAY CUSTOMERS WHO HAVE AT LEAST ONE ORDER WITH STATUS 'DELIVERED'.
50. DISPLAY EMPLOYEES WHO HAVE AT LEAST ONE PROJECT WITH STATUS 'COMPLETED'.
51. DISPLAY STUDENTS WHO HAVE AT LEAST ONE ASSIGNMENT WITH MARKS GREATER THAN 80.
52. DISPLAY COURSES FOR WHICH AT LEAST ONE STUDENT HAS ENROLLED.
53. DISPLAY PRODUCTS FOR WHICH AT LEAST ONE ORDER WAS PLACED IN AUGUST 2026.
54. DISPLAY CUSTOMERS WHO HAVE AT LEAST ONE ORDER PLACED IN CHENNAI.
55. DISPLAY EMPLOYEES WHO HAVE AT LEAST ONE PROJECT ASSIGNED TO THE 'DATA ENGINEERING' TEAM.
56. DISPLAY STUDENTS WHO HAVE AT LEAST ONE COURSE WITH FEES GREATER THAN 30000.
57. DISPLAY PRODUCTS WHOSE BRAND HAS AT LEAST ONE PRODUCT WITH STOCK BELOW 10.
58. DISPLAY EMPLOYEES WHOSE DEPARTMENT HAS AT LEAST ONE EMPLOYEE WITH DESIGNATION 'MANAGER'.
59. DISPLAY CUSTOMERS WHO HAVE AT LEAST ONE ORDER WITH QUANTITY GREATER THAN 10.
60. DISPLAY BOOKS WHOSE AUTHOR HAS WRITTEN AT LEAST ONE OTHER BOOK. */

SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'ACTIVE');
SELECT * FROM CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.ORDER_AMOUNT > 5000);
SELECT * FROM PRODUCTS P WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND O.QUANTITY > 5);
SELECT * FROM STUDENTS S WHERE EXISTS (SELECT 1 FROM ENROLLMENTS E JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID WHERE E.STUDENT_ID = S.STUDENT_ID AND C.COURSE_NAME = 'DATA ENGINEERING');
SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.SALARY > 60000);
SELECT * FROM STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTS S2 WHERE S2.DEPARTMENT_ID = S.DEPARTMENT_ID AND S2.MARKS > 90);
SELECT * FROM PRODUCTS P WHERE EXISTS (SELECT 1 FROM PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.STOCK > 100);
SELECT * FROM BOOKS B WHERE EXISTS (SELECT 1 FROM BOOKS B2 WHERE B2.CATEGORY = B.CATEGORY AND B2.PRICE < 500);
SELECT * FROM CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'DELIVERED');
SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'COMPLETED');
SELECT * FROM STUDENTS S WHERE EXISTS (SELECT 1 FROM ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID AND A.MARKS > 80);
SELECT * FROM COURSES C WHERE EXISTS (SELECT 1 FROM ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM PRODUCTS P WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND MONTH(O.ORDER_DATE) = 8 AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.CITY = 'CHENNAI');
SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP JOIN PROJECTS P ON EP.PROJECT_ID = P.PROJECT_ID WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND P.TEAM_NAME = 'DATA ENGINEERING');
SELECT * FROM STUDENTS S WHERE EXISTS (SELECT 1 FROM ENROLLMENTS E JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID WHERE E.STUDENT_ID = S.STUDENT_ID AND C.FEES > 30000);
SELECT * FROM PRODUCTS P WHERE EXISTS (SELECT 1 FROM PRODUCTS P2 WHERE P2.BRAND = P.BRAND AND P2.STOCK < 10);
SELECT * FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.DESIGNATION = 'MANAGER');
SELECT * FROM CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.QUANTITY > 10);
SELECT * FROM BOOKS B WHERE EXISTS (SELECT 1 FROM BOOKS B2 WHERE B2.AUTHOR = B.AUTHOR AND B2.BOOK_ID <> B.BOOK_ID);

/* D. NOT EXISTS WITH CONDITIONS - 20 QUESTIONS

61. DISPLAY CUSTOMERS WHO HAVE NO ORDERS WITH AN AMOUNT GREATER THAN 10000.
62. DISPLAY PRODUCTS THAT HAVE NO ORDERS WITH QUANTITY GREATER THAN 10.
63. DISPLAY EMPLOYEES WHO HAVE NO ACTIVE PROJECTS.
64. DISPLAY STUDENTS WHO HAVE NO ASSIGNMENTS WITH MARKS BELOW 40.
65. DISPLAY COURSES IN WHICH NO STUDENT HAS ENROLLED.
66. DISPLAY DEPARTMENTS WHERE NO EMPLOYEE EARNS MORE THAN 60000.
67. DISPLAY PRODUCTS WHOSE CATEGORY HAS NO PRODUCT WITH STOCK BELOW 5.
68. DISPLAY BOOKS WHOSE CATEGORY HAS NO BOOK PRICED ABOVE 2000.
69. DISPLAY CUSTOMERS WHO HAVE NO CANCELLED ORDERS.
70. DISPLAY EMPLOYEES WHO HAVE NO PROJECT WITH STATUS 'PENDING'.
71. DISPLAY STUDENTS WHO HAVE NO COURSE WITH FEES MORE THAN 50000.
72. DISPLAY PRODUCTS THAT WERE NEVER ORDERED IN 2026.
73. DISPLAY CUSTOMERS WHO DID NOT PLACE ANY ORDER IN AUGUST 2026.
74. DISPLAY EMPLOYEES WHO HAVE NO PROJECT BELONGING TO THE 'ANALYTICS' TEAM.
75. DISPLAY STUDENTS WHO HAVE NO ASSIGNMENT WITH MARKS GREATER THAN 90.
76. DISPLAY COURSES THAT HAVE NO STUDENTS FROM THE IT DEPARTMENT.
77. DISPLAY PRODUCTS WHOSE CATEGORY HAS NO PRODUCT PRICED ABOVE 100000.
78. DISPLAY EMPLOYEES WHOSE DEPARTMENT HAS NO EMPLOYEE WITH DESIGNATION 'MANAGER'.
79. DISPLAY CUSTOMERS WHO HAVE NO ORDERS WITH STATUS 'DELIVERED'.
80. DISPLAY STUDENTS WHO HAVE NO ENROLLMENT IN THE 'PYTHON' COURSE. */

SELECT * FROM CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.ORDER_AMOUNT > 10000);
SELECT * FROM PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND O.QUANTITY > 10);
SELECT * FROM EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'ACTIVE');
SELECT * FROM STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID AND A.MARKS < 40);
SELECT * FROM COURSES C WHERE NOT EXISTS (SELECT 1 FROM ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM DEPARTMENTS D WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.SALARY > 60000);
SELECT * FROM PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.STOCK < 5);
SELECT * FROM BOOKS B WHERE NOT EXISTS (SELECT 1 FROM BOOKS B2 WHERE B2.CATEGORY = B.CATEGORY AND B2.PRICE > 2000);
SELECT * FROM CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'CANCELLED');
SELECT * FROM EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'PENDING');
SELECT * FROM STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM ENROLLMENTS E JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID WHERE E.STUDENT_ID = S.STUDENT_ID AND C.FEES > 50000);
SELECT * FROM PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND MONTH(O.ORDER_DATE) = 8 AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP JOIN PROJECTS P ON EP.PROJECT_ID = P.PROJECT_ID WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND P.TEAM_NAME = 'ANALYTICS');
SELECT * FROM STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID AND A.MARKS > 90);
SELECT * FROM COURSES C WHERE NOT EXISTS (SELECT 1 FROM ENROLLMENTS E JOIN STUDENTS S ON E.STUDENT_ID = S.STUDENT_ID WHERE E.COURSE_ID = C.COURSE_ID AND S.DEPARTMENT = 'IT');
SELECT * FROM PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.PRICE > 100000);
SELECT * FROM EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.DESIGNATION = 'MANAGER');
SELECT * FROM CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'DELIVERED');
SELECT * FROM STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM ENROLLMENTS E JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID WHERE E.STUDENT_ID = S.STUDENT_ID AND C.COURSE_NAME = 'PYTHON');

/* E. CHALLENGE QUESTIONS

81. DISPLAY CUSTOMERS WHO HAVE PLACED AT LEAST ONE ORDER BUT HAVE NEVER PLACED A CANCELLED ORDER.
82. DISPLAY PRODUCTS THAT HAVE BEEN ORDERED BUT HAVE NEVER BEEN RETURNED.
83. DISPLAY EMPLOYEES WHO ARE ASSIGNED TO AT LEAST ONE PROJECT BUT HAVE NO COMPLETED PROJECT.
84. DISPLAY STUDENTS WHO HAVE ENROLLED IN AT LEAST ONE COURSE BUT HAVE NOT SUBMITTED ANY ASSIGNMENT.
85. DISPLAY DEPARTMENTS THAT HAVE AT LEAST ONE EMPLOYEE BUT NO EMPLOYEE EARNING BELOW 25000.
86. DISPLAY PRODUCTS THAT HAVE AT LEAST ONE ORDER BUT NO ORDER WITH QUANTITY GREATER THAN 20.
87. DISPLAY CUSTOMERS WHO HAVE AT LEAST ONE DELIVERED ORDER BUT NO CANCELLED ORDER.
88. DISPLAY EMPLOYEES WHOSE DEPARTMENT HAS AT LEAST ONE MANAGER BUT THE EMPLOYEE THEMSELVES IS NOT A MANAGER.
89. DISPLAY STUDENTS WHOSE DEPARTMENT HAS AT LEAST ONE STUDENT WITH MARKS ABOVE 90 BUT THE STUDENT THEMSELVES SCORED BELOW 90.
90. DISPLAY PRODUCTS WHOSE CATEGORY HAS AT LEAST ONE PREMIUM PRODUCT BUT THE PRODUCT ITSELF COSTS LESS THAN 50000. */

SELECT * 
FROM CUSTOMERS C
WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID)
AND NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'CANCELLED');

SELECT *
FROM PRODUCTS P
WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID)
AND NOT EXISTS (SELECT 1 FROM RETURNS R WHERE R.PRODUCT_ID = P.PRODUCT_ID);

SELECT *
FROM EMPLOYEES E
WHERE EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID)
AND NOT EXISTS (SELECT 1 FROM EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'COMPLETED');

SELECT *
FROM STUDENTS S
WHERE EXISTS (SELECT 1 FROM ENROLLMENTS E WHERE E.STUDENT_ID = S.STUDENT_ID)
AND NOT EXISTS (SELECT 1 FROM ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID);

SELECT *
FROM DEPARTMENTS D
WHERE EXISTS (SELECT 1 FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
AND NOT EXISTS (SELECT 1 FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.SALARY < 25000);

SELECT *
FROM PRODUCTS P
WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID)
AND NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND O.QUANTITY > 20);

SELECT *
FROM CUSTOMERS C
WHERE EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'DELIVERED')
AND NOT EXISTS (SELECT 1 FROM ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'CANCELLED');

SELECT *
FROM EMPLOYEES E
WHERE EXISTS (
    SELECT 1
    FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
    AND E2.DESIGNATION = 'MANAGER'
)
AND E.DESIGNATION <> 'MANAGER';

SELECT *
FROM STUDENTS S
WHERE EXISTS (
    SELECT 1
    FROM STUDENTS S2
    WHERE S2.DEPARTMENT_ID = S.DEPARTMENT_ID
    AND S2.MARKS > 90
)
AND S.MARKS < 90;

SELECT *
FROM PRODUCTS P
WHERE EXISTS (
    SELECT 1
    FROM PRODUCTS P2
    WHERE P2.CATEGORY = P.CATEGORY
    AND P2.PRODUCT_TYPE = 'PREMIUM'
)
AND P.PRICE < 50000;
