#Date: 26th August 2026
#Date Covered: 25th August 2026
#Topics Covered:

/*EXPRESSIONS
OBJECTIVE
PRACTICE USING SQL EXPRESSIONS WITH ARITHMETIC, COMPARISON, LOGICAL OPERATORS, FUNCTIONS, AND CALCULATED COLUMNS.

A. ARITHMETIC EXPRESSIONS – 20 QUESTIONS

USE OPERATORS: +, -, *, /, %

1. DISPLAY EACH EMPLOYEE'S SALARY AND CALCULATE A ₹5,000 BONUS.
2. DISPLAY EACH EMPLOYEE'S SALARY AFTER ADDING 10% INCREMENT.
3. DISPLAY EACH EMPLOYEE'S SALARY AFTER DEDUCTING ₹2,000.
4. DISPLAY EACH EMPLOYEE'S SALARY AND CALCULATE THE ANNUAL SALARY.
5. DISPLAY EACH EMPLOYEE'S SALARY AND CALCULATE THE MONTHLY SALARY AFTER A 5% DEDUCTION.
6. DISPLAY EACH PRODUCT'S PRICE AND CALCULATE THE PRICE AFTER ADDING 18% GST.
7. DISPLAY EACH PRODUCT'S PRICE AND CALCULATE THE PRICE AFTER APPLYING A 10% DISCOUNT.
8. DISPLAY EACH PRODUCT'S PRICE AND CALCULATE THE DISCOUNT AMOUNT FOR A 15% DISCOUNT.
9. DISPLAY EACH BOOK'S PRICE AND CALCULATE THE PRICE AFTER ADDING 10% TAX.
10. DISPLAY EACH BOOK'S PRICE AND CALCULATE THE PRICE AFTER A 20% DISCOUNT.
11. DISPLAY EACH COURSE'S FEES AND CALCULATE THE FEES AFTER ADDING 5% GST.
12. DISPLAY EACH COURSE'S FEES AND CALCULATE THE FEES AFTER A 10% DISCOUNT.
13. DISPLAY PRODUCT PRICE, QUANTITY, AND CALCULATE THE TOTAL PRODUCT VALUE.
14. DISPLAY BOOK PRICE, QUANTITY, AND CALCULATE THE TOTAL INVENTORY VALUE.
15. DISPLAY EMPLOYEE SALARY AND CALCULATE THE ANNUAL SALARY AFTER A 10% INCREMENT.
16. DISPLAY PRODUCT PRICE AND CALCULATE THE PRICE AFTER 20% DISCOUNT + 18% GST.
17. DISPLAY THE TOTAL SALARY OF EACH EMPLOYEE AFTER ADDING A ₹3,000 ALLOWANCE.
18. DISPLAY COURSE FEES AND CALCULATE THE FEES PAYABLE AFTER A 15% SCHOLARSHIP DISCOUNT.
19. DISPLAY PRODUCT PRICE AND STOCK QUANTITY AND CALCULATE THE TOTAL STOCK VALUE.
20. DISPLAY EMPLOYEE SALARY AND CALCULATE THE DIFFERENCE BETWEEN SALARY AND 50000. */

SELECT SALARY, SALARY + 5000 AS BONUS_SALARY FROM EMPLOYEES;
SELECT SALARY, SALARY * 1.10 AS INCREMENTED_SALARY FROM EMPLOYEES;
SELECT SALARY, SALARY - 2000 AS UPDATED_SALARY FROM EMPLOYEES;
SELECT SALARY, SALARY * 12 AS ANNUAL_SALARY FROM EMPLOYEES;
SELECT SALARY, SALARY * 0.95 AS MONTHLY_SALARY_AFTER_DEDUCTION FROM EMPLOYEES;
SELECT PRICE, PRICE * 1.18 AS PRICE_AFTER_GST FROM PRODUCTS;
SELECT PRICE, PRICE * 0.90 AS PRICE_AFTER_DISCOUNT FROM PRODUCTS;
SELECT PRICE, PRICE * 0.15 AS DISCOUNT_AMOUNT FROM PRODUCTS;
SELECT PRICE, PRICE * 1.10 AS PRICE_AFTER_TAX FROM BOOKS;
SELECT PRICE, PRICE * 0.80 AS PRICE_AFTER_DISCOUNT FROM BOOKS;
SELECT FEES, FEES * 1.05 AS FEES_AFTER_GST FROM COURSES;
SELECT FEES, FEES * 0.90 AS FEES_AFTER_DISCOUNT FROM COURSES;
SELECT PRICE, QUANTITY, PRICE * QUANTITY AS TOTAL_PRODUCT_VALUE FROM PRODUCTS;
SELECT PRICE, QUANTITY, PRICE * QUANTITY AS TOTAL_INVENTORY_VALUE FROM BOOKS;
SELECT SALARY, (SALARY * 12) * 1.10 AS ANNUAL_SALARY_AFTER_INCREMENT FROM EMPLOYEES;
SELECT PRICE, (PRICE * 0.80) * 1.18 AS FINAL_PRICE FROM PRODUCTS;
SELECT SALARY, SALARY + 3000 AS TOTAL_SALARY FROM EMPLOYEES;
SELECT FEES, FEES * 0.85 AS PAYABLE_FEES FROM COURSES;
SELECT PRICE, STOCK_QUANTITY, PRICE * STOCK_QUANTITY AS TOTAL_STOCK_VALUE FROM PRODUCTS;
SELECT SALARY, SALARY - 50000 AS DIFFERENCE FROM EMPLOYEES;

/* B. COMPARISON EXPRESSIONS – 15 QUESTIONS

21. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN 50000.
22. DISPLAY EMPLOYEES WHOSE SALARY IS LESS THAN 30000.
23. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN 20.
24. DISPLAY STUDENTS WHOSE AGE IS EQUAL TO 21.
25. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN 10000.
26. DISPLAY PRODUCTS WHOSE STOCK QUANTITY IS LESS THAN 10.
27. DISPLAY BOOKS WHOSE PRICE IS BETWEEN 500 AND 1500.
28. DISPLAY EMPLOYEES WHOSE SALARY IS NOT EQUAL TO 40000.
29. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN OR EQUAL TO 18.
30. DISPLAY PRODUCTS WHOSE PRICE IS LESS THAN OR EQUAL TO 50000.
31. DISPLAY COURSES WHOSE FEES ARE GREATER THAN 30000.
32. DISPLAY MOVIES WHOSE RATING IS GREATER THAN OR EQUAL TO 4.
33. DISPLAY PATIENTS WHOSE AGE IS LESS THAN 60.
34. DISPLAY CUSTOMERS WHOSE AGE IS NOT EQUAL TO 25.
35. DISPLAY EMPLOYEES WHOSE SALARY IS BETWEEN 40000 AND 70000. */

SELECT * FROM EMPLOYEES WHERE SALARY > 50000;
SELECT * FROM EMPLOYEES WHERE SALARY < 30000;
SELECT * FROM STUDENTS WHERE AGE > 20;
SELECT * FROM STUDENTS WHERE AGE = 21;
SELECT * FROM PRODUCTS WHERE PRICE > 10000;
SELECT * FROM PRODUCTS WHERE STOCK_QUANTITY < 10;
SELECT * FROM BOOKS WHERE PRICE BETWEEN 500 AND 1500;
SELECT * FROM EMPLOYEES WHERE SALARY <> 40000;
SELECT * FROM STUDENTS WHERE AGE >= 18;
SELECT * FROM PRODUCTS WHERE PRICE <= 50000;
SELECT * FROM COURSES WHERE FEES > 30000;
SELECT * FROM MOVIES WHERE RATING >= 4;
SELECT * FROM PATIENTS WHERE AGE < 60;
SELECT * FROM CUSTOMERS WHERE AGE <> 25;
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 40000 AND 70000;

/* C. LOGICAL EXPRESSIONS – 15 QUESTIONS

36. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN 40000 AND DEPARTMENT IS IT.
37. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN 20 AND DEPARTMENT IS CSE.
38. DISPLAY PRODUCTS WHOSE PRICE IS GREATER THAN 10000 AND STOCK IS GREATER THAN 10.
39. DISPLAY BOOKS WHOSE PRICE IS GREATER THAN 500 OR CATEGORY IS TECHNOLOGY.
40. DISPLAY EMPLOYEES WHO BELONG TO IT OR HR.
41. DISPLAY STUDENTS WHO ARE NOT FROM THE IT DEPARTMENT.
42. DISPLAY PRODUCTS WHOSE CATEGORY IS ELECTRONICS AND PRICE IS BETWEEN 10000 AND 50000.
43. DISPLAY CUSTOMERS WHO ARE FROM CHENNAI OR BANGALORE.
44. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN 50000 AND DESIGNATION IS DEVELOPER.
45. DISPLAY BOOKS WHOSE PRICE IS LESS THAN 500 OR GREATER THAN 1500.
46. DISPLAY PATIENTS WHOSE AGE IS GREATER THAN 30 AND BLOOD GROUP IS O+.
47. DISPLAY STUDENTS WHOSE DEPARTMENT IS IT OR WHOSE AGE IS GREATER THAN 22.
48. DISPLAY PRODUCTS WHOSE BRAND IS NOT NULL AND PRICE IS GREATER THAN 5000.
49. DISPLAY CUSTOMERS WHOSE EMAIL IS NOT NULL AND CITY IS CHENNAI.
50. DISPLAY EMPLOYEES WHOSE SALARY IS NOT BETWEEN 30000 AND 60000. */

SELECT * FROM EMPLOYEES WHERE SALARY > 40000 AND DEPARTMENT = 'IT';
SELECT * FROM STUDENTS WHERE AGE > 20 AND DEPARTMENT = 'CSE';
SELECT * FROM PRODUCTS WHERE PRICE > 10000 AND STOCK_QUANTITY > 10;
SELECT * FROM BOOKS WHERE PRICE > 500 OR CATEGORY = 'TECHNOLOGY';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN ('IT','HR');
SELECT * FROM STUDENTS WHERE DEPARTMENT <> 'IT';
SELECT * FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS' AND PRICE BETWEEN 10000 AND 50000;
SELECT * FROM CUSTOMERS WHERE CITY IN ('CHENNAI','BANGALORE');
SELECT * FROM EMPLOYEES WHERE SALARY > 50000 AND DESIGNATION = 'DEVELOPER';
SELECT * FROM BOOKS WHERE PRICE < 500 OR PRICE > 1500;
SELECT * FROM PATIENTS WHERE AGE > 30 AND BLOOD_GROUP = 'O+';
SELECT * FROM STUDENTS WHERE DEPARTMENT = 'IT' OR AGE > 22;
SELECT * FROM PRODUCTS WHERE BRAND IS NOT NULL AND PRICE > 5000;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND CITY = 'CHENNAI';
SELECT * FROM EMPLOYEES WHERE SALARY NOT BETWEEN 30000 AND 60000;

/* D. STRING EXPRESSIONS – 15 QUESTIONS

51. DISPLAY STUDENT NAMES IN UPPERCASE USING UPPER().
52. DISPLAY EMPLOYEE NAMES IN LOWERCASE USING LOWER().
53. DISPLAY THE LENGTH OF EACH STUDENT'S NAME USING LENGTH().
54. DISPLAY EMPLOYEE NAMES ALONG WITH THE FIRST 3 CHARACTERS USING LEFT().
55. DISPLAY STUDENT NAMES ALONG WITH THE LAST 2 CHARACTERS USING RIGHT().
56. DISPLAY PRODUCT NAMES IN UPPERCASE AND THEIR PRICES.
57. DISPLAY CUSTOMER NAMES ALONG WITH THEIR NAME LENGTH.
58. DISPLAY BOOK NAMES AFTER REMOVING LEADING AND TRAILING SPACES USING TRIM().
59. DISPLAY STUDENT FIRST NAME AND DEPARTMENT TOGETHER USING CONCAT().
60. DISPLAY EMPLOYEE NAME AND SALARY TOGETHER USING CONCAT().
61. DISPLAY PRODUCT NAME AND BRAND AS A SINGLE EXPRESSION.
62. DISPLAY CUSTOMER CITY AND STATE AS A SINGLE COMBINED VALUE.
63. DISPLAY COURSE NAME AND DEPARTMENT AS A SINGLE COMBINED COLUMN.
64. DISPLAY THE FIRST CHARACTER OF EACH STUDENT'S NAME.
65. DISPLAY THE LAST CHARACTER OF EACH EMPLOYEE'S NAME. */

SELECT UPPER(NAME) FROM STUDENTS;
SELECT LOWER(NAME) FROM EMPLOYEES;
SELECT NAME, LENGTH(NAME) AS NAME_LENGTH FROM STUDENTS;
SELECT NAME, LEFT(NAME,3) AS FIRST_3_CHARACTERS FROM EMPLOYEES;
SELECT NAME, RIGHT(NAME,2) AS LAST_2_CHARACTERS FROM STUDENTS;
SELECT UPPER(PRODUCT_NAME) AS PRODUCT_NAME, PRICE FROM PRODUCTS;
SELECT NAME, LENGTH(NAME) AS NAME_LENGTH FROM CUSTOMERS;
SELECT TRIM(BOOK_NAME) FROM BOOKS;
SELECT CONCAT(FIRST_NAME,' ',DEPARTMENT) AS STUDENT_DETAILS FROM STUDENTS;
SELECT CONCAT(NAME,' - ',SALARY) AS EMPLOYEE_DETAILS FROM EMPLOYEES;
SELECT CONCAT(PRODUCT_NAME,' - ',BRAND) AS PRODUCT_DETAILS FROM PRODUCTS;
SELECT CONCAT(CITY,' - ',STATE) AS LOCATION FROM CUSTOMERS;
SELECT CONCAT(COURSE_NAME,' - ',DEPARTMENT) AS COURSE_DETAILS FROM COURSES;
SELECT LEFT(NAME,1) AS FIRST_CHARACTER FROM STUDENTS;
SELECT RIGHT(NAME,1) AS LAST_CHARACTER FROM EMPLOYEES;

/* E. DATE & TIME EXPRESSIONS – 15 QUESTIONS

66. DISPLAY THE CURRENT DATE USING CURRENT_DATE().
67. DISPLAY THE CURRENT TIME USING CURRENT_TIME().
68. DISPLAY THE CURRENT DATE AND TIME USING CURRENT_TIMESTAMP().
69. DISPLAY THE CURRENT DATE AND TIME USING NOW().
70. DISPLAY EMPLOYEE JOINING DATE AND CALCULATE THE DATE 30 DAYS AFTER JOINING.
71. DISPLAY EMPLOYEE JOINING DATE AND CALCULATE THE DATE 90 DAYS BEFORE JOINING.
72. DISPLAY PATIENT ADMISSION DATE AND CALCULATE THE DATE 7 DAYS AFTER ADMISSION.
73. DISPLAY CUSTOMER REGISTRATION DATE AND CALCULATE THE DATE 42 DAYS BEFORE REGISTRATION.
74. DISPLAY PRODUCT MANUFACTURING DATE AND CALCULATE THE DATE 126 DAYS AFTER MANUFACTURING.
75. DISPLAY EMPLOYEE JOINING DATE IN DD-MM-YYYY FORMAT.
76. DISPLAY CUSTOMER REGISTRATION DATE IN MM/DD/YYYY FORMAT.
77. DISPLAY PRODUCT MANUFACTURING DATE IN DD-MONTH-YYYY STYLE USING DATE_FORMAT().
78. DISPLAY THE YEAR FROM THE EMPLOYEE JOINING DATE.
79. DISPLAY THE MONTH FROM THE CUSTOMER REGISTRATION DATE.
80. DISPLAY THE DAY FROM THE PRODUCT MANUFACTURING DATE. */ 

SELECT CURRENT_DATE();
SELECT CURRENT_TIME();
SELECT CURRENT_TIMESTAMP();
SELECT NOW();
SELECT JOINING_DATE, DATE_ADD(JOINING_DATE, INTERVAL 30 DAY) AS DATE_AFTER_30_DAYS FROM EMPLOYEES;
SELECT JOINING_DATE, DATE_SUB(JOINING_DATE, INTERVAL 90 DAY) AS DATE_BEFORE_90_DAYS FROM EMPLOYEES;
SELECT ADMISSION_DATE, DATE_ADD(ADMISSION_DATE, INTERVAL 7 DAY) AS DATE_AFTER_7_DAYS FROM PATIENTS;
SELECT REGISTRATION_DATE, DATE_SUB(REGISTRATION_DATE, INTERVAL 42 DAY) AS DATE_BEFORE_42_DAYS FROM CUSTOMERS;
SELECT MANUFACTURING_DATE, DATE_ADD(MANUFACTURING_DATE, INTERVAL 126 DAY) AS DATE_AFTER_126_DAYS FROM PRODUCTS;
SELECT DATE_FORMAT(JOINING_DATE,'%d-%m-%Y') AS FORMATTED_DATE FROM EMPLOYEES;
SELECT DATE_FORMAT(REGISTRATION_DATE,'%m/%d/%Y') AS FORMATTED_DATE FROM CUSTOMERS;
SELECT DATE_FORMAT(MANUFACTURING_DATE,'%d-%M-%Y') AS FORMATTED_DATE FROM PRODUCTS;
SELECT YEAR(JOINING_DATE) AS JOINING_YEAR FROM EMPLOYEES;
SELECT MONTH(REGISTRATION_DATE) AS REGISTRATION_MONTH FROM CUSTOMERS;
SELECT DAY(MANUFACTURING_DATE) AS MANUFACTURING_DAY FROM PRODUCTS;

/* F. AGGREGATE EXPRESSIONS – 10 QUESTIONS

81. FIND THE TOTAL SALARY OF ALL EMPLOYEES USING SUM().
82. FIND THE AVERAGE SALARY OF ALL EMPLOYEES USING AVG().
83. FIND THE HIGHEST EMPLOYEE SALARY USING MAX().
84. FIND THE LOWEST EMPLOYEE SALARY USING MIN().
85. COUNT THE TOTAL NUMBER OF EMPLOYEES USING COUNT().
86. FIND THE TOTAL VALUE OF ALL PRODUCTS USING SUM(PRICE * QUANTITY).
87. FIND THE AVERAGE PRICE OF PRODUCTS.
88. FIND THE HIGHEST PRICE AMONG BOOKS.
89. FIND THE LOWEST COURSE FEE.
90. COUNT THE NUMBER OF PRODUCTS WHOSE PRICE IS GREATER THAN 10000. */

SELECT SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES;
SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES;
SELECT MAX(SALARY) AS HIGHEST_SALARY FROM EMPLOYEES;
SELECT MIN(SALARY) AS LOWEST_SALARY FROM EMPLOYEES;
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES;
SELECT SUM(PRICE * QUANTITY) AS TOTAL_PRODUCT_VALUE FROM PRODUCTS;
SELECT AVG(PRICE) AS AVERAGE_PRICE FROM PRODUCTS;
SELECT MAX(PRICE) AS HIGHEST_BOOK_PRICE FROM BOOKS;
SELECT MIN(FEES) AS LOWEST_COURSE_FEE FROM COURSES;
SELECT COUNT(*) AS PRODUCT_COUNT FROM PRODUCTS WHERE PRICE > 10000;

/* G. EXPRESSION WITH ALIAS – 10 QUESTIONS

91. DISPLAY EMPLOYEE SALARY WITH THE ALIAS MONTHLY_SALARY.
92. DISPLAY ANNUAL SALARY WITH THE ALIAS ANNUAL_SALARY.
93. DISPLAY PRODUCT PRICE AFTER DISCOUNT WITH THE ALIAS DISCOUNTED_PRICE.
94. DISPLAY PRODUCT PRICE INCLUDING GST WITH THE ALIAS FINAL_PRICE.
95. DISPLAY TOTAL STOCK VALUE WITH THE ALIAS STOCK_VALUE.
96. DISPLAY BOOK PRICE AFTER A 10% DISCOUNT WITH THE ALIAS DISCOUNTED_PRICE.
97. DISPLAY COURSE FEES AFTER A 15% DISCOUNT WITH THE ALIAS FINAL_FEES.
98. DISPLAY STUDENT NAME LENGTH WITH THE ALIAS NAME_LENGTH.
99. DISPLAY EMPLOYEE SALARY AFTER A 10% INCREMENT WITH THE ALIAS INCREMENTED_SALARY.
100. DISPLAY PRODUCT PRICE MULTIPLIED BY STOCK QUANTITY WITH THE ALIAS TOTAL_VALUE. */

SELECT SALARY AS MONTHLY_SALARY FROM EMPLOYEES;
SELECT SALARY * 12 AS ANNUAL_SALARY FROM EMPLOYEES;
SELECT PRICE * 0.90 AS DISCOUNTED_PRICE FROM PRODUCTS;
SELECT PRICE * 1.18 AS FINAL_PRICE FROM PRODUCTS;
SELECT PRICE * STOCK_QUANTITY AS STOCK_VALUE FROM PRODUCTS;
SELECT PRICE * 0.90 AS DISCOUNTED_PRICE FROM BOOKS;
SELECT FEES * 0.85 AS FINAL_FEES FROM COURSES;
SELECT LENGTH(NAME) AS NAME_LENGTH FROM STUDENTS;
SELECT SALARY * 1.10 AS INCREMENTED_SALARY FROM EMPLOYEES;
SELECT PRICE * STOCK_QUANTITY AS TOTAL_VALUE FROM PRODUCTS;
