#Date: 28th August 2026
#Topics Covered:

/* SQL SET OPERATORS
TOPICS COVERED

● UNION
● UNION ALL
● INTERSECT
● EXCEPT
● IN
● NOT IN

NOTE: INTERSECT AND EXCEPT ARE SET OPERATORS. IN AND NOT IN ARE MEMBERSHIP/SUBQUERY OPERATORS, BUT THEY CAN BE USED TO ACHIEVE SIMILAR FILTERING LOGIC IN MANY PRACTICAL QUERIES.

A. UNION – 20 QUESTIONS

UNION COMBINES THE RESULTS OF TWO QUERIES AND REMOVES DUPLICATE ROWS.

1. DISPLAY ALL STUDENT NAMES FROM STUDENTS AND EMPLOYEE NAMES FROM EMPLOYEES IN A SINGLE RESULT.
2. DISPLAY ALL CITIES FROM CUSTOMERS AND EMPLOYEES.
3. DISPLAY ALL EMAIL ADDRESSES FROM STUDENTS AND EMPLOYEES.
4. DISPLAY ALL PHONE NUMBERS FROM STUDENTS AND CUSTOMERS.
5. DISPLAY ALL DEPARTMENT NAMES FROM STUDENTS AND EMPLOYEES.
6. DISPLAY ALL NAMES FROM STUDENTS AND CUSTOMERS.
7. DISPLAY ALL PRODUCT CATEGORIES FROM TWO DIFFERENT PRODUCT TABLES.
8. DISPLAY ALL COURSE NAMES FROM CURRENTCOURSES AND COMPLETEDCOURSES.
9. DISPLAY ALL CUSTOMER CITIES AND SUPPLIER CITIES WITHOUT DUPLICATES.
10. DISPLAY ALL EMPLOYEE AND MANAGER NAMES WITHOUT DUPLICATES.
11. DISPLAY ALL STUDENT IDS FROM STUDENTS AND ALUMNI.
12. DISPLAY ALL PRODUCT IDS FROM PRODUCTS AND DISCONTINUEDPRODUCTS.
13. DISPLAY ALL EMAIL IDS FROM CUSTOMERS AND SUPPLIERS.
14. DISPLAY ALL CITIES FROM CUSTOMERS AND SUPPLIERS WITHOUT DUPLICATES.
15. DISPLAY ALL DEPARTMENT IDS FROM EMPLOYEES AND MANAGERS.
16. DISPLAY ALL COURSE IDS FROM CURRENTSTUDENTS AND PREVIOUSSTUDENTS.
17. DISPLAY ALL NAMES OF PEOPLE FROM STUDENTS AND TEACHERS.
18. DISPLAY ALL UNIQUE PHONE NUMBERS FROM EMPLOYEES AND CUSTOMERS.
19. DISPLAY ALL UNIQUE LOCATIONS FROM TWO TABLES.
20. DISPLAY ALL UNIQUE IDS PRESENT IN TWO EMPLOYEE-RELATED TABLES. */

SELECT STUDENT_NAME FROM STUDENTS
UNION
SELECT EMPLOYEE_NAME FROM EMPLOYEES;

SELECT CITY FROM CUSTOMERS
UNION
SELECT CITY FROM EMPLOYEES;

SELECT EMAIL FROM STUDENTS
UNION
SELECT EMAIL FROM EMPLOYEES;

SELECT PHONE_NUMBER FROM STUDENTS
UNION
SELECT PHONE_NUMBER FROM CUSTOMERS;

SELECT DEPARTMENT_NAME FROM STUDENTS
UNION
SELECT DEPARTMENT_NAME FROM EMPLOYEES;

SELECT NAME FROM STUDENTS
UNION
SELECT NAME FROM CUSTOMERS;

SELECT CATEGORY FROM PRODUCTS1
UNION
SELECT CATEGORY FROM PRODUCTS2;

SELECT COURSE_NAME FROM CURRENTCOURSES
UNION
SELECT COURSE_NAME FROM COMPLETEDCOURSES;

SELECT CITY FROM CUSTOMERS
UNION
SELECT CITY FROM SUPPLIERS;

SELECT EMPLOYEE_NAME FROM EMPLOYEES
UNION
SELECT MANAGER_NAME FROM MANAGERS;

SELECT STUDENT_ID FROM STUDENTS
UNION
SELECT STUDENT_ID FROM ALUMNI;

SELECT PRODUCT_ID FROM PRODUCTS
UNION
SELECT PRODUCT_ID FROM DISCONTINUEDPRODUCTS;

SELECT EMAIL_ID FROM CUSTOMERS
UNION
SELECT EMAIL_ID FROM SUPPLIERS;

SELECT CITY FROM CUSTOMERS
UNION
SELECT CITY FROM SUPPLIERS;

SELECT DEPARTMENT_ID FROM EMPLOYEES
UNION
SELECT DEPARTMENT_ID FROM MANAGERS;

SELECT COURSE_ID FROM CURRENTSTUDENTS
UNION
SELECT COURSE_ID FROM PREVIOUSSTUDENTS;

SELECT NAME FROM STUDENTS
UNION
SELECT NAME FROM TEACHERS;

SELECT PHONE_NUMBER FROM EMPLOYEES
UNION
SELECT PHONE_NUMBER FROM CUSTOMERS;

SELECT LOCATION FROM TABLE1
UNION
SELECT LOCATION FROM TABLE2;

SELECT ID FROM EMPLOYEE_TABLE1
UNION
SELECT ID FROM EMPLOYEE_TABLE2;

/* B. UNION ALL – 20 QUESTIONS

UNION ALL COMBINES RESULTS AND KEEPS DUPLICATES.

21. DISPLAY ALL STUDENT NAMES AND EMPLOYEE NAMES USING UNION ALL.
22. DISPLAY ALL CUSTOMER CITIES AND EMPLOYEE CITIES USING UNION ALL.
23. DISPLAY ALL EMAIL ADDRESSES FROM STUDENTS AND CUSTOMERS.
24. DISPLAY ALL PHONE NUMBERS FROM EMPLOYEES AND CUSTOMERS.
25. DISPLAY ALL DEPARTMENT NAMES FROM EMPLOYEES AND STUDENTS.
26. DISPLAY ALL PRODUCT CATEGORIES FROM TWO PRODUCT TABLES.
27. DISPLAY ALL COURSE NAMES FROM CURRENTCOURSES AND COMPLETEDCOURSES.
28. DISPLAY ALL CUSTOMER NAMES FROM TWO CUSTOMER TABLES.
29. DISPLAY ALL EMPLOYEE IDS FROM TWO EMPLOYEE TABLES.
30. DISPLAY ALL PRODUCT IDS FROM PRODUCTS AND OLDPRODUCTS.
31. DISPLAY ALL CITIES FROM CUSTOMERS AND SUPPLIERS.
32. DISPLAY ALL COURSE IDS FROM TWO ENROLLMENT TABLES.
33. DISPLAY ALL EMAIL IDS FROM TWO EMPLOYEE TABLES.
34. DISPLAY ALL STUDENT IDS FROM STUDENTS AND ALUMNI.
35. DISPLAY ALL DEPARTMENT IDS FROM TWO EMPLOYEE-RELATED TABLES.
36. DISPLAY ALL PRODUCT NAMES FROM TWO PRODUCT TABLES.
37. DISPLAY ALL CUSTOMER PHONE NUMBERS FROM TWO CUSTOMER TABLES.
38. DISPLAY ALL EMPLOYEE NAMES FROM TWO EMPLOYEE TABLES.
39. DISPLAY ALL LOCATIONS FROM CUSTOMERS AND SUPPLIERS.
40. DISPLAY ALL IDS FROM TWO RELATED TABLES WHILE RETAINING DUPLICATE IDS. */

SELECT STUDENT_NAME FROM STUDENTS
UNION ALL
SELECT EMPLOYEE_NAME FROM EMPLOYEES;

SELECT CITY FROM CUSTOMERS
UNION ALL
SELECT CITY FROM EMPLOYEES;

SELECT EMAIL FROM STUDENTS
UNION ALL
SELECT EMAIL FROM CUSTOMERS;

SELECT PHONE_NUMBER FROM EMPLOYEES
UNION ALL
SELECT PHONE_NUMBER FROM CUSTOMERS;

SELECT DEPARTMENT_NAME FROM EMPLOYEES
UNION ALL
SELECT DEPARTMENT_NAME FROM STUDENTS;

SELECT CATEGORY FROM PRODUCTS1
UNION ALL
SELECT CATEGORY FROM PRODUCTS2;

SELECT COURSE_NAME FROM CURRENTCOURSES
UNION ALL
SELECT COURSE_NAME FROM COMPLETEDCOURSES;

SELECT CUSTOMER_NAME FROM CUSTOMERS1
UNION ALL
SELECT CUSTOMER_NAME FROM CUSTOMERS2;

SELECT EMPLOYEE_ID FROM EMPLOYEES1
UNION ALL
SELECT EMPLOYEE_ID FROM EMPLOYEES2;

SELECT PRODUCT_ID FROM PRODUCTS
UNION ALL
SELECT PRODUCT_ID FROM OLDPRODUCTS;

SELECT CITY FROM CUSTOMERS
UNION ALL
SELECT CITY FROM SUPPLIERS;

SELECT COURSE_ID FROM ENROLLMENTS1
UNION ALL
SELECT COURSE_ID FROM ENROLLMENTS2;

SELECT EMAIL_ID FROM EMPLOYEES1
UNION ALL
SELECT EMAIL_ID FROM EMPLOYEES2;

SELECT STUDENT_ID FROM STUDENTS
UNION ALL
SELECT STUDENT_ID FROM ALUMNI;

SELECT DEPARTMENT_ID FROM EMPLOYEES1
UNION ALL
SELECT DEPARTMENT_ID FROM EMPLOYEES2;

SELECT PRODUCT_NAME FROM PRODUCTS1
UNION ALL
SELECT PRODUCT_NAME FROM PRODUCTS2;

SELECT PHONE_NUMBER FROM CUSTOMERS1
UNION ALL
SELECT PHONE_NUMBER FROM CUSTOMERS2;

SELECT EMPLOYEE_NAME FROM EMPLOYEES1
UNION ALL
SELECT EMPLOYEE_NAME FROM EMPLOYEES2;

SELECT LOCATION FROM CUSTOMERS
UNION ALL
SELECT LOCATION FROM SUPPLIERS;

SELECT ID FROM TABLE1
UNION ALL
SELECT ID FROM TABLE2;

/* C. INTERSECT – 20 QUESTIONS

INTERSECT RETURNS ONLY THE ROWS THAT ARE COMMON TO BOTH QUERIES.

41. FIND CITIES THAT EXIST IN BOTH CUSTOMERS AND SUPPLIERS.
42. FIND EMAIL ADDRESSES THAT EXIST IN BOTH STUDENTS AND EMPLOYEES.
43. FIND PHONE NUMBERS THAT EXIST IN BOTH CUSTOMERS AND EMPLOYEES.
44. FIND DEPARTMENT NAMES THAT EXIST IN BOTH STUDENTS AND EMPLOYEES.
45. FIND STUDENT IDS THAT ARE PRESENT IN BOTH STUDENTS AND ALUMNI.
46. FIND PRODUCT IDS PRESENT IN BOTH PRODUCTS AND OLDPRODUCTS.
47. FIND COURSE IDS PRESENT IN BOTH CURRENTSTUDENTS AND PREVIOUSSTUDENTS.
48. FIND CUSTOMER CITIES THAT ARE ALSO SUPPLIER CITIES.
49. FIND EMPLOYEE NAMES THAT ALSO APPEAR IN THE MANAGERS TABLE.
50. FIND PRODUCT CATEGORIES COMMON TO TWO PRODUCT TABLES.
51. FIND EMAIL IDS COMMON TO CUSTOMERS AND SUPPLIERS.
52. FIND PHONE NUMBERS COMMON TO STUDENTS AND CUSTOMERS.
53. FIND DEPARTMENT IDS COMMON TO EMPLOYEES AND MANAGERS.
54. FIND COURSE NAMES COMMON TO TWO COURSE TABLES.
55. FIND CUSTOMER IDS PRESENT IN BOTH CURRENTCUSTOMERS AND PREVIOUSCUSTOMERS.
56. FIND PRODUCT NAMES PRESENT IN BOTH PRODUCTS AND DISCONTINUEDPRODUCTS.
57. FIND LOCATIONS COMMON TO TWO TABLES.
58. FIND EMPLOYEE IDS PRESENT IN BOTH EMPLOYEE-RELATED TABLES.
59. FIND STUDENTS WHO ARE ALSO PRESENT IN AN ALUMNI TABLE.
60. FIND ALL VALUES THAT OCCUR IN BOTH OF TWO SPECIFIED COLUMNS/TABLES. */

SELECT CITY FROM CUSTOMERS
INTERSECT
SELECT CITY FROM SUPPLIERS;

SELECT EMAIL FROM STUDENTS
INTERSECT
SELECT EMAIL FROM EMPLOYEES;

SELECT PHONE_NUMBER FROM CUSTOMERS
INTERSECT
SELECT PHONE_NUMBER FROM EMPLOYEES;

SELECT DEPARTMENT_NAME FROM STUDENTS
INTERSECT
SELECT DEPARTMENT_NAME FROM EMPLOYEES;

SELECT STUDENT_ID FROM STUDENTS
INTERSECT
SELECT STUDENT_ID FROM ALUMNI;

SELECT PRODUCT_ID FROM PRODUCTS
INTERSECT
SELECT PRODUCT_ID FROM OLDPRODUCTS;

SELECT COURSE_ID FROM CURRENTSTUDENTS
INTERSECT
SELECT COURSE_ID FROM PREVIOUSSTUDENTS;

SELECT CITY FROM CUSTOMERS
INTERSECT
SELECT CITY FROM SUPPLIERS;

SELECT EMPLOYEE_NAME FROM EMPLOYEES
INTERSECT
SELECT MANAGER_NAME FROM MANAGERS;

SELECT CATEGORY FROM PRODUCTS1
INTERSECT
SELECT CATEGORY FROM PRODUCTS2;

SELECT EMAIL_ID FROM CUSTOMERS
INTERSECT
SELECT EMAIL_ID FROM SUPPLIERS;

SELECT PHONE_NUMBER FROM STUDENTS
INTERSECT
SELECT PHONE_NUMBER FROM CUSTOMERS;

SELECT DEPARTMENT_ID FROM EMPLOYEES
INTERSECT
SELECT DEPARTMENT_ID FROM MANAGERS;

SELECT COURSE_NAME FROM COURSES1
INTERSECT
SELECT COURSE_NAME FROM COURSES2;

SELECT CUSTOMER_ID FROM CURRENTCUSTOMERS
INTERSECT
SELECT CUSTOMER_ID FROM PREVIOUSCUSTOMERS;

SELECT PRODUCT_NAME FROM PRODUCTS
INTERSECT
SELECT PRODUCT_NAME FROM DISCONTINUEDPRODUCTS;

SELECT LOCATION FROM TABLE1
INTERSECT
SELECT LOCATION FROM TABLE2;

SELECT EMPLOYEE_ID FROM EMPLOYEE_TABLE1
INTERSECT
SELECT EMPLOYEE_ID FROM EMPLOYEE_TABLE2;

SELECT STUDENT_NAME FROM STUDENTS
INTERSECT
SELECT STUDENT_NAME FROM ALUMNI;

SELECT COLUMN_NAME FROM TABLE1
INTERSECT
SELECT COLUMN_NAME FROM TABLE2;

/* D. EXCEPT – 20 QUESTIONS

EXCEPT RETURNS ROWS FROM THE FIRST QUERY THAT ARE NOT PRESENT IN THE SECOND QUERY.

61. FIND CITIES THAT HAVE CUSTOMERS BUT NO SUPPLIERS.
62. FIND EMAIL ADDRESSES PRESENT IN STUDENTS BUT NOT IN EMPLOYEES.
63. FIND PHONE NUMBERS PRESENT IN CUSTOMERS BUT NOT IN EMPLOYEES.
64. FIND DEPARTMENTS PRESENT IN STUDENTS BUT NOT IN EMPLOYEES.
65. FIND STUDENT IDS THAT ARE PRESENT IN STUDENTS BUT NOT IN ALUMNI.
66. FIND PRODUCT IDS PRESENT IN PRODUCTS BUT NOT IN OLDPRODUCTS.
67. FIND COURSE IDS PRESENT IN CURRENTSTUDENTS BUT NOT IN PREVIOUSSTUDENTS.
68. FIND CUSTOMER CITIES THAT ARE NOT SUPPLIER CITIES.
69. FIND EMPLOYEE NAMES THAT ARE NOT PRESENT IN THE MANAGERS TABLE.
70. FIND PRODUCT CATEGORIES PRESENT IN THE FIRST PRODUCT TABLE BUT NOT THE SECOND.
71. FIND EMAIL IDS PRESENT IN CUSTOMERS BUT NOT IN SUPPLIERS.
72. FIND PHONE NUMBERS PRESENT IN STUDENTS BUT NOT IN CUSTOMERS.
73. FIND DEPARTMENT IDS PRESENT IN EMPLOYEES BUT NOT IN MANAGERS.
74. FIND COURSE NAMES PRESENT IN CURRENTCOURSES BUT NOT IN COMPLETEDCOURSES.
75. FIND CUSTOMER IDS PRESENT IN CURRENTCUSTOMERS BUT NOT IN PREVIOUSCUSTOMERS.
76. FIND PRODUCT NAMES PRESENT IN PRODUCTS BUT NOT IN DISCONTINUEDPRODUCTS.
77. FIND LOCATIONS PRESENT IN THE FIRST TABLE BUT NOT IN THE SECOND.
78. FIND EMPLOYEE IDS PRESENT IN ONE EMPLOYEE TABLE BUT NOT ANOTHER.
79. FIND STUDENTS WHO ARE PRESENT IN STUDENTS BUT NOT IN ALUMNI.
80. FIND ALL VALUES PRESENT IN THE FIRST RESULT BUT ABSENT FROM THE SECOND RESULT. */

 
SELECT CITY FROM CUSTOMERS
EXCEPT
SELECT CITY FROM SUPPLIERS;

SELECT EMAIL FROM STUDENTS
EXCEPT
SELECT EMAIL FROM EMPLOYEES;

SELECT PHONE_NUMBER FROM CUSTOMERS
EXCEPT
SELECT PHONE_NUMBER FROM EMPLOYEES;

SELECT DEPARTMENT_NAME FROM STUDENTS
EXCEPT
SELECT DEPARTMENT_NAME FROM EMPLOYEES;

SELECT STUDENT_ID FROM STUDENTS
EXCEPT
SELECT STUDENT_ID FROM ALUMNI;

SELECT PRODUCT_ID FROM PRODUCTS
EXCEPT
SELECT PRODUCT_ID FROM OLDPRODUCTS;

SELECT COURSE_ID FROM CURRENTSTUDENTS
EXCEPT
SELECT COURSE_ID FROM PREVIOUSSTUDENTS;

SELECT CITY FROM CUSTOMERS
EXCEPT
SELECT CITY FROM SUPPLIERS;

SELECT EMPLOYEE_NAME FROM EMPLOYEES
EXCEPT
SELECT MANAGER_NAME FROM MANAGERS;

SELECT CATEGORY FROM PRODUCTS1
EXCEPT
SELECT CATEGORY FROM PRODUCTS2;

SELECT EMAIL_ID FROM CUSTOMERS
EXCEPT
SELECT EMAIL_ID FROM SUPPLIERS;

SELECT PHONE_NUMBER FROM STUDENTS
EXCEPT
SELECT PHONE_NUMBER FROM CUSTOMERS;

SELECT DEPARTMENT_ID FROM EMPLOYEES
EXCEPT
SELECT DEPARTMENT_ID FROM MANAGERS;

SELECT COURSE_NAME FROM CURRENTCOURSES
EXCEPT
SELECT COURSE_NAME FROM COMPLETEDCOURSES;

SELECT CUSTOMER_ID FROM CURRENTCUSTOMERS
EXCEPT
SELECT CUSTOMER_ID FROM PREVIOUSCUSTOMERS;

SELECT PRODUCT_NAME FROM PRODUCTS
EXCEPT
SELECT PRODUCT_NAME FROM DISCONTINUEDPRODUCTS;

SELECT LOCATION FROM TABLE1
EXCEPT
SELECT LOCATION FROM TABLE2;

SELECT EMPLOYEE_ID FROM EMPLOYEE_TABLE1
EXCEPT
SELECT EMPLOYEE_ID FROM EMPLOYEE_TABLE2;

SELECT STUDENT_NAME FROM STUDENTS
EXCEPT
SELECT STUDENT_NAME FROM ALUMNI;

SELECT COLUMN_NAME FROM TABLE1
EXCEPT
SELECT COLUMN_NAME FROM TABLE2;

/* E. IN – 10 QUESTIONS
 
IN CHECKS WHETHER A VALUE EXISTS IN A LIST OR SUBQUERY RESULT.
 
81. DISPLAY EMPLOYEES WHO WORK IN DEPARTMENTS THAT EXIST IN THE DEPARTMENTS TABLE.
82. DISPLAY STUDENTS WHOSE DEPARTMENTID EXISTS IN THE DEPARTMENTS TABLE.
83. DISPLAY CUSTOMERS WHOSE CUSTOMERID EXISTS IN THE ORDERS TABLE.
84. DISPLAY PRODUCTS WHOSE PRODUCTID EXISTS IN THE ORDERS TABLE.
85. DISPLAY EMPLOYEES WHOSE EMPLOYEEID EXISTS IN THE EMPLOYEEPROJECTS TABLE.
86. DISPLAY STUDENTS WHOSE STUDENTID EXISTS IN THE ENROLLMENTS TABLE.
87. DISPLAY CUSTOMERS WHO HAVE PLACED AN ORDER.
88. DISPLAY PRODUCTS THAT HAVE BEEN ORDERED.
89. DISPLAY EMPLOYEES BELONGING TO DEPARTMENTS LOCATED IN CHENNAI.
90. DISPLAY STUDENTS BELONGING TO DEPARTMENTS WHOSE NAME IS 'DATA SCIENCE' OR 'IT'.
 
EXAMPLE
 
SELECT *
FROM CUSTOMERS
WHERE CUSTOMERID IN (
SELECT CUSTOMERID
FROM ORDERS
);*/

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
);

SELECT *
FROM STUDENTS
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
);

SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM ORDERS
);

SELECT *
FROM PRODUCTS
WHERE PRODUCT_ID IN (
    SELECT PRODUCT_ID
    FROM ORDERS
);

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (
    SELECT EMPLOYEE_ID
    FROM EMPLOYEEPROJECTS
);

SELECT *
FROM STUDENTS
WHERE STUDENT_ID IN (
    SELECT STUDENT_ID
    FROM ENROLLMENTS
);

SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM ORDERS
);

SELECT *
FROM PRODUCTS
WHERE PRODUCT_ID IN (
    SELECT PRODUCT_ID
    FROM ORDERS
);

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE CITY = 'CHENNAI'
);

SELECT *
FROM STUDENTS
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_NAME IN ('DATA SCIENCE', 'IT')
);

 
/* F. NOT IN – 10 QUESTIONS
 
NOT IN CHECKS WHETHER A VALUE IS NOT PRESENT IN THE SPECIFIED LIST OR SUBQUERY RESULT.
 
91. DISPLAY CUSTOMERS WHO HAVE NEVER PLACED AN ORDER.
92. DISPLAY PRODUCTS THAT HAVE NEVER BEEN ORDERED.
93. DISPLAY STUDENTS WHO ARE NOT ENROLLED IN ANY COURSE.
94. DISPLAY EMPLOYEES WHO ARE NOT ASSIGNED TO ANY PROJECT.
95. DISPLAY DEPARTMENTS THAT HAVE NO EMPLOYEES.
96. DISPLAY CUSTOMERS WHOSE IDS ARE NOT PRESENT IN THE ORDERS TABLE.
97. DISPLAY PRODUCTS WHOSE IDS ARE NOT PRESENT IN THE ORDERS TABLE.
98. DISPLAY EMPLOYEES WHOSE IDS ARE NOT PRESENT IN THE EMPLOYEEPROJECTS TABLE.
99. DISPLAY STUDENTS WHOSE IDS ARE NOT PRESENT IN THE ENROLLMENTS TABLE.
100. DISPLAY COURSES WHOSE IDS ARE NOT PRESENT IN THE ENROLLMENTS TABLE.
*/

SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_ID NOT IN (
    SELECT CUSTOMER_ID
    FROM ORDERS
);

SELECT *
FROM PRODUCTS
WHERE PRODUCT_ID NOT IN (
    SELECT PRODUCT_ID
    FROM ORDERS
);

SELECT *
FROM STUDENTS
WHERE STUDENT_ID NOT IN (
    SELECT STUDENT_ID
    FROM ENROLLMENTS
);

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (
    SELECT EMPLOYEE_ID
    FROM EMPLOYEEPROJECTS
);

SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT IN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
);

SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_ID NOT IN (
    SELECT CUSTOMER_ID
    FROM ORDERS
);

SELECT *
FROM PRODUCTS
WHERE PRODUCT_ID NOT IN (
    SELECT PRODUCT_ID
    FROM ORDERS
);

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (
    SELECT EMPLOYEE_ID
    FROM EMPLOYEEPROJECTS
);

SELECT *
FROM STUDENTS
WHERE STUDENT_ID NOT IN (
    SELECT STUDENT_ID
    FROM ENROLLMENTS
);

SELECT *
FROM COURSES
WHERE COURSE_ID NOT IN (
    SELECT COURSE_ID
    FROM ENROLLMENTS
);
