#Date: 28th August 2026
#Topics Covered:

/* SQL GROUP BY & HAVING

A. GROUP BY – 20 QUESTIONS

1. DISPLAY THE NUMBER OF EMPLOYEES IN EACH DEPARTMENT.
2. DISPLAY THE NUMBER OF STUDENTS IN EACH DEPARTMENT.
3. DISPLAY THE NUMBER OF PRODUCTS IN EACH CATEGORY.
4. DISPLAY THE NUMBER OF CUSTOMERS IN EACH CITY.
5. DISPLAY THE NUMBER OF EMPLOYEES IN EACH DESIGNATION.
6. DISPLAY THE NUMBER OF STUDENTS IN EACH COURSE.
7. FIND THE TOTAL SALARY PAID FOR EACH DEPARTMENT.
8. FIND THE AVERAGE SALARY FOR EACH DEPARTMENT.
9. FIND THE MINIMUM SALARY IN EACH DEPARTMENT.
10. FIND THE MAXIMUM SALARY IN EACH DEPARTMENT.
11. FIND THE TOTAL PRODUCT STOCK FOR EACH CATEGORY.
12. FIND THE AVERAGE PRICE OF PRODUCTS IN EACH CATEGORY.
13. FIND THE MINIMUM PRODUCT PRICE IN EACH CATEGORY.
14. FIND THE MAXIMUM PRODUCT PRICE IN EACH CATEGORY.
15. FIND THE TOTAL COURSE FEES FOR EACH DEPARTMENT.
16. FIND THE AVERAGE COURSE FEES FOR EACH DEPARTMENT.
17. FIND THE NUMBER OF CUSTOMERS FROM EACH CITY.
18. FIND THE TOTAL ORDER QUANTITY FOR EACH PRODUCT.
19. FIND THE TOTAL ORDER AMOUNT FOR EACH CUSTOMER.
20. FIND THE NUMBER OF EMPLOYEES JOINING IN EACH YEAR. */ 

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_STUDENTS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT CATEGORY, COUNT(*) AS NUM_OF_PRODUCTS
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CITY, COUNT(*) AS NUM_OF_CUSTOMERS
FROM CUSTOMERS
GROUP BY CITY;

SELECT DESIGNATION, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY DESIGNATION;

SELECT COURSE, COUNT(*) AS NUM_OF_STUDENTS
FROM STUDENTS
GROUP BY COURSE;

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT CATEGORY, SUM(STOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, AVG(PRICE) AS AVG_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, MIN(PRICE) AS MIN_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT DEPARTMENT, SUM(FEES) AS TOTAL_FEES
FROM COURSES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, AVG(FEES) AS AVG_FEES
FROM COURSES
GROUP BY DEPARTMENT;

SELECT CITY, COUNT(*) AS NUM_OF_CUSTOMERS
FROM CUSTOMERS
GROUP BY CITY;

SELECT PRODUCT_ID, SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS
GROUP BY PRODUCT_ID;

SELECT CUSTOMER_ID, SUM(ORDER_AMOUNT) AS TOTAL_ORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT YEAR(JOINING_DATE) AS JOINING_YEAR, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY YEAR(JOINING_DATE);

/* B. GROUP BY WITH COUNT() – 15 QUESTIONS

21. COUNT THE NUMBER OF EMPLOYEES IN EACH DEPARTMENT.
22. COUNT THE NUMBER OF STUDENTS IN EACH DEPARTMENT.
23. COUNT THE NUMBER OF PRODUCTS IN EACH CATEGORY.
24. COUNT THE NUMBER OF CUSTOMERS IN EACH CITY.
25. COUNT THE NUMBER OF EMPLOYEES IN EACH JOB ROLE.
26. COUNT THE NUMBER OF STUDENTS IN EACH COURSE.
27. COUNT THE NUMBER OF ORDERS PLACED BY EACH CUSTOMER.
28. COUNT THE NUMBER OF ORDERS FOR EACH PRODUCT.
29. COUNT THE NUMBER OF EMPLOYEES HIRED IN EACH YEAR.
30. COUNT THE NUMBER OF STUDENTS FOR EACH GENDER.
31. COUNT THE NUMBER OF PRODUCTS FOR EACH BRAND.
32. COUNT THE NUMBER OF CUSTOMERS FOR EACH STATE.
33. COUNT THE NUMBER OF EMPLOYEES FOR EACH EXPERIENCE LEVEL.
34. COUNT THE NUMBER OF BOOKS WRITTEN BY EACH AUTHOR.
35. COUNT THE NUMBER OF COURSES OFFERED BY EACH DEPARTMENT. */ 

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_STUDENTS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT CATEGORY, COUNT(*) AS NUM_OF_PRODUCTS
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CITY, COUNT(*) AS NUM_OF_CUSTOMERS
FROM CUSTOMERS
GROUP BY CITY;

SELECT JOB_ROLE, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY JOB_ROLE;

SELECT COURSE, COUNT(*) AS NUM_OF_STUDENTS
FROM STUDENTS
GROUP BY COURSE;

SELECT CUSTOMER_ID, COUNT(*) AS NUM_OF_ORDERS
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT PRODUCT_ID, COUNT(*) AS NUM_OF_ORDERS
FROM ORDERS
GROUP BY PRODUCT_ID;

SELECT YEAR(HIRE_DATE) AS HIRE_YEAR, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY YEAR(HIRE_DATE);

SELECT GENDER, COUNT(*) AS NUM_OF_STUDENTS
FROM STUDENTS
GROUP BY GENDER;

SELECT BRAND, COUNT(*) AS NUM_OF_PRODUCTS
FROM PRODUCTS
GROUP BY BRAND;

SELECT STATE, COUNT(*) AS NUM_OF_CUSTOMERS
FROM CUSTOMERS
GROUP BY STATE;

SELECT EXPERIENCE_LEVEL, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY EXPERIENCE_LEVEL;

SELECT AUTHOR, COUNT(*) AS NUM_OF_BOOKS
FROM BOOKS
GROUP BY AUTHOR;

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_COURSES
FROM COURSES
GROUP BY DEPARTMENT;


/* C. GROUP BY WITH SUM() – 15 QUESTIONS

36. FIND THE TOTAL SALARY FOR EACH DEPARTMENT.
37. FIND THE TOTAL SALES AMOUNT FOR EACH CUSTOMER.
38. FIND THE TOTAL ORDER QUANTITY FOR EACH PRODUCT.
39. FIND THE TOTAL STOCK AVAILABLE FOR EACH CATEGORY.
40. FIND THE TOTAL PRODUCT VALUE FOR EACH CATEGORY.
41. FIND THE TOTAL COURSE FEES COLLECTED FOR EACH DEPARTMENT.
42. FIND THE TOTAL SALARY FOR EACH JOB ROLE.
43. FIND THE TOTAL SALES FOR EACH CITY.
44. FIND THE TOTAL ORDER AMOUNT FOR EACH MONTH.
45. FIND THE TOTAL QUANTITY SOLD FOR EACH PRODUCT CATEGORY.
46. FIND THE TOTAL INVENTORY VALUE FOR EACH BRAND.
47. FIND THE TOTAL SALARY PAID TO EMPLOYEES IN EACH YEAR.
48. FIND THE TOTAL SALES GENERATED BY EACH CUSTOMER.
49. FIND THE TOTAL FEES COLLECTED FOR EACH COURSE.
50. FIND THE TOTAL ORDER QUANTITY FOR EACH CUSTOMER. */

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM SALES
GROUP BY CUSTOMER_ID;

SELECT PRODUCT_ID, SUM(QUANTITY) AS TOTAL_ORDER_QUANTITY
FROM ORDERS
GROUP BY PRODUCT_ID;

SELECT CATEGORY, SUM(STOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, SUM(PRICE * STOCK) AS TOTAL_PRODUCT_VALUE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT DEPARTMENT, SUM(FEES) AS TOTAL_FEES_COLLECTED
FROM COURSES
GROUP BY DEPARTMENT;

SELECT JOB_ROLE, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY JOB_ROLE;

SELECT CITY, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES
GROUP BY CITY;

SELECT MONTH(ORDER_DATE) AS ORDER_MONTH, SUM(ORDER_AMOUNT) AS TOTAL_ORDER_AMOUNT
FROM ORDERS
GROUP BY MONTH(ORDER_DATE);

SELECT CATEGORY, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT BRAND, SUM(PRICE * STOCK) AS TOTAL_INVENTORY_VALUE
FROM PRODUCTS
GROUP BY BRAND;

SELECT YEAR(HIRE_DATE) AS HIRE_YEAR, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY YEAR(HIRE_DATE);

SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES
GROUP BY CUSTOMER_ID;

SELECT COURSE, SUM(FEES) AS TOTAL_FEES_COLLECTED
FROM COURSES
GROUP BY COURSE;

SELECT CUSTOMER_ID, SUM(QUANTITY) AS TOTAL_ORDER_QUANTITY
FROM ORDERS
GROUP BY CUSTOMER_ID;

/* D. GROUP BY WITH AVG(), MIN(), MAX() – 15 QUESTIONS

51. FIND THE AVERAGE SALARY FOR EACH DEPARTMENT.
52. FIND THE MAXIMUM SALARY FOR EACH DEPARTMENT.
53. FIND THE MINIMUM SALARY FOR EACH DEPARTMENT.
54. FIND THE AVERAGE PRODUCT PRICE FOR EACH CATEGORY.
55. FIND THE MAXIMUM PRODUCT PRICE FOR EACH CATEGORY.
56. FIND THE MINIMUM PRODUCT PRICE FOR EACH CATEGORY.
57. FIND THE AVERAGE MARKS FOR STUDENTS IN EACH DEPARTMENT.
58. FIND THE HIGHEST MARKS IN EACH DEPARTMENT.
59. FIND THE LOWEST MARKS IN EACH DEPARTMENT.
60. FIND THE AVERAGE COURSE FEES FOR EACH DEPARTMENT.
61. FIND THE HIGHEST COURSE FEE IN EACH DEPARTMENT.
62. FIND THE LOWEST COURSE FEE IN EACH DEPARTMENT.
63. FIND THE AVERAGE ORDER AMOUNT FOR EACH CUSTOMER.
64. FIND THE HIGHEST ORDER AMOUNT FOR EACH CUSTOMER.
65. FIND THE LOWEST ORDER AMOUNT FOR EACH CUSTOMER. */

SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT CATEGORY, AVG(PRICE) AS AVG_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, MIN(PRICE) AS MIN_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT DEPARTMENT, AVG(MARKS) AS AVG_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MAX(MARKS) AS HIGHEST_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MIN(MARKS) AS LOWEST_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, AVG(FEES) AS AVG_FEES
FROM COURSES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MAX(FEES) AS HIGHEST_FEE
FROM COURSES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MIN(FEES) AS LOWEST_FEE
FROM COURSES
GROUP BY DEPARTMENT;

SELECT CUSTOMER_ID, AVG(ORDER_AMOUNT) AS AVG_ORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT CUSTOMER_ID, MAX(ORDER_AMOUNT) AS HIGHEST_ORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT CUSTOMER_ID, MIN(ORDER_AMOUNT) AS LOWEST_ORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMER_ID;

/* E. HAVING – 15 QUESTIONS

66. DISPLAY DEPARTMENTS HAVING MORE THAN 5 EMPLOYEES.
67. DISPLAY DEPARTMENTS HAVING FEWER THAN 5 EMPLOYEES.
68. DISPLAY DEPARTMENTS HAVING EXACTLY 5 EMPLOYEES.
69. DISPLAY DEPARTMENTS WHERE THE AVERAGE SALARY IS GREATER THAN 50000.
70. DISPLAY DEPARTMENTS WHERE THE AVERAGE SALARY IS LESS THAN 40000.
71. DISPLAY DEPARTMENTS WHERE THE MAXIMUM SALARY IS GREATER THAN 100000.
72. DISPLAY DEPARTMENTS WHERE THE MINIMUM SALARY IS GREATER THAN 30000.
73. DISPLAY PRODUCT CATEGORIES HAVING MORE THAN 10 PRODUCTS.
74. DISPLAY PRODUCT CATEGORIES WHERE THE AVERAGE PRICE IS GREATER THAN 5000.
75. DISPLAY PRODUCT CATEGORIES WHERE THE TOTAL STOCK IS GREATER THAN 1000.
76. DISPLAY CITIES HAVING MORE THAN 20 CUSTOMERS.
77. DISPLAY CUSTOMERS WHO HAVE PLACED MORE THAN 5 ORDERS.
78. DISPLAY PRODUCTS THAT HAVE BEEN ORDERED MORE THAN 10 TIMES.
79. DISPLAY DEPARTMENTS WHERE THE TOTAL SALARY EXCEEDS 500000.
80. DISPLAY COURSES HAVING MORE THAN 30 STUDENTS. */

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) > 5;

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) < 5;

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) = 5;

SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 50000;

SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY) < 40000;

SELECT DEPARTMENT, MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING MAX(SALARY) > 100000;

SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING MIN(SALARY) > 30000;

SELECT CATEGORY, COUNT(*) AS NUM_OF_PRODUCTS
FROM PRODUCTS
GROUP BY CATEGORY
HAVING COUNT(*) > 10;

SELECT CATEGORY, AVG(PRICE) AS AVG_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
HAVING AVG(PRICE) > 5000;

SELECT CATEGORY, SUM(STOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY
HAVING SUM(STOCK) > 1000;

SELECT CITY, COUNT(*) AS NUM_OF_CUSTOMERS
FROM CUSTOMERS
GROUP BY CITY
HAVING COUNT(*) > 20;

SELECT CUSTOMER_ID, COUNT(*) AS NUM_OF_ORDERS
FROM ORDERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 5;

SELECT PRODUCT_ID, COUNT(*) AS NUM_OF_ORDERS
FROM ORDERS
GROUP BY PRODUCT_ID
HAVING COUNT(*) > 10;

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > 500000;

SELECT COURSE, COUNT(*) AS NUM_OF_STUDENTS
FROM STUDENTS
GROUP BY COURSE
HAVING COUNT(*) > 30;

/* F. WHERE + GROUP BY + HAVING – 10 QUESTIONS

81. FIND THE NUMBER OF EMPLOYEES IN EACH DEPARTMENT WHOSE SALARY IS GREATER THAN 30000. DISPLAY ONLY DEPARTMENTS HAVING MORE THAN 5 SUCH EMPLOYEES.
82. FIND THE AVERAGE SALARY OF EMPLOYEES IN EACH DEPARTMENT WHERE EMPLOYEES HAVE MORE THAN 2 YEARS OF EXPERIENCE. DISPLAY DEPARTMENTS WHERE THE AVERAGE SALARY IS GREATER THAN 50000.
83. FIND THE TOTAL SALES FOR EACH CUSTOMER FOR ORDERS GREATER THAN 1000. DISPLAY CUSTOMERS WHOSE TOTAL SALES EXCEED 10000.
84. FIND THE NUMBER OF PRODUCTS IN EACH CATEGORY WHERE PRICE IS GREATER THAN 500. DISPLAY CATEGORIES HAVING MORE THAN 5 PRODUCTS.
85. FIND THE AVERAGE MARKS FOR EACH DEPARTMENT FOR STUDENTS WHO SCORED ABOVE 40. DISPLAY DEPARTMENTS HAVING AN AVERAGE ABOVE 70.
86. FIND THE TOTAL STOCK FOR EACH CATEGORY WHERE STOCK IS GREATER THAN 10. DISPLAY CATEGORIES HAVING TOTAL STOCK GREATER THAN 500.
87. FIND THE NUMBER OF CUSTOMERS IN EACH CITY WHOSE AGE IS GREATER THAN 18. DISPLAY CITIES HAVING MORE THAN 10 CUSTOMERS.
88. FIND THE AVERAGE COURSE FEES FOR EACH DEPARTMENT WHERE FEES ARE GREATER THAN 20000. DISPLAY DEPARTMENTS HAVING AN AVERAGE FEE ABOVE 30000.
89. FIND THE NUMBER OF ORDERS FOR EACH CUSTOMER WHERE ORDER AMOUNT IS GREATER THAN 5000. DISPLAY CUSTOMERS HAVING MORE THAN 3 SUCH ORDERS.
90. FIND THE TOTAL SALARY FOR EACH DEPARTMENT WHERE EMPLOYEE SALARY IS GREATER THAN 40000. DISPLAY DEPARTMENTS HAVING TOTAL SALARY ABOVE 300000. */

SELECT DEPARTMENT, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
WHERE SALARY > 30000
GROUP BY DEPARTMENT
HAVING COUNT(*) > 5;

SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
WHERE EXPERIENCE > 2
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 50000;

SELECT CUSTOMER_ID, SUM(ORDER_AMOUNT) AS TOTAL_SALES
FROM ORDERS
WHERE ORDER_AMOUNT > 1000
GROUP BY CUSTOMER_ID
HAVING SUM(ORDER_AMOUNT) > 10000;

SELECT CATEGORY, COUNT(*) AS NUM_OF_PRODUCTS
FROM PRODUCTS
WHERE PRICE > 500
GROUP BY CATEGORY
HAVING COUNT(*) > 5;

SELECT DEPARTMENT, AVG(MARKS) AS AVG_MARKS
FROM STUDENTS
WHERE MARKS > 40
GROUP BY DEPARTMENT
HAVING AVG(MARKS) > 70;

SELECT CATEGORY, SUM(STOCK) AS TOTAL_STOCK
FROM PRODUCTS
WHERE STOCK > 10
GROUP BY CATEGORY
HAVING SUM(STOCK) > 500;

SELECT CITY, COUNT(*) AS NUM_OF_CUSTOMERS
FROM CUSTOMERS
WHERE AGE > 18
GROUP BY CITY
HAVING COUNT(*) > 10;

SELECT DEPARTMENT, AVG(FEES) AS AVG_FEES
FROM COURSES
WHERE FEES > 20000
GROUP BY DEPARTMENT
HAVING AVG(FEES) > 30000;

SELECT CUSTOMER_ID, COUNT(*) AS NUM_OF_ORDERS
FROM ORDERS
WHERE ORDER_AMOUNT > 5000
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 3;

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
WHERE SALARY > 40000
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > 300000;

/* G. GROUP BY MULTIPLE COLUMNS – 10 QUESTIONS

91. FIND THE NUMBER OF EMPLOYEES FOR EACH DEPARTMENT AND DESIGNATION.
92. FIND THE AVERAGE SALARY FOR EACH DEPARTMENT AND DESIGNATION.
93. FIND THE NUMBER OF STUDENTS FOR EACH DEPARTMENT AND GENDER.
94. FIND THE AVERAGE MARKS FOR EACH DEPARTMENT AND GENDER.
95. FIND THE NUMBER OF PRODUCTS FOR EACH CATEGORY AND BRAND.
96. FIND THE AVERAGE PRICE FOR EACH CATEGORY AND BRAND.
97. FIND THE TOTAL SALES FOR EACH CUSTOMER AND CITY.
98. FIND THE TOTAL ORDER QUANTITY FOR EACH CUSTOMER AND PRODUCT.
99. FIND THE NUMBER OF CUSTOMERS FOR EACH CITY AND STATE.
100. FIND THE TOTAL SALARY FOR EACH DEPARTMENT AND JOB ROLE, AND DISPLAY ONLY GROUPS WHERE THE TOTAL SALARY IS GREATER THAN 200000. */ 

SELECT DEPARTMENT, DESIGNATION, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT, DESIGNATION;

SELECT DEPARTMENT, DESIGNATION, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT, DESIGNATION;

SELECT DEPARTMENT, GENDER, COUNT(*) AS NUM_OF_STUDENTS
FROM STUDENTS
GROUP BY DEPARTMENT, GENDER;

SELECT DEPARTMENT, GENDER, AVG(MARKS) AS AVG_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT, GENDER;

SELECT CATEGORY, BRAND, COUNT(*) AS NUM_OF_PRODUCTS
FROM PRODUCTS
GROUP BY CATEGORY, BRAND;

SELECT CATEGORY, BRAND, AVG(PRICE) AS AVG_PRICE
FROM PRODUCTS
GROUP BY CATEGORY, BRAND;

SELECT CUSTOMER_ID, CITY, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES
GROUP BY CUSTOMER_ID, CITY;

SELECT CUSTOMER_ID, PRODUCT_ID, SUM(QUANTITY) AS TOTAL_ORDER_QUANTITY
FROM ORDERS
GROUP BY CUSTOMER_ID, PRODUCT_ID;

SELECT CITY, STATE, COUNT(*) AS NUM_OF_CUSTOMERS
FROM CUSTOMERS
GROUP BY CITY, STATE;

SELECT DEPARTMENT, JOB_ROLE, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT, JOB_ROLE
HAVING SUM(SALARY) > 200000;

