#Date: 28th August 2026
#Date Covered: 27th August 2026
#Topics Covered:

/* ORDER BY COLUMN POSITION

A. BASIC ORDER BY POSITION - 20 QUESTIONS

1. DISPLAY STUDENTNAME, AGE, AND DEPARTMENT. SORT THE RESULT USING THE 1ST COLUMN IN ASCENDING ORDER.
2. DISPLAY STUDENTNAME, AGE, AND MARKS. SORT USING THE 3RD COLUMN IN DESCENDING ORDER.
3. DISPLAY EMPLOYEENAME, DEPARTMENT, AND SALARY. SORT USING THE 3RD COLUMN IN DESCENDING ORDER.
4. DISPLAY EMPLOYEENAME, SALARY, AND JOBROLE. SORT USING THE 2ND COLUMN IN ASCENDING ORDER.
5. DISPLAY PRODUCTNAME, PRICE, AND STOCK. SORT USING THE 2ND COLUMN IN DESCENDING ORDER.
6. DISPLAY PRODUCTNAME, CATEGORY, AND PRICE. SORT USING THE 3RD COLUMN IN ASCENDING ORDER.
7. DISPLAY BOOKNAME, AUTHOR, AND PRICE. SORT USING THE 3RD COLUMN IN DESCENDING ORDER.
8. DISPLAY BOOKNAME, CATEGORY, AND PRICE. SORT USING THE 2ND COLUMN IN ASCENDING ORDER.
9. DISPLAY COURSENAME, DURATION, AND FEES. SORT USING THE 3RD COLUMN IN DESCENDING ORDER.
10. DISPLAY CUSTOMERNAME, CITY, AND AGE. SORT USING THE 2ND COLUMN ALPHABETICALLY.
11. DISPLAY CUSTOMERNAME, CITY, AND AGE. SORT USING THE 3RD COLUMN IN DESCENDING ORDER.
12. DISPLAY PATIENTNAME, AGE, AND BLOOD_GROUP. SORT USING THE 2ND COLUMN IN ASCENDING ORDER.
13. DISPLAY MOVIENAME, LANGUAGE, AND RATING. SORT USING THE 3RD COLUMN IN DESCENDING ORDER.
14. DISPLAY EMPLOYEENAME, SALARY, AND EXPERIENCE. SORT USING THE 2ND COLUMN IN DESCENDING ORDER.
15. DISPLAY STUDENTNAME, DEPARTMENT, AND MARKS. SORT USING THE 3RD COLUMN IN DESCENDING ORDER.
16. DISPLAY PRODUCTNAME, BRAND, PRICE, AND STOCK. SORT USING THE 3RD COLUMN IN DESCENDING ORDER.
17. DISPLAY BOOKNAME, AUTHOR, CATEGORY, AND PRICE. SORT USING THE 4TH COLUMN IN DESCENDING ORDER.
18. DISPLAY COURSENAME, DEPARTMENT, DURATION, AND FEES. SORT USING THE 4TH COLUMN IN DESCENDING ORDER.
19. DISPLAY CUSTOMERNAME, CITY, EMAIL, AND PHONE. SORT USING THE 2ND COLUMN ASCENDING.
20. DISPLAY EMPLOYEENAME, DEPARTMENT, JOBROLE, AND SALARY. SORT USING THE 4TH COLUMN DESCENDING. */

SELECT STUDENTNAME, AGE, DEPARTMENT
FROM STUDENTS
ORDER BY 1 ASC;

SELECT STUDENTNAME, AGE, MARKS
FROM STUDENTS
ORDER BY 3 DESC;

SELECT EMPLOYEENAME, DEPARTMENT, SALARY
FROM EMPLOYEES
ORDER BY 3 DESC;

SELECT EMPLOYEENAME, SALARY, JOBROLE
FROM EMPLOYEES
ORDER BY 2 ASC;

SELECT PRODUCTNAME, PRICE, STOCK
FROM PRODUCTS
ORDER BY 2 DESC;

SELECT PRODUCTNAME, CATEGORY, PRICE
FROM PRODUCTS
ORDER BY 3 ASC;

SELECT BOOKNAME, AUTHOR, PRICE
FROM BOOKS
ORDER BY 3 DESC;

SELECT BOOKNAME, CATEGORY, PRICE
FROM BOOKS
ORDER BY 2 ASC;

SELECT COURSENAME, DURATION, FEES
FROM COURSES
ORDER BY 3 DESC;

SELECT CUSTOMERNAME, CITY, AGE
FROM CUSTOMERS
ORDER BY 2 ASC;

SELECT CUSTOMERNAME, CITY, AGE
FROM CUSTOMERS
ORDER BY 3 DESC;

SELECT PATIENTNAME, AGE, BLOOD_GROUP
FROM PATIENTS
ORDER BY 2 ASC;

SELECT MOVIENAME, LANGUAGE, RATING
FROM MOVIES
ORDER BY 3 DESC;

SELECT EMPLOYEENAME, SALARY, EXPERIENCE
FROM EMPLOYEES
ORDER BY 2 DESC;

SELECT STUDENTNAME, DEPARTMENT, MARKS
FROM STUDENTS
ORDER BY 3 DESC;

SELECT PRODUCTNAME, BRAND, PRICE, STOCK
FROM PRODUCTS
ORDER BY 3 DESC;

SELECT BOOKNAME, AUTHOR, CATEGORY, PRICE
FROM BOOKS
ORDER BY 4 DESC;

SELECT COURSENAME, DEPARTMENT, DURATION, FEES
FROM COURSES
ORDER BY 4 DESC;

SELECT CUSTOMERNAME, CITY, EMAIL, PHONE
FROM CUSTOMERS
ORDER BY 2 ASC;

SELECT EMPLOYEENAME, DEPARTMENT, JOBROLE, SALARY
FROM EMPLOYEES
ORDER BY 4 DESC

/* B. MULTIPLE COLUMN POSITIONS - 20 QUESTIONS

21. DISPLAY EMPLOYEENAME, DEPARTMENT, AND SALARY. SORT FIRST BY THE 2ND COLUMN ASCENDING AND THEN THE 3RD COLUMN DESCENDING.
22. DISPLAY STUDENTNAME, DEPARTMENT, AND MARKS. SORT FIRST BY THE 2ND COLUMN ASCENDING AND THEN THE 3RD COLUMN DESCENDING.
23. DISPLAY PRODUCTNAME, CATEGORY, PRICE, AND STOCK. SORT FIRST BY THE 2ND COLUMN ASCENDING AND THEN THE 3RD COLUMN DESCENDING.
24. DISPLAY BOOKNAME, CATEGORY, PRICE, AND AUTHOR. SORT FIRST BY THE 2ND COLUMN ASCENDING AND THEN THE 3RD COLUMN DESCENDING.
25. DISPLAY COURSENAME, DEPARTMENT, FEES, AND DURATION. SORT FIRST BY THE 2ND COLUMN ASCENDING AND THEN THE 3RD COLUMN DESCENDING.
26. DISPLAY CUSTOMERNAME, CITY, AND AGE. SORT FIRST BY THE 2ND COLUMN ASCENDING AND THEN THE 3RD COLUMN DESCENDING.
27. DISPLAY EMPLOYEENAME, JOBROLE, DEPARTMENT, AND SALARY. SORT BY THE 3RD COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
28. DISPLAY PRODUCTNAME, BRAND, CATEGORY, AND PRICE. SORT BY THE 2ND COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
29. DISPLAY STUDENTNAME, DEPARTMENT, AGE, AND MARKS. SORT BY THE 2ND COLUMN ASCENDING, 4TH COLUMN DESCENDING.
30. DISPLAY BOOKNAME, AUTHOR, CATEGORY, AND PRICE. SORT BY THE 3RD COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
31. DISPLAY EMPLOYEENAME, DEPARTMENT, SALARY, AND EXPERIENCE. SORT BY THE 2ND COLUMN ASCENDING AND 3RD COLUMN DESCENDING.
32. DISPLAY PRODUCTNAME, CATEGORY, PRICE, AND STOCK. SORT BY THE 2ND COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
33. DISPLAY COURSENAME, DEPARTMENT, DURATION, AND FEES. SORT BY THE 2ND COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
34. DISPLAY CUSTOMERNAME, CITY, AGE, AND EMAIL. SORT BY THE 2ND COLUMN ASCENDING AND 3RD COLUMN DESCENDING.
35. DISPLAY PATIENTNAME, BLOOD_GROUP, AGE, AND DISEASE. SORT BY THE 2ND COLUMN ASCENDING AND 3RD COLUMN DESCENDING.
36. DISPLAY MOVIENAME, LANGUAGE, GENRE, AND RATING. SORT BY THE 2ND COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
37. DISPLAY EMPLOYEENAME, DEPARTMENT, JOBROLE, SALARY, AND EXPERIENCE. SORT BY THE 2ND COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
38. DISPLAY PRODUCTNAME, BRAND, CATEGORY, PRICE, AND STOCK. SORT BY THE 3RD COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
39. DISPLAY STUDENTNAME, DEPARTMENT, AGE, MARKS, AND ATTENDANCE. SORT BY THE 2ND COLUMN ASCENDING AND 4TH COLUMN DESCENDING.
40. DISPLAY COURSENAME, DEPARTMENT, FEES, DURATION, AND MODE. SORT BY THE 2ND COLUMN ASCENDING AND 3RD COLUMN DESCENDING. */ 

SELECT EMPLOYEENAME, DEPARTMENT, SALARY
FROM EMPLOYEES
ORDER BY 2 ASC, 3 DESC;

SELECT STUDENTNAME, DEPARTMENT, MARKS
FROM STUDENTS
ORDER BY 2 ASC, 3 DESC;

SELECT PRODUCTNAME, CATEGORY, PRICE, STOCK
FROM PRODUCTS
ORDER BY 2 ASC, 3 DESC;

SELECT BOOKNAME, CATEGORY, PRICE, AUTHOR
FROM BOOKS
ORDER BY 2 ASC, 3 DESC;

SELECT COURSENAME, DEPARTMENT, FEES, DURATION
FROM COURSES
ORDER BY 2 ASC, 3 DESC;

SELECT CUSTOMERNAME, CITY, AGE
FROM CUSTOMERS
ORDER BY 2 ASC, 3 DESC;

SELECT EMPLOYEENAME, JOBROLE, DEPARTMENT, SALARY
FROM EMPLOYEES
ORDER BY 3 ASC, 4 DESC;

SELECT PRODUCTNAME, BRAND, CATEGORY, PRICE
FROM PRODUCTS
ORDER BY 2 ASC, 4 DESC;

SELECT STUDENTNAME, DEPARTMENT, AGE, MARKS
FROM STUDENTS
ORDER BY 2 ASC, 4 DESC;

SELECT BOOKNAME, AUTHOR, CATEGORY, PRICE
FROM BOOKS
ORDER BY 3 ASC, 4 DESC;

SELECT EMPLOYEENAME, DEPARTMENT, SALARY, EXPERIENCE
FROM EMPLOYEES
ORDER BY 2 ASC, 3 DESC;

SELECT PRODUCTNAME, CATEGORY, PRICE, STOCK
FROM PRODUCTS
ORDER BY 2 ASC, 4 DESC;

SELECT COURSENAME, DEPARTMENT, DURATION, FEES
FROM COURSES
ORDER BY 2 ASC, 4 DESC;

SELECT CUSTOMERNAME, CITY, AGE, EMAIL
FROM CUSTOMERS
ORDER BY 2 ASC, 3 DESC;

SELECT PATIENTNAME, BLOOD_GROUP, AGE, DISEASE
FROM PATIENTS
ORDER BY 2 ASC, 3 DESC;

SELECT MOVIENAME, LANGUAGE, GENRE, RATING
FROM MOVIES
ORDER BY 2 ASC, 4 DESC;

SELECT EMPLOYEENAME, DEPARTMENT, JOBROLE, SALARY, EXPERIENCE
FROM EMPLOYEES
ORDER BY 2 ASC, 4 DESC;

SELECT PRODUCTNAME, BRAND, CATEGORY, PRICE, STOCK
FROM PRODUCTS
ORDER BY 3 ASC, 4 DESC;

SELECT STUDENTNAME, DEPARTMENT, AGE, MARKS, ATTENDANCE
FROM STUDENTS
ORDER BY 2 ASC, 4 DESC;

SELECT COURSENAME, DEPARTMENT, FEES, DURATION, MODE
FROM COURSES
ORDER BY 2 ASC, 3 DESC;

/* C. ORDER BY POSITION WITH EXPRESSIONS - 20 QUESTIONS

41. DISPLAY EMPLOYEE NAME AND SALARY * 12. SORT USING THE 2ND COLUMN IN DESCENDING ORDER.
42. DISPLAY PRODUCT NAME AND PRICE * QUANTITY. SORT USING THE 2ND COLUMN IN DESCENDING ORDER.
43. DISPLAY EMPLOYEE NAME AND SALARY * 1.10. SORT USING THE 2ND COLUMN DESCENDING.
44. DISPLAY PRODUCT NAME AND PRICE * 0.90. SORT USING THE 2ND COLUMN ASCENDING.
45. DISPLAY STUDENT NAME AND LENGTH(STUDENTNAME). SORT USING THE 2ND COLUMN DESCENDING.
46. DISPLAY EMPLOYEE NAME AND SALARY / 12. SORT USING THE 2ND COLUMN ASCENDING.
47. DISPLAY PRODUCT NAME AND PRICE * QUANTITY AS TOTAL_VALUE. SORT USING POSITION 2 DESCENDING.
48. DISPLAY BOOK NAME AND PRICE * 0.80 AS DISCOUNTED_PRICE. SORT USING POSITION 2 ASCENDING.
49. DISPLAY COURSE NAME AND FEES * 0.85 AS FINAL_FEES. SORT USING POSITION 2 DESCENDING.
50. DISPLAY STUDENT NAME AND AGE + 1 AS NEXT_YEAR_AGE. SORT USING POSITION 2 ASCENDING.
51. DISPLAY EMPLOYEE NAME, DEPARTMENT, AND ANNUAL SALARY. SORT USING POSITION 3 DESCENDING.
52. DISPLAY PRODUCT NAME, CATEGORY, AND TOTAL STOCK VALUE. SORT USING POSITION 3 DESCENDING.
53. DISPLAY STUDENT NAME, DEPARTMENT, AND NAME LENGTH. SORT USING POSITION 3 DESCENDING.
54. DISPLAY BOOK NAME, CATEGORY, AND DISCOUNTED PRICE. SORT USING POSITION 3 ASCENDING.
55. DISPLAY COURSE NAME, DEPARTMENT, AND FINAL FEES. SORT USING POSITION 3 DESCENDING.
56. DISPLAY EMPLOYEE NAME, SALARY, AND ANNUAL SALARY. SORT USING POSITION 3 DESCENDING.
57. DISPLAY PRODUCT NAME, PRICE, QUANTITY, AND TOTAL VALUE. SORT USING POSITION 4 DESCENDING.
58. DISPLAY STUDENT NAME, MARKS, ATTENDANCE, AND AVERAGE SCORE (MARKS + ATTENDANCE) / 2. SORT USING POSITION 4 DESCENDING.
59. DISPLAY EMPLOYEE NAME, SALARY, EXPERIENCE, AND YEARLY PAY. SORT USING POSITION 4 DESCENDING.
60. DISPLAY PRODUCT NAME, PRICE, STOCK, AND INVENTORY VALUE. SORT USING POSITION 4 DESCENDING. */

SELECT EMPLOYEENAME, SALARY * 12
FROM EMPLOYEES
ORDER BY 2 DESC;

SELECT PRODUCTNAME, PRICE * QUANTITY
FROM PRODUCTS
ORDER BY 2 DESC;

SELECT EMPLOYEENAME, SALARY * 1.10
FROM EMPLOYEES
ORDER BY 2 DESC;

SELECT PRODUCTNAME, PRICE * 0.90
FROM PRODUCTS
ORDER BY 2 ASC;

SELECT STUDENTNAME, LENGTH(STUDENTNAME)
FROM STUDENTS
ORDER BY 2 DESC;

SELECT EMPLOYEENAME, SALARY / 12
FROM EMPLOYEES
ORDER BY 2 ASC;

SELECT PRODUCTNAME, PRICE * QUANTITY AS TOTAL_VALUE
FROM PRODUCTS
ORDER BY 2 DESC;

SELECT BOOKNAME, PRICE * 0.80 AS DISCOUNTED_PRICE
FROM BOOKS
ORDER BY 2 ASC;

SELECT COURSENAME, FEES * 0.85 AS FINAL_FEES
FROM COURSES
ORDER BY 2 DESC;

SELECT STUDENTNAME, AGE + 1 AS NEXT_YEAR_AGE
FROM STUDENTS
ORDER BY 2 ASC;

SELECT EMPLOYEENAME, DEPARTMENT, SALARY * 12 AS ANNUAL_SALARY
FROM EMPLOYEES
ORDER BY 3 DESC;

SELECT PRODUCTNAME, CATEGORY, PRICE * STOCK AS TOTAL_STOCK_VALUE
FROM PRODUCTS
ORDER BY 3 DESC;

SELECT STUDENTNAME, DEPARTMENT, LENGTH(STUDENTNAME) AS NAME_LENGTH
FROM STUDENTS
ORDER BY 3 DESC;

SELECT BOOKNAME, CATEGORY, PRICE * 0.80 AS DISCOUNTED_PRICE
FROM BOOKS
ORDER BY 3 ASC;

SELECT COURSENAME, DEPARTMENT, FEES * 0.85 AS FINAL_FEES
FROM COURSES
ORDER BY 3 DESC;

SELECT EMPLOYEENAME, SALARY, SALARY * 12 AS ANNUAL_SALARY
FROM EMPLOYEES
ORDER BY 3 DESC;

SELECT PRODUCTNAME, PRICE, QUANTITY, PRICE * QUANTITY AS TOTAL_VALUE
FROM PRODUCTS
ORDER BY 4 DESC;

SELECT STUDENTNAME, MARKS, ATTENDANCE, (MARKS + ATTENDANCE) / 2 AS AVERAGE_SCORE
FROM STUDENTS
ORDER BY 4 DESC;

SELECT EMPLOYEENAME, SALARY, EXPERIENCE, SALARY * 12 AS YEARLY_PAY
FROM EMPLOYEES
ORDER BY 4 DESC;

SELECT PRODUCTNAME, PRICE, STOCK, PRICE * STOCK AS INVENTORY_VALUE
FROM PRODUCTS
ORDER BY 4 DESC;

/* D. ORDER BY POSITION WITH AGGREGATE FUNCTIONS - 20 QUESTIONS

61. DISPLAY DEPARTMENT AND COUNT(*). SORT USING POSITION 2 DESCENDING.
62. DISPLAY DEPARTMENT AND AVG(SALARY). SORT USING POSITION 2 DESCENDING.
63. DISPLAY DEPARTMENT AND SUM(SALARY). SORT USING POSITION 2 DESCENDING.
64. DISPLAY DEPARTMENT AND MAX(SALARY). SORT USING POSITION 2 DESCENDING.
65. DISPLAY DEPARTMENT AND MIN(SALARY). SORT USING POSITION 2 ASCENDING.
66. DISPLAY CATEGORY AND COUNT(*). SORT USING POSITION 2 DESCENDING.
67. DISPLAY CATEGORY AND AVG(PRICE). SORT USING POSITION 2 ASCENDING.
68. DISPLAY CATEGORY AND MAX(PRICE). SORT USING POSITION 2 DESCENDING.
69. DISPLAY CATEGORY AND MIN(PRICE). SORT USING POSITION 2 ASCENDING.
70. DISPLAY CATEGORY AND SUM(PRICE * QUANTITY). SORT USING POSITION 2 DESCENDING.
71. DISPLAY DEPARTMENT, EMPLOYEE COUNT, AND AVERAGE SALARY. SORT USING POSITION 2 DESCENDING.
72. DISPLAY DEPARTMENT, EMPLOYEE COUNT, AND AVERAGE SALARY. SORT USING POSITION 3 DESCENDING.
73. DISPLAY CATEGORY, PRODUCT COUNT, AND TOTAL STOCK. SORT USING POSITION 2 DESCENDING.
74. DISPLAY CATEGORY, PRODUCT COUNT, AND TOTAL STOCK. SORT USING POSITION 3 DESCENDING.
75. DISPLAY DEPARTMENT, MINIMUM SALARY, AND MAXIMUM SALARY. SORT USING POSITION 2 ASCENDING.
76. DISPLAY DEPARTMENT, MINIMUM SALARY, AND MAXIMUM SALARY. SORT USING POSITION 3 DESCENDING.
77. DISPLAY CATEGORY, AVERAGE PRICE, AND MAXIMUM PRICE. SORT USING POSITION 2 DESCENDING.
78. DISPLAY CATEGORY, AVERAGE PRICE, AND MAXIMUM PRICE. SORT USING POSITION 3 DESCENDING.
79. DISPLAY DEPARTMENT, TOTAL SALARY, AND EMPLOYEE COUNT. SORT USING POSITION 2 DESCENDING AND THEN POSITION 3 ASCENDING.
80. DISPLAY CATEGORY, TOTAL VALUE, AND PRODUCT COUNT. SORT USING POSITION 2 DESCENDING AND THEN POSITION 3 DESCENDING. */

SELECT DEPARTMENT, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 ASC;

SELECT CATEGORY, COUNT(*)
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT CATEGORY, AVG(PRICE)
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 ASC;

SELECT CATEGORY, MAX(PRICE)
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT CATEGORY, MIN(PRICE)
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 ASC;

SELECT CATEGORY, SUM(PRICE * QUANTITY)
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT, AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT, AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 3 DESC;

SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT, SUM(STOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT, SUM(STOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 3 DESC;

SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY, MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 ASC;

SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY, MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 3 DESC;

SELECT CATEGORY, AVG(PRICE) AS AVERAGE_PRICE, MAX(PRICE) AS MAXIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT CATEGORY, AVG(PRICE) AS AVERAGE_PRICE, MAX(PRICE) AS MAXIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 3 DESC;

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC, 3 ASC;

SELECT CATEGORY, SUM(PRICE * STOCK) AS TOTAL_VALUE, COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC, 3 DESC;


