#Date: 28th August 2026
#Date Covered: 27th August 2026
#Topics Covered:

/* ORDER BY
OBJECTIVE
PRACTICE SORTING SQL QUERY RESULTS USING THE ORDER BY CLAUSE.

• ASC → ASCENDING ORDER (DEFAULT)
• DESC → DESCENDING ORDER
• SORT BY ONE COLUMN
• SORT BY MULTIPLE COLUMNS
• SORT USING EXPRESSIONS AND ALIASES

A. ORDER BY – SINGLE COLUMN

1. DISPLAY ALL STUDENTS IN ASCENDING ORDER OF THEIR NAMES.
2. DISPLAY ALL STUDENTS IN DESCENDING ORDER OF THEIR NAMES.
3. DISPLAY EMPLOYEES IN ASCENDING ORDER OF SALARY.
4. DISPLAY EMPLOYEES IN DESCENDING ORDER OF SALARY.
5. DISPLAY PRODUCTS IN ASCENDING ORDER OF PRICE.
6. DISPLAY PRODUCTS IN DESCENDING ORDER OF PRICE.
7. DISPLAY BOOKS IN ASCENDING ORDER OF BOOK PRICE.
8. DISPLAY BOOKS IN DESCENDING ORDER OF BOOK PRICE.
9. DISPLAY STUDENTS IN ASCENDING ORDER OF AGE.
10. DISPLAY STUDENTS IN DESCENDING ORDER OF AGE.
11. DISPLAY EMPLOYEES IN ASCENDING ORDER OF JOINING DATE.
12. DISPLAY EMPLOYEES IN DESCENDING ORDER OF JOINING DATE.
13. DISPLAY COURSES IN ASCENDING ORDER OF FEES.
14. DISPLAY COURSES IN DESCENDING ORDER OF FEES.
15. DISPLAY MOVIES IN DESCENDING ORDER OF RATING.
16. DISPLAY CUSTOMERS IN ASCENDING ORDER OF CITY.
17. DISPLAY PRODUCTS IN DESCENDING ORDER OF STOCK QUANTITY.
18. DISPLAY PATIENTS IN ASCENDING ORDER OF AGE.
19. DISPLAY EMPLOYEES IN DESCENDING ORDER OF EXPERIENCE.
20. DISPLAY BOOKS IN ASCENDING ORDER OF PUBLICATION YEAR. */

SELECT * FROM STUDENTS ORDER BY NAME ASC;
SELECT * FROM STUDENTS ORDER BY NAME DESC;
SELECT * FROM EMPLOYEES ORDER BY SALARY ASC;
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM PRODUCTS ORDER BY PRICE ASC;
SELECT * FROM PRODUCTS ORDER BY PRICE DESC;
SELECT * FROM BOOKS ORDER BY BOOK_PRICE ASC;
SELECT * FROM BOOKS ORDER BY BOOK_PRICE DESC;
SELECT * FROM STUDENTS ORDER BY AGE ASC;
SELECT * FROM STUDENTS ORDER BY AGE DESC;
SELECT * FROM EMPLOYEES ORDER BY JOINING_DATE ASC;
SELECT * FROM EMPLOYEES ORDER BY JOINING_DATE DESC;
SELECT * FROM COURSES ORDER BY FEES ASC;
SELECT * FROM COURSES ORDER BY FEES DESC;
SELECT * FROM MOVIES ORDER BY RATING DESC;
SELECT * FROM CUSTOMERS ORDER BY CITY ASC;
SELECT * FROM PRODUCTS ORDER BY STOCK_QUANTITY DESC;
SELECT * FROM PATIENTS ORDER BY AGE ASC;
SELECT * FROM EMPLOYEES ORDER BY EXPERIENCE DESC;
SELECT * FROM BOOKS ORDER BY PUBLICATION_YEAR ASC;

/* B. ORDER BY WITH WHERE

21. DISPLAY IT EMPLOYEES AND SORT THEM BY SALARY IN ASCENDING ORDER.
22. DISPLAY IT EMPLOYEES AND SORT THEM BY SALARY IN DESCENDING ORDER.
23. DISPLAY STUDENTS FROM THE CSE DEPARTMENT AND SORT THEM BY AGE IN DESCENDING ORDER.
24. DISPLAY PRODUCTS FROM THE ELECTRONICS CATEGORY AND SORT THEM BY PRICE IN ASCENDING ORDER.
25. DISPLAY BOOKS PRICED ABOVE 500 AND SORT THEM BY PRICE IN DESCENDING ORDER.
26. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN 40000 AND SORT THEM BY SALARY.
27. DISPLAY STUDENTS WHOSE AGE IS GREATER THAN 20 AND SORT THEM BY NAME ALPHABETICALLY.
28. DISPLAY PRODUCTS WHOSE STOCK IS LESS THAN 10 AND SORT THEM BY STOCK IN ASCENDING ORDER.
29. DISPLAY COURSES WHOSE FEES ARE GREATER THAN 30000 AND SORT THEM BY FEES IN DESCENDING ORDER.
30. DISPLAY CUSTOMERS FROM CHENNAI AND SORT THEM BY CUSTOMER NAME.*/

SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT' ORDER BY SALARY ASC;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT' ORDER BY SALARY DESC;
SELECT * FROM STUDENTS WHERE DEPARTMENT = 'CSE' ORDER BY AGE DESC;
SELECT * FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS' ORDER BY PRICE ASC;
SELECT * FROM BOOKS WHERE BOOK_PRICE > 500 ORDER BY BOOK_PRICE DESC;
SELECT * FROM EMPLOYEES WHERE SALARY > 40000 ORDER BY SALARY ASC;
SELECT * FROM STUDENTS WHERE AGE > 20 ORDER BY NAME ASC;
SELECT * FROM PRODUCTS WHERE STOCK_QUANTITY < 10 ORDER BY STOCK_QUANTITY ASC;
SELECT * FROM COURSES WHERE FEES > 30000 ORDER BY FEES DESC;
SELECT * FROM CUSTOMERS WHERE CITY = 'CHENNAI' ORDER BY CUSTOMER_NAME ASC;

/* C. ORDER BY WITH MULTIPLE COLUMNS

31. DISPLAY EMPLOYEES SORTED FIRST BY DEPARTMENT ASCENDING AND THEN BY SALARY DESCENDING.
32. DISPLAY STUDENTS SORTED FIRST BY DEPARTMENT ASCENDING AND THEN BY AGE DESCENDING.
33. DISPLAY PRODUCTS SORTED FIRST BY CATEGORY ASCENDING AND THEN BY PRICE DESCENDING.
34. DISPLAY BOOKS SORTED FIRST BY CATEGORY ASCENDING AND THEN BY PRICE ASCENDING.
35. DISPLAY EMPLOYEES SORTED FIRST BY DESIGNATION ASCENDING AND THEN BY SALARY DESCENDING.
36. DISPLAY STUDENTS SORTED FIRST BY GENDER ASCENDING AND THEN BY MARKS DESCENDING.
37. DISPLAY CUSTOMERS SORTED FIRST BY CITY ASCENDING AND THEN BY CUSTOMER NAME ASCENDING.
38. DISPLAY PRODUCTS SORTED FIRST BY BRAND ASCENDING AND THEN BY PRICE DESCENDING.
39. DISPLAY COURSES SORTED FIRST BY DEPARTMENT ASCENDING AND THEN BY FEES DESCENDING.
40. DISPLAY PATIENTS SORTED FIRST BY BLOOD GROUP ASCENDING AND THEN BY AGE DESCENDING. */

SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT ASC, SALARY DESC;
SELECT * FROM STUDENTS ORDER BY DEPARTMENT ASC, AGE DESC;
SELECT * FROM PRODUCTS ORDER BY CATEGORY ASC, PRICE DESC;
SELECT * FROM BOOKS ORDER BY CATEGORY ASC, PRICE ASC;
SELECT * FROM EMPLOYEES ORDER BY DESIGNATION ASC, SALARY DESC;
SELECT * FROM STUDENTS ORDER BY GENDER ASC, MARKS DESC;
SELECT * FROM CUSTOMERS ORDER BY CITY ASC, CUSTOMER_NAME ASC;
SELECT * FROM PRODUCTS ORDER BY BRAND ASC, PRICE DESC;
SELECT * FROM COURSES ORDER BY DEPARTMENT ASC, FEES DESC;
SELECT * FROM PATIENTS ORDER BY BLOOD_GROUP ASC, AGE DESC;

/* D. ORDER BY WITH EXPRESSIONS

41. DISPLAY EMPLOYEES AND SORT THEM BY ANNUAL SALARY IN DESCENDING ORDER.
42. DISPLAY PRODUCTS AND SORT THEM BY TOTAL VALUE (PRICE × QUANTITY) IN DESCENDING ORDER.
43. DISPLAY EMPLOYEES AND SORT THEM BY SALARY AFTER A 10% INCREMENT.
44. DISPLAY PRODUCTS AND SORT THEM BY PRICE AFTER A 10% DISCOUNT.
45. DISPLAY STUDENTS AND SORT THEM BY NAME LENGTH IN DESCENDING ORDER.
46. DISPLAY EMPLOYEES AND SORT THEM BY ANNUAL SALARY IN ASCENDING ORDER.
47. DISPLAY PRODUCTS AND SORT THEM BY STOCK VALUE (PRICE × QUANTITY) IN DESCENDING ORDER.
48. DISPLAY BOOKS AND SORT THEM BY PRICE AFTER A 20% DISCOUNT.
49. DISPLAY COURSES AND SORT THEM BY FEES AFTER A 15% DISCOUNT.
50. DISPLAY STUDENTS AND SORT THEM BY AGE + 1 IN ASCENDING ORDER. */

SELECT * FROM EMPLOYEES ORDER BY SALARY * 12 DESC;
SELECT * FROM PRODUCTS ORDER BY PRICE * QUANTITY DESC;
SELECT * FROM EMPLOYEES ORDER BY SALARY * 1.10 ASC;
SELECT * FROM PRODUCTS ORDER BY PRICE * 0.90 ASC;
SELECT * FROM STUDENTS ORDER BY LENGTH(NAME) DESC;
SELECT * FROM EMPLOYEES ORDER BY SALARY * 12 ASC;
SELECT * FROM PRODUCTS ORDER BY PRICE * QUANTITY DESC;
SELECT * FROM BOOKS ORDER BY PRICE * 0.80 ASC;
SELECT * FROM COURSES ORDER BY FEES * 0.85 ASC;
SELECT * FROM STUDENTS ORDER BY AGE + 1 ASC;

/* E. ORDER BY WITH ALIAS

51. DISPLAY EMPLOYEE SALARY × 12 WITH THE ALIAS ANNUAL_SALARY AND SORT BY ANNUAL_SALARY DESCENDING.
52. DISPLAY PRODUCT PRICE × QUANTITY WITH THE ALIAS TOTAL_VALUE AND SORT BY TOTAL_VALUE DESCENDING.
53. DISPLAY STUDENT NAME LENGTH WITH THE ALIAS NAME_LENGTH AND SORT BY NAME_LENGTH ASCENDING.
54. DISPLAY EMPLOYEE SALARY AFTER A 10% INCREMENT WITH THE ALIAS INCREMENTED_SALARY AND SORT BY IT DESCENDING.
55. DISPLAY PRODUCT PRICE AFTER DISCOUNT WITH THE ALIAS DISCOUNTED_PRICE AND SORT BY IT ASCENDING.
56. DISPLAY COURSE FEES AFTER DISCOUNT WITH THE ALIAS FINAL_FEES AND SORT BY IT DESCENDING.
57. DISPLAY STUDENT AGE CATEGORY USING CASE WITH THE ALIAS AGE_CATEGORY AND SORT BY THE ALIAS.
58. DISPLAY EMPLOYEE SALARY CATEGORY USING CASE WITH THE ALIAS SALARY_CATEGORY AND SORT BY IT.
59. DISPLAY PRODUCT STOCK STATUS USING CASE WITH THE ALIAS STOCK_STATUS AND SORT BY IT.
60. DISPLAY MOVIE RATING CATEGORY USING CASE WITH THE ALIAS RATING_CATEGORY AND SORT BY IT. */

SELECT NAME, SALARY * 12 AS ANNUAL_SALARY FROM EMPLOYEES ORDER BY ANNUAL_SALARY DESC;
SELECT PRODUCT_NAME, PRICE * QUANTITY AS TOTAL_VALUE FROM PRODUCTS ORDER BY TOTAL_VALUE DESC;
SELECT NAME, LENGTH(NAME) AS NAME_LENGTH FROM STUDENTS ORDER BY NAME_LENGTH ASC;
SELECT NAME, SALARY * 1.10 AS INCREMENTED_SALARY FROM EMPLOYEES ORDER BY INCREMENTED_SALARY DESC;
SELECT PRODUCT_NAME, PRICE * 0.90 AS DISCOUNTED_PRICE FROM PRODUCTS ORDER BY DISCOUNTED_PRICE ASC;
SELECT COURSE_NAME, FEES * 0.85 AS FINAL_FEES FROM COURSES ORDER BY FINAL_FEES DESC;
SELECT NAME, CASE WHEN AGE < 18 THEN 'MINOR' ELSE 'ADULT' END AS AGE_CATEGORY FROM STUDENTS ORDER BY AGE_CATEGORY;
SELECT NAME, CASE WHEN SALARY >= 50000 THEN 'HIGH' ELSE 'LOW' END AS SALARY_CATEGORY FROM EMPLOYEES ORDER BY SALARY_CATEGORY;
SELECT PRODUCT_NAME, CASE WHEN STOCK_QUANTITY > 0 THEN 'IN STOCK' ELSE 'OUT OF STOCK' END AS STOCK_STATUS FROM PRODUCTS ORDER BY STOCK_STATUS;
SELECT MOVIE_NAME, CASE WHEN RATING >= 4 THEN 'GOOD' ELSE 'AVERAGE' END AS RATING_CATEGORY FROM MOVIES ORDER BY RATING_CATEGORY;

/* F. ORDER BY WITH AGGREGATE FUNCTIONS

61. DISPLAY THE TOTAL NUMBER OF EMPLOYEES IN EACH DEPARTMENT AND SORT BY EMPLOYEE COUNT IN DESCENDING ORDER.
62. DISPLAY THE TOTAL NUMBER OF STUDENTS IN EACH DEPARTMENT AND SORT BY COUNT IN ASCENDING ORDER.
63. DISPLAY THE AVERAGE SALARY OF EACH DEPARTMENT AND SORT BY AVERAGE SALARY IN DESCENDING ORDER.
64. DISPLAY THE MINIMUM SALARY OF EACH DEPARTMENT AND SORT BY MINIMUM SALARY ASCENDING.
65. DISPLAY THE MAXIMUM SALARY OF EACH DEPARTMENT AND SORT BY MAXIMUM SALARY DESCENDING.
66. DISPLAY THE TOTAL SALARY OF EACH DEPARTMENT AND SORT BY TOTAL SALARY DESCENDING.
67. DISPLAY THE AVERAGE PRODUCT PRICE FOR EACH CATEGORY AND SORT BY AVERAGE PRICE DESCENDING.
68. DISPLAY THE MAXIMUM PRODUCT PRICE FOR EACH CATEGORY AND SORT BY MAXIMUM PRICE DESCENDING.
69. DISPLAY THE MINIMUM PRODUCT PRICE FOR EACH CATEGORY AND SORT BY MINIMUM PRICE ASCENDING.
70. DISPLAY THE TOTAL STOCK FOR EACH PRODUCT CATEGORY AND SORT BY TOTAL STOCK DESCENDING. */

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT FROM EMPLOYEES GROUP BY DEPARTMENT ORDER BY EMPLOYEE_COUNT DESC;
SELECT DEPARTMENT, COUNT(*) AS STUDENT_COUNT FROM STUDENTS GROUP BY DEPARTMENT ORDER BY STUDENT_COUNT ASC;
SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT ORDER BY AVG_SALARY DESC;
SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT ORDER BY MIN_SALARY ASC;
SELECT DEPARTMENT, MAX(SALARY) AS MAX_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT ORDER BY MAX_SALARY DESC;
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT ORDER BY TOTAL_SALARY DESC;
SELECT CATEGORY, AVG(PRICE) AS AVG_PRICE FROM PRODUCTS GROUP BY CATEGORY ORDER BY AVG_PRICE DESC;
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM PRODUCTS GROUP BY CATEGORY ORDER BY MAX_PRICE DESC;
SELECT CATEGORY, MIN(PRICE) AS MIN_PRICE FROM PRODUCTS GROUP BY CATEGORY ORDER BY MIN_PRICE ASC;
SELECT CATEGORY, SUM(STOCK_QUANTITY) AS TOTAL_STOCK FROM PRODUCTS GROUP BY CATEGORY ORDER BY TOTAL_STOCK DESC;

/* G. ADVANCED PRACTICE

71. DISPLAY THE TOP 5 HIGHEST-PAID EMPLOYEES.
72. DISPLAY THE 5 LOWEST-PRICED PRODUCTS.
73. DISPLAY THE 3 MOST EXPENSIVE BOOKS.
74. DISPLAY THE 10 STUDENTS WITH THE HIGHEST MARKS.
75. DISPLAY THE 5 EMPLOYEES WITH THE LONGEST EXPERIENCE.
76. DISPLAY THE TOP 5 PRODUCTS BASED ON TOTAL STOCK VALUE.
77. DISPLAY THE 3 COURSES WITH THE HIGHEST FEES.
78. DISPLAY THE 5 HIGHEST-RATED MOVIES.
79. DISPLAY THE 10 MOST RECENTLY JOINED EMPLOYEES.
80. DISPLAY THE 5 CUSTOMERS WHO REGISTERED MOST RECENTLY. */

SELECT * FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 5;
SELECT * FROM PRODUCTS ORDER BY PRICE ASC LIMIT 5;
SELECT * FROM BOOKS ORDER BY PRICE DESC LIMIT 3;
SELECT * FROM STUDENTS ORDER BY MARKS DESC LIMIT 10;
SELECT * FROM EMPLOYEES ORDER BY EXPERIENCE DESC LIMIT 5;
SELECT * FROM PRODUCTS ORDER BY PRICE * STOCK_QUANTITY DESC LIMIT 5;
SELECT * FROM COURSES ORDER BY FEES DESC LIMIT 3;
SELECT * FROM MOVIES ORDER BY RATING DESC LIMIT 5;
SELECT * FROM EMPLOYEES ORDER BY JOINING_DATE DESC LIMIT 10;
SELECT * FROM CUSTOMERS ORDER BY REGISTRATION_DATE DESC LIMIT 5;
