#Date: 28th August 2026
#Topics Covered:

/* SQL JOINS

TOPICS COVERED
- INNER JOIN
- LEFT JOIN
- RIGHT JOIN
- FULL OUTER JOIN
- CROSS JOIN
- SELF JOIN

BASIC CONCEPT
A JOIN IS USED TO COMBINE DATA FROM TWO OR MORE TABLES BASED ON A RELATED COLUMN.

FOR PRACTICE, ASSUME THESE TABLES:

STUDENTS

STUDENTID
STUDENTNAME
DEPARTMENTID
COURSEID

DEPARTMENTS

DEPARTMENTID
DEPARTMENTNAME

COURSES

COURSEID
COURSENAME
FEES

EMPLOYEES

EMPLOYEEID
EMPLOYEENAME
MANAGERID
DEPARTMENTID

ORDERS

ORDERID
CUSTOMERID
PRODUCTID
QUANTITY

CUSTOMERS

CUSTOMERID
CUSTOMERNAME
CITY

PRODUCTS

PRODUCTID
PRODUCTNAME
PRICE

!!!!!!!!!A. INNER JOIN – 20 QUESTIONS

RETURNS ONLY THE ROWS THAT HAVE MATCHING VALUES IN BOTH TABLES.

1. DISPLAY STUDENT NAMES ALONG WITH THEIR DEPARTMENT NAMES USING INNER JOIN.
2. DISPLAY STUDENTID, STUDENTNAME, AND DEPARTMENTNAME.
3. DISPLAY STUDENTS ALONG WITH THEIR COURSE NAMES.
4. DISPLAY STUDENT NAMES, DEPARTMENT NAMES, AND COURSE NAMES.
5. DISPLAY EMPLOYEES ALONG WITH THEIR DEPARTMENT NAMES.
6. DISPLAY EMPLOYEE NAMES AND DEPARTMENT NAMES FOR EMPLOYEES BELONGING TO AN EXISTING DEPARTMENT.
7. DISPLAY CUSTOMERS ALONG WITH THEIR ORDER IDS.
8. DISPLAY CUSTOMER NAMES AND ORDER QUANTITIES.
9. DISPLAY ORDERS ALONG WITH PRODUCT NAMES.
10. DISPLAY ORDER ID, PRODUCT NAME, AND QUANTITY.
11. DISPLAY CUSTOMERS ALONG WITH THE PRODUCTS THEY ORDERED.
12. DISPLAY CUSTOMER NAME, PRODUCT NAME, AND QUANTITY.
13. DISPLAY PRODUCTS ALONG WITH THEIR ORDER DETAILS.
14. DISPLAY EMPLOYEES ALONG WITH THEIR DEPARTMENT NAMES AND SALARIES.
15. DISPLAY STUDENTS ALONG WITH THEIR COURSE NAME AND COURSE FEES.
16. DISPLAY EMPLOYEES WORKING IN THE IT DEPARTMENT USING INNER JOIN.
17. DISPLAY STUDENTS ENROLLED IN COURSES WHOSE FEES ARE GREATER THAN 30000.
18. DISPLAY CUSTOMERS WHO HAVE PLACED AN ORDER.
19. DISPLAY PRODUCTS THAT HAVE BEEN ORDERED.
20. DISPLAY CUSTOMER NAME, PRODUCT NAME, QUANTITY, AND PRODUCT PRICE.

EXAMPLE

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID; */

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTID, S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
INNER JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME, C.COURSENAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID
INNER JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT C.CUSTOMERNAME, O.QUANTITY
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.ORDERID, P.PRODUCTNAME
FROM ORDERS O
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT O.ORDERID, P.PRODUCTNAME, O.QUANTITY
FROM ORDERS O
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME, O.QUANTITY
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM PRODUCTS P
INNER JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME, E.SALARY
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME, C.FEES
FROM STUDENTS S
INNER JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'IT';

SELECT S.STUDENTNAME, C.COURSENAME, C.FEES
FROM STUDENTS S
INNER JOIN COURSES C
ON S.COURSEID = C.COURSEID
WHERE C.FEES > 30000;

SELECT DISTINCT C.CUSTOMERNAME
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT DISTINCT P.PRODUCTNAME
FROM PRODUCTS P
INNER JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME, O.QUANTITY, P.PRICE
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;


/* !!!!!!! B. LEFT JOIN – 20 QUESTIONS

RETURNS ALL ROWS FROM THE LEFT TABLE, EVEN WHEN THERE IS NO MATCHING ROW IN THE RIGHT TABLE.

21. DISPLAY ALL STUDENTS ALONG WITH THEIR DEPARTMENT NAMES.
22. DISPLAY ALL DEPARTMENTS ALONG WITH THEIR STUDENTS.
23. DISPLAY ALL STUDENTS, INCLUDING STUDENTS WHO ARE NOT ASSIGNED TO A DEPARTMENT.
24. DISPLAY ALL STUDENTS ALONG WITH THEIR COURSE NAMES.
25. DISPLAY ALL COURSES, INCLUDING COURSES WITH NO STUDENTS ENROLLED.
26. DISPLAY ALL EMPLOYEES ALONG WITH THEIR DEPARTMENT NAMES.
27. DISPLAY ALL DEPARTMENTS ALONG WITH THEIR EMPLOYEES.
28. DISPLAY ALL CUSTOMERS ALONG WITH THEIR ORDERS.
29. DISPLAY ALL CUSTOMERS, INCLUDING CUSTOMERS WHO HAVE NEVER PLACED AN ORDER.
30. DISPLAY ALL ORDERS ALONG WITH CUSTOMER NAMES.
31. DISPLAY ALL PRODUCTS ALONG WITH THEIR ORDER DETAILS.
32. DISPLAY ALL PRODUCTS, INCLUDING PRODUCTS THAT HAVE NEVER BEEN ORDERED.
33. DISPLAY ALL CUSTOMERS AND THE TOTAL NUMBER OF ORDERS PLACED BY EACH CUSTOMER.
34. DISPLAY ALL DEPARTMENTS AND THE NUMBER OF EMPLOYEES IN EACH DEPARTMENT.
35. DISPLAY ALL COURSES AND THE NUMBER OF STUDENTS ENROLLED IN EACH COURSE.
36. DISPLAY ALL PRODUCTS AND THE TOTAL QUANTITY ORDERED FOR EACH PRODUCT.
37. DISPLAY ALL EMPLOYEES AND THEIR DEPARTMENT NAMES, REPLACING MISSING DEPARTMENTS WITH 'NOT ASSIGNED'.
38. DISPLAY ALL CUSTOMERS AND THEIR ORDER IDS, SHOWING NULL FOR CUSTOMERS WITHOUT ORDERS.
39. DISPLAY ALL PRODUCTS AND THEIR ORDER QUANTITIES, INCLUDING PRODUCTS WITH NO ORDERS.
40. DISPLAY ALL DEPARTMENTS AND THEIR EMPLOYEES, INCLUDING DEPARTMENTS WITH NO EMPLOYEES. */

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT D.DEPARTMENTNAME, S.STUDENTNAME
FROM DEPARTMENTS D
LEFT JOIN STUDENTS S
ON D.DEPARTMENTID = S.DEPARTMENTID;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
LEFT JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.ORDERID, C.CUSTOMERNAME
FROM ORDERS O
LEFT JOIN CUSTOMERS C
ON O.CUSTOMERID = C.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.CUSTOMERNAME, COUNT(O.ORDERID) AS TOTAL_ORDERS
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERNAME;

SELECT D.DEPARTMENTNAME, COUNT(E.EMPLOYEEID) AS EMPLOYEE_COUNT
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

SELECT C.COURSENAME, COUNT(S.STUDENTID) AS STUDENT_COUNT
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
GROUP BY C.COURSENAME;

SELECT P.PRODUCTNAME, SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
GROUP BY P.PRODUCTNAME;

SELECT E.EMPLOYEENAME,
COALESCE(D.DEPARTMENTNAME, 'NOT ASSIGNED') AS DEPARTMENTNAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.QUANTITY
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

/* !!!!!!!C. RIGHT JOIN – 15 QUESTIONS

RETURNS ALL ROWS FROM THE RIGHT TABLE, EVEN WHEN THERE IS NO MATCHING ROW IN THE LEFT TABLE.

41. DISPLAY ALL DEPARTMENTS ALONG WITH THEIR EMPLOYEES USING RIGHT JOIN.
42. DISPLAY ALL EMPLOYEES ALONG WITH THEIR DEPARTMENTS USING RIGHT JOIN.
43. DISPLAY ALL COURSES ALONG WITH ENROLLED STUDENTS.
44. DISPLAY ALL STUDENTS ALONG WITH THEIR COURSES.
45. DISPLAY ALL CUSTOMERS ALONG WITH THEIR ORDERS.
46. DISPLAY ALL ORDERS ALONG WITH CUSTOMERS.
47. DISPLAY ALL PRODUCTS ALONG WITH THEIR ORDER DETAILS.
48. DISPLAY ALL ORDERS ALONG WITH PRODUCTS.
49. DISPLAY ALL DEPARTMENTS, INCLUDING DEPARTMENTS WITH NO EMPLOYEES.
50. DISPLAY ALL COURSES, INCLUDING COURSES WITH NO ENROLLED STUDENTS.
51. DISPLAY ALL PRODUCTS, INCLUDING PRODUCTS THAT HAVE NEVER BEEN ORDERED.
52. DISPLAY ALL CUSTOMERS, INCLUDING CUSTOMERS WHO HAVE NO ORDERS.
53. DISPLAY ALL DEPARTMENTS AND EMPLOYEE COUNTS.
54. DISPLAY ALL COURSES AND THE NUMBER OF ENROLLED STUDENTS.
55. DISPLAY ALL PRODUCTS AND TOTAL ORDERED QUANTITY.

EXAMPLE

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID; */

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM STUDENTS S
RIGHT JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
RIGHT JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.ORDERID, C.CUSTOMERNAME
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT O.ORDERID, P.PRODUCTNAME
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM STUDENTS S
RIGHT JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT D.DEPARTMENTNAME, COUNT(E.EMPLOYEEID) AS EMPLOYEE_COUNT
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

SELECT C.COURSENAME, COUNT(S.STUDENTID) AS STUDENT_COUNT
FROM STUDENTS S
RIGHT JOIN COURSES C
ON S.COURSEID = C.COURSEID
GROUP BY C.COURSENAME;

SELECT P.PRODUCTNAME, SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
GROUP BY P.PRODUCTNAME;

/*!!!!!!! D. FULL OUTER JOIN – 15 QUESTIONS

RETURNS ALL MATCHING AND NON-MATCHING ROWS FROM BOTH TABLES.

MYSQL DOES NOT DIRECTLY SUPPORT FULL OUTER JOIN.
IN MYSQL, IT CAN BE SIMULATED USING LEFT JOIN + RIGHT JOIN + UNION.

56. DISPLAY ALL STUDENTS AND DEPARTMENTS, INCLUDING UNMATCHED RECORDS.
57. DISPLAY ALL EMPLOYEES AND DEPARTMENTS, INCLUDING EMPLOYEES WITHOUT DEPARTMENTS AND DEPARTMENTS WITHOUT EMPLOYEES.
58. DISPLAY ALL CUSTOMERS AND ORDERS, INCLUDING CUSTOMERS WITHOUT ORDERS AND ORDERS WITHOUT CUSTOMERS.
59. DISPLAY ALL PRODUCTS AND ORDERS, INCLUDING PRODUCTS WITHOUT ORDERS AND ORDERS WITHOUT PRODUCTS.
60. DISPLAY ALL COURSES AND STUDENTS, INCLUDING COURSES WITHOUT STUDENTS AND STUDENTS WITHOUT COURSES.
61. DISPLAY ALL DEPARTMENTS AND EMPLOYEES USING A SIMULATED FULL OUTER JOIN.
62. DISPLAY ALL CUSTOMERS AND ORDERS USING LEFT JOIN, RIGHT JOIN, AND UNION.
63. DISPLAY ALL PRODUCTS AND ORDERS USING A SIMULATED FULL OUTER JOIN.
64. DISPLAY ALL COURSES AND STUDENTS USING A SIMULATED FULL OUTER JOIN.
65. DISPLAY ALL DEPARTMENTS AND EMPLOYEES, SHOWING UNMATCHED RECORDS FROM BOTH TABLES.
66. FIND DEPARTMENTS THAT HAVE NO EMPLOYEES AND EMPLOYEES THAT HAVE NO DEPARTMENTS.
67. FIND CUSTOMERS WITHOUT ORDERS AND ORDERS WITHOUT CUSTOMERS.
68. FIND PRODUCTS WITHOUT ORDERS AND ORDERS WITHOUT PRODUCTS.
69. FIND COURSES WITHOUT STUDENTS AND STUDENTS WITHOUT COURSES.
70. DISPLAY ALL MATCHING AND NON-MATCHING RECORDS BETWEEN STUDENTS AND DEPARTMENTS.

MYSQL EXAMPLE

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID
UNION

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
RIGHT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID; */

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID

UNION

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
RIGHT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID

UNION

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID

UNION

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID

UNION

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID

UNION

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
RIGHT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID

UNION

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
RIGHT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID

UNION

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID

UNION

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID

UNION

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
RIGHT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE E.EMPLOYEEID IS NULL

UNION

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
RIGHT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE D.DEPARTMENTID IS NULL;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
WHERE O.ORDERID IS NULL

UNION

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
WHERE C.CUSTOMERID IS NULL;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
WHERE O.ORDERID IS NULL

UNION

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
WHERE P.PRODUCTID IS NULL;

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
WHERE S.STUDENTID IS NULL

UNION

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
RIGHT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
WHERE C.COURSEID IS NULL;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID

UNION

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
RIGHT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;


/* !!!!!!! E. CROSS JOIN – 15 QUESTIONS

CROSS JOIN PRODUCES A CARTESIAN PRODUCT.

IF TABLE A HAS 5 ROWS AND TABLE B HAS 4 ROWS:

5 × 4 = 20 ROWS

71. DISPLAY EVERY STUDENT WITH EVERY COURSE.
72. DISPLAY EVERY EMPLOYEE WITH EVERY DEPARTMENT.
73. DISPLAY EVERY PRODUCT WITH EVERY CUSTOMER.
74. DISPLAY EVERY CUSTOMER WITH EVERY PRODUCT.
75. DISPLAY EVERY COURSE WITH EVERY DEPARTMENT.
76. DISPLAY EVERY EMPLOYEE WITH EVERY COURSE.
77. DISPLAY EVERY STUDENT WITH EVERY DEPARTMENT.
78. DISPLAY EVERY PRODUCT WITH EVERY COURSE.
79. DISPLAY EVERY CUSTOMER WITH EVERY COURSE.
80. GENERATE ALL POSSIBLE COMBINATIONS OF EMPLOYEES AND DEPARTMENTS.
81. GENERATE ALL POSSIBLE COMBINATIONS OF PRODUCTS AND CUSTOMERS.
82. GENERATE ALL POSSIBLE COMBINATIONS OF STUDENTS AND COURSES.
83. DISPLAY EMPLOYEE NAMES AND ALL AVAILABLE DEPARTMENTS.
84. DISPLAY PRODUCT NAMES AND ALL AVAILABLE COURSES.
85. DISPLAY CUSTOMER NAMES AND ALL AVAILABLE PRODUCTS.

EXAMPLE

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
CROSS JOIN COURSES C;

NO ON CONDITION IS REQUIRED. */

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
CROSS JOIN COURSES C;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.CUSTOMERNAME
FROM PRODUCTS P
CROSS JOIN CUSTOMERS C;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM CUSTOMERS C
CROSS JOIN PRODUCTS P;

SELECT C.COURSENAME, D.DEPARTMENTNAME
FROM COURSES C
CROSS JOIN DEPARTMENTS D;

SELECT E.EMPLOYEENAME, C.COURSENAME
FROM EMPLOYEES E
CROSS JOIN COURSES C;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
CROSS JOIN DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.COURSENAME
FROM PRODUCTS P
CROSS JOIN COURSES C;

SELECT C.CUSTOMERNAME, CO.COURSENAME
FROM CUSTOMERS C
CROSS JOIN COURSES CO;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.CUSTOMERNAME
FROM PRODUCTS P
CROSS JOIN CUSTOMERS C;

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
CROSS JOIN COURSES C;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.COURSENAME
FROM PRODUCTS P
CROSS JOIN COURSES C;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM CUSTOMERS C
CROSS JOIN PRODUCTS P;

/*!!!!!! F. SELF JOIN – 15 QUESTIONS

A SELF JOIN JOINS A TABLE WITH ITSELF.

A COMMON EXAMPLE IS AN EMPLOYEE-MANAGER RELATIONSHIP.

EMPLOYEES

EMPLOYEEID
EMPLOYEENAME
MANAGERID

HERE MANAGERID REFERS TO ANOTHER EMPLOYEEID IN THE SAME TABLE.

86. DISPLAY EACH EMPLOYEE ALONG WITH THEIR MANAGER NAME.
87. DISPLAY EMPLOYEE NAME AND MANAGER NAME USING SELF JOIN.
88. DISPLAY EMPLOYEES WHO HAVE A MANAGER.
89. DISPLAY EMPLOYEES WHO DO NOT HAVE A MANAGER.
90. DISPLAY EMPLOYEE ID, EMPLOYEE NAME, MANAGER ID, AND MANAGER NAME.
91. DISPLAY ALL EMPLOYEES AND THEIR RESPECTIVE MANAGERS.
92. DISPLAY EMPLOYEES WHOSE MANAGER BELONGS TO THE IT DEPARTMENT.
93. DISPLAY EMPLOYEES WHOSE MANAGER'S SALARY IS GREATER THAN 70000.
94. DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN THEIR MANAGER'S SALARY.
95. DISPLAY EMPLOYEES WHOSE SALARY IS LESS THAN THEIR MANAGER'S SALARY.
96. DISPLAY EMPLOYEE AND MANAGER NAMES ALONG WITH THEIR RESPECTIVE SALARIES.
97. DISPLAY EMPLOYEES WHO REPORT TO THE SAME MANAGER.
98. DISPLAY EMPLOYEES AND THEIR MANAGERS, SORTED BY MANAGER NAME.
99. DISPLAY EMPLOYEES WHOSE MANAGER IS ALSO AN EMPLOYEE IN THE SAME DEPARTMENT.
100. DISPLAY THE EMPLOYEE-MANAGER HIERARCHY USING A SELF JOIN.

QUICK JOIN REFERENCE

INNER JOIN = MATCHING ROWS FROM BOTH TABLES
LEFT JOIN = ALL LEFT ROWS + MATCHING RIGHT ROWS
RIGHT JOIN = ALL RIGHT ROWS + MATCHING LEFT ROWS
FULL OUTER JOIN = ALL ROWS FROM BOTH TABLES
CROSS JOIN = EVERY POSSIBLE COMBINATION
SELF JOIN = A TABLE JOINED WITH ITSELF */

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.MANAGERID IS NULL;

SELECT E.EMPLOYEEID, E.EMPLOYEENAME, E.MANAGERID, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE M.DEPARTMENTID = (
    SELECT DEPARTMENTID
    FROM DEPARTMENTS
    WHERE DEPARTMENTNAME = 'IT'
);

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE M.SALARY > 70000;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.SALARY > M.SALARY;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.SALARY < M.SALARY;

SELECT E.EMPLOYEENAME, E.SALARY, M.EMPLOYEENAME AS MANAGERNAME, M.SALARY AS MANAGERSALARY
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E1.EMPLOYEENAME, E2.EMPLOYEENAME AS COLLEAGUE
FROM EMPLOYEES E1
INNER JOIN EMPLOYEES E2
ON E1.MANAGERID = E2.MANAGERID
AND E1.EMPLOYEEID <> E2.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
ORDER BY M.EMPLOYEENAME;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.DEPARTMENTID = M.DEPARTMENTID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;
