#Date: 1st September 2026
#Date Covered: 31st August 2026
#Topics Covered:

/* SQL TRANSACTION CONTROL

A. AUTOCOMMIT

1. CREATE A TABLE NAMED EMPLOYEES WITH EMPLOYEEID, EMPLOYEENAME, DEPARTMENT, AND SALARY. INSERT ONE RECORD AND VERIFY WHETHER THE RECORD
IS AUTOMATICALLY COMMITTED.
2. CHECK THE CURRENT AUTOCOMMIT SETTING IN MYSQL.
3. DISABLE AUTOCOMMIT AND INSERT A NEW EMPLOYEE RECORD. VERIFY THE RECORD BEFORE AND AFTER CLOSING/REOPENING THE TRANSACTION.
4. WITH AUTOCOMMIT DISABLED, INSERT THREE EMPLOYEE RECORDS AND VERIFY THAT ALL THREE RECORDS ARE PART OF THE SAME TRANSACTION.
5. ENABLE AUTOCOMMIT AGAIN AND INSERT A NEW EMPLOYEE RECORD. VERIFY WHETHER THE CHANGE IS COMMITTED AUTOMATICALLY. */ 

CREATE TABLE EMPLOYEES (
EMPLOYEEID INT PRIMARY KEY,
EMPLOYEENAME VARCHAR(100),
DEPARTMENT VARCHAR(100),
SALARY DECIMAL(10,2)
);

INSERT INTO EMPLOYEES
VALUES (1,'JOHN','HR',50000);

SELECT * FROM EMPLOYEES;

SELECT @@AUTOCOMMIT;

SET AUTOCOMMIT = 0;

INSERT INTO EMPLOYEES
VALUES (2,'SMITH','IT',60000);

SELECT * FROM EMPLOYEES;

COMMIT;

SELECT * FROM EMPLOYEES;

SET AUTOCOMMIT = 0;

INSERT INTO EMPLOYEES
VALUES (3,'DAVID','SALES',55000);

INSERT INTO EMPLOYEES
VALUES (4,'MARY','FINANCE',65000);

INSERT INTO EMPLOYEES
VALUES (5,'JAMES','IT',70000);

SELECT * FROM EMPLOYEES;

COMMIT;

SET AUTOCOMMIT = 1;

INSERT INTO EMPLOYEES
VALUES (6,'LINDA','HR',58000);

SELECT * FROM EMPLOYEES;

/* B. COMMIT

6. DISABLE AUTOCOMMIT, INSERT FIVE EMPLOYEE RECORDS, AND USE COMMIT TO PERMANENTLY SAVE THE CHANGES.
7. UPDATE THE SALARY OF AN EMPLOYEE, VERIFY THE UPDATED VALUE, AND USE COMMIT TO PERMANENTLY SAVE THE CHANGE.
8. DELETE ONE EMPLOYEE RECORD, VERIFY THE DELETION, AND USE COMMIT TO PERMANENTLY SAVE THE DELETION.
9. PERFORM AN INSERT, UPDATE, AND DELETE WITHIN THE SAME TRANSACTION AND USE A SINGLE COMMIT TO SAVE ALL THREE CHANGES.
10. INSERT TWO NEW PRODUCTS, UPDATE THE PRICE OF AN EXISTING PRODUCT, AND USE COMMIT TO SAVE ALL CHANGES PERMANENTLY. */

SET AUTOCOMMIT = 0;

INSERT INTO EMPLOYEES
VALUES (7,'ALEX','IT',60000);

INSERT INTO EMPLOYEES
VALUES (8,'SARAH','HR',55000);

INSERT INTO EMPLOYEES
VALUES (9,'MIKE','SALES',62000);

INSERT INTO EMPLOYEES
VALUES (10,'EMMA','FINANCE',70000);

INSERT INTO EMPLOYEES
VALUES (11,'DAVID','IT',65000);

COMMIT;

SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES
SET SALARY = 75000
WHERE EMPLOYEEID = 7;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID = 7;

COMMIT;

DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 8;

SELECT * FROM EMPLOYEES;

COMMIT;

INSERT INTO EMPLOYEES
VALUES (12,'JOHN','HR',58000);

UPDATE EMPLOYEES
SET SALARY = 80000
WHERE EMPLOYEEID = 9;

DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 10;

COMMIT;

SELECT * FROM EMPLOYEES;

INSERT INTO PRODUCTS
VALUES (101,'LAPTOP',50000);

INSERT INTO PRODUCTS
VALUES (102,'MOUSE',1000);

UPDATE PRODUCTS
SET PRICE = 55000
WHERE PRODUCTID = 101;

COMMIT;

SELECT * FROM PRODUCTS;

/* C. ROLLBACK

11. DISABLE AUTOCOMMIT, INSERT THREE EMPLOYEE RECORDS, AND USE ROLLBACK. VERIFY WHETHER THE INSERTED RECORDS STILL EXIST.
12. UPDATE THE SALARY OF AN EMPLOYEE AND USE ROLLBACK BEFORE COMMITTING. VERIFY THAT THE ORIGINAL SALARY IS RESTORED.
13. DELETE TWO EMPLOYEE RECORDS AND USE ROLLBACK. VERIFY WHETHER THE DELETED RECORDS ARE RESTORED.
14. PERFORM AN INSERT, UPDATE, AND DELETE IN ONE TRANSACTION. USE ROLLBACK AND VERIFY THE STATE OF THE TABLE.
15. PERFORM THE FOLLOWING TRANSACTION:

• DISABLE AUTOCOMMIT
• INSERT TWO RECORDS
• UPDATE ONE EXISTING RECORD
• DELETE ONE RECORD

• VERIFY ALL CHANGES
• USE ROLLBACK
• VERIFY THE TABLE AGAIN
• REPEAT THE SAME OPERATIONS
• USE COMMIT
• VERIFY THE FINAL TABLE DATA */

SET AUTOCOMMIT = 0;

INSERT INTO EMPLOYEES
VALUES (13,'ROBERT','IT',65000);

INSERT INTO EMPLOYEES
VALUES (14,'ANNA','HR',55000);

INSERT INTO EMPLOYEES
VALUES (15,'PETER','SALES',60000);

ROLLBACK;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID IN (13,14,15);

UPDATE EMPLOYEES
SET SALARY = 90000
WHERE EMPLOYEEID = 7;

ROLLBACK;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID = 7;

DELETE FROM EMPLOYEES
WHERE EMPLOYEEID IN (11,12);

ROLLBACK;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID IN (11,12);

INSERT INTO EMPLOYEES
VALUES (16,'MARK','IT',70000);

UPDATE EMPLOYEES
SET SALARY = 85000
WHERE EMPLOYEEID = 9;

DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 10;

ROLLBACK;

SELECT * FROM EMPLOYEES;

SET AUTOCOMMIT = 0;

INSERT INTO EMPLOYEES
VALUES (17,'KEVIN','HR',62000);

INSERT INTO EMPLOYEES
VALUES (18,'LISA','FINANCE',68000);

UPDATE EMPLOYEES
SET SALARY = 95000
WHERE EMPLOYEEID = 7;

DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 9;

SELECT * FROM EMPLOYEES;

ROLLBACK;

SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES
VALUES (17,'KEVINSMILKSHAKE','HR',62000);

INSERT INTO EMPLOYEES
VALUES (18,'LISAM','FINANCE',68000);

UPDATE EMPLOYEES
SET SALARY = 95000
WHERE EMPLOYEEID = 7;

DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 9;

COMMIT;

SELECT * FROM EMPLOYEES;

