#Date: 1st September 2026
#Date Covered: 31st August 2026
#Topics Covered:

/* STRING FUNCTIONS

1. DISPLAY ALL EMPLOYEE NAMES IN UPPERCASE USING UPPER().
2. DISPLAY ALL EMPLOYEE NAMES IN LOWERCASE USING LOWER().
3. FIND THE LENGTH OF EACH EMPLOYEE'S NAME USING LENGTH().
4. DISPLAY THE FIRST 3 CHARACTERS OF EACH EMPLOYEE NAME USING LEFT().
5. DISPLAY THE LAST 3 CHARACTERS OF EACH EMPLOYEE NAME USING RIGHT().
6. COMBINE EMPLOYEE FIRST NAME AND LAST NAME USING CONCAT() AND GIVE THE RESULT THE ALIAS FULL NAME.
7. REMOVE LEADING AND TRAILING SPACES FROM CUSTOMER NAMES USING TRIM().
8. REPLACE THE WORD 'CHENNAI' WITH 'MADRAS' IN THE CITY COLUMN USING REPLACE(). */

SELECT UPPER(EMPLOYEE_NAME)
FROM EMPLOYEES;

SELECT LOWER(EMPLOYEE_NAME)
FROM EMPLOYEES;

SELECT EMPLOYEE_NAME, LENGTH(EMPLOYEE_NAME)
FROM EMPLOYEES;

SELECT LEFT(EMPLOYEE_NAME, 3)
FROM EMPLOYEES;

SELECT RIGHT(EMPLOYEE_NAME, 3)
FROM EMPLOYEES;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME
FROM EMPLOYEES;

SELECT TRIM(CUSTOMER_NAME)
FROM CUSTOMERS;

SELECT REPLACE(CITY, 'CHENNAI', 'MADRAS')
FROM CUSTOMERS;
