#Date: 1st September 2026
#Date Covered: 31st August 2026
#Topics:


/* NUMERIC FUNCTIONS

1. ROUND THE EMPLOYEE SALARY TO THE NEAREST THOUSAND USING ROUND().
2. DISPLAY THE ABSOLUTE DIFFERENCE BETWEEN AN EMPLOYEE'S SALARY AND 50000 USING ABS().
3. FIND THE CEILING VALUE OF PRODUCT PRICES USING CEIL().
4. FIND THE FLOOR VALUE OF PRODUCT PRICES USING FLOOR().
5. CALCULATE THE REMAINDER WHEN EMPLOYEE SALARY IS DIVIDED BY 10000 USING MOD().
6. CALCULATE THE SQUARE OF EACH STUDENT'S MARKS USING POWER().
7. CALCULATE THE SQUARE ROOT OF PRODUCT PRICES USING SQRT().
8. ROUND PRODUCT PRICES TO 2 DECIMAL PLACES USING ROUND(). */

SELECT ROUND(SALARY, -3) AS ROUNDED_SALARY
FROM EMPLOYEES;

SELECT ABS(SALARY - 50000) AS ABSOLUTE_DIFFERENCE
FROM EMPLOYEES;

SELECT CEIL(PRICE) AS CEILING_PRICE
FROM PRODUCTS;

SELECT FLOOR(PRICE) AS FLOOR_PRICE
FROM PRODUCTS;

SELECT MOD(SALARY, 10000) AS REMAINDER
FROM EMPLOYEES;

SELECT POWER(MARKS, 2) AS SQUARE_OF_MARKS
FROM STUDENTS;

SELECT SQRT(PRICE) AS SQUARE_ROOT_PRICE
FROM PRODUCTS;

SELECT ROUND(PRICE, 2) AS ROUNDED_PRICE
FROM PRODUCTS;
