#Date: 1st September 2026
#Date Covered: 31st August 2026
#Topics Covered:

/* LIMIT & OFFSET

1. DISPLAY THE FIRST 5 EMPLOYEES FROM THE EMPLOYEES TABLE.
2. DISPLAY THE 10 HIGHEST-PAID EMPLOYEES USING ORDER BY AND LIMIT.
3. DISPLAY THE 5 EMPLOYEES WITH THE LOWEST SALARIES.
4. DISPLAY THE FIRST 10 PRODUCTS SORTED BY PRICE IN DESCENDING ORDER.
5. DISPLAY THE NEXT 5 EMPLOYEES AFTER THE FIRST 5 RECORDS USING LIMIT AND OFFSET.
6. DISPLAY RECORDS 11 TO 20 FROM THE STUDENTS TABLE.
7. DISPLAY THE SECOND PAGE OF 10 PRODUCTS, ASSUMING EACH PAGE CONTAINS 10 RECORDS.
8. DISPLAY THE THIRD PAGE OF 5 EMPLOYEES.
9. DISPLAY THE 3 MOST EXPENSIVE PRODUCTS, EXCLUDING THE MOST EXPENSIVE PRODUCT.
10. DISPLAY THE 5TH TO 10TH HIGHEST-PAID EMPLOYEES USING ORDER BY, LIMIT, AND OFFSET. */


SELECT *
FROM Employees
LIMIT 5;


SELECT *
FROM Employees
ORDER BY Salary DESC
LIMIT 10;


SELECT *
FROM Employees
ORDER BY Salary ASC
LIMIT 5;


SELECT *
FROM Products
ORDER BY Price DESC
LIMIT 10;


SELECT *
FROM Employees
LIMIT 5 OFFSET 5; -- records show from 6th to 10th, bcz offset 5 kuduthu irukom


SELECT *
FROM Students
LIMIT 10 OFFSET 10;


SELECT *
FROM Products
LIMIT 10 OFFSET 10;


SELECT *
FROM Employees
LIMIT 5 OFFSET 10;

SELECT *
FROM Products
ORDER BY Price DESC
LIMIT 3 OFFSET 1;

SELECT *
FROM Employees
ORDER BY Salary DESC
LIMIT 6 OFFSET 4;
