#Date: 1st September 2026
#Date Covered: 31st August 2026
#Topics Covered:

/* IMPLICIT & EXPLICIT CONVERSION

1. WRITE A QUERY TO DEMONSTRATE IMPLICIT CONVERSION BY ADDING A NUMERIC VALUE STORED AS A STRING TO AN INTEGER.
2. WRITE A QUERY THAT DEMONSTRATES IMPLICIT CONVERSION BETWEEN A STRING AND A NUMERIC VALUE.
3. CONVERT THE STRING '2026-08-31' INTO A DATE USING AN EXPLICIT CONVERSION FUNCTION.
4. CONVERT THE NUMERIC VALUE 25000 INTO A CHAR/VARCHAR VALUE EXPLICITLY.
5. CONVERT THE STRING '1250.75' INTO A DECIMAL VALUE EXPLICITLY.
6. CONVERT A DATE VALUE INTO A FORMATTED CHARACTER VALUE USING AN APPROPRIATE CONVERSION/DATE-FORMAT FUNCTION.
7. CONVERT THE STRING '2026-08-31 15:30:00' INTO A DATETIME VALUE EXPLICITLY.
8. CREATE EXAMPLES SHOWING THE DIFFERENCE BETWEEN IMPLICIT CONVERSION AND EXPLICIT CONVERSION IN MYSQL. */

SELECT '100' + 50 AS RESULT;
SELECT '200' * 2 AS RESULT;
SELECT STR_TO_DATE('2026-08-31', '%Y-%m-%d') AS CONVERTED_DATE;
SELECT CAST(25000 AS CHAR) AS CHAR_VALUE;
SELECT CAST('1250.75' AS DECIMAL(10,2)) AS DECIMAL_VALUE;
SELECT DATE_FORMAT(CURDATE(), '%d-%m-%Y') AS FORMATTED_DATE;
SELECT CAST('2026-08-31 15:30:00' AS DATETIME) AS DATETIME_VALUE;
SELECT '100' + 50 AS IMPLICIT_CONVERSION;
SELECT CAST('100' AS UNSIGNED) + 50 AS EXPLICIT_CONVERSION;
