#Date: 1st September 2026
#Date Covered: 31st August 2026
#Topics Covered:

/* STATISTICAL / AGGREGATE FUNCTIONS
1. FIND THE TOTAL NUMBER OF EMPLOYEES USING COUNT().
2. FIND THE TOTAL SALARY PAID TO ALL EMPLOYEES USING SUM().
3. FIND THE AVERAGE SALARY OF EMPLOYEES USING AVG().
4. FIND THE HIGHEST SALARY USING MAX().
5. FIND THE LOWEST SALARY USING MIN().
6. FIND THE TOTAL NUMBER OF STUDENTS IN EACH DEPARTMENT.
7. FIND THE AVERAGE MARKS FOR EACH DEPARTMENT.
8. FIND THE HIGHEST MARKS AND LOWEST MARKS FOR EACH DEPARTMENT.
9. FIND THE TOTAL SALES AMOUNT FOR EACH CUSTOMER.
10. FIND THE AVERAGE PRODUCT PRICE FOR EACH PRODUCT CATEGORY. */

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES;

SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES;

SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEES;

SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEES;

SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL_STUDENTS
FROM STUDENTS
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, AVG(MARKS) AS AVERAGE_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, MAX(MARKS) AS HIGHEST_MARKS, MIN(MARKS) AS LOWEST_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT_ID;

SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES
GROUP BY CUSTOMER_ID;

SELECT CATEGORY_ID, AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY_ID;

/* CHALLENGE QUESTIONS

1. DISPLAY THE TOP 5 HIGHEST-PAID EMPLOYEES, SHOWING EMPLOYEE NAME, SALARY, AND ANNUAL SALARY.
2. DISPLAY EMPLOYEE NAMES IN UPPERCASE ALONG WITH THEIR NAME LENGTH, SORTED BY NAME LENGTH IN DESCENDING ORDER.
3. DISPLAY PRODUCTS WITH THEIR PRICE ROUNDED TO 2 DECIMAL PLACES, SORTED FROM HIGHEST TO LOWEST PRICE.
4. DISPLAY THE SECOND PAGE OF 10 PRODUCTS, SORTED BY PRICE FROM HIGHEST TO LOWEST.
5. FIND THE DEPARTMENT WITH THE HIGHEST AVERAGE SALARY USING GROUP BY, AVG(), ORDER BY, AND LIMIT.
6. DISPLAY EMPLOYEE NAME, SALARY, ANNUAL SALARY, SALARY ROUNDED TO THE NEAREST THOUSAND, AND SALARY CATEGORY USING CASE.
SORT THE RESULT BY ANNUAL SALARY IN DESCENDING ORDER. */

SELECT EMPLOYEE_NAME, SALARY, SALARY * 12 AS ANNUAL_SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 5;

SELECT UPPER(EMPLOYEE_NAME) AS EMPLOYEE_NAME,
       LENGTH(EMPLOYEE_NAME) AS NAME_LENGTH
FROM EMPLOYEES
ORDER BY NAME_LENGTH DESC;

SELECT PRODUCT_NAME,
       ROUND(PRICE, 2) AS ROUNDED_PRICE
FROM PRODUCTS
ORDER BY PRICE DESC;

SELECT *
FROM PRODUCTS
ORDER BY PRICE DESC
LIMIT 10 OFFSET 10;

SELECT DEPARTMENT_ID,
       AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY AVERAGE_SALARY DESC
LIMIT 1;

SELECT EMPLOYEE_NAME,
       SALARY,
       SALARY * 12 AS ANNUAL_SALARY,
       ROUND(SALARY, -3) AS ROUNDED_SALARY,
       CASE
           WHEN SALARY >= 80000 THEN 'HIGH'
           WHEN SALARY >= 50000 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS SALARY_CATEGORY
FROM EMPLOYEES
ORDER BY ANNUAL_SALARY DESC;
