#Date: 2nd September 2026
#Date Covered: 2nd September 2026
#Topics Covered:

/* SQL - TEMPORARY TABLE, TRUNCATE, SEQUENCE & COPY

PRACTICE QUESTIONS

NOTE: SEQUENCE AND COPY SYNTAX VARIES BY DATABASE. THE QUESTIONS BELOW ARE SUITABLE FOR SQL PRACTICE, 
ESPECIALLY POSTGRESQL-STYLE SYNTAX. FOR MYSQL, AUTO_INCREMENT IS GENERALLY USED INSTEAD OF SEQUENCE, AND 
LOAD DATA IS COMMONLY USED INSTEAD OF COPY.

A. TEMPORARY TABLE - 8 QUESTIONS

1. CREATE A TEMPORARY TABLE NAMED TEMP_EMPLOYEES WITH EMPLOYEEID, EMPLOYEENAME, DEPARTMENT, AND SALARY.
2. INSERT 5 EMPLOYEE RECORDS INTO THE TEMPORARY TABLE.
3. DISPLAY ALL RECORDS FROM THE TEMPORARY TABLE.
4. DISPLAY THE STRUCTURE OF THE TEMPORARY TABLE.
5. CREATE A TEMPORARY TABLE CONTAINING ONLY EMPLOYEES WHOSE SALARY IS GREATER THAN 50000 USING CREATE TEMPORARY TABLE ... AS SELECT.
6. CREATE A TEMPORARY TABLE CONTAINING ONLY EMPLOYEEID, EMPLOYEENAME, AND DEPARTMENT FROM THE EMPLOYEES TABLE.
7. UPDATE THE SALARY OF AN EMPLOYEE IN THE TEMPORARY TABLE AND DISPLAY THE UPDATED RECORD.
8. DROP THE TEMPORARY TABLE AND VERIFY THAT IT NO LONGER EXISTS. */

CREATE TEMPORARY TABLE TEMP_EMPLOYEES (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2)
);

INSERT INTO TEMP_EMPLOYEES VALUES
(1,'JOHN','HR',45000),
(2,'SMITH','IT',60000),
(3,'DAVID','SALES',55000),
(4,'MARY','FINANCE',70000),
(5,'JAMES','IT',50000);

SELECT * FROM TEMP_EMPLOYEES;

\d TEMP_EMPLOYEES;

CREATE TEMPORARY TABLE TEMP_HIGH_SALARY_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE SALARY > 50000;

CREATE TEMPORARY TABLE TEMP_EMPLOYEE_DETAILS AS
SELECT EMPLOYEEID, EMPLOYEENAME, DEPARTMENT
FROM EMPLOYEES;

UPDATE TEMP_EMPLOYEES
SET SALARY = 65000
WHERE EMPLOYEEID = 2;

SELECT *
FROM TEMP_EMPLOYEES
WHERE EMPLOYEEID = 2;

DROP TABLE TEMP_EMPLOYEES;

SELECT *
FROM TEMP_EMPLOYEES;

/* B. TRUNCATE - 7 QUESTIONS

9. CREATE A TABLE NAMED STUDENT_TEST AND INSERT 10 RECORDS INTO IT. USE TRUNCATE TO REMOVE ALL RECORDS.
10. DISPLAY THE RECORDS BEFORE AND AFTER EXECUTING TRUNCATE.
11. COMPARE THE EFFECT OF DELETE AND TRUNCATE ON A TABLE CONTAINING 10 RECORDS.
12. INSERT RECORDS INTO A TABLE, EXECUTE TRUNCATE, AND THEN VERIFY THE TABLE STRUCTURE.
13. TRUNCATE A TABLE CONTAINING EMPLOYEE RECORDS WITHOUT DELETING THE TABLE ITSELF.
14. CREATE A TABLE WITH AN IDENTITY/AUTO-GENERATED ID, INSERT RECORDS, TRUNCATE THE TABLE, AND OBSERVE THE BEHAVIOR OF THE GENERATED ID.
15. EXPLAIN AND DEMONSTRATE THE DIFFERENCE BETWEEN DELETE, TRUNCATE, AND DROP. */

CREATE TABLE STUDENT_TEST (
    STUDENTID INT,
    STUDENTNAME VARCHAR(100)
);

INSERT INTO STUDENT_TEST VALUES
(1,'A'),(2,'B'),(3,'C'),(4,'D'),(5,'E'),(6,'F'),(7,'G'),(8,'H'),(9,'I'),(10,'J');

TRUNCATE TABLE STUDENT_TEST;

INSERT INTO STUDENT_TEST VALUES
(1,'A'),(2,'B'),(3,'C'),(4,'D'),(5,'E'),(6,'F'),(7,'G'),(8,'H'),(9,'I'),(10,'J');

SELECT * FROM STUDENT_TEST;

TRUNCATE TABLE STUDENT_TEST;

SELECT * FROM STUDENT_TEST;

CREATE TABLE DELETE_TEST (
    ID INT
);

INSERT INTO DELETE_TEST VALUES
(1),(2),(3),(4),(5),(6),(7),(8),(9),(10);

DELETE FROM DELETE_TEST;

INSERT INTO DELETE_TEST VALUES
(1),(2),(3),(4),(5),(6),(7),(8),(9),(10);

TRUNCATE TABLE DELETE_TEST;

CREATE TABLE EMPLOYEE_RECORDS (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100)
);

INSERT INTO EMPLOYEE_RECORDS VALUES
(1,'JOHN'),
(2,'SMITH');

TRUNCATE TABLE EMPLOYEE_RECORDS;

SELECT * FROM EMPLOYEE_RECORDS;

CREATE TABLE EMPLOYEES (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100)
);

TRUNCATE TABLE EMPLOYEES;

CREATE TABLE EMPLOYEE_AUTO (
    ID SERIAL,
    EMPLOYEENAME VARCHAR(100)
);

INSERT INTO EMPLOYEE_AUTO (EMPLOYEENAME) VALUES
('JOHN'),
('SMITH'),
('DAVID');

TRUNCATE TABLE EMPLOYEE_AUTO RESTART IDENTITY;

INSERT INTO EMPLOYEE_AUTO (EMPLOYEENAME)
VALUES ('MARY');

SELECT * FROM EMPLOYEE_AUTO;

CREATE TABLE DEMO_TABLE (
    ID INT
);

INSERT INTO DEMO_TABLE VALUES
(1),(2),(3);

DELETE FROM DEMO_TABLE;

INSERT INTO DEMO_TABLE VALUES
(1),(2),(3);

TRUNCATE TABLE DEMO_TABLE;

DROP TABLE DEMO_TABLE;

/* C. SEQUENCE - 8 QUESTIONS

16. CREATE A SEQUENCE NAMED EMPLOYEE_SEQ STARTING FROM 1001.
17. GENERATE THE NEXT VALUE FROM THE SEQUENCE.
18. GENERATE THE NEXT 5 SEQUENCE VALUES.
19. CREATE A SEQUENCE THAT STARTS AT 1 AND INCREMENTS BY 1.
20. CREATE A SEQUENCE THAT STARTS AT 100 AND INCREMENTS BY 10.
21. CREATE AN EMPLOYEES TABLE AND USE A SEQUENCE TO GENERATE EMPLOYEE IDS AUTOMATICALLY DURING INSERTION.
22. INSERT 5 EMPLOYEES USING THE SEQUENCE-GENERATED IDS.
23. ALTER OR RESTART THE SEQUENCE SO THAT THE NEXT GENERATED VALUE STARTS FROM 5001. */

CREATE SEQUENCE EMPLOYEE_SEQ
START WITH 1001;

SELECT NEXTVAL('EMPLOYEE_SEQ');

SELECT NEXTVAL('EMPLOYEE_SEQ');
SELECT NEXTVAL('EMPLOYEE_SEQ');
SELECT NEXTVAL('EMPLOYEE_SEQ');
SELECT NEXTVAL('EMPLOYEE_SEQ');
SELECT NEXTVAL('EMPLOYEE_SEQ');

CREATE SEQUENCE SEQ_ONE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_TEN
START WITH 100
INCREMENT BY 10;

CREATE TABLE EMPLOYEES (
    EMPLOYEEID INT PRIMARY KEY,
    EMPLOYEENAME VARCHAR(100),
    DEPARTMENT VARCHAR(50)
);

INSERT INTO EMPLOYEES
VALUES (
    NEXTVAL('EMPLOYEE_SEQ'),
    'JOHN',
    'HR'
);

INSERT INTO EMPLOYEES
VALUES
(NEXTVAL('EMPLOYEE_SEQ'),'SMITH','IT'),
(NEXTVAL('EMPLOYEE_SEQ'),'DAVID','SALES'),
(NEXTVAL('EMPLOYEE_SEQ'),'MARY','FINANCE'),
(NEXTVAL('EMPLOYEE_SEQ'),'JAMES','IT'),
(NEXTVAL('EMPLOYEE_SEQ'),'LINDA','HR');

ALTER SEQUENCE EMPLOYEE_SEQ
RESTART WITH 5001;

SELECT NEXTVAL('EMPLOYEE_SEQ');

/* D. COPY - 7 QUESTIONS

24. CREATE A STUDENTS TABLE AND USE COPY TO EXPORT THE TABLE DATA TO A CSV FILE.
25. USE COPY TO IMPORT STUDENT RECORDS FROM A CSV FILE INTO THE STUDENTS TABLE.
26. EXPORT ONLY STUDENTID, STUDENTNAME, AND MARKS INTO A CSV FILE USING COPY.
27. IMPORT A CSV FILE CONTAINING EMPLOYEE DATA INTO AN EMPLOYEES TABLE USING COPY.
28. USE COPY TO EXPORT EMPLOYEE RECORDS WHERE THE SALARY IS GREATER THAN 50000.
29. IMPORT A CSV FILE CONTAINING NULL VALUES AND CORRECTLY HANDLE THE NULL VALUES WHILE USING COPY.
30. EXPORT A TABLE TO CSV WITH A HEADER ROW AND SPECIFY THE APPROPRIATE DELIMITER USING COPY. */

CREATE TABLE STUDENTS (
    STUDENTID INT,
    STUDENTNAME VARCHAR(100),
    MARKS INT
);

COPY STUDENTS
TO '/PATH/STUDENTS.CSV'
DELIMITER ','
CSV HEADER;

COPY STUDENTS
FROM '/PATH/STUDENTS.CSV'
DELIMITER ','
CSV HEADER;

COPY (
    SELECT STUDENTID, STUDENTNAME, MARKS
    FROM STUDENTS
)
TO '/PATH/STUDENT_MARKS.CSV'
DELIMITER ','
CSV HEADER;

CREATE TABLE EMPLOYEES (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2)
);

COPY EMPLOYEES
FROM '/PATH/EMPLOYEES.CSV'
DELIMITER ','
CSV HEADER;

COPY (
    SELECT *
    FROM EMPLOYEES
    WHERE SALARY > 50000
)
TO '/PATH/HIGH_SALARY_EMPLOYEES.CSV'
DELIMITER ','
CSV HEADER;

COPY EMPLOYEES
FROM '/PATH/EMPLOYEES_NULL.CSV'
DELIMITER ','
CSV HEADER
NULL '';

COPY STUDENTS
TO '/PATH/STUDENTS_EXPORT.CSV'
DELIMITER ';'
CSV HEADER;

/* CHALLENGE QUESTIONS

31. CREATE A TEMPORARY TABLE FROM THE EMPLOYEES TABLE, CALCULATE THE AVERAGE SALARY BY DEPARTMENT, AND STORE THE RESULT IN THE TEMPORARY TABLE.
32. CREATE A SEQUENCE AND USE IT TO GENERATE UNIQUE IDS WHILE INSERTING 10 RECORDS INTO A TABLE.
33. LOAD EMPLOYEE DATA FROM A CSV FILE INTO A TABLE, VERIFY THE RECORDS, AND THEN TRUNCATE THE TABLE.
34. CREATE A TEMPORARY TABLE, INSERT RECORDS USING A SEQUENCE-GENERATED ID, UPDATE SOME RECORDS, AND FINALLY REMOVE ALL RECORDS USING TRUNCATE.
35. DEMONSTRATE THE COMPLETE WORKFLOW:

CSV -> COPY -> TABLE -> TEMPORARY TABLE -> UPDATE -> TRUNCATE

AND VERIFY THE RESULT AFTER EACH STEP. */

CREATE TEMPORARY TABLE TEMP_DEPT_AVG_SALARY AS
SELECT
    DEPARTMENT,
    AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT * FROM TEMP_DEPT_AVG_SALARY;



CREATE SEQUENCE STUDENT_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE STUDENTS (
    STUDENTID INT PRIMARY KEY,
    STUDENTNAME VARCHAR(100)
);

INSERT INTO STUDENTS
VALUES
(NEXTVAL('STUDENT_SEQ'),'STUDENT1'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT2'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT3'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT4'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT5'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT6'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT7'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT8'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT9'),
(NEXTVAL('STUDENT_SEQ'),'STUDENT10');

SELECT * FROM STUDENTS;



CREATE TABLE EMPLOYEES (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2)
);

COPY EMPLOYEES
FROM '/PATH/EMPLOYEES.CSV'
DELIMITER ','
CSV HEADER;

SELECT * FROM EMPLOYEES;

TRUNCATE TABLE EMPLOYEES;

SELECT * FROM EMPLOYEES;



CREATE SEQUENCE TEMP_EMP_SEQ
START WITH 1001
INCREMENT BY 1;

CREATE TEMPORARY TABLE TEMP_EMPLOYEES (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100),
    SALARY DECIMAL(10,2)
);

INSERT INTO TEMP_EMPLOYEES
VALUES
(NEXTVAL('TEMP_EMP_SEQ'),'JOHN',45000),
(NEXTVAL('TEMP_EMP_SEQ'),'SMITH',50000),
(NEXTVAL('TEMP_EMP_SEQ'),'DAVID',55000);

UPDATE TEMP_EMPLOYEES
SET SALARY = 60000
WHERE EMPLOYEENAME = 'JOHN';

SELECT * FROM TEMP_EMPLOYEES;

TRUNCATE TABLE TEMP_EMPLOYEES;

SELECT * FROM TEMP_EMPLOYEES;



CREATE TABLE EMPLOYEE_DATA (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100),
    SALARY DECIMAL(10,2)
);

COPY EMPLOYEE_DATA
FROM '/PATH/EMPLOYEES.CSV'
DELIMITER ','
CSV HEADER;

SELECT * FROM EMPLOYEE_DATA;

CREATE TEMPORARY TABLE TEMP_EMPLOYEE_DATA AS
SELECT *
FROM EMPLOYEE_DATA;

SELECT * FROM TEMP_EMPLOYEE_DATA;

UPDATE TEMP_EMPLOYEE_DATA
SET SALARY = SALARY + 5000
WHERE EMPLOYEEID = 1;

SELECT * FROM TEMP_EMPLOYEE_DATA;

TRUNCATE TABLE TEMP_EMPLOYEE_DATA;

SELECT * FROM TEMP_EMPLOYEE_DATA;
