#Date: 3rd September 2026

/* USER-DEFINED FUNCTIONS (UDF) IN MYSQL

A USER-DEFINED FUNCTION (UDF) IS A FUNCTION CREATED BY THE USER TO PERFORM A SPECIFIC OPERATION AND RETURN ONE VALUE.

PRACTICE QUESTIONS – UDF

1. CREATE A FUNCTION TO ADD TWO NUMBERS.
2. CREATE A FUNCTION TO SUBTRACT TWO NUMBERS.
3. CREATE A FUNCTION TO CALCULATE THE SQUARE OF A NUMBER.
4. CREATE A FUNCTION TO CALCULATE THE CUBE OF A NUMBER.
5. CREATE A FUNCTION TO FIND THE GREATER OF TWO NUMBERS.
6. CREATE A FUNCTION TO CHECK WHETHER A NUMBER IS EVEN OR ODD.
7. CREATE A FUNCTION TO CALCULATE EMPLOYEE ANNUAL SALARY.
8. CREATE A FUNCTION TO CALCULATE AGE FROM DATE OF BIRTH.
9. CREATE A FUNCTION TO CONVERT A NAME TO UPPERCASE.
10. CREATE A FUNCTION TO RETURN THE LENGTH OF A GIVEN STRING.
11. CREATE A FUNCTION TO CALCULATE DISCOUNT BASED ON PURCHASE AMOUNT.
12. CREATE A FUNCTION TO RETURN PASS OR FAIL BASED ON MARKS.
13. CREATE A FUNCTION TO CALCULATE THE TOTAL PRICE FROM QUANTITY AND UNIT PRICE.
14. CREATE A FUNCTION TO CALCULATE GST FOR A GIVEN AMOUNT.
15. CREATE A FUNCTION TO CALCULATE EMPLOYEE EXPERIENCE FROM JOINING DATE.
16. CREATE A FUNCTION TO RETURN ELIGIBLE IF AGE IS 18 OR ABOVE.
17. CREATE A FUNCTION TO CALCULATE BMI FROM HEIGHT AND WEIGHT.
18. CREATE A FUNCTION TO RETURN THE LAST FOUR CHARACTERS OF A STRING.
19. CREATE A FUNCTION TO CALCULATE COMMISSION BASED ON SALES.
20. CREATE A FUNCTION USING CASE TO RETURN GRADES BASED ON MARKS. */

-- 1. ADD TWO NUMBERS
CREATE OR REPLACE FUNCTION ADD_NUMBERS(A INT, B INT)
RETURNS INT
RETURN A + B;

-- 2. SUBTRACT TWO NUMBERS
CREATE OR REPLACE FUNCTION SUBTRACT_NUMBERS(A INT, B INT)
RETURNS INT
RETURN A - B;

-- 3. SQUARE OF A NUMBER
CREATE OR REPLACE FUNCTION SQUARE_NUMBER(N INT)
RETURNS INT
RETURN N * N;

-- 4. CUBE OF A NUMBER
CREATE OR REPLACE FUNCTION CUBE_NUMBER(N INT)
RETURNS INT
RETURN N * N * N;

-- 5. GREATER OF TWO NUMBERS
CREATE OR REPLACE FUNCTION GREATER_NUMBER(A INT, B INT)
RETURNS INT
RETURN GREATEST(A, B);

-- 6. CHECK EVEN OR ODD
CREATE OR REPLACE FUNCTION EVEN_ODD(N INT)
RETURNS STRING
RETURN CASE
    WHEN N % 2 = 0 THEN 'EVEN'
    ELSE 'ODD'
END;

-- 7. EMPLOYEE ANNUAL SALARY
CREATE OR REPLACE FUNCTION ANNUAL_SALARY(MONTHLY_SALARY DOUBLE)
RETURNS DOUBLE
RETURN MONTHLY_SALARY * 12;

-- 8. CALCULATE AGE
CREATE OR REPLACE FUNCTION CALCULATE_AGE(DOB DATE)
RETURNS INT
RETURN FLOOR(DATEDIFF(CURRENT_DATE(), DOB) / 365);

-- 9. CONVERT NAME TO UPPERCASE
CREATE OR REPLACE FUNCTION TO_UPPERCASE(NAME STRING)
RETURNS STRING
RETURN UPPER(NAME);

-- 10. LENGTH OF STRING
CREATE OR REPLACE FUNCTION STRING_LENGTH(TXT STRING)
RETURNS INT
RETURN LENGTH(TXT);

-- 11. DISCOUNT BASED ON PURCHASE AMOUNT
CREATE OR REPLACE FUNCTION DISCOUNT_AMOUNT(AMOUNT DOUBLE)
RETURNS DOUBLE
RETURN CASE
    WHEN AMOUNT >= 10000 THEN AMOUNT * 0.20
    WHEN AMOUNT >= 5000 THEN AMOUNT * 0.10
    ELSE 0
END;

-- 12. PASS OR FAIL
CREATE OR REPLACE FUNCTION PASS_FAIL(MARKS INT)
RETURNS STRING
RETURN CASE
    WHEN MARKS >= 35 THEN 'PASS'
    ELSE 'FAIL'
END;

-- 13. TOTAL PRICE
CREATE OR REPLACE FUNCTION TOTAL_PRICE(QTY INT, UNIT_PRICE DOUBLE)
RETURNS DOUBLE
RETURN QTY * UNIT_PRICE;

-- 14. GST CALCULATION
CREATE OR REPLACE FUNCTION GST_AMOUNT(AMOUNT DOUBLE)
RETURNS DOUBLE
RETURN AMOUNT * 0.18;

-- 15. EMPLOYEE EXPERIENCE
CREATE OR REPLACE FUNCTION EMP_EXPERIENCE(JOIN_DATE DATE)
RETURNS INT
RETURN FLOOR(DATEDIFF(CURRENT_DATE(), JOIN_DATE) / 365);

-- 16. ELIGIBILITY CHECK
CREATE OR REPLACE FUNCTION CHECK_ELIGIBILITY(AGE INT)
RETURNS STRING
RETURN CASE
    WHEN AGE >= 18 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END;

-- 17. BMI CALCULATION
CREATE OR REPLACE FUNCTION CALCULATE_BMI(WEIGHT DOUBLE, HEIGHT DOUBLE)
RETURNS DOUBLE
RETURN WEIGHT / (HEIGHT * HEIGHT);

-- 18. LAST FOUR CHARACTERS
CREATE OR REPLACE FUNCTION LAST_FOUR_CHARS(TXT STRING)
RETURNS STRING
RETURN RIGHT(TXT, 4);

-- 19. COMMISSION BASED ON SALES
CREATE OR REPLACE FUNCTION COMMISSION(SALES DOUBLE)
RETURNS DOUBLE
RETURN CASE
    WHEN SALES >= 100000 THEN SALES * 0.10
    ELSE SALES * 0.05
END;

-- 20. GRADE USING CASE
CREATE OR REPLACE FUNCTION GRADE(MARKS INT)
RETURNS STRING
RETURN CASE
    WHEN MARKS >= 90 THEN 'A'
    WHEN MARKS >= 75 THEN 'B'
    WHEN MARKS >= 50 THEN 'C'
    ELSE 'F'
END;

