#Date: 2nd September 2026
#Date Covered: 2nd September 2026
#Topics Covered:

/* SQL WINDOW FUNCTIONS

TOPICS COVERED

• WINDOW FUNCTIONS
• ROW_NUMBER()
• RANK()
• DENSE_RANK()
• RUNNING TOTAL
• RUNNING AVERAGE
• AGGREGATE FUNCTIONS WITH WINDOW FUNCTIONS
• LEAD()
• LAG()

A. ROW_NUMBER()

1. DISPLAY ALL EMPLOYEES WITH A UNIQUE SEQUENTIAL ROW NUMBER BASED ON THEIR SALARY IN ASCENDING ORDER.
2. DISPLAY EMPLOYEES WITH A ROW NUMBER BASED ON SALARY IN DESCENDING ORDER.
3. ASSIGN A ROW NUMBER TO EMPLOYEES SEPARATELY WITHIN EACH DEPARTMENT.
4. DISPLAY THE TOP 3 EMPLOYEES FROM EACH DEPARTMENT USING ROW_NUMBER().
5. ASSIGN ROW NUMBERS TO STUDENTS BASED ON THEIR MARKS FROM HIGHEST TO LOWEST WITHIN EACH DEPARTMENT. */

SELECT *,
       ROW_NUMBER() OVER(ORDER BY SALARY ASC) AS ROW_NUM
FROM EMPLOYEES;

SELECT *,
       ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS ROW_NUM
FROM EMPLOYEES;

SELECT *,
       ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROW_NUM
FROM EMPLOYEES;

SELECT *
FROM
(
    SELECT *,
           ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROW_NUM
    FROM EMPLOYEES
) T
WHERE ROW_NUM <= 3;

SELECT *,
       ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY MARKS DESC) AS ROW_NUM
FROM STUDENTS;

/* B. RANK()

6. RANK EMPLOYEES BASED ON THEIR SALARY FROM HIGHEST TO LOWEST USING RANK().
7. RANK STUDENTS BASED ON THEIR MARKS FROM HIGHEST TO LOWEST.
8. RANK EMPLOYEES SEPARATELY WITHIN EACH DEPARTMENT BASED ON SALARY.
9. DISPLAY EMPLOYEES WHOSE SALARY RANK IS 1 WITHIN THEIR DEPARTMENT.
10. FIND THE TOP 3 SALARY RANKS IN EACH DEPARTMENT USING RANK(). */

SELECT *,
       RANK() OVER(ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

SELECT *,
       RANK() OVER(ORDER BY MARKS DESC) AS MARK_RANK
FROM STUDENTS;

SELECT *,
       RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

SELECT *
FROM
(
    SELECT *,
           RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEES
) T
WHERE SALARY_RANK = 1;

SELECT *
FROM
(
    SELECT *,
           RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEES
) T
WHERE SALARY_RANK <= 3;

/* C. DENSE_RANK()

11. RANK EMPLOYEES BASED ON SALARY USING DENSE_RANK().
12. RANK STUDENTS BASED ON MARKS USING DENSE_RANK().
13. GENERATE A DENSE SALARY RANK SEPARATELY FOR EACH DEPARTMENT.
14. DISPLAY EMPLOYEES WHO HAVE THE SECOND-HIGHEST SALARY IN EACH DEPARTMENT USING DENSE_RANK().
15. COMPARE THE RESULTS OF RANK() AND DENSE_RANK() WHEN EMPLOYEES HAVE THE SAME SALARY. */

SELECT *,
       DENSE_RANK() OVER(ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

SELECT *,
       DENSE_RANK() OVER(ORDER BY MARKS DESC) AS MARK_RANK
FROM STUDENTS;

SELECT *,
       DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

SELECT *
FROM
(
    SELECT *,
           DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEES
) T
WHERE SALARY_RANK = 2;

SELECT EMPLOYEE_ID,
       EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY,
       RANK() OVER(ORDER BY SALARY DESC) AS RANK_VALUE,
       DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK_VALUE
FROM EMPLOYEES;

/* D. RUNNING TOTAL

16. CALCULATE THE RUNNING TOTAL OF EMPLOYEE SALARIES ORDERED BY EMPLOYEE ID.
17. CALCULATE THE RUNNING TOTAL OF SALES ORDERED BY SALE DATE.
18. CALCULATE THE RUNNING TOTAL OF SALES SEPARATELY FOR EACH CUSTOMER.
19. CALCULATE THE RUNNING TOTAL OF ORDER AMOUNTS FOR EACH CUSTOMER ORDERED BY ORDER DATE.
20. DISPLAY EMPLOYEE NAME, SALARY, AND CUMULATIVE SALARY ORDERED BY SALARY. */

SELECT *,
       SUM(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS RUNNING_TOTAL
FROM EMPLOYEES;

SELECT *,
       SUM(SALES_AMOUNT) OVER(ORDER BY SALE_DATE) AS RUNNING_TOTAL
FROM SALES;

SELECT *,
       SUM(SALES_AMOUNT) OVER(PARTITION BY CUSTOMER_ID ORDER BY SALE_DATE) AS RUNNING_TOTAL
FROM SALES;

SELECT *,
       SUM(ORDER_AMOUNT) OVER(PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS RUNNING_TOTAL
FROM ORDERS;

SELECT EMPLOYEE_NAME,
       SALARY,
       SUM(SALARY) OVER(ORDER BY SALARY) AS CUMULATIVE_SALARY
FROM EMPLOYEES;

/* E. RUNNING AVERAGE

21. CALCULATE THE RUNNING AVERAGE OF EMPLOYEE SALARIES ORDERED BY EMPLOYEE ID.
22. CALCULATE THE RUNNING AVERAGE OF SALES ORDERED BY SALE DATE.
23. CALCULATE THE RUNNING AVERAGE OF SALARY SEPARATELY FOR EACH DEPARTMENT. */

SELECT *,
       AVG(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS RUNNING_AVERAGE
FROM EMPLOYEES;

SELECT *,
       AVG(SALES_AMOUNT) OVER(ORDER BY SALE_DATE) AS RUNNING_AVERAGE
FROM SALES;

SELECT *,
       AVG(SALARY) OVER(PARTITION BY DEPARTMENT ORDER BY SALARY) AS RUNNING_AVERAGE
FROM EMPLOYEES;

/* F. AGGREGATE FUNCTIONS WITH WINDOW FUNCTIONS

24. DISPLAY EACH EMPLOYEE'S SALARY ALONG WITH THE TOTAL SALARY OF ALL EMPLOYEES.
25. DISPLAY EACH EMPLOYEE'S SALARY ALONG WITH THE AVERAGE SALARY OF ALL EMPLOYEES.
26. DISPLAY EACH EMPLOYEE'S SALARY ALONG WITH THE MAXIMUM SALARY IN THE COMPANY.
27. DISPLAY EACH EMPLOYEE'S SALARY ALONG WITH THE TOTAL SALARY OF THEIR DEPARTMENT. */

SELECT *,
       SUM(SALARY) OVER() AS TOTAL_SALARY
FROM EMPLOYEES;

SELECT *,
       AVG(SALARY) OVER() AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT *,
       MAX(SALARY) OVER() AS MAX_SALARY
FROM EMPLOYEES;

SELECT *,
       SUM(SALARY) OVER(PARTITION BY DEPARTMENT) AS DEPARTMENT_TOTAL_SALARY
FROM 

/* G. LEAD()

28. DISPLAY EACH EMPLOYEE'S SALARY ALONG WITH THE SALARY OF THE NEXT EMPLOYEE BASED ON EMPLOYEE ID.
29. DISPLAY EACH EMPLOYEE'S JOINING DATE ALONG WITH THE JOINING DATE OF THE NEXT EMPLOYEE.
30. DISPLAY EACH EMPLOYEE'S SALES AMOUNT ALONG WITH THE NEXT SALE AMOUNT ORDERED BY SALE DATE.
31. DISPLAY EACH EMPLOYEE'S SALARY AND CALCULATE THE DIFFERENCE BETWEEN THEIR SALARY AND THE NEXT EMPLOYEE'S SALARY USING LEAD(). */

SELECT *,
       LEAD(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS NEXT_SALARY
FROM EMPLOYEES;

SELECT *,
       LEAD(JOINING_DATE) OVER(ORDER BY JOINING_DATE) AS NEXT_JOINING_DATE
FROM EMPLOYEES;

SELECT *,
       LEAD(SALES_AMOUNT) OVER(ORDER BY SALE_DATE) AS NEXT_SALE_AMOUNT
FROM SALES;

SELECT *,
       SALARY - LEAD(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS SALARY_DIFFERENCE
FROM EMPLOYEES;

/* H. LAG()

32. DISPLAY EACH EMPLOYEE'S SALARY ALONG WITH THE SALARY OF THE PREVIOUS EMPLOYEE BASED ON EMPLOYEE ID.
33. DISPLAY EACH EMPLOYEE'S JOINING DATE ALONG WITH THE PREVIOUS EMPLOYEE'S JOINING DATE.
34. DISPLAY EACH SALE AMOUNT ALONG WITH THE PREVIOUS SALE AMOUNT ORDERED BY SALE DATE.
35. DISPLAY EACH EMPLOYEE'S SALARY AND CALCULATE THE DIFFERENCE BETWEEN THEIR SALARY AND THE PREVIOUS EMPLOYEE'S SALARY USING LAG(). */

SELECT *,
       LAG(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS PREVIOUS_SALARY
FROM EMPLOYEES;

SELECT *,
       LAG(JOINING_DATE) OVER(ORDER BY JOINING_DATE) AS PREVIOUS_JOINING_DATE
FROM EMPLOYEES;

SELECT *,
       LAG(SALES_AMOUNT) OVER(ORDER BY SALE_DATE) AS PREVIOUS_SALE_AMOUNT
FROM SALES;

SELECT *,
       SALARY - LAG(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS SALARY_DIFFERENCE
FROM EMPLOYEES;


/* ADVANCED WINDOW FUNCTION QUESTIONS

36. FIND THE HIGHEST-PAID EMPLOYEE FROM EACH DEPARTMENT USING ROW_NUMBER().
37. FIND THE SECOND-HIGHEST-PAID EMPLOYEE FROM EACH DEPARTMENT USING DENSE_RANK().
38. DISPLAY EACH EMPLOYEE'S SALARY, DEPARTMENT AVERAGE SALARY, AND DIFFERENCE BETWEEN THEIR SALARY AND DEPARTMENT AVERAGE.
39. DISPLAY EACH EMPLOYEE'S SALARY ALONG WITH THEIR PREVIOUS AND NEXT EMPLOYEE'S SALARY USING BOTH LAG() AND LEAD().
40. DISPLAY EMPLOYEE NAME, DEPARTMENT, SALARY, ROW_NUMBER, RANK, AND DENSE_RANK TOGETHER AND COMPARE THE RESULTS. */

SELECT *
FROM
(
    SELECT *,
           ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROW_NUM
    FROM EMPLOYEES
) T
WHERE ROW_NUM = 1;

SELECT *
FROM
(
    SELECT *,
           DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEES
) T
WHERE SALARY_RANK = 2;

SELECT EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY,
       AVG(SALARY) OVER(PARTITION BY DEPARTMENT) AS DEPARTMENT_AVG_SALARY,
       SALARY - AVG(SALARY) OVER(PARTITION BY DEPARTMENT) AS DIFFERENCE
FROM EMPLOYEES;

SELECT *,
       LAG(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS PREVIOUS_SALARY,
       LEAD(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS NEXT_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY,
       ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROW_NUM,
       RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANK_VALUE,
       DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS DENSE_RANK_VALUE
FROM EMPLOYEES;
