#Date: 3rd September 2026
#Date Covered: 2nd September 2026
#Topics Covered:

/* SQL TRIGGERS

A. BEFORE INSERT - 5 QUESTIONS

1. CREATE A TRIGGER THAT AUTOMATICALLY SETS THE EMPLOYEE'S CREATEDDATE TO THE CURRENT DATE BEFORE A NEW EMPLOYEE RECORD IS INSERTED.
2. CREATE A TRIGGER THAT PREVENTS INSERTING AN EMPLOYEE WITH A SALARY LESS THAN 10000.
3. CREATE A TRIGGER THAT CONVERTS AN EMPLOYEE'S NAME TO UPPERCASE BEFORE INSERTING THE RECORD.
4. CREATE A TRIGGER THAT SETS THE DEFAULT DEPARTMENT TO 'GENERAL' IF THE DEPARTMENT IS NOT PROVIDED DURING INSERTION.
5. CREATE A TRIGGER THAT PREVENTS INSERTING A PRODUCT WITH A NEGATIVE PRICE. */

CREATE TRIGGER TRG_SET_CREATEDDATE
ON EMPLOYEES
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO EMPLOYEES
    SELECT EMPLOYEEID, EMPLOYEENAME, SALARY, GETDATE(), DEPARTMENT
    FROM INSERTED;
END;
GO

CREATE TRIGGER TRG_CHECK_SALARY
ON EMPLOYEES
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM INSERTED WHERE SALARY < 10000)
    BEGIN
        RAISERROR('SALARY MUST BE AT LEAST 10000',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        INSERT INTO EMPLOYEES
        SELECT * FROM INSERTED;
    END
END;
GO

CREATE TRIGGER TRG_UPPERCASE_NAME
ON EMPLOYEES
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO EMPLOYEES
    SELECT EMPLOYEEID, UPPER(EMPLOYEENAME), SALARY, CREATEDDATE, DEPARTMENT
    FROM INSERTED;
END;
GO

CREATE TRIGGER TRG_DEFAULT_DEPARTMENT
ON EMPLOYEES
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO EMPLOYEES
    SELECT EMPLOYEEID,
           EMPLOYEENAME,
           SALARY,
           CREATEDDATE,
           ISNULL(DEPARTMENT,'GENERAL')
    FROM INSERTED;
END;
GO

CREATE TRIGGER TRG_CHECK_PRICE
ON PRODUCTS
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM INSERTED WHERE PRICE < 0)
    BEGIN
        RAISERROR('PRICE CANNOT BE NEGATIVE',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        INSERT INTO PRODUCTS
        SELECT * FROM INSERTED;
    END
END;
GO
 
/* B. AFTER INSERT - 5 QUESTIONS

6. CREATE AN EMPLOYEE_AUDIT TABLE AND CREATE AN AFTER INSERT TRIGGER TO STORE THE DETAILS OF EVERY NEWLY INSERTED EMPLOYEE.
7. CREATE A TRIGGER THAT AUTOMATICALLY RECORDS THE EMPLOYEE ID AND INSERTION TIME WHENEVER A NEW EMPLOYEE IS ADDED.
8. CREATE AN ORDER_AUDIT TABLE AND CREATE AN AFTER INSERT TRIGGER TO RECORD EVERY NEWLY CREATED ORDER.
9. CREATE A TRIGGER THAT UPDATES A DEPARTMENT'S EMPLOYEE COUNT WHENEVER A NEW EMPLOYEE IS INSERTED.
10. INSERT THREE EMPLOYEES AND VERIFY THAT THE AFTER INSERT TRIGGER HAS EXECUTED CORRECTLY. */

CREATE TABLE EMPLOYEE_AUDIT
(
    AUDITID INT IDENTITY(1,1),
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100),
    SALARY DECIMAL(10,2),
    AUDITDATE DATETIME
);
GO

CREATE TRIGGER TRG_EMPLOYEE_AUDIT
ON EMPLOYEES
AFTER INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE_AUDIT
    (
        EMPLOYEEID,
        EMPLOYEENAME,
        SALARY,
        AUDITDATE
    )
    SELECT
        EMPLOYEEID,
        EMPLOYEENAME,
        SALARY,
        GETDATE()
    FROM INSERTED;
END;
GO

CREATE TABLE EMPLOYEE_INSERT_LOG
(
    EMPLOYEEID INT,
    INSERTTIME DATETIME
);
GO

CREATE TRIGGER TRG_EMPLOYEE_INSERT_LOG
ON EMPLOYEES
AFTER INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE_INSERT_LOG
    (
        EMPLOYEEID,
        INSERTTIME
    )
    SELECT
        EMPLOYEEID,
        GETDATE()
    FROM INSERTED;
END;
GO

CREATE TABLE ORDER_AUDIT
(
    AUDITID INT IDENTITY(1,1),
    ORDERID INT,
    AUDITDATE DATETIME
);
GO

CREATE TRIGGER TRG_ORDER_AUDIT
ON ORDERS
AFTER INSERT
AS
BEGIN
    INSERT INTO ORDER_AUDIT
    (
        ORDERID,
        AUDITDATE
    )
    SELECT
        ORDERID,
        GETDATE()
    FROM INSERTED;
END;
GO

CREATE TRIGGER TRG_UPDATE_EMPLOYEE_COUNT
ON EMPLOYEES
AFTER INSERT
AS
BEGIN
    UPDATE D
    SET EMPLOYEECOUNT = EMPLOYEECOUNT + I.CNT
    FROM DEPARTMENTS D
    JOIN
    (
        SELECT DEPARTMENT, COUNT(*) CNT
        FROM INSERTED
        GROUP BY DEPARTMENT
    ) I
    ON D.DEPARTMENTNAME = I.DEPARTMENT;
END;
GO

INSERT INTO EMPLOYEES
VALUES
(101,'AVI',25000,'2026-09-03','IT'),
(102,'JOHN',30000,'2026-09-03','HR'),
(103,'SARAH',28000,'2026-09-03','FINANCE');

SELECT * FROM EMPLOYEE_AUDIT;

/* C. BEFORE UPDATE - 5 QUESTIONS

11. CREATE A TRIGGER THAT PREVENTS AN EMPLOYEE'S SALARY FROM BEING REDUCED.
12. CREATE A TRIGGER THAT PREVENTS UPDATING AN EMPLOYEE'S SALARY TO A VALUE BELOW 15000.
13. CREATE A TRIGGER THAT AUTOMATICALLY UPDATES A MODIFIEDDATE COLUMN BEFORE AN EMPLOYEE RECORD IS UPDATED.
14. CREATE A TRIGGER THAT CONVERTS THE EMPLOYEE NAME TO UPPERCASE BEFORE AN UPDATE.
15. CREATE A TRIGGER THAT PREVENTS CHANGING AN EMPLOYEE'S EMPLOYEEID. */

CREATE TRIGGER TRG_PREVENT_SALARY_REDUCTION
ON EMPLOYEES
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM INSERTED I
        JOIN DELETED D
        ON I.EMPLOYEEID = D.EMPLOYEEID
        WHERE I.SALARY < D.SALARY
    )
    BEGIN
        RAISERROR('SALARY CANNOT BE REDUCED',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        UPDATE E
        SET E.EMPLOYEENAME = I.EMPLOYEENAME,
            E.SALARY = I.SALARY,
            E.DEPARTMENT = I.DEPARTMENT
        FROM EMPLOYEES E
        JOIN INSERTED I
        ON E.EMPLOYEEID = I.EMPLOYEEID;
    END
END;
GO

CREATE TRIGGER TRG_MIN_SALARY
ON EMPLOYEES
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM INSERTED WHERE SALARY < 15000)
    BEGIN
        RAISERROR('SALARY CANNOT BE BELOW 15000',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        UPDATE E
        SET E.SALARY = I.SALARY
        FROM EMPLOYEES E
        JOIN INSERTED I
        ON E.EMPLOYEEID = I.EMPLOYEEID;
    END
END;
GO

CREATE TRIGGER TRG_UPDATE_MODIFIEDDATE
ON EMPLOYEES
INSTEAD OF UPDATE
AS
BEGIN
    UPDATE E
    SET E.EMPLOYEENAME = I.EMPLOYEENAME,
        E.SALARY = I.SALARY,
        E.DEPARTMENT = I.DEPARTMENT,
        E.MODIFIEDDATE = GETDATE()
    FROM EMPLOYEES E
    JOIN INSERTED I
    ON E.EMPLOYEEID = I.EMPLOYEEID;
END;
GO

CREATE TRIGGER TRG_UPPERCASE_NAME_UPDATE
ON EMPLOYEES
INSTEAD OF UPDATE
AS
BEGIN
    UPDATE E
    SET E.EMPLOYEENAME = UPPER(I.EMPLOYEENAME),
        E.SALARY = I.SALARY,
        E.DEPARTMENT = I.DEPARTMENT
    FROM EMPLOYEES E
    JOIN INSERTED I
    ON E.EMPLOYEEID = I.EMPLOYEEID;
END;
GO

CREATE TRIGGER TRG_PREVENT_EMPLOYEEID_CHANGE
ON EMPLOYEES
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM INSERTED I
        JOIN DELETED D
        ON I.EMPLOYEEID <> D.EMPLOYEEID
    )
    BEGIN
        RAISERROR('EMPLOYEEID CANNOT BE CHANGED',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        UPDATE E
        SET E.EMPLOYEENAME = I.EMPLOYEENAME,
            E.SALARY = I.SALARY,
            E.DEPARTMENT = I.DEPARTMENT
        FROM EMPLOYEES E
        JOIN INSERTED I
        ON E.EMPLOYEEID = I.EMPLOYEEID;
    END
END;
GO

/* D. AFTER UPDATE - 5 QUESTIONS

16. CREATE AN EMPLOYEE_SALARY_AUDIT TABLE AND CREATE AN AFTER UPDATE TRIGGER TO STORE THE EMPLOYEE'S OLD AND NEW SALARY.
17. CREATE A TRIGGER THAT RECORDS THE DATE AND TIME WHENEVER AN EMPLOYEE'S DEPARTMENT IS CHANGED.
18. CREATE A TRIGGER THAT STORES THE OLD AND NEW VALUES WHENEVER AN EMPLOYEE'S SALARY IS UPDATED.
19. UPDATE THE SALARY OF THREE EMPLOYEES AND VERIFY THE RECORDS CREATED BY THE AFTER UPDATE TRIGGER.
20. CREATE A TRIGGER THAT RECORDS CHANGES MADE TO AN EMPLOYEE'S DESIGNATION. */

CREATE TABLE EMPLOYEE_SALARY_AUDIT
(
    AUDITID INT IDENTITY(1,1),
    EMPLOYEEID INT,
    OLDSALARY DECIMAL(10,2),
    NEWSALARY DECIMAL(10,2),
    UPDATEDATE DATETIME
);
GO

CREATE TRIGGER TRG_EMPLOYEE_SALARY_AUDIT
ON EMPLOYEES
AFTER UPDATE
AS
BEGIN
    INSERT INTO EMPLOYEE_SALARY_AUDIT
    (
        EMPLOYEEID,
        OLDSALARY,
        NEWSALARY,
        UPDATEDATE
    )
    SELECT
        D.EMPLOYEEID,
        D.SALARY,
        I.SALARY,
        GETDATE()
    FROM DELETED D
    JOIN INSERTED I
    ON D.EMPLOYEEID = I.EMPLOYEEID;
END;
GO

CREATE TABLE DEPARTMENT_CHANGE_AUDIT
(
    EMPLOYEEID INT,
    OLDDEPARTMENT VARCHAR(100),
    NEWDEPARTMENT VARCHAR(100),
    CHANGEDATE DATETIME
);
GO

CREATE TRIGGER TRG_DEPARTMENT_CHANGE
ON EMPLOYEES
AFTER UPDATE
AS
BEGIN
    INSERT INTO DEPARTMENT_CHANGE_AUDIT
    (
        EMPLOYEEID,
        OLDDEPARTMENT,
        NEWDEPARTMENT,
        CHANGEDATE
    )
    SELECT
        D.EMPLOYEEID,
        D.DEPARTMENT,
        I.DEPARTMENT,
        GETDATE()
    FROM DELETED D
    JOIN INSERTED I
    ON D.EMPLOYEEID = I.EMPLOYEEID
    WHERE D.DEPARTMENT <> I.DEPARTMENT;
END;
GO

CREATE TABLE SALARY_CHANGE_AUDIT
(
    EMPLOYEEID INT,
    OLDSALARY DECIMAL(10,2),
    NEWSALARY DECIMAL(10,2),
    CHANGEDATE DATETIME
);
GO

CREATE TRIGGER TRG_SALARY_CHANGE
ON EMPLOYEES
AFTER UPDATE
AS
BEGIN
    INSERT INTO SALARY_CHANGE_AUDIT
    (
        EMPLOYEEID,
        OLDSALARY,
        NEWSALARY,
        CHANGEDATE
    )
    SELECT
        D.EMPLOYEEID,
        D.SALARY,
        I.SALARY,
        GETDATE()
    FROM DELETED D
    JOIN INSERTED I
    ON D.EMPLOYEEID = I.EMPLOYEEID
    WHERE D.SALARY <> I.SALARY;
END;
GO

UPDATE EMPLOYEES
SET SALARY = 35000
WHERE EMPLOYEEID = 101;

UPDATE EMPLOYEES
SET SALARY = 40000
WHERE EMPLOYEEID = 102;

UPDATE EMPLOYEES
SET SALARY = 45000
WHERE EMPLOYEEID = 103;

SELECT * FROM EMPLOYEE_SALARY_AUDIT;
GO

CREATE TABLE DESIGNATION_AUDIT
(
    EMPLOYEEID INT,
    OLDDESIGNATION VARCHAR(100),
    NEWDESIGNATION VARCHAR(100),
    CHANGEDATE DATETIME
);
GO

CREATE TRIGGER TRG_DESIGNATION_CHANGE
ON EMPLOYEES
AFTER UPDATE
AS
BEGIN
    INSERT INTO DESIGNATION_AUDIT
    (
        EMPLOYEEID,
        OLDDESIGNATION,
        NEWDESIGNATION,
        CHANGEDATE
    )
    SELECT
        D.EMPLOYEEID,
        D.DESIGNATION,
        I.DESIGNATION,
        GETDATE()
    FROM DELETED D
    JOIN INSERTED I
    ON D.EMPLOYEEID = I.EMPLOYEEID
    WHERE D.DESIGNATION <> I.DESIGNATION;
END;
GO

/* E. BEFORE DELETE - 5 QUESTIONS

21. CREATE A TRIGGER THAT PREVENTS DELETING AN EMPLOYEE WHOSE DESIGNATION IS 'MANAGER'.
22. CREATE A TRIGGER THAT PREVENTS DELETING EMPLOYEES WHOSE SALARY IS GREATER THAN 100000.
23. CREATE A TRIGGER THAT PREVENTS DELETION OF AN EMPLOYEE IF THEY ARE ASSOCIATED WITH AN ACTIVE PROJECT.
24. CREATE A TRIGGER THAT CHECKS A CONDITION BEFORE DELETING A PRODUCT.
25. CREATE A TRIGGER THAT PREVENTS DELETION OF A CUSTOMER WHO HAS EXISTING ORDERS. */

CREATE TRIGGER TRG_PREVENT_MANAGER_DELETE
ON EMPLOYEES
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM DELETED
        WHERE DESIGNATION = 'MANAGER'
    )
    BEGIN
        RAISERROR('MANAGER CANNOT BE DELETED',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        DELETE FROM EMPLOYEES
        WHERE EMPLOYEEID IN
        (
            SELECT EMPLOYEEID
            FROM DELETED
        );
    END
END;
GO

CREATE TRIGGER TRG_PREVENT_HIGH_SALARY_DELETE
ON EMPLOYEES
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM DELETED
        WHERE SALARY > 100000
    )
    BEGIN
        RAISERROR('EMPLOYEE CANNOT BE DELETED',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        DELETE FROM EMPLOYEES
        WHERE EMPLOYEEID IN
        (
            SELECT EMPLOYEEID
            FROM DELETED
        );
    END
END;
GO

CREATE TRIGGER TRG_PREVENT_ACTIVE_PROJECT_DELETE
ON EMPLOYEES
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM DELETED D
        JOIN PROJECTS P
        ON D.EMPLOYEEID = P.EMPLOYEEID
        WHERE P.STATUS = 'ACTIVE'
    )
    BEGIN
        RAISERROR('EMPLOYEE HAS ACTIVE PROJECT',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        DELETE FROM EMPLOYEES
        WHERE EMPLOYEEID IN
        (
            SELECT EMPLOYEEID
            FROM DELETED
        );
    END
END;
GO

CREATE TRIGGER TRG_CHECK_PRODUCT_DELETE
ON PRODUCTS
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM DELETED
        WHERE PRICE > 1000
    )
    BEGIN
        RAISERROR('PRODUCT CANNOT BE DELETED',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        DELETE FROM PRODUCTS
        WHERE PRODUCTID IN
        (
            SELECT PRODUCTID
          

/* F. AFTER DELETE - 5 QUESTIONS

26. CREATE AN EMPLOYEE_DELETE_AUDIT TABLE AND CREATE AN AFTER DELETE TRIGGER TO STORE THE DETAILS OF DELETED EMPLOYEES.
27. CREATE A TRIGGER THAT RECORDS THE EMPLOYEE ID, EMPLOYEE NAME, AND DELETION DATE WHENEVER AN EMPLOYEE IS DELETED.
28. DELETE THREE EMPLOYEE RECORDS AND VERIFY THAT THEIR DETAILS ARE STORED IN THE AUDIT TABLE.
29. CREATE AN ORDER_DELETE_AUDIT TABLE AND CREATE AN AFTER DELETE TRIGGER TO MAINTAIN A HISTORY OF DELETED ORDERS.
30. CREATE SEPARATE AFTER INSERT, AFTER UPDATE, AND AFTER DELETE TRIGGERS FOR THE EMPLOYEES TABLE AND STORE ALL CHANGES IN A SINGLE AUDIT TABLE. */

CREATE TABLE EMPLOYEE_DELETE_AUDIT
(
    AUDITID INT IDENTITY(1,1),
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100),
    SALARY DECIMAL(10,2),
    DELETEDATE DATETIME
);
GO

CREATE TRIGGER TRG_EMPLOYEE_DELETE_AUDIT
ON EMPLOYEES
AFTER DELETE
AS
BEGIN
    INSERT INTO EMPLOYEE_DELETE_AUDIT
    (
        EMPLOYEEID,
        EMPLOYEENAME,
        SALARY,
        DELETEDATE
    )
    SELECT
        EMPLOYEEID,
        EMPLOYEENAME,
        SALARY,
        GETDATE()
    FROM DELETED;
END;
GO

CREATE TABLE EMPLOYEE_DELETE_LOG
(
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(100),
    DELETEDATE DATETIME
);
GO

CREATE TRIGGER TRG_EMPLOYEE_DELETE_LOG
ON EMPLOYEES
AFTER DELETE
AS
BEGIN
    INSERT INTO EMPLOYEE_DELETE_LOG
    (
        EMPLOYEEID,
        EMPLOYEENAME,
        DELETEDATE
    )
    SELECT
        EMPLOYEEID,
        EMPLOYEENAME,
        GETDATE()
    FROM DELETED;
END;
GO

DELETE FROM EMPLOYEES
WHERE EMPLOYEEID IN (101,102,103);

SELECT * FROM EMPLOYEE_DELETE_AUDIT;
GO

CREATE TABLE ORDER_DELETE_AUDIT
(
    AUDITID INT IDENTITY(1,1),
    ORDERID INT,
    DELETEDATE DATETIME
);
GO

CREATE TRIGGER TRG_ORDER_DELETE_AUDIT
ON ORDERS
AFTER DELETE
AS
BEGIN
    INSERT INTO ORDER_DELETE_AUDIT
    (
        ORDERID,
        DELETEDATE
    )
    SELECT
        ORDERID,
        GETDATE()
    FROM DELETED;
END;
GO

CREATE TABLE EMPLOYEE_AUDIT_ALL
(
    AUDITID INT IDENTITY(1,1),
    EMPLOYEEID INT,
    ACTIONTYPE VARCHAR(20),
    AUDITDATE DATETIME
);
GO

CREATE TRIGGER TRG_EMPLOYEE_INSERT_AUDIT
ON EMPLOYEES
AFTER INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE_AUDIT_ALL
    (
        EMPLOYEEID,
        ACTIONTYPE,
        AUDITDATE
    )
    SELECT
        EMPLOYEEID,
        'INSERT',
        GETDATE()
    FROM INSERTED;
END;
GO

CREATE TRIGGER TRG_EMPLOYEE_UPDATE_AUDIT
ON EMPLOYEES
AFTER UPDATE
AS
BEGIN
    INSERT INTO EMPLOYEE_AUDIT_ALL
    (
        EMPLOYEEID,
        ACTIONTYPE,
        AUDITDATE
    )
    SELECT
        EMPLOYEEID,
        'UPDATE',
        GETDATE()
    FROM INSERTED;
END;
GO

CREATE TRIGGER TRG_EMPLOYEE_DELETE_AUDIT_ALL
ON EMPLOYEES
AFTER DELETE
AS
BEGIN
    INSERT INTO EMPLOYEE_AUDIT_ALL
    (
        EMPLOYEEID,
        ACTIONTYPE,
        AUDITDATE
    )
    SELECT
        EMPLOYEEID,
        'DELETE',
        GETDATE()
    FROM DELETED;
END;
GO

/* CHALLENGE QUESTIONS

31. CREATE A PRODUCTS TABLE WITH PRODUCTID, PRODUCTNAME, PRICE, AND CREATEDDATE. CREATE A BEFORE INSERT TRIGGER TO REJECT NEGATIVE PRICES.
32. CREATE A BEFORE UPDATE TRIGGER THAT PREVENTS A PRODUCT PRICE FROM BEING REDUCED BY MORE THAN 20%.
33. CREATE AN AUDIT TABLE AND AN AFTER UPDATE TRIGGER THAT STORES THE OLD AND NEW PRODUCT PRICES.
34. CREATE A BEFORE DELETE TRIGGER TO PREVENT DELETION OF PRODUCTS WHOSE STOCK IS GREATER THAN 0.
35. CREATE AN AUDIT SYSTEM USING AFTER INSERT, AFTER UPDATE, AND AFTER DELETE TRIGGERS TO MAINTAIN A COMPLETE HISTORY OF CHANGES MADE TO 
THE EMPLOYEES TABLE. */

CREATE TABLE PRODUCTS
(
    PRODUCTID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(100),
    PRICE DECIMAL(10,2),
    CREATEDDATE DATE
);
GO

CREATE TRIGGER TRG_REJECT_NEGATIVE_PRICE
ON PRODUCTS
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM INSERTED WHERE PRICE < 0)
    BEGIN
        RAISERROR('NEGATIVE PRICE NOT ALLOWED',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        INSERT INTO PRODUCTS
        (
            PRODUCTID,
            PRODUCTNAME,
            PRICE,
            CREATEDDATE
        )
        SELECT
            PRODUCTID,
            PRODUCTNAME,
            PRICE,
            CREATEDDATE
        FROM INSERTED;
    END
END;
GO

CREATE TRIGGER TRG_PRICE_REDUCTION_CHECK
ON PRODUCTS
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM INSERTED I
        JOIN DELETED D
        ON I.PRODUCTID = D.PRODUCTID
        WHERE I.PRICE < D.PRICE * 0.8
    )
    BEGIN
        RAISERROR('PRICE CANNOT BE REDUCED BY MORE THAN 20 PERCENT',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        UPDATE P
        SET P.PRODUCTNAME = I.PRODUCTNAME,
            P.PRICE = I.PRICE
        FROM PRODUCTS P
        JOIN INSERTED I
        ON P.PRODUCTID = I.PRODUCTID;
    END
END;
GO

CREATE TABLE PRODUCT_PRICE_AUDIT
(
    AUDITID INT IDENTITY(1,1),
    PRODUCTID INT,
    OLDPRICE DECIMAL(10,2),
    NEWPRICE DECIMAL(10,2),
    UPDATEDATE DATETIME
);
GO

CREATE TRIGGER TRG_PRODUCT_PRICE_AUDIT
ON PRODUCTS
AFTER UPDATE
AS
BEGIN
    INSERT INTO PRODUCT_PRICE_AUDIT
    (
        PRODUCTID,
        OLDPRICE,
        NEWPRICE,
        UPDATEDATE
    )
    SELECT
        D.PRODUCTID,
        D.PRICE,
        I.PRICE,
        GETDATE()
    FROM DELETED D
    JOIN INSERTED I
    ON D.PRODUCTID = I.PRODUCTID;
END;
GO

CREATE TRIGGER TRG_PREVENT_STOCK_DELETE
ON PRODUCTS
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM DELETED
        WHERE STOCK > 0
    )
    BEGIN
        RAISERROR('PRODUCT WITH STOCK CANNOT BE DELETED',16,1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        DELETE FROM PRODUCTS
        WHERE PRODUCTID IN
        (
            SELECT PRODUCTID
            FROM DELETED
        );
    END
END;
GO

CREATE TABLE EMPLOYEE_AUDIT_HISTORY
(
    AUDITID INT IDENTITY(1,1),
    EMPLOYEEID INT,
    ACTIONTYPE VARCHAR(20),
    AUDITDATE DATETIME
);
GO

CREATE TRIGGER TRG_EMPLOYEE_INSERT_HISTORY
ON EMPLOYEES
AFTER INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE_AUDIT_HISTORY
    (
        EMPLOYEEID,
        ACTIONTYPE,
        AUDITDATE
    )
    SELECT
        EMPLOYEEID,
        'INSERT',
        GETDATE()
    FROM INSERTED;
END;
GO

CREATE TRIGGER TRG_EMPLOYEE_UPDATE_HISTORY
ON EMPLOYEES
AFTER UPDATE
AS
BEGIN
    INSERT INTO EMPLOYEE_AUDIT_HISTORY
    (
        EMPLOYEEID,
        ACTIONTYPE,
        AUDITDATE
    )
    SELECT
        EMPLOYEEID,
        'UPDATE',
        GETDATE()
    FROM INSERTED;
END;
GO

CREATE TRIGGER TRG_EMPLOYEE_DELETE_HISTORY
ON EMPLOYEES
AFTER DELETE
AS
BEGIN
    INSERT INTO EMPLOYEE_AUDIT_HISTORY
    (
        EMPLOYEEID,
        ACTIONTYPE,
        AUDITDATE
    )
    SELECT
        EMPLOYEEID,
        'DELETE',
        GETDATE()
    FROM DELETED;
END;
GO

