#Date: 10th September 2026
#Topics covered: Stored Procedures

/* STORED PROCEDURE

BANKING SYSTEM

1. CREATE A STORED PROCEDURE TO TRANSFER MONEY FROM ONE BANK ACCOUNT TO ANOTHER. THE PROCEDURE SHOULD DEDUCT THE AMOUNT FROM ONE ACCOUNT AND ADD IT TO THE OTHER ACCOUNT.
2. CREATE A PROCEDURE TO CHECK ACCOUNT BALANCE FOR A GIVEN ACCOUNT NUMBER.
3. CREATE A PROCEDURE TO DEPOSIT MONEY INTO A CUSTOMER'S ACCOUNT AND MAINTAIN A TRANSACTION HISTORY.
4. CREATE A PROCEDURE TO WITHDRAW MONEY ONLY IF THE ACCOUNT HAS SUFFICIENT BALANCE. OTHERWISE, DISPLAY AN APPROPRIATE MESSAGE.
5. CREATE A PROCEDURE TO GENERATE A MONTHLY BANK STATEMENT FOR A GIVEN CUSTOMER.*/

DELIMITER //

CREATE PROCEDURE TRANSFER_MONEY(
    IN P_FROM_ACC INT,
    IN P_TO_ACC INT,
    IN P_AMOUNT DECIMAL(10,2)
)
BEGIN
    UPDATE ACCOUNTS
    SET BALANCE = BALANCE - P_AMOUNT
    WHERE ACCOUNT_ID = P_FROM_ACC;

    UPDATE ACCOUNTS
    SET BALANCE = BALANCE + P_AMOUNT
    WHERE ACCOUNT_ID = P_TO_ACC;
END //

CREATE PROCEDURE CHECK_BALANCE(
    IN P_ACCOUNT_ID INT
)
BEGIN
    SELECT BALANCE
    FROM ACCOUNTS
    WHERE ACCOUNT_ID = P_ACCOUNT_ID;
END //

CREATE PROCEDURE DEPOSIT_MONEY(
    IN P_ACCOUNT_ID INT,
    IN P_AMOUNT DECIMAL(10,2)
)
BEGIN
    UPDATE ACCOUNTS
    SET BALANCE = BALANCE + P_AMOUNT
    WHERE ACCOUNT_ID = P_ACCOUNT_ID;

    INSERT INTO TRANSACTIONS(ACCOUNT_ID, AMOUNT, TRANSACTION_TYPE)
    VALUES(P_ACCOUNT_ID, P_AMOUNT, 'DEPOSIT');
END //

CREATE PROCEDURE WITHDRAW_MONEY(
    IN P_ACCOUNT_ID INT,
    IN P_AMOUNT DECIMAL(10,2)
)
BEGIN
    DECLARE CUR_BALANCE DECIMAL(10,2);

    SELECT BALANCE
    INTO CUR_BALANCE
    FROM ACCOUNTS
    WHERE ACCOUNT_ID = P_ACCOUNT_ID;

    IF CUR_BALANCE >= P_AMOUNT THEN
        UPDATE ACCOUNTS
        SET BALANCE = BALANCE - P_AMOUNT
        WHERE ACCOUNT_ID = P_ACCOUNT_ID;
    ELSE
        SELECT 'INSUFFICIENT BALANCE' AS MESSAGE;
    END IF;
END //

CREATE PROCEDURE MONTHLY_BANK_STATEMENT(
    IN P_ACCOUNT_ID INT
)
BEGIN
    SELECT *
    FROM TRANSACTIONS
    WHERE ACCOUNT_ID = P_ACCOUNT_ID
    AND MONTH(TRANSACTION_DATE) = MONTH(CURDATE())
    AND YEAR(TRANSACTION_DATE) = YEAR(CURDATE());
END //

DELIMITER ;

/* E-COMMERCE SYSTEM

6. CREATE A PROCEDURE TO PLACE A NEW ORDER FOR A CUSTOMER. THE PROCEDURE SHOULD INSERT ORDER DETAILS AND CALCULATE THE TOTAL ORDER AMOUNT.
7. CREATE A PROCEDURE TO ADD A PRODUCT TO AN EXISTING ORDER AND UPDATE THE ORDER TOTAL.
8. CREATE A PROCEDURE TO CHECK PRODUCT STOCK AVAILABILITY BEFORE PLACING AN ORDER.
9. CREATE A PROCEDURE TO REDUCE PRODUCT STOCK AFTER AN ORDER IS PLACED.
10. CREATE A PROCEDURE TO CANCEL AN ORDER AND RESTORE THE ORDERED QUANTITY BACK TO PRODUCT STOCK.
11. CREATE A PROCEDURE TO FIND THE TOTAL AMOUNT SPENT BY A CUSTOMER BETWEEN TWO GIVEN DATES.
12. CREATE A PROCEDURE TO RETRIEVE ALL PENDING ORDERS FOR A PARTICULAR CUSTOMER. */

DELIMITER //

CREATE PROCEDURE PLACE_NEW_ORDER(
    IN P_CUSTOMER_ID INT,
    IN P_TOTAL DECIMAL(10,2)
)
BEGIN
    INSERT INTO ORDERS(CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
    VALUES(P_CUSTOMER_ID, CURDATE(), P_TOTAL);
END //

CREATE PROCEDURE ADD_PRODUCT_TO_ORDER(
    IN P_ORDER_ID INT,
    IN P_PRODUCT_ID INT,
    IN P_QTY INT,
    IN P_PRICE DECIMAL(10,2)
)
BEGIN
    INSERT INTO ORDER_DETAILS(ORDER_ID, PRODUCT_ID, QUANTITY, PRICE)
    VALUES(P_ORDER_ID, P_PRODUCT_ID, P_QTY, P_PRICE);

    UPDATE ORDERS
    SET TOTAL_AMOUNT = TOTAL_AMOUNT + (P_QTY * P_PRICE)
    WHERE ORDER_ID = P_ORDER_ID;
END //

CREATE PROCEDURE CHECK_STOCK(
    IN P_PRODUCT_ID INT
)
BEGIN
    SELECT STOCK
    FROM PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID;
END //

CREATE PROCEDURE REDUCE_STOCK(
    IN P_PRODUCT_ID INT,
    IN P_QTY INT
)
BEGIN
    UPDATE PRODUCTS
    SET STOCK = STOCK - P_QTY
    WHERE PRODUCT_ID = P_PRODUCT_ID;
END //

CREATE PROCEDURE CANCEL_ORDER(
    IN P_ORDER_ID INT,
    IN P_PRODUCT_ID INT,
    IN P_QTY INT
)
BEGIN
    UPDATE PRODUCTS
    SET STOCK = STOCK + P_QTY
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    DELETE FROM ORDERS
    WHERE ORDER_ID = P_ORDER_ID;
END //

CREATE PROCEDURE TOTAL_SPENT(
    IN P_CUSTOMER_ID INT,
    IN P_START_DATE DATE,
    IN P_END_DATE DATE
)
BEGIN
    SELECT SUM(TOTAL_AMOUNT) AS TOTAL_SPENT
    FROM ORDERS
    WHERE CUSTOMER_ID = P_CUSTOMER_ID
    AND ORDER_DATE BETWEEN P_START_DATE AND P_END_DATE;
END //

CREATE PROCEDURE PENDING_ORDERS(
    IN P_CUSTOMER_ID INT
)
BEGIN
    SELECT *
    FROM ORDERS
    WHERE CUSTOMER_ID = P_CUSTOMER_ID
    AND STATUS = 'PENDING';
END //

DELIMITER ;


/* EMPLOYEE / HR SYSTEM

13. CREATE A PROCEDURE TO RETRIEVE ALL EMPLOYEES BELONGING TO A PARTICULAR DEPARTMENT.
14. CREATE A PROCEDURE TO INCREASE AN EMPLOYEE'S SALARY BY A GIVEN PERCENTAGE.
15. CREATE A PROCEDURE TO CALCULATE AN EMPLOYEE'S ANNUAL SALARY USING THEIR MONTHLY SALARY.
16. CREATE A PROCEDURE TO FIND EMPLOYEES WHOSE SALARY IS GREATER THAN A GIVEN AMOUNT.
17. CREATE A PROCEDURE TO GENERATE A DEPARTMENT-WISE EMPLOYEE SALARY REPORT.
18. CREATE A PROCEDURE TO CALCULATE THE TOTAL SALARY EXPENSE OF A DEPARTMENT. */

DELIMITER //

CREATE PROCEDURE GET_EMPLOYEES_BY_DEPARTMENT(
    IN P_DEPT_ID INT
)
BEGIN
    SELECT *
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = P_DEPT_ID;
END //

CREATE PROCEDURE INCREASE_EMPLOYEE_SALARY(
    IN P_EMP_ID INT,
    IN P_PERCENT DECIMAL(5,2)
)
BEGIN
    UPDATE EMPLOYEES
    SET SALARY = SALARY + (SALARY * P_PERCENT / 100)
    WHERE EMPLOYEE_ID = P_EMP_ID;
END //

CREATE PROCEDURE CALCULATE_ANNUAL_SALARY(
    IN P_EMP_ID INT
)
BEGIN
    SELECT EMPLOYEE_NAME,
           SALARY * 12 AS ANNUAL_SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = P_EMP_ID;
END //

CREATE PROCEDURE EMPLOYEES_GREATER_THAN_AMOUNT(
    IN P_AMOUNT DECIMAL(10,2)
)
BEGIN
    SELECT *
    FROM EMPLOYEES
    WHERE SALARY > P_AMOUNT;
END //

CREATE PROCEDURE DEPARTMENT_SALARY_REPORT()
BEGIN
    SELECT DEPARTMENT_ID,
           EMPLOYEE_NAME,
           SALARY
    FROM EMPLOYEES
    ORDER BY DEPARTMENT_ID;
END //

CREATE PROCEDURE TOTAL_DEPARTMENT_SALARY_EXPENSE(
    IN P_DEPT_ID INT
)
BEGIN
    SELECT SUM(SALARY) AS TOTAL_SALARY_EXPENSE
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = P_DEPT_ID;
END //

DELIMITER ;

/* STUDENT MANAGEMENT SYSTEM

19. CREATE A PROCEDURE TO RETRIEVE ALL STUDENTS BELONGING TO A PARTICULAR COURSE.
20. CREATE A PROCEDURE TO CALCULATE A STUDENT'S TOTAL MARKS AND AVERAGE MARKS.
21. CREATE A PROCEDURE TO DETERMINE WHETHER A STUDENT HAS PASSED OR FAILED BASED ON THEIR MARKS.
22. CREATE A PROCEDURE TO RETRIEVE STUDENTS WHOSE AVERAGE MARK IS GREATER THAN A GIVEN VALUE.
23. CREATE A PROCEDURE TO GENERATE A STUDENT RESULT REPORT CONTAINING STUDENT NAME, TOTAL, AVERAGE, GRADE, AND RESULT STATUS. */

DELIMITER //

CREATE PROCEDURE GET_STUDENTS_BY_COURSE(
    IN P_COURSE_ID INT
)
BEGIN
    SELECT *
    FROM STUDENTS
    WHERE COURSE_ID = P_COURSE_ID;
END //

CREATE PROCEDURE STUDENT_TOTAL_AVERAGE(
    IN P_STUDENT_ID INT
)
BEGIN
    SELECT STUDENT_NAME,
           (MARK1 + MARK2 + MARK3) AS TOTAL_MARKS,
           (MARK1 + MARK2 + MARK3) / 3 AS AVERAGE_MARKS
    FROM STUDENTS
    WHERE STUDENT_ID = P_STUDENT_ID;
END //

CREATE PROCEDURE CHECK_PASS_FAIL(
    IN P_STUDENT_ID INT
)
BEGIN
    DECLARE AVG_MARK DECIMAL(5,2);

    SELECT (MARK1 + MARK2 + MARK3) / 3
    INTO AVG_MARK
    FROM STUDENTS
    WHERE STUDENT_ID = P_STUDENT_ID;

    IF AVG_MARK >= 50 THEN
        SELECT 'PASS' AS RESULT;
    ELSE
        SELECT 'FAIL' AS RESULT;
    END IF;
END //

CREATE PROCEDURE STUDENTS_ABOVE_AVERAGE(
    IN P_AVG DECIMAL(5,2)
)
BEGIN
    SELECT *
    FROM STUDENTS
    WHERE (MARK1 + MARK2 + MARK3) / 3 > P_AVG;
END //

CREATE PROCEDURE STUDENT_RESULT_REPORT(
    IN P_STUDENT_ID INT
)
BEGIN
    SELECT STUDENT_NAME,
           (MARK1 + MARK2 + MARK3) AS TOTAL,
           (MARK1 + MARK2 + MARK3) / 3 AS AVERAGE,
           CASE
               WHEN (MARK1 + MARK2 + MARK3) / 3 >= 90 THEN 'A'
               WHEN (MARK1 + MARK2 + MARK3) / 3 >= 75 THEN 'B'
               WHEN (MARK1 + MARK2 + MARK3) / 3 >= 50 THEN 'C'
               ELSE 'D'
           END AS GRADE,
           CASE
               WHEN (MARK1 + MARK2 + MARK3) / 3 >= 50 THEN 'PASS'
               ELSE 'FAIL'
           END AS RESULT_STATUS
    FROM STUDENTS
    WHERE STUDENT_ID = P_STUDENT_ID;
END //

DELIMITER ;

/* HOSPITAL MANAGEMENT SYSTEM

24. CREATE A PROCEDURE TO RETRIEVE ALL APPOINTMENTS FOR A PARTICULAR DOCTOR ON A GIVEN DATE.
25. CREATE A PROCEDURE TO CALCULATE THE TOTAL BILL AMOUNT FOR A PATIENT'S HOSPITAL VISIT.
26. CREATE A PROCEDURE TO RETRIEVE ALL PATIENTS WHO WERE ADMITTED BETWEEN TWO DATES.
27. CREATE A PROCEDURE TO UPDATE A PATIENT'S DISCHARGE STATUS AND DISCHARGE DATE.*/ 

DELIMITER //

CREATE PROCEDURE GET_DOCTOR_APPOINTMENTS(
    IN P_DOCTOR_ID INT,
    IN P_DATE DATE
)
BEGIN
    SELECT *
    FROM APPOINTMENTS
    WHERE DOCTOR_ID = P_DOCTOR_ID
    AND APPOINTMENT_DATE = P_DATE;
END //

CREATE PROCEDURE CALCULATE_PATIENT_BILL(
    IN P_PATIENT_ID INT
)
BEGIN
    SELECT PATIENT_ID,
           SUM(BILL_AMOUNT) AS TOTAL_BILL
    FROM BILLS
    WHERE PATIENT_ID = P_PATIENT_ID
    GROUP BY PATIENT_ID;
END //

CREATE PROCEDURE PATIENTS_ADMITTED_BETWEEN_DATES(
    IN P_START_DATE DATE,
    IN P_END_DATE DATE
)
BEGIN
    SELECT *
    FROM PATIENTS
    WHERE ADMISSION_DATE
    BETWEEN P_START_DATE AND P_END_DATE;
END //

CREATE PROCEDURE UPDATE_DISCHARGE_STATUS(
    IN P_PATIENT_ID INT,
    IN P_DISCHARGE_DATE DATE
)
BEGIN
    UPDATE PATIENTS
    SET DISCHARGE_STATUS = 'DISCHARGED',
        DISCHARGE_DATE = P_DISCHARGE_DATE
    WHERE PATIENT_ID = P_PATIENT_ID;
END //

DELIMITER ;

/* INVENTORY MANAGEMENT

28. CREATE A PROCEDURE TO IDENTIFY PRODUCTS WHOSE STOCK IS BELOW THE REORDER LEVEL.
29. CREATE A PROCEDURE TO INCREASE PRODUCT STOCK WHEN A NEW SHIPMENT ARRIVES.
30. CREATE A PROCEDURE TO GENERATE AN INVENTORY REPORT SHOWING PRODUCT NAME, AVAILABLE QUANTITY, REORDER LEVEL, AND STOCK STATUS. */

DELIMITER //

CREATE PROCEDURE LOW_STOCK_PRODUCTS()
BEGIN
    SELECT *
    FROM PRODUCTS
    WHERE STOCK < REORDER_LEVEL;
END //

CREATE PROCEDURE INCREASE_PRODUCT_STOCK(
    IN P_PRODUCT_ID INT,
    IN P_QUANTITY INT
)
BEGIN
    UPDATE PRODUCTS
    SET STOCK = STOCK + P_QUANTITY
    WHERE PRODUCT_ID = P_PRODUCT_ID;
END //

CREATE PROCEDURE INVENTORY_REPORT()
BEGIN
    SELECT PRODUCT_NAME,
           STOCK AS AVAILABLE_QUANTITY,
           REORDER_LEVEL,
           CASE
               WHEN STOCK < REORDER_LEVEL THEN 'LOW STOCK'
               ELSE 'IN STOCK'
           END AS STOCK_STATUS
    FROM PRODUCTS;
END //

DELIMITER ;

/* ADVANCED REAL-TIME SCENARIOS

31. CREATE A PROCEDURE TO TRANSFER MONEY BETWEEN TWO ACCOUNTS USING TRANSACTION, COMMIT, AND ROLLBACK. IF ANY OPERATION FAILS, ALL CHANGES SHOULD BE ROLLED BACK.
32. CREATE A PROCEDURE TO PLACE AN ORDER USING MULTIPLE TABLES SUCH AS CUSTOMERS, ORDERS, ORDER_ITEMS, AND PRODUCTS.
33. CREATE A PROCEDURE THAT ACCEPTS A CUSTOMER ID AND DATE RANGE AND RETURNS THE CUSTOMER'S TOTAL NUMBER OF ORDERS AND TOTAL SPENDING.
34. CREATE A PROCEDURE TO UPDATE EMPLOYEE SALARY AND SIMULTANEOUSLY INSERT THE OLD SALARY AND NEW SALARY INTO A SALARY AUDIT TABLE.
35. CREATE A PROCEDURE TO DELETE A CUSTOMER ONLY WHEN THE CUSTOMER HAS NO ACTIVE ORDERS. OTHERWISE, PREVENT THE DELETION.
36. CREATE A PROCEDURE TO CALCULATE AN EMPLOYEE'S BONUS BASED ON SALARY AND PERFORMANCE RATING.
37. CREATE A PROCEDURE TO IDENTIFY INACTIVE CUSTOMERS WHO HAVE NOT PLACED AN ORDER IN THE LAST 6 MONTHS.
38. CREATE A PROCEDURE TO GENERATE A MONTHLY SALES REPORT CONTAINING TOTAL ORDERS, TOTAL QUANTITY SOLD, AND TOTAL REVENUE.
39. CREATE A PROCEDURE THAT ACCEPTS A PRODUCT ID AND QUANTITY AND DETERMINES WHETHER THE PRODUCT CAN BE ORDERED BASED ON AVAILABLE STOCK.
40. CREATE A PROCEDURE FOR ORDER PROCESSING THAT:
• CHECKS CUSTOMER EXISTENCE
• CHECKS PRODUCT AVAILABILITY
• INSERTS THE ORDER
• UPDATES STOCK
• CALCULATES TOTAL AMOUNT
• COMMITS IF SUCCESSFUL
• ROLLS BACK IF ANY OPERATION FAILS */

DELIMITER //

CREATE PROCEDURE TRANSFER_MONEY_TXN(
    IN P_FROM_ACC INT,
    IN P_TO_ACC INT,
    IN P_AMOUNT DECIMAL(10,2)
)
BEGIN
    START TRANSACTION;

    UPDATE ACCOUNTS
    SET BALANCE = BALANCE - P_AMOUNT
    WHERE ACCOUNT_ID = P_FROM_ACC;

    UPDATE ACCOUNTS
    SET BALANCE = BALANCE + P_AMOUNT
    WHERE ACCOUNT_ID = P_TO_ACC;

    COMMIT;
END //

CREATE PROCEDURE PLACE_ORDER_MULTI_TABLE(
    IN P_CUSTOMER_ID INT,
    IN P_PRODUCT_ID INT,
    IN P_QTY INT
)
BEGIN
    DECLARE V_PRICE DECIMAL(10,2);

    SELECT PRICE
    INTO V_PRICE
    FROM PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    INSERT INTO ORDERS(CUSTOMER_ID, ORDER_DATE)
    VALUES(P_CUSTOMER_ID, CURDATE());

    INSERT INTO ORDER_ITEMS(ORDER_ID, PRODUCT_ID, QUANTITY, PRICE)
    VALUES(LAST_INSERT_ID(), P_PRODUCT_ID, P_QTY, V_PRICE);

    UPDATE PRODUCTS
    SET STOCK = STOCK - P_QTY
    WHERE PRODUCT_ID = P_PRODUCT_ID;
END //

CREATE PROCEDURE CUSTOMER_ORDER_SUMMARY(
    IN P_CUSTOMER_ID INT,
    IN P_START_DATE DATE,
    IN P_END_DATE DATE
)
BEGIN
    SELECT COUNT(*) AS TOTAL_ORDERS,
           SUM(TOTAL_AMOUNT) AS TOTAL_SPENDING
    FROM ORDERS
    WHERE CUSTOMER_ID = P_CUSTOMER_ID
    AND ORDER_DATE BETWEEN P_START_DATE AND P_END_DATE;
END //

CREATE PROCEDURE UPDATE_SALARY_AUDIT(
    IN P_EMP_ID INT,
    IN P_NEW_SALARY DECIMAL(10,2)
)
BEGIN
    DECLARE V_OLD_SALARY DECIMAL(10,2);

    SELECT SALARY
    INTO V_OLD_SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = P_EMP_ID;

    UPDATE EMPLOYEES
    SET SALARY = P_NEW_SALARY
    WHERE EMPLOYEE_ID = P_EMP_ID;

    INSERT INTO SALARY_AUDIT
    (EMPLOYEE_ID, OLD_SALARY, NEW_SALARY)
    VALUES
    (P_EMP_ID, V_OLD_SALARY, P_NEW_SALARY);
END //

CREATE PROCEDURE DELETE_CUSTOMER_IF_NO_ACTIVE_ORDERS(
    IN P_CUSTOMER_ID INT
)
BEGIN
    IF NOT EXISTS (
        SELECT *
        FROM ORDERS
        WHERE CUSTOMER_ID = P_CUSTOMER_ID
        AND STATUS = 'ACTIVE'
    ) THEN
        DELETE FROM CUSTOMERS
        WHERE CUSTOMER_ID = P_CUSTOMER_ID;
    ELSE
        SELECT 'ACTIVE ORDERS EXIST' AS MESSAGE;
    END IF;
END //

CREATE PROCEDURE CALCULATE_EMPLOYEE_BONUS(
    IN P_EMP_ID INT,
    IN P_RATING INT
)
BEGIN
    SELECT EMPLOYEE_NAME,
           SALARY,
           CASE
               WHEN P_RATING >= 5 THEN SALARY * 0.20
               WHEN P_RATING >= 3 THEN SALARY * 0.10
               ELSE SALARY * 0.05
           END AS BONUS
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = P_EMP_ID;
END //

CREATE PROCEDURE INACTIVE_CUSTOMERS()
BEGIN
    SELECT *
    FROM CUSTOMERS
    WHERE CUSTOMER_ID NOT IN (
        SELECT CUSTOMER_ID
        FROM ORDERS
        WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH)
    );
END //

CREATE PROCEDURE MONTHLY_SALES_REPORT()
BEGIN
    SELECT COUNT(*) AS TOTAL_ORDERS,
           SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD,
           SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM ORDERS;
END //

CREATE PROCEDURE CHECK_PRODUCT_ORDERABLE(
    IN P_PRODUCT_ID INT,
    IN P_QTY INT
)
BEGIN
    DECLARE V_STOCK INT;

    SELECT STOCK
    INTO V_STOCK
    FROM PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    IF V_STOCK >= P_QTY THEN
        SELECT 'ORDER CAN BE PLACED' AS STATUS;
    ELSE
        SELECT 'INSUFFICIENT STOCK' AS STATUS;
    END IF;
END //

CREATE PROCEDURE PROCESS_ORDER(
    IN P_CUSTOMER_ID INT,
    IN P_PRODUCT_ID INT,
    IN P_QTY INT
)
BEGIN
    DECLARE V_STOCK INT;
    DECLARE V_PRICE DECIMAL(10,2);

    START TRANSACTION;

    SELECT STOCK, PRICE
    INTO V_STOCK, V_PRICE
    FROM PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    IF V_STOCK >= P_QTY THEN

        INSERT INTO ORDERS(CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
        VALUES(P_CUSTOMER_ID, CURDATE(), P_QTY * V_PRICE);

        UPDATE PRODUCTS
        SET STOCK = STOCK - P_QTY
        WHERE PRODUCT_ID = P_PRODUCT_ID;

        COMMIT;

    ELSE

        ROLLBACK;
        SELECT 'ORDER FAILED - INSUFFICIENT STOCK' AS MESSAGE;

    END IF;
END //
DELIMITER ;

