#Date: 11th September 2026
#Topic Covered: SQL Views

/* SQL VIEWS

BANKING – VIEW QUESTIONS

1. CREATE A VIEW TO DISPLAY CUSTOMER NAME, ACCOUNT NUMBER, ACCOUNT TYPE, AND BALANCE.
2. CREATE A VIEW TO DISPLAY CUSTOMERS WHOSE ACCOUNT BALANCE IS GREATER THAN ₹50,000.
3. CREATE A VIEW SHOWING ALL ACTIVE BANK ACCOUNTS.
4. CREATE A VIEW DISPLAYING CUSTOMER TRANSACTION DETAILS INCLUDING CUSTOMER NAME, TRANSACTION TYPE, AMOUNT, AND TRANSACTION DATE.
5. CREATE A VIEW SHOWING CUSTOMERS WHO HAVE PERFORMED TRANSACTIONS DURING THE CURRENT MONTH. */

CREATE VIEW VW_CUSTOMER_ACCOUNTS AS
SELECT CUSTOMER_NAME, ACCOUNT_NUMBER, ACCOUNT_TYPE, BALANCE
FROM ACCOUNTS;

CREATE VIEW VW_HIGH_BALANCE_CUSTOMERS AS
SELECT CUSTOMER_NAME, ACCOUNT_NUMBER, BALANCE
FROM ACCOUNTS
WHERE BALANCE > 50000;

CREATE VIEW VW_ACTIVE_ACCOUNTS AS
SELECT *
FROM ACCOUNTS
WHERE STATUS = 'ACTIVE';

CREATE VIEW VW_CUSTOMER_TRANSACTIONS AS
SELECT C.CUSTOMER_NAME,
       T.TRANSACTION_TYPE,
       T.AMOUNT,
       T.TRANSACTION_DATE
FROM CUSTOMERS C
JOIN ACCOUNTS A
ON C.CUSTOMER_ID = A.CUSTOMER_ID
JOIN TRANSACTIONS T
ON A.ACCOUNT_ID = T.ACCOUNT_ID;

CREATE VIEW VW_CURRENT_MONTH_TRANSACTIONS AS
SELECT DISTINCT C.CUSTOMER_NAME
FROM CUSTOMERS C
JOIN ACCOUNTS A
ON C.CUSTOMER_ID = A.CUSTOMER_ID
JOIN TRANSACTIONS T
ON A.ACCOUNT_ID = T.ACCOUNT_ID
WHERE MONTH(T.TRANSACTION_DATE) = MONTH(CURDATE())
  AND YEAR(T.TRANSACTION_DATE) = YEAR(CURDATE());

/* E-COMMERCE – VIEW QUESTIONS

6. CREATE A VIEW DISPLAYING PRODUCT NAME, CATEGORY, PRICE, AND AVAILABLE STOCK.
7. CREATE A VIEW SHOWING PRODUCTS WHOSE STOCK IS BELOW THE REORDER LEVEL.
8. CREATE A VIEW DISPLAYING CUSTOMER NAME, ORDER ID, ORDER DATE, AND ORDER AMOUNT.
9. CREATE A VIEW SHOWING ALL PENDING ORDERS.
10. CREATE A VIEW DISPLAYING ORDER DETAILS ALONG WITH CUSTOMER AND PRODUCT INFORMATION USING JOINS.
11. CREATE A VIEW TO DISPLAY THE TOTAL AMOUNT SPENT BY EACH CUSTOMER.
12. CREATE A VIEW SHOWING CATEGORY-WISE TOTAL SALES.
13. CREATE A VIEW DISPLAYING THE TOP-SELLING PRODUCTS BASED ON QUANTITY SOLD. */

CREATE VIEW VW_PRODUCTS AS
SELECT PRODUCT_NAME, CATEGORY, PRICE, STOCK
FROM PRODUCTS;

CREATE VIEW VW_LOW_STOCK_PRODUCTS AS
SELECT PRODUCT_NAME, STOCK, REORDER_LEVEL
FROM PRODUCTS
WHERE STOCK < REORDER_LEVEL;

CREATE VIEW VW_CUSTOMER_ORDERS AS
SELECT C.CUSTOMER_NAME,
       O.ORDER_ID,
       O.ORDER_DATE,
       O.ORDER_AMOUNT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID;

CREATE VIEW VW_PENDING_ORDERS AS
SELECT *
FROM ORDERS
WHERE STATUS = 'PENDING';

CREATE VIEW VW_ORDER_DETAILS AS
SELECT O.ORDER_ID,
       C.CUSTOMER_NAME,
       P.PRODUCT_NAME,
       O.ORDER_DATE,
       O.ORDER_AMOUNT
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID;

CREATE VIEW VW_CUSTOMER_TOTAL_SPENT AS
SELECT C.CUSTOMER_ID,
       C.CUSTOMER_NAME,
       SUM(O.ORDER_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME;

CREATE VIEW VW_CATEGORY_SALES AS
SELECT P.CATEGORY,
       SUM(O.ORDER_AMOUNT) AS TOTAL_SALES
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY;

CREATE VIEW VW_TOP_SELLING_PRODUCTS AS
SELECT P.PRODUCT_ID,
       P.PRODUCT_NAME,
       SUM(O.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PRODUCTS P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME;

/* EMPLOYEE / HR – VIEW QUESTIONS

14. CREATE A VIEW DISPLAYING EMPLOYEE NAME, DEPARTMENT, DESIGNATION, AND SALARY.
15. CREATE A VIEW SHOWING EMPLOYEES WHOSE SALARY IS GREATER THAN ₹50,000.
16. CREATE A VIEW DISPLAYING EMPLOYEES BELONGING TO THE IT DEPARTMENT.
17. CREATE A VIEW SHOWING DEPARTMENT-WISE EMPLOYEE COUNT.
18. CREATE A VIEW SHOWING DEPARTMENT-WISE AVERAGE SALARY.
19. CREATE A VIEW DISPLAYING EMPLOYEES ALONG WITH THEIR MANAGER'S NAME USING A SELF JOIN.
20. CREATE A VIEW SHOWING EMPLOYEES WHO JOINED THE COMPANY WITHIN THE LAST 1 YEAR. */

CREATE VIEW VW_EMPLOYEE_DETAILS AS
SELECT EMPLOYEE_NAME, DEPARTMENT, DESIGNATION, SALARY
FROM EMPLOYEES;

CREATE VIEW VW_HIGH_SALARY_EMPLOYEES AS
SELECT EMPLOYEE_NAME, DEPARTMENT, SALARY
FROM EMPLOYEES
WHERE SALARY > 50000;

CREATE VIEW VW_IT_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT';

CREATE VIEW VW_DEPARTMENT_EMPLOYEE_COUNT AS
SELECT DEPARTMENT,
       COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT;

CREATE VIEW VW_DEPARTMENT_AVG_SALARY AS
SELECT DEPARTMENT,
       AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

CREATE VIEW VW_EMPLOYEE_MANAGER AS
SELECT E.EMPLOYEE_NAME,
       M.EMPLOYEE_NAME AS MANAGER_NAME
FROM EMPLOYEES E
JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;

CREATE VIEW VW_RECENT_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE JOIN_DATE >= CURDATE() - INTERVAL 1 YEAR;

/* STUDENT MANAGEMENT – VIEW QUESTIONS

21. CREATE A VIEW DISPLAYING STUDENT NAME, COURSE, TOTAL MARKS, AND AVERAGE MARKS.
22. CREATE A VIEW SHOWING STUDENTS WHO HAVE PASSED ALL SUBJECTS.
23. CREATE A VIEW DISPLAYING STUDENTS WITH AN AVERAGE MARK GREATER THAN 80.
24. CREATE A VIEW SHOWING COURSE-WISE STUDENT COUNT.
25. CREATE A VIEW DISPLAYING COURSE-WISE AVERAGE MARKS.
26. CREATE A VIEW THAT CALCULATES THE STUDENT'S GRADE USING CASE. */

CREATE VIEW VW_STUDENT_MARKS AS
SELECT STUDENT_NAME,
       COURSE,
       TOTAL_MARKS,
       TOTAL_MARKS / SUBJECT_COUNT AS AVERAGE_MARKS
FROM STUDENTS;

CREATE VIEW VW_PASSED_STUDENTS AS
SELECT *
FROM STUDENTS
WHERE RESULT = 'PASS';

CREATE VIEW VW_HIGH_AVERAGE_STUDENTS AS
SELECT STUDENT_NAME,
       COURSE,
       AVERAGE_MARKS
FROM STUDENTS
WHERE AVERAGE_MARKS > 80;

CREATE VIEW VW_COURSE_STUDENT_COUNT AS
SELECT COURSE,
       COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY COURSE;

CREATE VIEW VW_COURSE_AVERAGE_MARKS AS
SELECT COURSE,
       AVG(AVERAGE_MARKS) AS COURSE_AVERAGE
FROM STUDENTS
GROUP BY COURSE;

CREATE VIEW VW_STUDENT_GRADES AS
SELECT STUDENT_ID,
       STUDENT_NAME,
       AVERAGE_MARKS,
       CASE
           WHEN AVERAGE_MARKS >= 90 THEN 'A'
           WHEN AVERAGE_MARKS >= 80 THEN 'B'
           WHEN AVERAGE_MARKS >= 70 THEN 'C'
           WHEN AVERAGE_MARKS >= 60 THEN 'D'
           ELSE 'F'
       END AS GRADE
FROM STUDENTS;

/* HOSPITAL – VIEW QUESTIONS

27. CREATE A VIEW DISPLAYING PATIENT NAME, DOCTOR NAME, APPOINTMENT DATE, AND APPOINTMENT STATUS.
28. CREATE A VIEW SHOWING ALL CURRENTLY ADMITTED PATIENTS.
29. CREATE A VIEW DISPLAYING PATIENT NAME, ADMISSION DATE, DISCHARGE DATE, AND TOTAL BILL.
30. CREATE A VIEW SHOWING THE NUMBER OF PATIENTS HANDLED BY EACH DOCTOR.
31. CREATE A VIEW SHOWING PATIENTS WHOSE BILL AMOUNT EXCEEDS ₹25,000. */

CREATE VIEW VW_PATIENT_APPOINTMENTS AS
SELECT P.PATIENT_NAME,
       D.DOCTOR_NAME,
       A.APPOINTMENT_DATE,
       A.STATUS
FROM APPOINTMENTS A
JOIN PATIENTS P
ON A.PATIENT_ID = P.PATIENT_ID
JOIN DOCTORS D
ON A.DOCTOR_ID = D.DOCTOR_ID;

CREATE VIEW VW_ADMITTED_PATIENTS AS
SELECT *
FROM PATIENTS
WHERE STATUS = 'ADMITTED';

CREATE VIEW VW_PATIENT_BILLS AS
SELECT PATIENT_NAME,
       ADMISSION_DATE,
       DISCHARGE_DATE,
       TOTAL_BILL
FROM PATIENTS;

CREATE VIEW VW_DOCTOR_PATIENT_COUNT AS
SELECT D.DOCTOR_ID,
       D.DOCTOR_NAME,
       COUNT(A.PATIENT_ID) AS PATIENT_COUNT
FROM DOCTORS D
JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
GROUP BY D.DOCTOR_ID, D.DOCTOR_NAME;

CREATE VIEW VW_HIGH_BILL_PATIENTS AS
SELECT PATIENT_NAME,
       TOTAL_BILL
FROM PATIENTS
WHERE TOTAL_BILL > 25000;

/* ADVANCED VIEW SCENARIOS

32. CREATE A VIEW COMBINING CUSTOMERS, ORDERS, AND ORDER_ITEMS TO DISPLAY A COMPLETE CUSTOMER ORDER REPORT.
33. CREATE A VIEW TO DISPLAY MONTHLY SALES SUMMARY WITH MONTH, NUMBER OF ORDERS, QUANTITY SOLD, AND TOTAL REVENUE.
34. CREATE A VIEW SHOWING CUSTOMERS WHO HAVE NEVER PLACED AN ORDER.
35. CREATE A VIEW SHOWING PRODUCTS THAT HAVE NEVER BEEN SOLD.
36. CREATE A VIEW DISPLAYING THE HIGHEST-PAID EMPLOYEE IN EACH DEPARTMENT.
37. CREATE A VIEW SHOWING THE SECOND-HIGHEST SALARY IN EACH DEPARTMENT.
38. CREATE A VIEW USING A SUBQUERY TO DISPLAY EMPLOYEES EARNING MORE THAN THEIR DEPARTMENT'S AVERAGE SALARY.
39. CREATE A VIEW USING A WINDOW FUNCTION TO RANK EMPLOYEES BASED ON SALARY WITHIN EACH DEPARTMENT.
40. CREATE A VIEW THAT COMBINES WHERE, GROUP BY, HAVING, JOIN, AND AGGREGATE FUNCTIONS TO GENERATE A MANAGEMENT-LEVEL SALES REPORT.*/

CREATE VIEW VW_CUSTOMER_ORDER_REPORT AS
SELECT C.CUSTOMER_ID,
       C.CUSTOMER_NAME,
       O.ORDER_ID,
       O.ORDER_DATE,
       OI.PRODUCT_ID,
       OI.QUANTITY
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID;

CREATE VIEW VW_MONTHLY_SALES_SUMMARY AS
SELECT MONTH(ORDER_DATE) AS MONTH,
       COUNT(ORDER_ID) AS NUMBER_OF_ORDERS,
       SUM(QUANTITY) AS QUANTITY_SOLD,
       SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS
GROUP BY MONTH(ORDER_DATE);

CREATE VIEW VW_CUSTOMERS_NO_ORDERS AS
SELECT C.*
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL;

CREATE VIEW VW_UNSOLD_PRODUCTS AS
SELECT P.*
FROM PRODUCTS P
LEFT JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
WHERE OI.PRODUCT_ID IS NULL;

CREATE VIEW VW_HIGHEST_PAID_EMPLOYEE AS
SELECT EMPLOYEE_ID,
       EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY
FROM EMPLOYEES E
WHERE SALARY = (
    SELECT MAX(SALARY)
    FROM EMPLOYEES
    WHERE DEPARTMENT = E.DEPARTMENT
);

CREATE VIEW VW_SECOND_HIGHEST_SALARY AS
SELECT EMPLOYEE_ID,
       EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY
FROM (
    SELECT EMPLOYEE_ID,
           EMPLOYEE_NAME,
           DEPARTMENT,
           SALARY,
           DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RNK
    FROM EMPLOYEES
) X
WHERE RNK = 2;

CREATE VIEW VW_ABOVE_AVERAGE_SALARY AS
SELECT EMPLOYEE_ID,
       EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY
FROM EMPLOYEES E
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM EMPLOYEES
    WHERE DEPARTMENT = E.DEPARTMENT
);

CREATE VIEW VW_EMPLOYEE_SALARY_RANK AS
SELECT EMPLOYEE_ID,
       EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY,
       RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

CREATE VIEW VW_MANAGEMENT_SALES_REPORT AS
SELECT C.CUSTOMER_ID,
       C.CUSTOMER_NAME,
       COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
       SUM(O.TOTAL_AMOUNT) AS TOTAL_SALES
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.STATUS = 'COMPLETED'
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING SUM(O.TOTAL_AMOUNT) > 10000;
